class AutoSuggestions99103456 { static final reviewedTitles99103456 = const {"N-veces Inversiones - Calle Villaflor con Union, CC City Market N, 163 Calle L, Caracas 1050, Distrito Capital, Venezuela",
"Inversiones Mepix C.A - C.C. City Market, piso 4, local 444 y, 416 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"Repuesto Cell OOC - C.C Sábana Grande, Nivel Mezanina, Local 04 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"Bluestore C.A - C.C City Market, Nivel 4, Local 441, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"IC Fix Servicio Técnico - C.C Sábana Grande, nivel sotano,local 25, Caracas 1050, Distrito Capital, Venezuela",
"Imperio Bodegon Cafe - Av. Casanova con negrin Edf, PB L-2, Caracas 1050, Distrito Capital, Venezuela",
"Alpha Computers C.A - C.C. City Market, Nivel Bazar, Local, B327, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"Cerámicas y Materiales Carmire, C.A. - Barrio Madre Vieja calle 5 entre carreras 5 y, 6, Guanarito 3354, Portuguesa, Venezuela",
"Korea Partes Táchira - QQ5C+G46, San Cristobal 5001, Táchira, Venezuela",
"Novedades Romary - Calle Villaflor con Union, CC City Market N- Bazar L-B102 Caracas, Caracas 1050, Distrito Capital, Venezuela",
"Accesorios y Tecnologia DYH - Calle Villaflor con Union, CC City Market, Nivel Bazar L-D226 caracas, Caracas 1050, Distrito Capital, Venezuela",
"Soporte Store 57 - Calle Villaflor con Union, CC City Market Bazar N-2 L- B 302 Caracas, Caracas 1050, Distrito Capital, Venezuela",
"Inversiones JHR - Calle Baruta / Casanova y boulebart Edf, PB C. María Auxiliadora, Caracas 1050, Distrito Capital, Venezuela",
};
}
