class AutoSuggestions99991565 {
  static final reviewedTitles99991565 = const {
    "Heyday Authentic Store - R. da Irmandade 15, 2640-022 Santo Isidoro, Portugal",
    "Atlas-Agencia De Viagens E Turismo (Braga), Lda. - Praça Conde de Agrolongo 127, 4700-317 Braga, Portugal",
    "Explorer Investments SCR SA - Av. Eng. Duarte Pacheco 7 7A, 1070-100 Lisboa, Portugal",
    "EPICUR - Wine Boutique & Food - R. Alexandre Herculano 22A, 8000-204 Faro, Portugal",
    "Vegana By Tentúgal - R. de Santo Ildefonso 412 4300, 4300 Porto, Portugal",
    "TOPTOUR PORTUGAL - Azinhaga da Torre do Fato 33B, 1600-297 Lisboa, Portugal",
    "Átrio da Cidade - Av. 5 de Outubro 23A, 2560-270 Torres Vedras, Portugal",
    "Paviljoen ...aan het Water - Brielselaan 157, 3081 AC Rotterdam, Netherlands",
    "MEGHEE - 110 E - W Rd, Rumuodara 500102, Port Harcourt, Nigeria",
    "MOVITEREDIL SRL - Contrada Vermica, 88841 Isola di Capo Rizzuto KR, Italy",
    "HOPS BEER BAR BUDAPEST - Budapest, Wesselényi utca 13, 1077 Hungary",
    "LCD Fix - Budapest, Október huszonharmadika utca 8, 1117 Hungary",
    "Tifan Co. Vegetarian Bistro - Spinčićeva ul. 2, 51000, Rijeka, Croatia",
    "Vau Hotel - Donji Vukojevac 80, 44272, Donji Vukojevac, Croatia",
    "Dharma hostel - Spinčićeva ul. 2, 51000, Rijeka, Croatia",
    "Molo Longo - Integrated hotel (apartments & rooms) - Trpimirova ul. 1A, 51000, Rijeka, Croatia",
    "PEEK&POKE Computer Museum - Ul. Ivana Grohovca 2A, 51000, Rijeka, Croatia",
    "Premier Bar - Ul. Andrije Medulića 7, 51000, Rijeka, Croatia",
    "Web Flowers d.o.o. - Slavonska avenija, Struge I 52d, 10000, Zagreb, Croatia",
    "Boutique Restaurant - Ul. Maršala Tita 142, 51410, Opatija, Croatia",
    "bar Thausend - Vozišće 5, 51216, Viškovo, Croatia",
    "Priroda i društvo - Užarska ulica 14 dvorišna strana iza Hg Spot-a, 51000, Rijeka, Croatia",
    "Hilton Rijeka Costabella Beach Resort & Spa - Opatijska ul. 9, 51000, Rijeka, Croatia",
    "ShoeBeDo - City Center One, Jankomir 33, 10000, Zagreb, Croatia",
    "Romeo bar & Juliet caffe - Šišmiš ul., 51000, Rijeka, Croatia",
    "Tools Milic Ltd. - Management - Wholesale Podsused - Susedbreška ul. 2, 10090, Zagreb, Croatia",
    "My travel - Grivica ul. 4, 51000, Rijeka, Croatia",
    "Tools Milic Ltd. - Branch 4th Sesvete - Sesvetska cesta 22, 10360, Sesvete, Croatia",
    "Supermajice.hr - Šetalište Andrije Kačića Miošića 8A, 51000, Rijeka, Croatia",
    "Na Kantunu Tavern - Wenzelova ul. 4, 51000, Rijeka, Croatia",
    "Rijeka Clinical Hospital Center Sušak Locality - Ul. Tome Strižića 3, 51000, Rijeka, Croatia",
    "Foto Kurti - Trg riječkih olimpijaca 10, 51000, Rijeka, Croatia",
    "Oikos Korčula Real Estate - Ul. Hrvatske Bratske Zajednice 88, 20260, Korčula, Croatia",
    "Gastro Roko - Fiumara ul. 7, 51000, Rijeka, Croatia",
    "Eko selo Selce - 51250, Selce, Croatia",
    "GRAD eat,drink&mingle - Ul. Riva Boduli 7b, 51000, Rijeka, Croatia",
    "Slika - Ul. Janka Polića Kamova 81, 51000, Rijeka, Croatia",
    "Cukarikafe - Trg Julija Klovića 4, 51000, Rijeka, Croatia",
    "Stop caffe & club - Užarska ul. 17, 51000, Rijeka, Croatia",
    "Tools Milic Ltd. - Branch 3rd Zabok - Ul. Matije Gupca 115, 49000, Zabok, Croatia",
    "Konoba Ribica - Pulska ul. 30, 51000, Rijeka, Croatia",
    "Bistro oštarija Fortica - Trg Matka Laginje 1, 51215, Kastav, Croatia",
    "Khao Sun - Ul. Slaviše Vajnera Čiče 11, 51000, Rijeka, Croatia",
    // "Eko selo Selce - 51250, Selce, Croatia",
    "City Center one East - Slavonska avenija 11d, 10000, Zagreb, Croatia",
    "Kerver - Ul. Akcije Maslenica 1, 23000, Zadar, Croatia",
    "Kerver - Ul. Rudolfa Kolaka 14, 10000, Zagreb, Croatia",
    "Kerver - Ul. Janka Polića Kamova 81a, 51000, Rijeka, Croatia",
    "Shopping Mall Rijeka - Riva 6, 51000, Rijeka, Croatia",
    "Magic Adria Real Estate - Prolaz Ante Dukića 2, 51215, Kastav, Croatia",
    "City Center one West - Jankomir 33, 10000, Zagreb, Croatia",
    "Moto mondo - Hanuševa ul., 10000, Zagreb, Croatia",
    "City taxi - Novo pračno 83, 44010, Sisak, Croatia",
    "Karić Automobili d.o.o. - Ul. Andrije Žaje 5, 10000, Zagreb, Croatia",
    "BitLucky d.o.o. - 1st, floor, Riva 8, 51000, Rijeka, Croatia",
    "Rakhia bar - Ul. Andrije Medulića 5, 51000, Rijeka, Croatia",
    "Master’s Barber Shop - Ul. Andrije Medulića 6, 51000, Rijeka, Croatia",
    "DNK Garaža - Ul. Slavka Cindrića 9, 51000, Rijeka, Croatia",
    "Tools Milic Ltd. - Branch 2nd Split - Velebitska ul. 9, 21000, Split, Croatia",
// "Tools Milic Ltd. - Branch 2nd Split - Velebitska ul. 9, 21000, Split, Croatia",
    "Tools Milic - Branch first Malesnica - Ul. Mirka Viriusa 1, 10090, Zagreb, Croatia",
    "Tunel Bar - Školjić 12, 51000, Rijeka, Croatia",
    "Beach Bar PHANAS - Ul. Stara Voda bb, 51221, Paveki, Croatia",
    "Phanas Pub Rijeka est.2001 - Ul. Ivana Zajca 9, 51000, Rijeka, Croatia",
    "Khao Sun - Malešnica 14, 10000, Zagreb, Croatia",
    "Pet Jedan Tapas Bar - Riva 14A, 51000, Rijeka, Croatia",
    "Morski žal - Obala 9, 51264, Jadranovo, Croatia",
// "Pet Jedan Tapas Bar - Riva 14A, 51000, Rijeka, Croatia",
    "Sex Shop TABOO - Riva 6, 51000, Rijeka, Croatia",
    "Smartshop Sextasy - Ciottina ul. 10a, 51000, Rijeka, Croatia",
    "CENTAR ZA KVALITETU I SIGURNOST d.o.o. - II Trokut 3, 10020, Zagreb, Croatia",
    "Primorska konoba - Krojačka ul. 1, 51000, Rijeka, Croatia",
    "Big Blue Sport - Podan Glavice 2, 21420, Bol, Croatia",
    "Big Blue Cafe - Ul. Bolskih Pomoraca 15, 21420, Bol, Croatia",
    "Big Blue Bike&Beach Shop - Put Zlatnog Rata 46, 21420, Bol, Croatia",
    "OPG Grancigula - Rakovo Selo 67, 22000, Dubrava kod Šibenika, Croatia",
    // "OPG Grancigula - Rakovo Selo 67, 22000, Dubrava kod Šibenika, Croatia",
    "Alo Alo 12 - Ul. Josipa Jovića 93, 21000, Split, Croatia",
    "Konoba Blato - Titov trg 8C, 51000, Rijeka, Croatia",
    "PO-MARK D.O.O. - Ul. Gustava Krkleca 40, 10000, Zagreb, Croatia",
    "Art Nails - Trg Vladimira Nazora, 10310, Ivanić Grad, Croatia",
    "VOYAGER TRAVEL AGENCY - Dolac 3/c, 51000, Rijeka, Croatia",
    "SPOT shopping park - Trogirska cesta 6, 21220, Plano, Croatia",
    "Pub Bačva - Dolac 8, 51000, Rijeka, Croatia",
    "Good Gate video produkcija - Obrovacka 16 Veliko Polje, 10010, Zagreb, Croatia",
    "CHOCOLAND - Ul. Andrije Medulića 8, 51000, Rijeka, Croatia",
    "Big Box d.o.o. - Kumičićeva ul. 62A, 51000, Rijeka, Croatia",
    "Octopus Piercing & Tattoo Studio - prilaz Gjure Deželića 23, 10000, Zagreb, Croatia",
    "Slastičarnica Slon by Moreno Debartoli - Grivica ul. 4, 51000, Rijeka, Croatia",
    "Kaokakao - Ul. Andrije Štangera 44, 51410, Opatija, Croatia",
    "CAFFE BAR 2020 - Ul. Nikole Tesle 1A, 51000, Rijeka, Croatia",
    "Taxi transfers Croatia - Airport Taxi Sevices - Call Taxi Zagreb - Ul. Barutanski jarak 22/1, 10000, Zagreb, Croatia",
    "Muzej čokolade Zagreb (Chocolate Museum Zagreb) - Varšavska ul. 5, 10000, Zagreb, Croatia",
    "Konoba Tarsa - J. Kulfaneka, Strmica 10, 51000, Rijeka, Croatia",
    "Tiskara SUŠAK - Ul. Milutina Barača 54, 51000, Rijeka, Croatia",
    "Harat's Pub - Ul. pod Kaštelom 9, 51000, Rijeka, Croatia",
    "DVD OSIJEK TENJA - Ul. Vladka Mačeka 18, 31207, Tenja, Croatia",
    "Alo Alo 10 - Vukovarska ul. 207, 21000, Split, Croatia",
    "Alo Alo 3 - Ul. kralja Zvonimira 21, 22300, Knin, Croatia",
    "Alo Alo 5 - Obala kralja Zvonimira 9, 21220, Trogir, Croatia",
    "STUDENAC MARKET - Put Ribnjaka 1A, 21310, Omiš, Croatia",
    "Alo Alo 8 - Ul. Velimira Škorpika 23, 22000, Šibenik, Croatia",
// "Alo Alo 8 - Ul. Velimira Škorpika 23, 22000, Šibenik, Croatia",
    "Mateyaneira - Črnomerec 63, 10000, Zagreb, Croatia",
    "Restaurant Mijo - Ul. Tina Ujevića 28, 23000, Zadar, Croatia",
    "RIart Galerija - Ul. Marka Marulića 10, 51000, Rijeka, Croatia",
    "KARIĆ AUTOMOBILI - Rakovac ul. 60, 47000, Karlovac, Croatia",
    // "Art Nails - Trg Vladimira Nazora, 10310, Ivanić Grad, Croatia",
    "Taxi Rijeka - VIP Car Service Rijeka - Trg kralja Tomislava 2, 51000, Rijeka, Croatia",
    "Youth Club Rijeka - Ul. Erazma Barčića 9A, 51000, Rijeka, Croatia",
    "MPS Hotnja doo, P5 - Volavje 29B, 10450, Volavje, Croatia",
    "MPS Hotnja doo, P4 - Petrovina 87, 10450, Petrovina, Croatia",
    "MPS Hotnja doo - Unnamed Road, 44272, 44272, Brežane Lekeničke, Croatia",
    "MPS Hotnja doo, P1 - Hotnja 99, 10414, Pokupsko, Croatia",
// "MPS Hotnja doo, P1 - Hotnja 99, 10414, Pokupsko, Croatia",
    "MPS Hotnja, P15 - Rimski trg 2, 10431, Kerestinec, Croatia",
    "Mps Hotnja doo, P14 - Karlovačka ul. 9, 10450, Klinča Sela, Croatia",
    "MPS Hotnja doo, P13 - 10450, Donji Desinec, Croatia",
    "MPS Hotnja doo - Stubička ul. 35, 10000, Zagreb, Croatia",
// "MPS Hotnja doo - Stubička ul. 35, 10000, Zagreb, Croatia",
    "MPS Hotnja doo, P8 - 10410, Velika Kosnica, Croatia",
// "MPS Hotnja doo, P1 - Hotnja 99, 10414, Pokupsko, Croatia",
    "PriMarius craft pivovara d.o.o. - Radnička cesta 37, 10000, Zagreb, Croatia",
// "PriMarius craft pivovara d.o.o. - Radnička cesta 37, 10000, Zagreb, Croatia",
    "Fan Shop HNK Rijeka - Ul. Pavla Rittera Vitezovića 1, 51000, Rijeka, Croatia",
    // "Karić Automobili d.o.o. - Ul. Andrije Žaje 5, 10000, Zagreb, Croatia",
    "BAČANI ŽELJKO - Jablanska ul. 2, 10000, Zagreb, Croatia",
    "Prima 4 rooms - Verdijeva ul. 17, 51000, Rijeka, Croatia",
// "Karić Automobili d.o.o. - Ul. Andrije Žaje 5, 10000, Zagreb, Croatia",
    "Mare art poklon galerija - Ul. Andrije Medulića 1C, 51000, Rijeka, Croatia",
// "Mare art poklon galerija - Ul. Andrije Medulića 1C, 51000, Rijeka, Croatia",
    "FOTO KURTI - Užarska ul. 20, 51000, Rijeka, Croatia",
    "Caffe-Bar Corso - Andrije Palmovića 27, 48312, Rasinja, Croatia",
    "Smiljana - Titov trg 12, 51000, Rijeka, Croatia",
    "McDonald's Rijeka - Trg 111 Brigade Hrvatske Vojske 1, 51000, Rijeka, Croatia",
    "CATERING AS - Trg 111 Brigade Hrvatske Vojske 2, 51000, Rijeka, Croatia",
    "Food Bar Cantina - Verdijeva ul. 10, 51000, Rijeka, Croatia",
    "Silent Caffe - Ul. Kneza Mislava 7, 10000, Zagreb, Croatia",
    "Big Blue Sport Windsurfing center - Put Zlatnog Rata 3, 21420, Bol, Croatia",
    // "Big Blue Sport - Podan Glavice 2, 21420, Bol, Croatia",
// "Big Blue Sport - Podan Glavice 2, 21420, Bol, Croatia",
    "4 Elements - Riva 6, 51000, Rijeka, Croatia",
    "Cammeo Taxi Zagreb - Ulica Damira Tomljanovića Gavrana 15, 10000, Zagreb, Croatia",
    "Caffe bar Red Hot - Ul. Ivana Filipovića 1A, 51000, Rijeka, Croatia",
    "Triggerimpulse - Vankina ul. 17, 10000, Zagreb, Croatia",
    // "Alo Alo 10 - Vukovarska ul. 207, 21000, Split, Croatia",
    "HARREITHER d.o.o. - Martinkovac ul. 112, 51000, Rijeka, Croatia",
    "Adriatic Sailing Academy - Prolaz Marije Krucifiske, Kozulić 1, 51000, Rijeka, Croatia",
    "Vintage Room - Trg Matije Vlačića Flaciusa 7, 51000, Rijeka, Croatia",
    "Roko - Ul. Maršala Tita 114, 51410, Opatija, Croatia",
    "Mali dućan - Hegedušićeva ul. 14, 51000, Rijeka, Croatia",
    "Villa ROKO - Kamena 6, 21325, Tučepi, Croatia",
    "Maslina - Trg Ivana Koblera bb, 51000, Rijeka, Croatia",
    "Apartments Roko - Ante Rastovca 8, Tisno, 22240, 22240, Tisno, Croatia",
    "Restaurant Roko Grill - Grebaštica donja 102, 22000, Grebaštica, Croatia",
    // "Moto mondo - Hanuševa ul., 10000, Zagreb, Croatia",
    "Caffe Bar Iskra - Ul. Šime Ljubića 12, 51000, Rijeka, Croatia",
    "Forum - Hosti 43a, 51000, Rijeka, Croatia",
// "Moto mondo - Hanuševa ul., 10000, Zagreb, Croatia",
    "Infinity Caffe & Night Bar - Vozišće 23, 51216, Viškovo, Croatia",
    "Caffe bar SAMOVAR - Trg Matije V. Flaciusa 2, 51000, Rijeka, Croatia",
  };
}
