class AutoSuggestions49177304 { static final reviewedTitles49177304 = const {"ZDK Liberty Radio 97.1 FM - All Saints Road, St John&#39;s, Antigua and Barbuda",
"Northside EZ Grab - 558X+5J2, Jabberwock Road, and Barbuda, Antigua and Barbuda",
"Antigua Yacht Club Marina & Resort - Falmouth Harbour, Antigua and Barbuda",
"Townhouse Megastore - Corner of All Saints and, American Road, Antigua and Barbuda",
"The Athletes Foot (#416) - Heritage Quay, St John&#39;s, Antigua and Barbuda",
"Relocate Antigua | Relocation Services Antigua - EHLORE Ltd., Suite 10, Jolly Harbour Commercial Centre Jolly Harbour, St Mary&#39;s, Antigua and Barbuda",
"Akropolis Greek Restaurant - jolly harbour, saint Mary’s antigua, and barbuda, Antigua and Barbuda",
"Thirty six 5 - St John&#39;s, Antigua and Barbuda",
"Hemingway's Caribbean Cafe - 45C4+93R, Saint Mary&#39;s Street, St John&#39;s, Antigua and Barbuda",
"Quay Necessities - 45C3+4JW, Redcliffe St, St John&#39;s, Antigua and Barbuda",
"Spirits of the Caribbean - St, 45C3+CFP, John&#39;s, Antigua and Barbuda",
"Twist Fitness - Lower RedCliff Street, Twist Mall, 3rd floor, St John&#39;s, Antigua and Barbuda",
"TWIST Mall - St John&#39;s, Antigua and Barbuda",
"Kon Tiki Bar and Grill - 544W+9X8, Dickenson Bay St, St John&#39;s, Antigua and Barbuda",
"Basilico Italian Restautant | Antigua - Jolly Harbour Commercial Complex AG, Jolly Harbour, Antigua and Barbuda",
"Ana's on the Beach - Dickenson Bay, St. John, 5542+J56, s, Antigua, Antigua and Barbuda",
"NOMAD RESTAURANT - Marble Hill Road, Antigua and Barbuda",
"Cheers Antigua - Heritage Quay, Saint John&#39;s,, St John&#39;s, Antigua and Barbuda",
"Steph & Vlada’s Studio - Commercial centre, Jolly Harbour, Antigua and Barbuda",
"The Cool Pool - West Coast Village Valley Road, Antigua and Barbuda",
"The Tailor's Daughter - 45C3+5QG, Redcliffe St, St John&#39;s, Antigua and Barbuda",
"Creole Antigua Tours - Jolly Harbour, Antigua and Barbuda",
};
}
