class AutoSuggestions23499205 { static final reviewedTitles23499205 = const {"SimCardRental - Centro Ciudad Comercial Tamanaco nivel C1 Caracas, Caracas 1060, Distrito Capital, Venezuela",
"HABITACOM - Av. Ppal de Las Mercedes, Edif. Centro Summum, con C. Mucuchíes, Caracas 1060, Miranda, Venezuela",
"Sushi One - Soler 5837, PalermoC1425 CABA, Argentina",
"Café Sushi One 2017, C.A - Calle Urdaneta, Edif. Urdaneta Piso PB. Local n° 2 Sector, Caracas 1060, Distrito Capital, Venezuela",
"HABITACOM - Av. Ppal de Las Mercedes, Edif. Centro Summum, con C. Mucuchíes, Caracas 1060, Miranda, Venezuela",
"Café Sushi One 2017, C.A - Calle Urdaneta, Edif. Urdaneta Piso PB. Local n° 2 Sector, Caracas 1060, Distrito Capital, Venezuela",
"Grupo Comunica 555, C.A - Calle Sucre, Edif. Leandro Piso PB Local B Urb, Chacao, Caracas 1060, Distrito Capital, Venezuela",
"HUGONODONTE Café - Estacionamiento público Centro Plaza, Trans. 1, Caracas 1060, Miranda, Venezuela",
"KMC Laboratorio Clínico - 1071 Caracas, Caracas 1071, Distrito Capital, Venezuela",
"Gigi Playa - Calle 11 entre Carreras 18 y 19, Local N°1, San Cristóbal 5001, Táchira, Venezuela",
"Gürt Cocina Vegetariana - Edificio La Trinidad, Local PB1, carrera 23 entre calles 9 y 10, San Cristóbal 5001, Táchira, Venezuela",
"Alarmas Beto C.A. - F5W8+FRM, Caracas 1071, Miranda, Venezuela",
"PRC333, C.A. - Av. Diego Cisneros, Edif. Centro Empresarial Danisa, Urb, Caracas 1071, Miranda, Venezuela",
"SimCardRental - Centro Ciudad Comercial Tamanaco nivel C1 Caracas, Caracas 1060, Distrito Capital, Venezuela",
};
}
