class AutoSuggestions74889152 { static final reviewedTitles74889152 = const {"Opti Ávila, C.A - Av Abraham Lincoln CC Sabana Grande Nivel PB Local MT-PB, 9 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"Inversiones Bodemax 2019, C.A - Calle Negrín CC Mini Tiendas 199 Nivel PB Local 36 Urbanización, Caracas 1050, Distrito Capital, Venezuela",
"El portal MiniMarket - Avenida Mohedano con Calle Urdaneta local gm-25, Mercado Municipal de Chacao, Caracas 1060, Miranda, Venezuela",
"Suministros AFI C.A - 1070 Caracas, Caracas 1071, Distrito Capital, Venezuela",
"Autorepuestos21 C.A - 1050 Caracas, Caracas 1050, Distrito Capital, Venezuela",
"Moto Repuestos El Ruso - Mercado César Nieves piso 1 local 387 Catia la mar vargar, Catia La Mar 1162, La Guaira, Venezuela",
"Kiosco Betania - Calle Villaflor, Entre Boulevard de Sabana Grande, y, Av. Casanova, Caracas 1050, Distrito Capital, Venezuela",
"Quisco Yosiani - Final AV. Casanova, Frente a Hotel las Americas Caracas, F4RH+2VR, Caracas 1050, Distrito Capital, Venezuela",
"Centro Comercial Único - Blvr. de Sabana Grande, Caracas 1060, Distrito Capital, Venezuela",
"Restaurant El Semáforo - F4RJ+6P6, Caracas 1060, Miranda, Venezuela",
"Comercial Maria Mia C.A - Avenida los Jabillos, Edificio Continental, PB Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"Ferre electricos vizcaya c.a - 9 C. 4 Bis, San Cristóbal 5001, Táchira, Venezuela",
"Quiosco Mifla - Frente al Centro Comercial Chacaito Chacaito, Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
"Space CCS C.A - C.C City Market, Piso 4 Local 439, Caracas 1050, Caracas 1050, Distrito Capital, Venezuela",
"Cyber Café JKVO C.A - 4 Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
"Comercializadora de Alimentos 218 C.A - Edificio Proto Fijo, PB Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
"IEPAN - calle Guaicaipuro, centro comercial metropolitano, local 42, Chacao. (A 3 cuadras de la Pastelería Danubio), Avenida Guaicaipuro, Caracas 1060, Distrito Capital, Venezuela",
"Supermercado Negrin - Parque Negrin, 6 C. Negrín, Caracas 1050, Distrito Capital, Venezuela",
"Feria de la confiteria chacaito - Final Avenida Casanova, Frente al Hotel Las Américas, F4RH+5QF, C. Chacaíto, Caracas 1050, Distrito Capital, Venezuela",
"Quiosco Central - Frente al Centro Comercial Chacaito Chacaito, Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
"Charcuteria y Carniceria MR - 3era Avenida de las Delicias, Edificio, Planta baja, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"Majagua bar Caracas - Av José, María Varga, norte, Caracas 1080, Distrito Capital, Venezuela",
"Don Manuel Grill - C. Los Baños, Maiquetía 1161, La Guaira, Venezuela",
"W&BEYELASH - Mercado Comunitario Cesar Nieves, Piao 2, Local nro. 344, Catia La Mar 1162, La Guaira, Venezuela",
"Abasto Mimar - Edificio las Delicias, 3ra Avenida de, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"Club de Videos LaFa C.A - C.C. Chacaito, Local 165 - 2 Boulevard de Chacaito Caracas, Caracas 1050, Distrito Capital, Venezuela",
"Restaurant Carlos IV - C.C Sábana Grande, nivel feria, 11 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"Stephinet Solutions - C.C. SABANA GRANDE ,NIVEL PB LOCAL PB-12 CARACAS, Caracas 1050, Distrito Capital, Venezuela",
"Zetron - Sabana Grande, bajando por la, F4VF+6CM, C. Negrín, Caracas 1050, Distrito Capital, Venezuela",
};
}
