class AutoSuggestions90671291 {
  static final reviewedTitles90671291 = const {
    "Joyas Juan del Gaudio - Av. Libertador. Multicentro Empresarial del Este, Local 20. Nivel Miranda, Caracas 1060, Miranda, Venezuela",
    "Fotocopias Marbelia, C.A - Calle Miranda, Casa N° 24-10, Local 1, Barrio Sucre, La Cañada, Caracas 1030, Distrito Capital, Venezuela",
    "Kiosko Raysol - Calle Nicolas Copernico &amp;, Avenida Principal de las Mercedes, Caracas 1080, Miranda, Venezuela",
    "AMD Computer Shop - G33M+R4M, Caracas 1014, Capital District, Venezuela",
    "Comercializadora somos sazón k.y,c.a - F3WJ+CH9, Caracas 1014, Capital District, Venezuela",
    "Foto Relampago C.A. - Edificio Plaza Miranda, Torre A, Nivel PB, Local 9, Av Baralt, Zona Postal, con Av. Oeste 8 Bis, Caracas 1010, Distrito Capital, Venezuela",
    "Inv. Di-Quesos 2000 - Avenida Sur 2, entre esquina de Hospital a Cárcel, Edif. Belmonte, planta baja, Local 1 Av Sur 2, Caracas 1014, Distrito Capital, Venezuela",
    "MOTORCYCLES LOS ANDES C.A - Prolongacion de la 5ta avenida , edificio Maxicol local 1 al lado de bicicletas, al M. Publico, 5ta. Av &quot;Francisco García de Hevia&quot;, San Cristóbal 5001, Táchira, Venezuela",
    "Kiosko lorena - Calle abanico a socorro frente a la residencia el dorado diagonal a pdval Parroquia Altagracia diagonal a la, Avenida Fuerzas Armadas, Caracas 1020, Distrito Capital, Venezuela",
    // "Joyas Juan del Gaudio - Av. Libertador. Multicentro Empresarial del Este, Local 20. Nivel Miranda, Caracas 1060, Miranda, Venezuela",
    "Kiosco Ortega- M - Esquina de Perico a San Lazaro.. Av Universidad. Mercado La Hoyada, Pasillo ARAGUA, local 940 941, Caracas 1011, Avenida Universidad, Caracas 1011, Distrito Capital, Venezuela",
    "Santa Barbara, C.A - Avenida Baralt, entre calle Maderero y Calle Miranda, Edificio Miranda, Nivel PB, Local A, G32J+4H7, Caracas 1014, Distrito Capital, Venezuela",
    "Emprendedora Jj 2017, C.A - Avenida Principal de las Mercedes, Kiosco N°13, con C. Mucuchíes, Caracas 1080, Miranda, Venezuela",
    "Cafetin con sabor chacaro - Calle 5 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "Auto repuestos Canmar - Calle5, San Cristóbal 5001, Táchira, Venezuela",
    "Inversiones García Guzman, C.A. - Av. Universidad, con Av Baralt, Esquina de Pedrera, Galerías José Antonio Páez, P.B, Local 1, Diagonal al C.C. Metro Center, Capitolio, Caracas 1012, Caracas 1012, Distrito Capital, Venezuela",
    "Quincalla y Ferretería Zapata, C.A. - Calle Ayacucho, Cruce con Calle Miranda, P.B, Casa n° 23-10, Local 1, Frente a la Redoma del Bloque 7, La Cañada, Caracas 1030, Distrito Capital, Venezuela",
    "Mini Market DS, C.A - J263+346, Maiquetía 1162, Vargas, Venezuela",
    "TecnoLion MerpoEste - Centro Comercial MerpoEste, C. Los Ángeles, Caracas 1064, Distrito Capital, Venezuela",
    "Burger Center - Centro Comercial Metrocenter Nivel Amarillo Local PA-07, Caracas 1012, Distrito Capital, Venezuela",
    "La botanita mexicana - Av. Baralt con esquina pedrera, cc metrocenter, nivel colonial, paseo colonial, local mp29, Av. Baralt, Caracas 1012, Distrito Capital, Venezuela",
    "Andina Venezolana del Repuesto - QQ48+W8Q, Carrera 6 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "INVERSIONES ARANGO TECHNOLOGY C,A - CHACAO MULTICENTRO EMPRESARIAL DEL ESTE TORRE MIRANDA NUCLEO A LOCAL PB 10 GRAN CARACAS, Caracas 1060, Miranda, Venezuela",
    "Blue Store - Calle Chico Carrasquel con Calle Los Angeles. Local 46, Nivel PB. 1060, Caracas 1064, Miranda, Venezuela",
    "Mamro Cell - local 27, Centro comercial Plaza, Caracas 1011, Distrito Capital, Venezuela",
    "Maison Plaza - F5W3+JQR, Caracas 1060, Miranda, Venezuela",
    "V58 Store City Market 4 - C.C City Market, Nivel PB, Local Arca, N° 456 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Mr.ShopCcs - C.C. Metrocenter Pasaje Contemporáneo, Local MT08 Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Kiosko Restaurant mi Rinconcito - Playa Candilejas, Calle Real De Playa Verde, Maiquetía 1162, La Guaira, Venezuela",
    "Frigorífico El Imperio del Pollo - JX26+586, Avenida El Ejército, Catia La Mar 1162, Vargas, Venezuela",
    "Kiosko restaurant Oshun - Playa Culito, Calle Real De Playa Verde, Maiquetía 1162, La Guaira, Venezuela",
    "Autopartes Bencarmotor - QQ48+85Q, Calle 6, San Cristóbal 5001, Táchira, Venezuela",
    "Inversiones Cleoribet, C.A. - Av. Baralt, Esquina de Pedrera, Centro Comercial Galerías Capitolio, PB, Local P6F2, Capitolio, Caracas 1030, Caracas 1012, Distrito Capital, Venezuela",
    "Di Catia Pizza,C.A. - 2da Avenida, Entre Boulevar España y Calle Colombia, Quinta Corazón de Jesús, Local 1, Caracas 1030, Distrito Capital, Venezuela",
    "Repuestos Guayas Car's - QQ48+C5C, Carrera 6 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "Mesón de Pita Restaurante - F4RW+XC8, Caracas 1060, Miranda, Venezuela",
    "Molise Bistro - Centro, Caracas 1012, Caracas 1012, Caracas 1012 Edificio Carmo Caracas, Caracas 1012, Distrito Capital, Venezuela",
    "Perfumescss Metrocenter - Centro comercial metrocenter nivel avenida local pb-2 Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Tocoquera 2021, C.A. - F3WJ+WQP, Caracas 1014, Capital District, Venezuela",
    // "Inversiones Tocoquera 2021, C.A. - F3WJ+WQP, Caracas 1014, Capital District, Venezuela",
    "PC MANIA, C.A. - Av. Francisco de Miranda, Multicentro Empresarial del Este, Edif. Central Planta Baja, Local PB-24, Caracas 1060, Miranda, Venezuela",
    "Joyeria Liria C. A. - Av. Libertador con Av. José Félix Sosa. Multicentro Empresarial del Este Chacao, Nivel Miranda, local 9, Caracas 1060, Miranda, Venezuela",
    "Maniceria Parque Caracas, c.a - Caracas, 1011, Distrito Capital, Venezuela",
    "Lolar store - Centro comercial Merpoeste, piso 1, pasillo tigre, local 125. Chacao, Caracas 1060, Caracas, Caracas 1060, Distrito Capital, Venezuela",
    "Los Golfeados de Samuel - Merpoeste. Piso 2 Local 105 Nivel Los Andes, Pasillo Manatí, C. Chico Carrasquel, Caracas 1060, Miranda, Venezuela",
    "Inversiones Samar - Piso 3 ultimo piso nivel feria de comida Centro Comercial Merpoeste, Local 49 C. Los Ángeles, Caracas 1071, Miranda, Venezuela",
    "Antojitos Restaurant - Local 322 Mercado comunitario de, Catia La Mar 1162, La Guaira, Venezuela",
    // "Antojitos Restaurant - Local 322 Mercado comunitario de, Catia La Mar 1162, La Guaira, Venezuela",
    "T lo tengo 31, C.A - Esquina de Avilanes a Rio, Edificio Doravi, Local F Pb, G34W+R86, Caracas 1010, Distrito Capital, Venezuela",
    "Panaderia el cubo Azul c.a. - Av oeste 6 esquina de Mercaderes con esquina la Gorda Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Almicell - Madrices a San Jacinto, Edificio Auge, Nro 8, Parroquia, Caracas 1010, Distrito Capital, Venezuela",
    "Junqui Fresas Norkys Chacao - Local 9H. Planta Baja. Avenida Libertador con Calle Elice. Edificio Rudolf, Caracas 1060, Miranda, Venezuela",
    "DeliExpress Barrio Obrero - Barrio Obrero Carrera 21 Entre calle 10 y, Pasaje Acueducto, San Cristóbal 5001, Táchira, Venezuela",
    "Kiosco mi orgullo - Playa Candilejas, Calle Real De Playa Verde, Maiquetía 1162, La Guaira, Venezuela",
    "CENTRO HIPICO PITAZO SPORT BOOK - F4QM+62M, Avenida Guaicaipuro, Caracas 1060, Distrito Capital, Venezuela",
    "Candy Man Globos RL - Esquina Gradillas a San Jacinto Edif. Gradillas C Piso PB Local 2 Urb. Catedral Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Haysali - G35R+636, Caracas 1010, Capital District, Venezuela",
    "4 EVER PHONE, C.A. - G34P+7WG, Avenida Sur 1, Caracas 1012, Distrito Capital, Venezuela",
    "inversiones super chick c.a - G37R+FQQ, Avenida Fuerzas Armadas, Caracas 1010, Distrito Capital, Venezuela",
    "AquaPalma CA - Calle Cumana c/c Ppal de Las Palmas Edf Rosa, Local D, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones mi cabrita - local hm-11 mezzanina, Mercado Municipal de Chacao, Caracas 1060, Distrito Capital, Venezuela",
    "kiosco Negrin - Calle negrin con esquina, Calle Los Apamates, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Moncherri One, C.A - Av Los Jabillos, entre los Árboles Piso 1 Apto 104. Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Olofidio Mary, C.A - Calle Las Flores Edif. Libertador 1 Torre B Local PB Urb, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Repuestos Orlando Motos - Calle 5, San Cristóbal 5001, Táchira, Venezuela",
    "AdriCar's - Calle 5, con carrera 5, San Cristóbal 5001, Táchira, Venezuela",
    "Bar y Restaurante El Meson De Cervantes - 8 Av. Urdaneta, Caracas 1010, Distrito Capital, Venezuela",
    "Proyectos Yaku Kiria Refill - Av. Fuerzas Armadas Esquina de Socorro Edif. Conjunto residencial El Dorado Piso PB Local 4-1 Urb, Caracas 1010, Distrito Capital, Venezuela",
    "Repuestos Viking Moto, C.A - Av. Norte Nueve Edif. San Onofre Piso PB Local 1 Sector Las Esquinas De Animas Caracas Caracas, Caracas 1030, Distrito Capital, Venezuela",
    "BRYGA 325748, C.A - C.C. Plaza La Candelaria PB Local 4 Esquina de Candilito a Cruz frente a La Plaza, Caracas 1010, Distrito Capital, Venezuela",
    "Víveres Deisy - Av. Sur 15 Local San Luis Nro 3C Y 4D Sector Entre las Esquinas de Peligro a, Edificio Alcabala, Caracas 1010, Distrito Capital, Venezuela",
    "V58 STORE SAMBIL CARACAS - AV LIBERTADOR CC SAMBIL NIVEL ACUARIO LOCAL AC-C19SECTOR, Caracas 1064, Miranda, Venezuela",
    "Kaprichos Susy C.A - Edificio El Tejar y Mohedano, Nivel Sotano 1, Local NCS, 19 Avenida Lecuna, Caracas 1015, Distrito Capital, Venezuela",
    "ToyoMotors Malpica - Calle 5, San Cristóbal 5001, Táchira, Venezuela",
    "El Buen Sabor Andino - Esquina Miguelacho a Tracabordo Edif. Cachazo Piso PB Local Nro 12 Urbanización, Caracas 1010, Distrito Capital, Venezuela",
    "Mundi Partes Alejandro - Calle 5, San Cristóbal 5001, Táchira, Venezuela",
    "171 Emergencia, C.A. - Av. Don Bosco, con 1ra Transv., Edif. 171 Emergencia CA,, Caracas 1050, Distrito Capital, Venezuela",
    "Hotel Royal Palace - F4WH+VPG, Calle Cantuara, Caracas 1050, Distrito Capital, Venezuela",
    "Casona Gourmet - 6 C. Negrín, Caracas 1060, Distrito Capital, Venezuela",
    // "Casona Gourmet - 6 C. Negrín, Caracas 1060, Distrito Capital, Venezuela",
    // "Casona Gourmet - 6 C. Negrín, Caracas 1060, Distrito Capital, Venezuela",
    "Restaurante Mr. Alí - Calle Pascual Navarro Antigua San Antonio, Local Hotel Royal Urb, F4V9+WPG, Blvr. de Sabana Grande, Caracas 1059, Distrito Capital, Venezuela",
    "Autopartes Hidalgo Todo Corsa - Calle 6 entre carrera 6 y prolongacion de la, 5ta. Av &quot;Francisco García de Hevia&quot;, San Cristóbal 5001, Táchira, Venezuela",
    "Luncheria Madame Fru Fru self service. - Centro empresarial del este, planta ingreso, local 2. Caracas 1060, Caracas 1060, Distrito Capital, Venezuela",
    "Rapiforros Caracas c.a - n 54 Calle Pedroza, Caracas 1050, Distrito Capital, Venezuela",
    "Comercializadora el Rincón del Gordo Juanky, C.A - Calle Ávila, quinta Perijá PB Mncp. Libertador, G42H+M8M, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones MM 2020 - Metrobus Ávila I, Av. Juan Bautista Arismendi, Caracas 1050, Distrito Capital, Venezuela",
    "Kanji Sushi Barquisimeto - 22 y 23 C. 15, Barquisimeto 3001, Lara, Venezuela",
    "Metrolandia center 18k C.A - Avenida universidad centro comercial metrocenter local pb-m4 Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Delicatessen Willson 2 - Planta Baja, Edificio Mary, local A, Av. Andrés Bello, Caracas 1050, Distrito Capital, Venezuela",
    "Nomada Store - Av. El Parque Cruce con Av. Urdaneta CC. Galerías Ávila Local P68 Urb, Caracas 1011, Distrito Capital, Venezuela",
    "Óptica Contact-o-Lent C.A - F5X3+54Q, Caracas 1060, Miranda, Venezuela",
    "Comercializadora BS 3000 - Avenida principal de Maripérez, Quinta Tibidabo, PB, frente a la Toyota. Caracas 1050, Caracas 1050, Distrito Capital, Venezuela",
    // "Comercializadora BS 3000 - Avenida principal de Maripérez, Quinta Tibidabo, PB, frente a la Toyota. Caracas 1050, Caracas 1050, Distrito Capital, Venezuela",
    "Oasis H²O - G434+Q2M, Transversal 2 Sur, Caracas 1050, Distrito Capital, Venezuela",
    "Home Clean JC - Avenida principal de Sarria, calle real Los Cortijos de Sarria, urbanización, local 10, Caracas 1050, Distrito Capital, Venezuela",
    "Plaza Bolívar Caracas - Edificio Casa del Profesor, Av. Las Acacias, Caracas 1041, Distrito Capital, Venezuela",
    "Game Play Centro - Av. Urdaneta, Torres a Veroes, Mini Centro Plaza Bolívar, Locales 89 y, 94 Av. Urdaneta, Caracas 1012, Distrito Capital, Venezuela",
    "Cindy's Studio - Parroquia Carlos Soublette Pariata. 2da calle los 2 cerritos, La Guaira 1161, La Guaira, Venezuela",
    "Restaurante Las Vegas II,C.A - Esq. De Torres A Veroes Edificio. 6 Piso PB parroquia Catedral Caracas, Caracas 1060, Distrito Capital, Venezuela",
    "El Papá de las Gorras, C.A - Esq. La Marron Edif. Galerias la Marron Piso PB Local 6 Urb. Pquia. Catedral Caracas, Caracas 1030, Distrito Capital, Venezuela",
    "Inversiones FASYMJ, C.A - Esquina Marrón a Madrices Edif. 38 PB Local 2 Urbanización Catedral Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "ABA Electronic, C.A - Esquina Gradillas Edif.Centro Pasaje Gradillas Piso PB Local 5 Zona, Caracas 1010, Distrito Capital, Venezuela",
    // "Candy Man Globos RL - Esquina Gradillas a San Jacinto Edif. Gradillas C Piso PB Local 2 Urb. Catedral Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "MODAKIDS - Avenida sur 1 Esquina Madrices a San Jacinto, Centro de Caracas, Centro Comercial Galerias Edsam, Pb28 Urb. Catedral, Caracas 1012, Distrito Capital, Venezuela",
    "My First Princess, C.A. - Esq candilito a la cruz Edf centrol locatel Pb local 8A Caracas, Caracas 1011, Distrito Capital, Venezuela",
    "Hotel Crillon Suites - Esquina, Av. Libertador, Caracas 1050, Distrito Capital, Venezuela",
    "Kartofell La Papota del Sabor, C.A - Planta baja, esquina Coromoto, Edificio Oramas, Local 6 Av. Casanova, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Todo Oficina Y Computación C.A. - Esquina de Candilito a Cruz de Candelaria, G34V+9W4, Caracas 1011, Distrito Capital, Venezuela",
    "Inversiones RRR - Esquina Paradero Av Venus Edif Venus Piso PB Local A, Urb. Terrazas de Guaicoco, Caracas 1010, Distrito Capital, Venezuela",
    "Dilybert Serv Cell - C.C. Plaza Candelaria, Nivel MZ Local 07-A ➗ Banco Provincial y C.C. Reservista Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "V58 STORE SAN IGNACIO - Av Blandin CC San Ignacio Nivel Jardin Local J-36, Caracas 1060, Miranda, Venezuela",
    "Shenzhen Electronics - Calle Norte 13 Esq. Cruz a Candilito Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Panaderia Safari Bakery - G33W+R7R, Caracas 1011, Capital District, Venezuela",
    "Restaurante Novo Akelarre - Caracas 1011, Capital District, Venezuela",
    "CANDY SHOP CRUNCHY C.A - AV ESTE 0 CON SUR 21 C.C.PARQUE CARACAS NIVEL PLANTA BAJA LOCAL 44 ALADO DE BURGER KING, Caracas 1010, Distrito Capital, Venezuela",
    "Bartolo's Pizza - G33X+GMR, Caracas 1011, Capital District, Venezuela",
    "ZONA PARTS - Av. Principal de Maripérez, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Toyomen 360 - local 2, Av. Principal de Maripérez, entre 6ta y 9na transversal. Quinta Gloria PB, Av. Principal de Maripérez, Caracas 1050, Distrito Capital, Venezuela",
    "Agridulce Sabores - av. intercomunal del valle, con calle el palmar. Res, C. 19 De Abril, Caracas 1090, Distrito Capital, Venezuela",
    "Ferretería Mfwollmer - Av. Vollmer, Caracas 1011, Distrito Capital, Venezuela",
    "Quinservices 21 C.A. - Av. Wollmer, Centro Comercial Lord Center, Sotano 1 L-17, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones azriel 2020 c.a - avenida principal de camburito numero 410-a, Maracay 2102, Aragua, Venezuela",
    "Petalos Café - Av. Wollmer, CC Lord Center Nivel Feria, L-S1-40, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones The champions JN y GR - C.C. Sábana Grande, local MT20, 11 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Rest. Casa Bermeo - G33X+J2C, Avenida Sur 17, Caracas 1011, Distrito Capital, Venezuela",
    "JN Global Celular - C.C.City Market, Bulevar de Sabana Grande, Nivel Boulevard, local 232, nível 4, Local MT20 Caracas 1050, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Dulceria el milagro de Theos - Edificio El Tejar y Mohedano, Avenida Lecuna, Caracas 1015, Distrito Capital, Venezuela",
    "Willmarket - Parque Central, Sótano 1, local 2Cs05, Caracas 1015, Caracas 1015, Caracas 1015, Distrito Capital, Venezuela",
    "Laminados Central Park - Todo para el carpintero - Parque Central, Sótano 2, Sector E, locales 47 al 50, Caracas 1015, Caracas 1015 Caracas, Caracas 1014, Distrito Capital, Venezuela",
    "Charcutería Fraga 2020, C.A - Calle Norte 7 Entre la esquina de Socorro Y San Ramón Edif. Torre Jadim Piso PB Local 49 Urb, Caracas 1010, Distrito Capital, Venezuela",
    "Charcuteria y delicateses Stuart Little, c.a. - av. fuerzas Armadas. entre esquinas San Enrique a San José. local 10 Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Alexvall, C.A - Av. Fuerzas Armadas CC. Teleader Los Andes Nivel PB Local, G37V+P3W, Av. A-1, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Mascotalandia - G36R+PQR, Caracas 1010, Capital District, Venezuela",
    "Inversiones Mascotalandia II, C.A - AV. Fuerzas Armadas Edif. Acre Piso PB Local Urb, G39P+7R5, Av. San José Del Ávila, Caracas 1010, Distrito Capital, Venezuela",
    "Comercial Santa Ana 2008, C.A - Av. Éste 2 Edif. Cabudare Piso PB Local Mezzanine Nro 1 Urb, Caracas 1010, Distrito Capital, Venezuela",
    "RDCELL 2019, C.A - Av Abraham Lincoln Con Calle Union Y Villaflor CC. City market Nivel PB Local 150 Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Al Giorno C.A. - Sótano 1 Locales, Edificio El Tejar y Mohedano, 33 y 37 Avenida Lecuna, Caracas 1015, Distrito Capital, Venezuela",
    "Judibana 2010 C.A - Edificio El Tejar y Mohedano, Sótano 1, Local 2CS06, Avenida Lecuna, Caracas 1015, Distrito Capital, Venezuela",
    "Modas CV C.A. - Edificio El Tejar y Mohedano, Sótano 1, Local NCS, 08 Avenida Lecuna, Caracas 1015, Distrito Capital, Venezuela",
    "Luz Publicidad C.A. - Edificio El Tejar y Mohedano, Sótano 1, Local 2CS04, Avenida Lecuna, Caracas 1015, Distrito Capital, Venezuela",
    "Gigis Diseños Exclusivos - C.C Locatel, Esquina de Cruz a Candelito, Urb, G34V+4W6, Caracas 1010, Distrito Capital, Venezuela",
    "Electronica Nivel Urdaneta - G34W+CXX, Avenida Urdaneta, Caracas 1011, Distrito Capital, Venezuela",
    "Only Electronic - Calle El Parque, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Inversiones Pollo Rico 2013, C.A - Esquina Miguelacho a Peligro Edif. Ivón PB Local Nro B Sector, G33W+C2J, Caracas 1010, Distrito Capital, Venezuela",
    "Limpex Service C.A - Edificio El Tejar y Mohedano, Avenida Lecuna, Caracas 1015, Distrito Capital, Venezuela",
    "Agropecuaria la fortuna - Parque Central, Edificio San Martín, Pasillo peatonal, local F, Caracas 1015, Caracas 1015 Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Distribuidora Hortifrutas XXI, C.A - Esquina Ferrenquin a Tracabordo Edif. Ferrenquin Piso PB Local G Sector Las, G34V+7C2, Caracas 1010, Distrito Capital, Venezuela",
    "Opti Ávila, C.A - Av Abraham Lincoln CC Sabana Grande Nivel PB Local MT-PB, 9 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Bodemax 2019, C.A - Calle Negrín CC Mini Tiendas 199 Nivel PB Local 36 Urbanización, Caracas 1050, Distrito Capital, Venezuela",
    "El portal MiniMarket - Avenida Mohedano con Calle Urdaneta local gm-25, Mercado Municipal de Chacao, Caracas 1060, Miranda, Venezuela",
    "Suministros AFI C.A - 1070 Caracas, Caracas 1071, Distrito Capital, Venezuela",
    "Autorepuestos21 C.A - 1050 Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Moto Repuestos El Ruso - Mercado César Nieves piso 1 local 387 Catia la mar vargar, Catia La Mar 1162, La Guaira, Venezuela",
    "Kiosco Betania - Calle Villaflor, Entre Boulevard de Sabana Grande, y, Av. Casanova, Caracas 1050, Distrito Capital, Venezuela",
    "Quisco Yosiani - Final AV. Casanova, Frente a Hotel las Americas Caracas, F4RH+2VR, Caracas 1050, Distrito Capital, Venezuela",
    "Centro Comercial Único - Blvr. de Sabana Grande, Caracas 1060, Distrito Capital, Venezuela",
    "Restaurant El Semáforo - F4RJ+6P6, Caracas 1060, Miranda, Venezuela",
    "Comercial Maria Mia C.A - Avenida los Jabillos, Edificio Continental, PB Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Ferre electricos vizcaya c.a - 9 C. 4 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "Quiosco Mifla - Frente al Centro Comercial Chacaito Chacaito, Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
    "Space CCS C.A - C.C City Market, Piso 4 Local 439, Caracas 1050, Caracas 1050, Distrito Capital, Venezuela",
    "Cyber Café JKVO C.A - 4 Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
    "Comercializadora de Alimentos 218 C.A - Edificio Proto Fijo, PB Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
    "IEPAN - calle Guaicaipuro, centro comercial metropolitano, local 42, Chacao. (A 3 cuadras de la Pastelería Danubio), Avenida Guaicaipuro, Caracas 1060, Distrito Capital, Venezuela",
    "Supermercado Negrin - Parque Negrin, 6 C. Negrín, Caracas 1050, Distrito Capital, Venezuela",
    "Feria de la confiteria chacaito - Final Avenida Casanova, Frente al Hotel Las Américas, F4RH+5QF, C. Chacaíto, Caracas 1050, Distrito Capital, Venezuela",
    "Quiosco Central - Frente al Centro Comercial Chacaito Chacaito, Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
    "Charcuteria y Carniceria MR - 3era Avenida de las Delicias, Edificio, Planta baja, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Majagua bar Caracas - Av José, María Varga, norte, Caracas 1080, Distrito Capital, Venezuela",
    "Don Manuel Grill - C. Los Baños, Maiquetía 1161, La Guaira, Venezuela",
    "W&BEYELASH - Mercado Comunitario Cesar Nieves, Piao 2, Local nro. 344, Catia La Mar 1162, La Guaira, Venezuela",
    "Abasto Mimar - Edificio las Delicias, 3ra Avenida de, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Club de Videos LaFa C.A - C.C. Chacaito, Local 165 - 2 Boulevard de Chacaito Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Restaurant Carlos IV - C.C Sábana Grande, nivel feria, 11 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Stephinet Solutions - C.C. SABANA GRANDE ,NIVEL PB LOCAL PB-12 CARACAS, Caracas 1050, Distrito Capital, Venezuela",
    "Zetron - Sabana Grande, bajando por la, F4VF+6CM, C. Negrín, Caracas 1050, Distrito Capital, Venezuela",
    "Infiniti Cell C.A - C.C. City Market, Piso 4, Local 436, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Lion Tech - Entre Boulevard De Sabana grande y Av. Casanova Callejón Borges Edificio Permontsa, piso 2 ofic 8, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Tinna C.A - Mercado Municipal de Chacao, Caracas 1040, Distrito Capital, Venezuela",
    "Katykar bodegon - 1070 Caracas, Caracas 1071, Distrito Capital, Venezuela",
    "Panadería Regal - F4Q9+HFP, Caracas 1041, Capital District, Venezuela",
    // "Lion Tech - Entre Boulevard De Sabana grande y Av. Casanova Callejón Borges Edificio Permontsa, piso 2 ofic 8, Caracas 1050, Distrito Capital, Venezuela",
    // "Katykar bodegon - 1070 Caracas, Caracas 1071, Distrito Capital, Venezuela",
    "Tu Dulce Tentación Caracas - Edificio Blanca Araya, Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
    "Margaritas Cakes Caracas - Av Intercomunal Valle Coche, Residencias La Rinconada, Piso 1, Caracas 1090, Distrito Capital, Venezuela",
    "Kiosco El Toldito Amarillo - Calle los angeles, frente al centro comercial Merpoeste, F4QV+QVJ, Caracas 1060, Distrito Capital, Venezuela",
    "Tasca Restaurant Madame Fru Fru - Multicentro Empresarial del Este, Av. Libertador, Caracas 1060, Miranda, Venezuela",
    "Kiosco Elice - Av. Elice, Entre Libertador y, F4RV+8Q7, Avenida Francisco de Miranda, Caracas 1060, Distrito Capital, Venezuela",
    "BODEGON LA FORTALEZA & 2020 C.A FRUTERIA Y PANIFICADORA - 0102 Caracas, Caracas 0102, Distrito Capital, Venezuela",
    "ToyoFord - Calle5, San Cristóbal 5001, Táchira, Venezuela",
    "Punto y Coma - Quinta Soledad Calle principal de, G442+8HP, Caracas 1050, Distrito Capital, Venezuela",
    "Kiosco El Poeta - Av. Andres bello, G434+WFP, 4ta Transversal, Caracas 1050, Distrito Capital, Venezuela",
    "La Principal Renault F-1 C.A - San Cristobal 5001, Táchira, Venezuela",
    "SH GENERICOS Y MAS - QQ49+XXJ, Calle 4 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "Tiendas Yaris - C.C MetroCenter, Caracas 1234, Distrito Capital, Venezuela",
    "Purificadora de agua alda - G422+WG4, Av Este 2, Caracas 1011, Distrito Capital, Venezuela",
    "Centro de Copiado Bargoni - Av. Norte 13, Local 27, Centro Comercial Candilito, con Av. Urdaneta, Caracas 1010, Distrito Capital, Venezuela",
    "restaurante mosoly - plaza local16 bp, Centro Comercial Galería, Av. Urdaneta, Caracas 1011, Distrito Capital, Venezuela",
    "Hamaca Cafe - Av. Avila con Urdaneta, CC Galerias Avila, Nivel Anauco, L-A41, Caracas 1011, Distrito Capital, Venezuela",
    "Optimoda - Av. Avila con Urdaneta, CC Galerias Avila, Nivel Parque, L-P58, Caracas 1011, Distrito Capital, Venezuela",
    "Importadora 212 - Centro comercial Galerías Ávila, local U36, Caracas 1011, Distrito Capital, Venezuela",
    "Centro de Copiado Speed Copy J & G - G432+99P, Caracas 1011, Capital District, Venezuela",
    "Edgar Yanez Repostería - local gm-15, Mercado Municipal de Chacao, Caracas 1060, Miranda, Venezuela",
    "Toner Xpres - Edificio San Martín, Caracas 1015, Distrito Capital, Venezuela",
    "Comercial Ponketa - Edificio San Martín, Caracas 1015, Distrito Capital, Venezuela",
    "Truco Café C.A - Edificio San Martín, Pasillo peatonal, local E, Caracas 1015, Caracas 1015, Caracas 1015, Distrito Capital, Venezuela",
    "Mundo Tavo Cell C.A. - Parque Central, Edificio San Martín, Pasillo peatonal, local F, Caracas 1015, Caracas 1015, Caracas 1060, Distrito Capital, Venezuela",
    "Beat Celular C.A. - mini tiendas 6 y 8 Centro Parque Caracas. Torre E, Av. Este 0, Caracas 1011, Distrito Capital, Venezuela",
    "Restaurant Royal - G42H+H54, C. Real de Chapellín, Caracas 1050, Distrito Capital, Venezuela",
    "Batstore.ve - Calle Villaflor con Union, CC City Market N- Plaza Local Kiosco K-178 Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "La Merienda Express, C.A - Av Juan Bautista Arismendi, local 75A, con C. Negrín, Caracas 1050, Distrito Capital, Venezuela",
    "Kiosko Alexmar - Calle Arismendi Frente al CC, G42G+JP3, Caracas 1050, Distrito Capital, Venezuela",
    "Distribuidora Alfredroame - Av Andrés Bello entre las Palmas y Las acacias, Quinta Lilian, G43C+77G, Norte 12, Caracas 1060, Distrito Capital, Venezuela",
    "Abasto y Perfumería los Tres Casiques - Calle tercera Transversal Norte Quinta Coromoto PB Local 2 Urbanización Guaicaipuro, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Bella 2012 C.A. - Av. Wollmer, Edf. Caracas, PB, L-3, Caracas 1011, Distrito Capital, Venezuela",
    "Soluciones ACJ 1938, C.A - https://www.facebook.com, Local 63, Soluciones-ACJ-CA, C. El Muñeco, Caracas 1060, Miranda, Venezuela",
    "Mercado Bolivariano de La Hoyada - mercado la hoyada, Caracas 1010, Distrito Capital, Venezuela",
    "Perros Calientes y Hamburguesas Ortega M - Entrada mercado Bolivariano La Hoyada, G33R+26R, Avenida Fuerzas Armadas, Caracas 1012, Distrito Capital, Venezuela",
    "INVERSIONES CORALEMI C.A - JX3F+2GQ, C. 15, Catia La Mar 1162, La Guaira, Venezuela",
    // "Perros Calientes y Hamburguesas Ortega M - Entrada mercado Bolivariano La Hoyada, G33R+26R, Avenida Fuerzas Armadas, Caracas 1012, Distrito Capital, Venezuela",
    "ADVERSUM5 - C.C. Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Moder Cell AD 2021 - Centro Comercial City Market, nivel feria galerias, local 321, Caracas 1050, Distrito Capital, Venezuela",
    "Bluaxcel, C.A - Av Casanova CC City Market Nivel 4 Local 421 Urb, Caracas 1040, Distrito Capital, Venezuela",
    "COMERCIALIZADORA IREMI - Avenida Quito, Caracas 1050, Caracas 1041, Distrito Capital, Venezuela",
    "Genius Machine Import, C.A - Av. Abraham Lincoln Entre calle unión Y Miraflor CC city market Nivel Feria, Local 324, Caracas 1050, Distrito Capital, Venezuela",
    "Grupo Global Tec 2724, C.A - Calle Villa flor con Boulevard de sabana grande Cc City Market Nivel Mezz Local B319, Caracas 1050, Distrito Capital, Venezuela",
    "Ovistore - Calle Villaflor CC Sabana Grande, Nivel Feria Local 12 Pasillo Central Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Centro Comercial del Este - F4VC+P2V, Av. Casanova, Caracas 1050, Distrito Capital, Venezuela",
    "electronica Marsali - Calle las palmas, Edf. OPP 16 PB L-2, Caracas 1050, Distrito Capital, Venezuela",
    "Superformica C.A - Caracas 1050, Capital District, Venezuela",
    "Mangueras los Molinos - QQ5C+C3P, San Cristobal 5001, Táchira, Venezuela",
    "Serviphone - 1071 Caracas, Caracas 1071, Distrito Capital, Venezuela",
    "Coffe Party Piñateria - CC del Este, Nv. PB L-16 Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Coffe Party Automotriz - CC del Este Nv PB, L-14 Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Forromania - Calle Villaflor con Union, CC City Market, N, L-175 C. El Kiosco, Caracas 1050, Distrito Capital, Venezuela",
    "Tecnova - Calle Villaflor con Union C.C. Sabana Grande, N-Feria, L-1 Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Yumarca 44, C.A - Av. Abraham lincolin CC. City Market Nivel Plaza Local 168 Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Grupo Dinero Express C.A - F4VF+479, Av. Casanova, Caracas 1050, Distrito Capital, Venezuela",
    "Bodegón y Delicateses La Esmeralda - Edificio Oramas, Av. Casanova, Caracas 1050, Distrito Capital, Venezuela",
    "Electroauto Zabala - Barrio bolivar calle el alto parte baja, San Cristóbal 5001, Táchira, Venezuela",
    "Optica Oleic, C.A - Boulevard de Sabana Grande, entre calle Union y Villaflor Centro Comercial City Market, Piso 4 Local L426,, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Digital Security - Av. Humbolt Edf. Italia Local A y B, F4RG+7M9, Caracas 1050, Distrito Capital, Venezuela",
    "Lion Tech Chacaito - Plaza Brion, Royal Palace, PB Local B, Chacaito Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "La Mejor Paella de Caracas - Av. Casanova con 2da Av. de, Edif. Campanero, Caracas 1050, Distrito Capital, Venezuela",
    "MULTISERVICIOS VORTEX 1337 - Central de Campo Rico, Caracas 1073, Miranda, Venezuela",
    "Inversiónes Santi 28 - Edificio Oramas, Calle Coromoto, Caracas 1050, Distrito Capital, Venezuela",
    "El Mundo del Libro - frente a la UCV, Av. P.º Los Ilustres, Caracas 1040, Distrito Capital, Venezuela",
    "Panaderia Pasteleria La Petit Folie Bakery - F5X4+FV2, Trans. 1, Caracas 1060, Distrito Capital, Venezuela",
    "La Tostadita Luncheria - Andres bello / 4 y, Quinta Cisco L-1, 5 Transversal, Caracas 1050, Distrito Capital, Venezuela",
    "Pet house - Centro Comercial Bello Monte, Caracas 1041, Distrito Capital, Venezuela",
    "Restaurante Da Tulio, C.A - Calle el colegio Edif. Hotel Luna luna, Planta baja, Local 1 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Fergia's Studio's - 1071 Caracas, Caracas 1071, Miranda, Venezuela",
    "Mercería Tejeycrea - Centro Comercial Propatria, nivel 2, local A-26 Frente a panadería La Gran Sabana Caracas, Caracas 1000, Distrito Capital, Venezuela",
    "Jhony Car's Repuestos - C. 4 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "Repuestos Cordillera - Repuestos Cordillera Calle 4 con Carrera 9, La Concordia Local N 9 - 15, San Cristóbal 5001, Táchira, Venezuela",
    "Sport London - Edificio Sport London, Esquina de Muñoz a Padre Sierra, Av Este 2, Caracas 1012, Distrito Capital, Venezuela",
    "Restaurante Doña Barbara - Local B, Edificio Ovidio, Av Francisco Solano Lopez, Caracas 1050, Distrito Capital, Venezuela",
    "Fashion View Óptica - 1071 Caracas, Caracas 1071, Miranda, Venezuela",
    "Centro Medico Diagnóstico Sabana Grande - 11 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "SimCardRental - Centro Ciudad Comercial Tamanaco nivel C1 Caracas, Caracas 1060, Distrito Capital, Venezuela",
    "Opalooka Import - local 10, Torre Banvenez, PB Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "A&M servicios y repuestos - C.C. sábana grande, nivel mezanina, local 28 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "N-veces Inversiones - Calle Villaflor con Union, CC City Market N, 163 Calle L, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Mepix C.A - C.C. City Market, piso 4, local 444 y, 416 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Repuesto Cell OOC - C.C Sábana Grande, Nivel Mezanina, Local 04 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Bluestore C.A - C.C City Market, Nivel 4, Local 441, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "IC Fix Servicio Técnico - C.C Sábana Grande, nivel sotano,local 25, Caracas 1050, Distrito Capital, Venezuela",
    "Imperio Bodegon Cafe - Av. Casanova con negrin Edf, PB L-2, Caracas 1050, Distrito Capital, Venezuela",
    "Alpha Computers C.A - C.C. City Market, Nivel Bazar, Local, B327, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Cerámicas y Materiales Carmire, C.A. - Barrio Madre Vieja calle 5 entre carreras 5 y, 6, Guanarito 3354, Portuguesa, Venezuela",
    "Korea Partes Táchira - QQ5C+G46, San Cristobal 5001, Táchira, Venezuela",
    "Novedades Romary - Calle Villaflor con Union, CC City Market N- Bazar L-B102 Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Accesorios y Tecnologia DYH - Calle Villaflor con Union, CC City Market, Nivel Bazar L-D226 caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Soporte Store 57 - Calle Villaflor con Union, CC City Market Bazar N-2 L- B 302 Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones JHR - Calle Baruta / Casanova y boulebart Edf, PB C. María Auxiliadora, Caracas 1050, Distrito Capital, Venezuela",
    // "Inversiones JHR - Calle Baruta / Casanova y boulebart Edf, PB C. María Auxiliadora, Caracas 1050, Distrito Capital, Venezuela",
    "DISTRIBUIDORA DIMPERCA - Sukyo Mahikari, F4RF+9X6, Caracas 1050, Distrito Capital, Venezuela",
    // "A&M servicios y repuestos - C.C. sábana grande, nivel mezanina, local 28 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "La Tostadita - G434+WVR, Av. Andrés Bello, Caracas 1050, Distrito Capital, Venezuela",
    "Bodega 075 - Urb, N° 24, Edificio San Antonio, Av. José Félix Sosa, Caracas 1060, Miranda, Venezuela",
    "To The Games C.A - C.C City Market, Piso 4 Local 450 , Caracas 1050, Caracas 1050, Distrito Capital, Venezuela",
    "Bucare Deli-Burguers - Propatria 2da avenida. Entre calles 6 y 7 Caracas, Caracas 1030, Distrito Capital, Venezuela",
    "Espacios Kala´s - Edificio la piñata, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Lucky cell 2 - JX58+66P, Jl. Wonosobo - Purworejo, Tempelsari, Maduretno, Kec. Kalikajar, Kabupaten Wonosobo, Jawa Tengah 56372, Indonesia",
    "Coffe Party Ciber - C.C. del Este Nv. PB L-15 Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Lucky Cell - Calle Villaflor con Union CC City Market Nivel Bazar P- B401 Caracas Calle Villaflor con Union CC City Market Nivel Bazar P- B225 Caracas Boulevard De Sabana Grande Minicentro 199, Local 35 y 36, Caracas 1050, Distrito Capital, Venezuela",
    "Centro Médico Louis - Petare, Calle Sucre. zona colonial, frente a la plaza Sucre casa #12 Caracas, Caracas 1070, Distrito Capital, Venezuela",
    "Inversiones Farmacia Del Este - Edificio Colina, Local PB 01 Blvr. de Sabana Grande, Caracas 1071, Distrito Capital, Venezuela",
    // "W&BEYELASH - Mercado Comunitario Cesar Nieves, Piao 2, Local nro. 344, Catia La Mar 1162, La Guaira, Venezuela",
    "Kiosco Las Palmas - Frente al frigorifico, Avenida Principal De Las Palmas, Caracas 1050, Distrito Capital, Venezuela",
    "Kiosco kent - Kiosco N°45, Avenida Francisco de Miranda, Caracas 1060, Miranda, Venezuela",
    "Auto Sonido TipTronic - Entre Calle Nueva York y Calle Londres, Edificio Centro DMC, PB, Local N°3, Las Mercedes, Miranda, Zona Postal, Calle Londres, Caracas 1080, Miranda, Venezuela",
    "Bodegon Doña Paula, C.A - Esq. De Candilito Local Nro PB Urba La Candelaria, al Lado del Banco Vzla Caracas, G34V+2HF, Caracas 1010, Distrito Capital, Venezuela",
    "panaderia pasteleria la corona - Av. Jose Maria baralt, entre Av Oeste 6 y Av. Este Oeste 8 Local Nro 55-57 sector, Caracas 1020, Distrito Capital, Venezuela",
    "Celulares AM asociados - Calle San Antonio, reducto a Municipal, edificio 05, local PB 01, Caracas 1012, Caracas 1012, Distrito Capital, Venezuela",
    "Apoleo frigorífico - Avenida Sur 4 a dolores, esquina Soublette, local 112, Caracas 1014, Distrito Capital, Venezuela",
    "LICORERÍA BARALCA - G34M+83M, Av. Baralt, Caracas 1010, Distrito Capital, Venezuela",
    "Producciones y eventos okantomi 2019 - Avenida Sur 12, casa #13, esquina de delicias a Pepe alemán. Sector San Juan. Capuchinos, Caracas 1010, Avenida Sur 12, Caracas 1014, Distrito Capital, Venezuela",
    "Inversiones Mi Rey Vive - Avenida 14 sur con San Francisquito, a delicias. Edificio Almendares, PB, local 4. Caracas 1030, Oeste 4, Caracas 1014, Distrito Capital, Venezuela",
    "Clean Madel - Av. Principal de, Quinta 24, Av. Andrés Bello, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Hega 21 - Av. Andres Bello, Cruce con Merida, Quinta MArile L-8, Caracas 1050, Distrito Capital, Venezuela",
    "Restaurante JG - Calle Villaflor, CC Sabana Grande, Nivel Feria L-40 Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Soluciones CGT - Centro comercial Sabana grande local 29 nivel mezzanina, Caracas 1050, Distrito Capital, Venezuela",
    // "Soluciones CGT - Centro comercial Sabana grande local 29 nivel mezzanina, Caracas 1050, Distrito Capital, Venezuela",
    "phone star solutions c.a - sabana grande tel 02127611984 o al 0424 1543221 Whatsapp, Caracas 1010, Distrito Capital, Venezuela",
    "Cafeteria y Pasteleria Manolo - Av. Casanova C/C Baldo. Edf. Atlantida PB. L-E 50Mtrs de, Hidrocapital, Caracas 1050, Distrito Capital, Venezuela",
    // "Kanji Sushi Barquisimeto - 22 y 23 C. 15, Barquisimeto 3001, Lara, Venezuela",
    "Lady's Style - Local 20 C2 CC, Parque Cristal, 1060 Calle Miranda, Caracas 1060, Distrito Capital, Venezuela",
    "Farma Shop Chacao - C. Elice, Caracas 1060, Distrito Capital, Venezuela",
    "Distribuidora Okli's, C.A - Av. Élite, Edif. Eudron Piso PB Local 1,. Urb, Caracas 1060, Distrito Capital, Venezuela",
    "Romy stile - Calle el Samán con Calle Chico Carrasquel, C.C Merpoeste, Piso 1 Local H185, Caracas 1064, Miranda, Venezuela",
    "Inversiones Barbaramar, C.A. - Calle de Silencio a Jefatura, PB, Local 27-16, Maiquetía 1160, La Guaira, Venezuela",
    "Plaza C. Perfumería - Centro Comercial, Casa Bera Local PB022, Av. Urdaneta, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Wildriana - Esquina Monroy, pasillo Táchira con ecuador, local 1721 y 1722, Caracas, Caracas, Caracas 1011, Distrito Capital, Venezuela",
    "Cosméticos Leis - Mercado bolivariano la hoyada, pasillo Anzoátegui, local 1999, Caracas, Caracas, Caracas 1011, Distrito Capital, Venezuela",
    "Aguas de bello campo - Avenida principal de bello campo edificio San luis local A Caracas, Caracas 1060, Miranda, Venezuela",
    "Especias Market - F4JQ+7MF, Caracas 1080, Miranda, Venezuela",
// "Especias Market - F4JQ+7MF, Caracas 1080, Miranda, Venezuela",
    "El Rey de los Enrollados - Av Francisco de -Miranda, Centro comercial El Marques, piso 1 local 217, Caracas 1071, Miranda, Venezuela",
    "Toromaima mini market - San Bernardino, Caracas 1011, Capital District, Venezuela",
    "Monumental Tours C.A - Torre Banvenez, Pb local 3, Caracas 1050, Distrito Capital, Venezuela",
    "Casa Torino - Avenida Ávila de Bello Campo. Entre la Sede Principal de Salud Chacao y el Centro Automotriz Libertador I. Quinta #87, Caracas 1060, Miranda, Venezuela",
    "Kiosco Andres Bello - 3ra av con, frente a la plaza de, 2da Transversal, Caracas 1060, Distrito Capital, Venezuela",
    "Mayor de Alimentos DayRan - Local 5, Transversal 3, entre calle los higuerotes, Avenida Sta Isabel, Caracas 1040, Distrito Capital, Venezuela",
    "Inversiones exótica doris - local 183, Centro Comercial Mercado San Jorge, pasillo i, nivel PB, Caracas 1041, Av. Bogotá con Avenida de Capitan de Navío- Felipe, El Cementerio, Caracas 1040, Caracas 1040, Distrito Capital, Venezuela",
    "Grupo Romano C.A. - Entre esquina Santa Isabel y Prado de María, Quinta 65. 1040 Caracas, 1040, Caracas, Caracas 1040, Distrito Capital, Venezuela",
    "Comercializadora San Varca, C.A - Av. Francisco de Miranda Torre Cemica, piso Mezzanine Ofc. C Urb, F4VW+J2V, Caracas 1060, Dependencias Federales Venezolanas, Venezuela",
    // "SimCardRental - Centro Ciudad Comercial Tamanaco nivel C1 Caracas, Caracas 1060, Distrito Capital, Venezuela",
    "HABITACOM - Av. Ppal de Las Mercedes, Edif. Centro Summum, con C. Mucuchíes, Caracas 1060, Miranda, Venezuela",
    "Sushi One - Soler 5837, PalermoC1425 CABA, Argentina",
    "Café Sushi One 2017, C.A - Calle Urdaneta, Edif. Urdaneta Piso PB. Local n° 2 Sector, Caracas 1060, Distrito Capital, Venezuela",
// "HABITACOM - Av. Ppal de Las Mercedes, Edif. Centro Summum, con C. Mucuchíes, Caracas 1060, Miranda, Venezuela",
// "Café Sushi One 2017, C.A - Calle Urdaneta, Edif. Urdaneta Piso PB. Local n° 2 Sector, Caracas 1060, Distrito Capital, Venezuela",
    "Grupo Comunica 555, C.A - Calle Sucre, Edif. Leandro Piso PB Local B Urb, Chacao, Caracas 1060, Distrito Capital, Venezuela",
    "HUGONODONTE Café - Estacionamiento público Centro Plaza, Trans. 1, Caracas 1060, Miranda, Venezuela",
    "KMC Laboratorio Clínico - 1071 Caracas, Caracas 1071, Distrito Capital, Venezuela",
    "Gigi Playa - Calle 11 entre Carreras 18 y 19, Local N°1, San Cristóbal 5001, Táchira, Venezuela",
    "Gürt Cocina Vegetariana - Edificio La Trinidad, Local PB1, carrera 23 entre calles 9 y 10, San Cristóbal 5001, Táchira, Venezuela",
    "Alarmas Beto C.A. - F5W8+FRM, Caracas 1071, Miranda, Venezuela",
    "PRC333, C.A. - Av. Diego Cisneros, Edif. Centro Empresarial Danisa, Urb, Caracas 1071, Miranda, Venezuela",
// "SimCardRental - Centro Ciudad Comercial Tamanaco nivel C1 Caracas, Caracas 1060, Distrito Capital, Venezuela",
    "Rikway Shop - F5W8+4PP, Caracas 1071, Miranda, Venezuela",
    "Consultorio de Fisioterapia Quirón - Centro Profesional Pirineos, Piso 1, Local 1, Calle 12 entre carreras 23 y 24, Barrio Obrero, San Cristóbal 5001, Táchira, Venezuela",
    "Distribuidora los Varones C.A - local 1, Final Calle 1 De Mayo, Avenida Roosevelt, Caracas 1041, Distrito Capital, Venezuela",
    // "Kiosco Andres Bello - 3ra av con, frente a la plaza de, 2da Transversal, Caracas 1060, Distrito Capital, Venezuela",
    "Farmacia Parque Cristal - F5X4+6JX, Caracas,Los Palos Grandes 1060, Miranda, Venezuela",
    "Papelería Moderna - La concordia, barrio la castra, entre carreras 10 y 10 bis con calle 2 bis y calle 3, detrás de comercial la gran parada, San Cristóbal 5001, Táchira, Venezuela",
    "Perfumería el poder de la fe - Local-29, zona 71, Mercado de, Caracas 1020, Distrito Capital, Venezuela",
    "Marvic Style - Local 88-89. Calle Chico Carrasquel, Nivel PB, Pasillo Paují, Caracas 1064, Miranda, Venezuela",
// "Marvic Style - Local 88-89. Calle Chico Carrasquel, Nivel PB, Pasillo Paují, Caracas 1064, Miranda, Venezuela",
    "Basket Burguer - Centro comercial Merpoeste, nivel feria, local 50, Caracas 1060, Distrito Capital, Venezuela",
    "Romy Shop - Centro Comercial Merpoeste, P-1, L-189, Caracas 1060, Distrito Capital, Venezuela",
    "Sucursal Irowo Omaire y Asociados - Av Andrés Bello Mercado municipal de Guaicaipuro Piso Mezzanine local 72 Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Nemesis ladiosa - Avenida este, esquina Dr Paul a Salvador de león, Edificio 71 Nivel PB, local 10. La hoyada Caracas 1040, Avenida E, Caracas 1020, Caracas 1012, Distrito Capital, Venezuela",
    "Calle A - C. A, Caracas 1020, Distrito Capital, Venezuela",
    "Tu visión némesis C.A. - Avenida este, esquina Dr. Paul a Salvador de león, edificio 71 N.pb. L-11 La hoyada Caracas, Avenida E, Caracas 1040, Caracas 1012, Distrito Capital, Venezuela",
    "Global Systems Store C.A - Caracas 1060, Miranda, Venezuela",
    "Arte Express 99 - F5W3+JPV, Caracas 1060, Miranda, Venezuela",
    "American Book Shop 2026 - Centro Plaza, Nivel Jardín CC3-10, Caracas 1069, Distrito Capital, Venezuela",
    "Essor Group - local 31, nivel jardin, centro comercial centro plaza, Avenida Francisco de Miranda, Caracas 1060, Miranda, Venezuela",
    "La Red Ciber Cafe - Calle Enrique Eraso Torre La Noria, piso 1 (adentro de la ULAC, Caracas 1060, Distrito Capital, Venezuela",
    "Calle A - C. A, Caracas 1071, Miranda, Venezuela",
    "Erylyn Moda C.A - F5W3+QMV, Caracas 1060, Miranda, Venezuela",
    "Bar Restaurant el Naranjal - Centro Plaza, Nivel CC3, Local 12, Avenida Francisco de Miranda, Caracas 1060, Miranda, Venezuela",
    "SimCardRental - Avenida Intercomunal del Aeropuerto Internacional de Maiquetia &quot;Simón Bolívar Nivel PB, Local 05, La Guaira 1162, La Guaira, Venezuela",
    "Papel ahumado Paseo Anauco - local 17, Paseo Anauco, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Fares, C.A - Calle Cecilio Acosta Entre Av Francisco de Miranda y Calle Sucre Casa N° 213-2209, Caracas 1060, Distrito Capital, Venezuela",
    "Auto Cerrajería la Llave del Edén, C.A - Av. Francisco de Miranda CC Chacaito Nivel Boulevard Local 25 Urb. Chacaito Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Sastreria Camargo - F5X4+3RH, Caracas 1060, Miranda, Venezuela",
    // "Sastreria Camargo - F5X4+3RH, Caracas 1060, Miranda, Venezuela",
    "La Spezia Cafe - Av Francisco de Miranda, Centro Comercial Parque Cristal, nivel C1, local 12, Caracas 1060, Distrito Capital, Venezuela",
    "Bodegón Daroy - Av. 1, Edificio monte ulio, Caracas 1060, Distrito Capital, Venezuela",
    "Spa Beautiful Fitness - Urbanización montalban I Avenida Tres entre Calle 3 y Calle 2 Quinta Mami Caracas, Caracas 1020, Distrito Capital, Venezuela",
    "Kiosco Mene Grande - Avenida Francisco de Miranda, Edifico Mene Grande, F5W3+FFV, Caracas 1060, Distrito Capital, Venezuela",
    "Distribuidora Dimperca, C.A. - G457+GCP, Caracas 1050, Capital District, Venezuela",
// "Distribuidora Dimperca, C.A. - G457+GCP, Caracas 1050, Capital District, Venezuela",
    "Doravila Restaurante C.A - Norte quinta villaelisena, Av Principal de Boleíta, Caracas 1071, Distrito Capital, Venezuela",
    "Las Delicias de Vicenta - Calle monseñor Juan Grilc, Edificio Los Cárpatos - Piso 3, Apto. 43 Caracas, Caracas 1061, Distrito Capital, Venezuela",
    "Di-Masi Vinos C.A. - Galpón 2 Avenida Francisco de Miranda, Caracas 1071, Distrito Capital, Venezuela",
    // "Papelería Moderna - La concordia, barrio la castra, entre carreras 10 y 10 bis con calle 2 bis y calle 3, detrás de comercial la gran parada, San Cristóbal 5001, Táchira, Venezuela",
    "AquaFull - Av. Maracaibo, Caracas 1050, Distrito Capital, Venezuela",
    "GRUPO CYXCOM C.A. - CENTRO COMERCIAL SABANA GRANDE LOCAL 7 NIVEL MESANINA CARACAS, Caracas 1050, Distrito Capital, Venezuela",
    "Centro Comercial Lord Center - 1019 caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Javimay1804, c.a - CC. Multicentro Maiquetia, calle Los Baños, H2WX+C69, C. Los Baños, Maiquetía 1162, Vargas, Venezuela",
    "El Dulce Mundo de Cami - Centro Comercial Merpoeste, Piso 2, local 14, Caracas 1064, Miranda, Venezuela",
    // "Perfumería el poder de la fe - Local-29, zona 71, Mercado de, Caracas 1020, Distrito Capital, Venezuela",
    // "Bucare Deli-Burguers - Propatria 2da avenida. Entre calles 6 y 7 Caracas, Caracas 1030, Distrito Capital, Venezuela",
    // "Basket Burguer - Centro comercial Merpoeste, nivel feria, local 50, Caracas 1060, Distrito Capital, Venezuela",
  };
}
