class AutoSuggestionsE { static final reviewedTitlesE = const {"Zulyslunchandgrill - C. 26, Barquisimeto, Lara",
"Ferremetale.l - C.A, Barquisimeto, Lara",
"Gamersstationbqto - Avenida Carabobo, Barquisimeto, Lara",
"Bodega la 30 - Barquisimeto, Lara",
"Only Tech - Centro de Economía Comunal Manuelita Saenz, Bulevar de Sabana Grande, Caracas, Distrito Capital",
"Gaby Technology - Centro de Economía Comunal Manuelita Saenz, Bulevar de Sabana Grande, Caracas, Distrito Capital",
"ArepaTrekking - Santa Lucía, Miranda",
"Qoholet C.A. - 41, Caracas, Distrito Capital",
"Soul Rebel Moda - Caracas, Distrito Capital",
"11:11 Sport Bar Restaurant - Barquisimeto, Lara",
"Mr mascotas - planta baja cc.trinitarias, local 25g, Barquisimeto, Lara",
"Multiservicios Barreto - Barquisimeto, Lara",
"Comercial Marinera C.A - de, Avenida Principal, Catia La Mar, La Guaira",
"Sinaí Market - Primera Transversal, Caracas, Miranda",
"Bodegón Los Tesoros de Papá - Barquisimeto 3001, Lara",
"Beauty Shop - Guanare 3350, Portuguesa",
"abasto alvarez c.a. barquisimeto 3001 lara",
"Pizzas Rafucho - Los Próceres, Guanare, Portuguesa",
"antojitos guanare portuguesa",
"Pidiendo y Comiendo Pizzeria - casa 74 C. 9, Guanare, Portuguesa",
"POSADA VILLA DEL CARMEN - Calle 1, Catia La Mar 1162, La Guaira",
"La caridad fresco market - Maiquetía, La Guaira",
"Vaporhot vzla - Avenida Principal de Playa Grande, Catia La Mar, La Guaira",
"Ferretería Comercial Ramar - y, Calle La Estación, Caracas, Distrito Capital",
"Distribuidora Olivo C.A - Calle 33, Barquisimeto, Lara",
"Cassa Market - Carrera 25, Barquisimeto, Lara",
"Dulces y algo más - Calle 25, Barquisimeto, Lara",
"Clínica Vitalis - Avenida Venezuela, Caracas, Distrito Capital",
"Novedades Hello C.A. - Caracas, Distrito Capital",
"Frigus.ve - Avenida del Hotel, Marriott, La Guaira",
"11.11 Boutique - Avenida Transversal 10, Caracas, Distrito Capital",
"Pintacar Express - Calle Tacagua, Catia La Mar, La Guaira",
"Inversiones Oshun - C.A., Pasillo 3, Maiquetía, La Guaira",
"Fruber 1111 - Calle Páez, Caracas, Distrito Capital",
"Tu Cuevita Repostera La Arenosa - Guanare, Portuguesa",
"Helados Dulces y Antojos - Sector la Comunidad, Casa, Principal de la Comunidad, Guanare, Portuguesa",
"Bodegón RMR - edificio Aura, Carrera 12, Guanare, Portuguesa",
"Mega Perros - Calle 9, Guanare, Portuguesa",
"Strong Physical Center - C.A, Via Viboral, Maturín, Monagas",
"Alimentos y Suministros Galax - Via Viboral, Maturín, Monagas",
"Inversiones Marchael - C.A., pasillo 6, Maiquetía, La Guaira",
"Inversiones Jhoelins - C.A., Pasillo 5, Maiquetía, La Guaira",
"Pizzería Unda - Local 12, Guanare, Portuguesa",
"Café Plaza - Calle 16 Entre Carreras 4 Y 5 Edificio Don Armando local 02 Frente A La Plaza Bolivar, Guanare 3350, Portuguesa",
"Inversiones Don Miguelacho - Guanare, Portuguesa",
"La boca del lobo - librería sin límites, Calle 12, Entre carreras 21 y 22, edif. antigua, San Cristóbal 5001, Táchira",
"Restaurante Siglo XXI - Calle La Iglesia, Sabana Caracas, Distrito Capital",
"Puerkos Restaurant - Edificio Don Fernando, Sabana grande, local sede, PB, Av. Casanova, Caracas 1060, Distrito Capital",
"Antojitos de Ysabell - C.A, Calle Ricaurte, Valencia, Carabobo",
"Inversiones Foncho Peña - Local 08, Guanare, Portuguesa",
"Optica Servilens CA - Avenida Sucre, Maracay, Aragua",
"N.B King Shoes C.A - Calle El Bosque, Maracay, Aragua",
"Talabarteria m&g villalobos III - Avenida Lisandro Alyarado, Maracay, Aragua",
"Barber Tatto 911 - Táriba, Táchira",
"Mariangel Studio - Táriba, Táchira",
"Haru Nails Studio - Troncal 1, San Cristóbal, Táchira",
"La Brachera In C.A. - Calle Montilla, Guacara, Carabobo",
"Creaciones Doumari - F.P., Pasillo 1, Maiquetía, La Guaira",
"Inversiones Charay - C.A., Pasillo 12, Maiquetía, La Guaira",
"El Rincóncito de Romi - C.A., Pasillo 11, Maiquetía, La Guaira",
"Inversiones Somger Cells - C.A., Pasillo 11, Maiquetía, La Guaira",
"Disvimol - Táchira Venezuela, Vista Alegre, Panamá",
"Casa Proagro - Táriba, Táchira",
"RedsComp - San Cristóbal, Táchira",
"Multihidromaticos JJYAÑEZ CA - San Cristóbal, Táchira",
"Tecnochia - San Cristóbal, Táchira",
"Inversiones Darwin Rojas - C.A., Pasillo 11, Maiquetía, La Guaira",
"Inversiones Milca Torres 2021 - C.A., Pasillo 11, Maiquetía, La Guaira",
"Inversiones M & M 2013 - C.A., Pasillo 11, Maiquetía, La Guaira",
"Inversiones Josdavier 2017 - C.A., Pasillo 12, Maiquetía, La Guaira",
"Inversiones Delgado Maiquel(K.D.F.2176) F.P. - Pasillo Central, Maiquetía, La Guaira",
"Inversiones Orocristal - C.A., Pasillo 11, Maiquetía, La Guaira",
"Inversiones Carol - C.A., Pasillo 3, Maiquetía, La Guaira",
"Ferreteria Arturo G - Guanare, Portuguesa",
"El Tinajero Hogar C.A. - Guanare, Portuguesa",
"ricar2 house principal tocuyito carabobo",
"BB Store Servicios - CA, Piso 1, Maturín, Monagas",
"XTREMO JULKAR 27 - C.A, Avenida Alirio Ugarte Pelayo, Maturín, Monagas",
"FRUTTY MANIA - Via Viboral, Maturín, Monagas",
"Sucursal CA BST FARMA - Valencia, Carabobo",
"Inversiones Chiquita Plus - C.A., Pasillo 1, Maiquetía, La Guaira",
"Video Club - Piso 1, Maturín, Monagas",
"Inversiones Michelle - F.P., Pasillo 1, Maiquetía, La Guaira",
"Panda Verde - Guanare, Portuguesa",
"O&J Suministros C.A - San Diego, Carabobo",
"Mango de Oro C.A. - Guanare, Portuguesa",
"Mundo de Azúcar - f.p., Avenida Unda, Guanare, Portuguesa",
"UPF Delicateses la Gloria de Dios II - Tocuyito, Carabobo",
"AHOPE Style - Calle Rondon, Tocuyito, Carabobo",
"Inversiones Peña Nuñez 2015 C.A - Tocuyito, Carabobo",
"Don Miguel Pizzería - Avenida 109, Tocuyito, Carabobo",
"AHOPE Style - Calle Rondon, Tocuyito, Carabobo",
"Víveres Guacara F.P - Calle Laurencio Silva, Guacara, Carabobo",
"Abasto A Dios JL - Los Chorritos, Calle Las Bateas, Tocuyito, Carabobo",
"Inversiones Alianza de Dios JL C.A - Tocuyito, Carabobo",
"Liontech Sambil - Avenida Libertador, Caracas, Distrito Capital",
"La Casa del Volcan - Los chorritos, Calle el Valencia, Local Nro A4, 109-90 Calle el Valencia, Tocuyito 2035, Carabobo",
"Abasto Los Chorritos - Tocuyito, Carabobo",
"Inversiones Kemywill 2019 C.A - Troncal 1, Tocuyito, Carabobo",
"La Coromotana C.A - Avenida 110, Tocuyito, Carabobo",
"Variedades Mis Tesoros - Tocuyito, Carabobo",
"SC Canelones y Montaya - Guanare, Portuguesa",
"Distribuidora de AVON - Orihuela, A, España",
"plásticos y algo mas ca guanare portuguesa",
"WAFFLES & BOUQUET VZLA C.A - Maracay, Aragua",
"Frigorífico Carnes el terminal. C.A. - Avenida 107, Tocuyito, Carabobo",
"Importaciones Technology Import - Av 15 Las Delicias Con Calle 100, Cc Gran Bazar, N1, Local1569, 1570",
"Ferreteria Torres Ingenieria de Venezuela - Guanare, Portuguesa",
"Variedades Mafer Gómez - Tocuyito, Carabobo",
"Importaciones Technology Import - Av 15 Las Delicias Con Calle 100, Cc Gran Bazar, N1, Local1569, 1570",
"Inversiones Georgis JRS CA - Principal, Tocuyito, Carabobo",
"Keves Vision - Caracas, Distrito Capital",
"Frutimarket Ccs - Caracas, Distrito Capital",
"Casa Hot Dog - Avenida Universidad, Naguanagua, Carabobo",
"Lucian's tech - Maracaibo, Zulia",
"Representaciones Sitec C.A. - Quinta Irlanda, Calle Nicanor Bolet Peraza, Caracas, Distrito Capital",
"Inversiones Compucel DM - C.A., Centro Comercial Parque Caracas, Caracas, Distrito Capital",
"Tu market y algo más C.A - Centro Comercial Cap Conte, Avenida 100 Bolívar, Naguanagua, Carabobo",
"MULTISERVICIOS EL PUENTE II - C.A., Guacara, Carabobo",
"Importadora RCZ C.A. - Caracas, Miranda",
"Grachi C.A. - Caracas, Miranda",
"Licoven Guacara I c.a - 4, Guacara, Carabobo",
"Optica 360 - Maracaibo, Zulia",
"FRUTAS y Mas - Guanare, Portuguesa",
"Onlytie Sport - Caracas, Miranda",
"Servitmovil - Gran bazar, Maracaibo, Zulia",
"Reparaciones Con Tigo - Maracaibo, Zulia",
"Respuestos Pirineos - 5ta. Avenida "Francisco García de Hevia", San Cristóbal, Táchira",
"Inversiones Betty mis logros 2018 - .C.A., pasillo 02, Maiquetía, La Guaira",
"Inversiones De Todo un Poco 2019 - C.A., Pasillo 1, Maiquetía, La Guaira",
"Restaurante Mansión Oriental - Caraballeda, La Guaira",
"Burger Grill - C.A., Calle El Hambre, Caraballeda, La Guaira",
"Inversiones Erlyn - C.A., Puesto 215, Pasillo 3, Maiquetía, La Guaira",
"Inversiones Rubí Esmeralda - C.A., Pasillo 5, Maiquetia, La Guaira",
"Inversiones Yenitze Fashion - C.A, Pasillo 1, Maiquetía, La Guaira",
"Inversiones yed 2030 c.a - pasillo 1, Maiquetía, La Guaira",
"Krispy Donuts - Cagua, Aragua",
"Krispy Donuts El Limón - Zona Postal, El Limón, Aragua",
"Krispy Donuts El Terminal - Maracay, Aragua",
"Krispy Donuts San Jacinto - Zona Postal, Avenida Bolívar, Maracay, Aragua",
"Krispy Donuts - Calle Mariño Norte, Edif. Gonzalez Blank, PB, frente a la plaza, bicentenaria, Maracay 0221, Aragua",
"Krispy Donuts El Bosque - Maracay, Aragua",
"Krispy Donuts - Zona Postal, Avenida Las Delicias, Maracay 2101, Aragua",
"Krispy Donuts Las Delicias - Zona Postal, Avenida Las Delicias, Maracay, Aragua",
"Tecnoberry C.A - Guanare, Portuguesa",
"Tecnoberry C.A - Guanare, Portuguesa",
"Cerrajería Vícar 2015 - bajando hacia La Guairita, Avenida Luis De Camoens, Caracas, Distrito Capital",
"El Universo Del Churro - San Cristóbal, Táchira",
"Iluminaciones Alvarez - Carrera 7, Guanare, Portuguesa",
"Led-Computer - Maracaibo, Zulia",
"Diseños & creaciones Snarpy - Local 4, Av. Unda, barrio La Arenosa, esquina Carrera 7, C.C Cordillera, Nivel 1, Av. Unda, Guanare 3350, Portuguesa",
"Evoualji - Guanare, Portuguesa",
"Rio Celeste - Avenida Sucre, Caracas, Distrito Capital",
"MOTORS REPUESTOS OMG - Avenida Sucre, Caracas, Distrito Capital",
"Abasto la o de oro C.A - Zona Postal, Avenida Sucre, Caracas, Distrito Capital",
"Inversiones flor María 2010 c.a - Avenida Sucre, Caracas, Distrito Capital",
"Dulce Panela Cafe - Guanare, Portuguesa",
"Krispy Donuts Avenida Bolívar - Valencia, Carabobo",
"Ferreteria Fermil la 5ta - Troncal5, Guanare, Portuguesa",
"Inversiones Densor - Calle 8 Carrera 8, Guanarito 3354, Portuguesa",
"Velvet The Beauty House - Caracas, Distrito Capital",
"Boutique Jessimar - Guanarito, Portuguesa",
"Baby chic Boutique - Carrera 8, Guanarito, Portuguesa",
"SUPERMERCADO MIYOVI - C.A., Calle 7, Maturín, Monagas",
"Districar - Guanarito, Portuguesa",
"Creaciones Decomari - Maracaibo, Zulia",
"Gravity Games - Avenida Urdaneta, Caracas, Distrito Capital",
"Android Store - Avenida Libertador, Maracaibo, Zulia",
"Arepas Full Sabor - Maracaibo, Zulia",
"Inversiones Dey 98 ó 2013 - F.P., Pasillo 1, Maiquetía, La Guaira",
"Canguro sede city market 1 - Calle Villaflor, Caracas, Distrito Capital",
"Canguro sede city market 2 - Caracas, Distrito Capital",
"Canguro Sede City Market 3 C.A.",
"Canguro sede Urdaneta tienda mayorista - Avenida Urdaneta, Caracas, Distrito Capital",
"Canguro Sede Sabana Grande (Servicio Técnico) - Caracas - Calle Villaflor, Caracas, Distrito Capital",
"Canguro sede city market 2 - Caracas, Distrito Capital",
"Inversiones Sandy - F.P., Pasillo 3, Maiquetía, La Guaira",
"Inversiones Marcelo - C.C. Eustoquio, Calle 12, Guanare, Portuguesa",
"Ankara Catia - Caracas, Distrito Capital",
"Inversiones Linda 2014 - C.A., Pasillo 5, Maiquetía, La Guaira",
"Ankara Catia - Caracas, Distrito Capital",
"Ankara Sede Los Cortijos C.A. - Caracas - sede Ankara. 1071, 1 ofocina, Caracas, Miranda",
"Mojito House - Guanare, Portuguesa",
"Flamingru - Carrera 6, Guanare, Portuguesa",
"Lio's Store - Guanarito, Portuguesa",
"La Tiendita GA Saavedra - Guanarito, Portuguesa",
"D Vivas Shop - Guanarito, Portuguesa",
"Zapatería Jkamy Boutique segundo piso local 1 - Guanare, Portuguesa",
"GUERRERO SERVICELL CA (GRAN BAZAR) - Maracaibo, Zulia",
"Inversiones Barac 2013 - Caracas, Distrito Capital",
"lola express - Avenida San Martín, Caracas, Distrito Capital",
"Multiservicios Mundo Tecnologia C.A. - Maracaibo, Zulia",
"JKAMY Boutique - Calle 18, Guanare, Portuguesa",
"Inversiones la Esquina de Sharon - C.A., Pasillo 3, Maiquetía, La Guaira",
"Yessenia Montilla - F.P., Pasillo 1, Maiquetía, La Guaira",
"Boomerang La Guairita - Avenida Luis De Camoens, Caracas, Distrito Capital",
"Inversiones Mafer - C.A., Pasillo 3, Maiquetía, La Guaira",
"Agua Purificada y Algo Más... - Avenida Luis De Camoens, Caracas, Distrito Capital",
"inversiones jhoelins c.a. pasillo 5 maiquetía la guaira",
"Inversiones Chango 66 - C.A, Pasillo 3, Maiquetía, La Guaira",
"Inversiones Linda Bonita - C.A., Locales 375 y 376, Pasillo 3, Maiquetía, La Guaira",
};
}
