class AutoSuggestions41115809 { static final reviewedTitles41115809 = const {"Soul Rebel Moda - Boulevard de Sabana Grande, entre Mercado Colonial y Centro Comercial Chacaito, local 1, Caracas 1050, Distrito Capital, Venezuela",
"11:11 Sport Bar Restaurant - Centro Empresarial Barquisimeto, Local 14, Barquisimeto 3001, Lara, Venezuela",
"Mr mascotas - Av. Los Leones, planta baja cc.trinitarias, local 25g, Barquisimeto 3001, Lara, Venezuela",
"Multiservicios Barreto - Calle 41 &amp; Carrera 28, Barquisimeto 3001, Lara, Venezuela",
"Comercial Marinera C.A - JX5P+C37 de, Avenida Principal, Catia La Mar 1162, Vargas, Venezuela",
"Sinaí Market - Av Primera Transversal, Caracas 1060, Miranda, Venezuela",
"Bodegón Los Tesoros de Papá - Calle 8a entre carreras 1 y 2 El Carmen, Barquisimeto 3001, Lara, Venezuela",
"Beauty Shop - Av Unda CC del Este P/B Mini Tienda 3 Sector, Guanare 3350, Portuguesa, Venezuela",
"Abasto Alvarez C.A. - 3JJR+9VH, Barquisimeto 3001, Lara, Venezuela",
"Pizzas Rafucho - urb. Simón Bolívar, Av. 3, casa nro 8 local 01. Sector, Los Próceres, Guanare 3350, Portuguesa, Venezuela",
"Antojitos - Av. Unda, C.c del Este, planta baja, local 15, Guanare 3350, Portuguesa, Venezuela",
"Pidiendo y Comiendo Pizzeria - Sector los Proceres, local 1, casa 74 C. 9, Guanare 3350, Portuguesa, Venezuela",
"POSADA VILLA DEL CARMEN - Avenida principal de Playa Grande, Calle 1, Catia La Mar 1162, La Guaira, Venezuela",
"La caridad fresco market - Centro comercial galerías playa grande nivel 1 local 18, Maiquetía 1162, La Guaira, Venezuela",
};
}
