class AutoSuggestionsAM { static final reviewedTitlesAM = const {"Totimarket - 15 Avenida Las Delicias, Maracaibo 4005, Zulia, Venezuela",
"JEOTCELL - A.V 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"ALCANPO Cell Sucursal #2 - Av. 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"Agrotienda - 5M5J+32J, Avenida, El Cují 3001, Lara, Venezuela",
"DC Grand Bazaar - Av 15 Delicias, Calle 100, Av. Libertador, Maracaibo 4005, Zulia, Venezuela",
"Optica Visión - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"DC Grand Bazaar - Av 15 Delicias, Calle 100, Av. Libertador, Maracaibo 4005, Zulia, Venezuela",
"Comercializadora & Distribuidora Fabrimuebles Remolina C.a - Av José Antonio Paez, C.C Multiplaza El Paraíso, Nivel 6, Local C-12 y C-13, Urb, Zona Postal 1020, Caracas 1020, Distrito Capital, Venezuela",
"Global Cell System - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"Servicio Técnico JR Cell - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"Magic Import - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"mmsolucionestecnologicas - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"StarFactory4 - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"TECNOCELL2021,C.A - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"Ferreteria Coinvergar - Av Simón Bolívar con calle 23 y 24 Edificio Blandiski local 1 sector, Cementerio, Guanare 3350, Portuguesa, Venezuela",
"Glou Chic - Mercado Economía Popular la Hoyada. Pasillo Venezuela Local 1866, Avenida Fuerzas Armadas, Caracas 1012, Distrito Capital, Venezuela",
};
}
