class AutoSuggestionsAM { static final reviewedTitlesAM = const {"Anais Nails - Catia La Mar, La Guaira",
"Freddytattoo - Av. La Armada, Catia La Mar 1162, La Guaira",
"Zona Servi - Calle Jefatura a Cristo, Maiquetía, La Guaira",
"Multiservicios Germany C.A. - Caracas, Distrito Capital",
"Inversiones Valentina Bisutery C.A - Centro Comercial La Castilla, Calle Guillermo José Schael, Caracas, Distrito Capital",
"Inversiones Sport Family Full C.A - Avenida Mohedano, Caracas, Miranda",
"7 Estelas - Avenida Tacagua, Catia La Mar, La Guaira",
"Goodstyleccs - Caracas, Distrito Capital",
"Ekko Barber Shop - Centro Comercial La Castilla, Calle Guillermo José Schael, Caracas, Distrito Capital",
"Arame Accesorios - Transversal 1, Caracas, Distrito Capital",
"Inversiones Valentina Bisutery C.A - Centro Comercial La Castilla, Calle Guillermo José Schael, Caracas, Distrito Capital",
"Piso 2 - Multiservicios Germany C.A., Caracas, Distrito Capital",
"Tecno7Repair - Bellas Artes, Caracas, Distrito Capital",
"Goodstyleccs - Caracas, Distrito Capital",
"Ekko Barber Shop - Centro Comercial La Castilla, Calle Guillermo José Schael, Caracas, Distrito Capital",
"Arame Accesorios - Torre C, Transversal 1, Caracas, Distrito Capital",
"Área Electric - CC Lord Center, Avenida El Lago, Caracas, Distrito Capital",
"EJCA Electrónica - C.A., Caracas, Distrito Capital",
"Ojo de Loto - Centro Comercial Lord Center, Avenida El Lago, Caracas, Distrito Capital",
"PIZZA KIERO - Maracaibo, Zulia",
"ROTULARTE - Guanare, Portuguesa",
"Moto Sport - Guanare, Portuguesa",
"Crearteideas - Calle 100, Maracaibo, Zulia",
"Fina Fantasia - Calle 100, Maracaibo, Zulia",
"Cocos Sweet Shop - Calle Guillermo José Schael, Caracas, Distrito Capital",
"Big Fashion Ccs - Calle Guillermo José Schael, Caracas, Distrito Capital",
"Repuestos Betancourt - La Guaira",
"Inversiones Car21 Car30 - Maiquetía, La Guaira",
"H2WQ J8V Floristeria Paraiso Galipan - C. Real de Pariata, Maiquetía 1161, La Guaira",
"Trovas Ve - Calle 162, San Francisco, Zulia",
"Trovas Ve - Calle 162, San Francisco, Zulia",
"PandaFix - Calle 100, Maracaibo, Zulia",
"Pastelería El Punto Andino - Sector Cementerio, Guanare, Portuguesa",
"Supermercado La Sorpresa De Pariata - Maiquetía 1161, La Guaira",
"Luncheria el Rincon de Pariata - Maiquetía, La Guaira",
"Comercial el Divino Niño - Vía Teleférico, Macuto 1164, La Guaira",
"Café Teleférico Douglas - Vía Teleférico, Macuto 1164, La Guaira",
"Inversiones VFC - C. Los Baños, Maiquetía 1161, La Guaira",
"Electrónica Compusol - C. Los Baños, Maiquetía 1161, La Guaira",
"Inverciones YOYO C.A - Avenida Las Delicias, Maracaibo, Zulia",
"Party y Algo Más - Calle 100, Maracaibo, Zulia",
"Servicio técnico electrónica - Catia La Mar, La Guaira",
"Calzados Emanuel - Av. La Armada, Catia La Mar, La Guaira",
"Bungalow - Barquisimeto, Lara",
"Comercializadora Don Apolinar Campos",
"Comercializadora Don Apolinar Campos - Guanare, Portuguesa",
"Todo repuestos DF s.a - 500mtrs del mercal, Av principal a, Guanare, Portuguesa",
"Inversiones Chop 2017 - Avenida La Armada, Catia La Mar, La Guaira",
"Servicell - Av. La Armada, Catia La Mar, La Guaira",
"Repuestos Tu Preferido - Guanare, Portuguesa",
"Charcutería Capuchino C.A - Calle Roscio, San Juan de Los Morros, Guárico",
"Totimarket - Avenida Las Delicias, Maracaibo, Zulia",
"Un Lugar Diferente para Comprar - Avenida Padilla Calle 93, Maracaibo, Zulia",
"JEOTCELL - Calle 100, Maracaibo, Zulia",
"ALCANPO Cell Sucursal #2 - Calle 100, Maracaibo, Zulia",
"Agrotienda - Avenida, El Cují, Lara",
"Centro Comercial Gran Bazar - Avenida Libertador, Maracaibo, Zulia",
"Optica Visión - Calle 100, Maracaibo, Zulia",
"Comercializadora & Distribuidora Fabrimuebles Remolina C.a - Zona Postal 1020, Caracas, Distrito Capital",
"Global Cell System - Calle 100, Maracaibo, Zulia",
"Servicio Técnico JR Cell - Calle 100, Maracaibo, Zulia",
"Magic Import - Calle 100, Maracaibo, Zulia",
"mmsolucionestecnologicas - Calle 100, Maracaibo, Zulia",
"StarFactory4 - Calle 100, Maracaibo, Zulia",
"TECNOCELL2021 -C.A, Calle 100, Maracaibo, Zulia",
"Ferreteria Coinvergar - Guanare, Portuguesa",
"Glou Chic - Avenida Fuerzas Armadas, Caracas, Distrito Capital",
"Techno Spacex - Caracas, Distrito Capital",
"El Techo de La Ballena - entre esquina Gradilla y San Jacinto, Avenida Este 2, Caracas, Distrito Capital",
"Inversiones I Store - Av. Soublette, Maiquetía 1161, La Guaira",
"M&L2021 - 1060 C. Sorocaima, Maiquetía 1161, La Guaira",
"Mundo de Impresiones 2010 C.A - MINI LOCAL OESTE, VENEZUELA, ESTADO LA GUAIRA, MUNICIPIO VARGAS, AVENIDA SOUBLETTE, CENTRO COMERCIAL LITORAL, PISO PB",
"Inversiones Store Son - Av. Soublette, Maiquetía, La Guaira",
};
}
