class AutoSuggestions79461818 {
  static final reviewedTitles79461818 = const {
    "Multihidromaticos JJYAÑEZ CA - La Concordia Carrera 5 con calle 4 y 5 Local N- 4 - 96, San Cristóbal 5001, Táchira, Venezuela",
    "Mundo de Azúcar, f.p. - Av unda entre calle 9 y 8 C.C La arenosa nivel 1, local 39 Av. Unda, Guanare 3350, Portuguesa, Venezuela",
    "RedsComp - La Concordia Carrera 5 con calle 4 y 5 Casa N- 4 - 42, San Cristóbal 5001, Táchira, Venezuela",
// "RedsComp - La Concordia Carrera 5 con calle 4 y 5 Casa N- 4 - 42, San Cristóbal 5001, Táchira, Venezuela",
    "Tecnochia - 5ta avenida entre calles 8 y 9 CC Shopping Center Nivel PB Local 12, San Cristóbal 5001, Táchira, Venezuela",
    "Inversiones Darwin Rojas, C.A. - Calle Real de Maiquetia, Local 667, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Milca Torres 2021, C.A. - Calle Real de Maiquetia, Local 597, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones M & M 2013, C.A. - Calle Real de Maiquetia, Local 689, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Josdavier 2017, C.A. - Calle Real de Maiquetia, Local 677, Mercado Cacique Maiquetia, Pasillo 12, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Delgado Maiquel(K.D.F.2176) F.P. - Calle Real de Maiquetia, Local 631, Mercado Cacique Maiquetia, Pasillo Central, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Orocristal, C.A. - Calle Real de Maiquetia, Local 478, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Carol, C.A. - Calle Libertador local 247, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1162, La Guaira, Venezuela",
    "Ferreteria Arturo G - Carrera 6 con esquina calle 2 casa Nro 2-3, local 1 y 2, Guanare 3350, Portuguesa, Venezuela",
    "El Tinajero Hogar C.A. - Calle 11 entre carrera 5 y 6 Edificio El Tinajero P/B Local 1, Guanare 3350, Portuguesa, Venezuela",
    "Ricar2 House - Los Chorritos, Av Principal, Casa Nro 34, Principal, Tocuyito 2035, Carabobo, Venezuela",
    "BB Store Servicios, CA - AV. Alirio Ugarte Pelayo, Centro Comercial Virgen Del Valle, Local 47 Piso 1, Maturín 6201, Monagas, Venezuela",
    "XTREMO JULKAR 27, C.A - Local 41 Piso PB, Centro Comercial Virgen Del Valle, Av. Alirio Ugarte Pelayo, Maturín 6201, Monagas, Venezuela",
    "FRUTTY MANIA - Centro Comercial Virgen Del Valle, AV. Alirio Ugarte Pelayo, Local 53, Piso 1 Via Viboral, Maturín 6201, Monagas, Venezuela",
    "Sucursal CA BST FARMA - Zona Industrial Castillito Centro Comercial Termini PB local 2. Av. Don Julio Centeno San diego, Valencia 2006, Carabobo, Venezuela",
    "Inversiones Chiquita Plus, C.A. - Calle Libertador, local 016, Mercado Cacique Maiquetia, Pasillo 1, Maiquetía 1161, La Guaira, Venezuela",
// "Sucursal CA BST FARMA - Zona Industrial Castillito Centro Comercial Termini PB local 2. Av. Don Julio Centeno San diego, Valencia 2006, Carabobo, Venezuela",
    "Video Club - AV. Alirio Ugarte Pelayo, Centro Comercial Virgen Del Valle, Local 51 Piso 1, Maturín 6201, Monagas, Venezuela",
    "Inversiones Pris Muel David, F.P. - Calle Libertador, local 083, Mercado Cacique Maiquetia, pasillo 1, Maiquetía 1162, La Guaira, Venezuela",
    "Panda Verde - Carrera 12 entre calle 9 y 10 casa 9-28 Local 1 sector, Guanare 3350, Portuguesa, Venezuela",
    "O&J Suministros C.A - Av. 74, calle 106, Centro Comercial Infra, PB local 11, San Diego 2006, Carabobo, Venezuela",
    "Mango de Oro C.A. - Av unda esquina carrera 11 Casa nro 1 local 1 sector, Guanare 3350, Portuguesa, Venezuela",
    "11.11 Boutique - G46V+MR8, Avenida Transversal 10, Caracas 1060, Distrito Capital, Venezuela",
    "Pintacar Express - JX49+V7F, Calle Tacagua, Catia La Mar 1162, La Guaira, Venezuela",
    "Inversiones Oshun, C.A. - Calle libertador, Local 182, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1161, La Guaira, Venezuela",
    "Fruber 1111 - Calle Páez, entre Av Guaicaipuro y calle Elice. Edificio Caracas, local C. Chacao, Caracas 1080, C. Páez, Caracas 1060, Distrito Capital, Venezuela",
    "Tu Cuevita Repostera La Arenosa - Carrera 12 entre calles 14 y 15 local 1 casa 12-37, Sector, Guanare 3350, Portuguesa, Venezuela",
    "Helados Dulces y Antojos - Av. Paseo los Ilustres con, Local 01, Sector la Comunidad, Casa, nro 9-169 Principal de la Comunidad, Guanare 3350, Portuguesa, Venezuela",
    "2 PI, C.A. Materiales De Carpintería - 3MJH+RF5, Av. Simón Rodriguez, Barquisimeto 3001, Lara, Venezuela",
    "Inversiones Somger Cells, C.A. - Calle Real de Maiquetia, Local 670, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Disvimol - Carretera Panamericana altura Patiecitos casa N 9-6 local 1A, Táchira Venezuela, Vista Alegre, Panama",
    "Bodega la 30 - Carrera 30 &amp; Calle 26 y 25, Barquisimeto 3001, Lara, Venezuela",
    "Centro de Economia Comunal Manuelita Saenz - C.C Manuelita Sáenz Nv. 4, Local #123, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Jhoelins, C.A. - Calle Libertador, Local 406, Mercado Cacique Maiquetia, Pasillo 5, Maiquetía 1161, La Guaira, Venezuela",
    "Full Pizza - 27R4+2W6, Av. Unda, Guanare 3350, Portuguesa, Venezuela",
    "Café Plaza - Calle 16 Entre Carreras 4 Y 5 Edificio Don Armando local 02 Frente A La Plaza Bolivar, Guanare 3350, Portuguesa, Venezuela",
    "Inversiones Don Miguelacho - Av. Principal de los proceres entre calle 1 y 2, sector los Próceres, casa nro 30, local 01, Guanare 3350, Portuguesa, Venezuela",
    "la boca del lobo - HQGG+J5Q, Ejido 5111, Mérida, Venezuela",
    "Restaurante Siglo XXI - Calle la Iglesia, Casa numero 4, local PB Calle La Iglesia, Sabana Caracas 1050, Distrito Capital, Venezuela",
    "Puerkos Restaurant - Sabana grande, local sede, PB, Edificio Don Fernando, Av. Casanova, Caracas 1060, Distrito Capital, Venezuela",
    "Antojitos de Ysabell, C.A - Local 5, Catedral de San Agustín, C. Ricaurte, Valencia 2015, Carabobo, Venezuela",
    "Inversiones Foncho Peña - Av. Unda con carrera 9 y 11 Sector La Arenosa, Mercado Municipal, Muro de Los Lamentos, Local 08, Guanare 3350, Portuguesa, Venezuela",
    "Optica Servilens CA - Av. Sucre, Maracay 2101, Aragua, Venezuela",
    "N.B King Shoes C.A - C.c Las americas P.B 39, Calle El Bosque, Maracay 2101, Aragua, Venezuela",
    "Talabarteria m & villalobos g III - 2GQ9+89V, Avenida Lisandro Alyarado, Maracay 2126, Aragua, Venezuela",
    "Barber Tatto 911 - Carrera 4 calle 2 y 3 frente a la Plaza Bolívar Tariba Centro comercial Los Daniel&#39;s local N-16 P1, Táriba 5017, Táchira, Venezuela",
    "Soul Rebel Moda - Boulevard de Sabana Grande, entre Mercado Colonial y Centro Comercial Chacaito, local 1, Caracas 1050, Distrito Capital, Venezuela",
    "11:11 Sport Bar Restaurant - Centro Empresarial Barquisimeto, Local 14, Barquisimeto 3001, Lara, Venezuela",
    "Mr mascotas - Av. Los Leones, planta baja cc.trinitarias, local 25g, Barquisimeto 3001, Lara, Venezuela",
    "Multiservicios Barreto - Calle 41 &amp; Carrera 28, Barquisimeto 3001, Lara, Venezuela",
    "Comercial Marinera C.A - JX5P+C37 de, Avenida Principal, Catia La Mar 1162, Vargas, Venezuela",
    "Sinaí Market - Av Primera Transversal, Caracas 1060, Miranda, Venezuela",
    "Bodegón Los Tesoros de Papá - Calle 8a entre carreras 1 y 2 El Carmen, Barquisimeto 3001, Lara, Venezuela",
    "Beauty Shop - Av Unda CC del Este P/B Mini Tienda 3 Sector, Guanare 3350, Portuguesa, Venezuela",
    "Abasto Alvarez C.A. - 3JJR+9VH, Barquisimeto 3001, Lara, Venezuela",
    "Pizzas Rafucho - urb. Simón Bolívar, Av. 3, casa nro 8 local 01. Sector, Los Próceres, Guanare 3350, Portuguesa, Venezuela",
    "Antojitos - Av. Unda, C.c del Este, planta baja, local 15, Guanare 3350, Portuguesa, Venezuela",
    "Pidiendo y Comiendo Pizzeria - Sector los Proceres, local 1, casa 74 C. 9, Guanare 3350, Portuguesa, Venezuela",
    "POSADA VILLA DEL CARMEN - Avenida principal de Playa Grande, Calle 1, Catia La Mar 1162, La Guaira, Venezuela",
    "La caridad fresco market - Centro comercial galerías playa grande nivel 1 local 18, Maiquetía 1162, La Guaira, Venezuela",
    "Gaby Technology - local 123, Centro de Economía Comunal Manuelita Saenz, Piso 4 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "ArepaTrekking - Calle principal de Güeime, casa S/N, C92G+JC2, Santa Lucía 1214, Miranda, Venezuela",
    "Mariangel Studio - Carrera 4 calle 2 y 3 frente a la Plaza Bolívar Tariba Centro comercial Los Daniel&#39;s local N- 11 P1, Táriba 5017, Táchira, Venezuela",
    "Haru Nails Studio - Carrera 4 calle 2 y 3 frente a la Plaza Bolívar Tariba Centro comercial Los Daniel&#39;s local N-13, Troncal 1, Táriba 5017, Táchira, Venezuela",
    "La Brachera In C.A. - CALLE PIAR, LOCAL 03 C. Montilla, Guacara 2015, Carabobo, Venezuela",
    "Creaciones Doumari, F.P. - Calle Libertador, Local 013, Mercado Cacique Maiquetia, Pasillo 1, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Charay, C.A. - Calle Real de Maiquetia, Local 664, Mercado Cacique Maiquetia, Pasillo 12, Maiquetía 1162, La Guaira, Venezuela",
    "El Rincóncito de Romi, C.A. - Calle Real de Maiquetia, Local 669, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Bodegón RMR - Av. Unda con, P/B, edificio Aura, local 05 Carrera 12, Guanare 3350, Portuguesa, Venezuela",
    "Strong Physical Center, C.A - Nivel Mezzanina, Centro Comercial Virgen Del Valle, Local LM-45 A, Av. Alirio Ugarte Pelayo, Via Viboral, Maturín 6201, Monagas, Venezuela",
    "Alimentos y Suministros Galax - Centro Comercial Comunitario Norte, Local 0809, Av. Alirio Ugarte Pelayo, Via Viboral, Maturín 6201, Monagas, Venezuela",
    "Inversiones Marchael, C.A. - Calle Real de Maiquetia, Local 469, Mercado Cacique Maiquetia, pasillo 6, Maiquetía 1162, La Guaira, Venezuela",
    // "La caridad fresco market - Centro comercial galerías playa grande nivel 1 local 18, Maiquetía 1162, La Guaira, Venezuela",
    "Vaporhot vzla - Av Principal de Playa Grande, Catia La Mar 1162, La Guaira, Venezuela",
    "Ferretería Comercial Ramar - Quinta Nilsa N°31. Calle Real De Antimano, entre calle montalbancito, y, C. La Estación, Caracas 1100, Distrito Capital, Venezuela",
    "Distribuidora Olivo C.A - Carrera 25 &amp;, C. 33, Barquisimeto 3001, Lara, Venezuela",
    "Cassa Market - 37 Carrera 25, Barquisimeto 3001, Lara, Venezuela",
    "Dulces y algo más - Carrera 28 &amp;, Calle 25, Barquisimeto 3001, Lara, Venezuela",
    "Clínica Vitalis - Piso 10, oficina 03, Torre América, Avenida Venezuela, Caracas 1050, Distrito Capital, Venezuela",
    "Novedades Hello C.A. - Av. Principal de Propatria &amp; Av Simón Bolívar. Centro Comercial Propatria, nivel 2, local 26 A, Caracas 1030, Distrito Capital, Venezuela",
    "Frigususa - Urb. Playa Grande Av. Hotel Marriott, 1162, La Guaira, Venezuela",
    "Zulyslunchandgrill - 3MGJ+6WX, C. 26, Barquisimeto 3001, Lara, Venezuela",
  };
}
