class AutoSuggestions95763284 { static final reviewedTitles95763284 = const {"La Spezia Cafe - Av Francisco de Miranda, Centro Comercial Parque Cristal, nivel C1, local 12, Caracas 1060, Distrito Capital, Venezuela",
"Bodegón Daroy - Av. 1, Edificio monte ulio, Caracas 1060, Distrito Capital, Venezuela",
"Spa Beautiful Fitness - Urbanización montalban I Avenida Tres entre Calle 3 y Calle 2 Quinta Mami Caracas, Caracas 1020, Distrito Capital, Venezuela",
"Kiosco Mene Grande - Avenida Francisco de Miranda, Edifico Mene Grande, F5W3+FFV, Caracas 1060, Distrito Capital, Venezuela",
"Distribuidora Dimperca, C.A. - G457+GCP, Caracas 1050, Capital District, Venezuela",
"Distribuidora Dimperca, C.A. - G457+GCP, Caracas 1050, Capital District, Venezuela",
"Doravila Restaurante C.A - Norte quinta villaelisena, Av Principal de Boleíta, Caracas 1071, Distrito Capital, Venezuela",
"Las Delicias de Vicenta - Calle monseñor Juan Grilc, Edificio Los Cárpatos - Piso 3, Apto. 43 Caracas, Caracas 1061, Distrito Capital, Venezuela",
"Di-Masi Vinos C.A. - Galpón 2 Avenida Francisco de Miranda, Caracas 1071, Distrito Capital, Venezuela",
"Papelería Moderna - La concordia, barrio la castra, entre carreras 10 y 10 bis con calle 2 bis y calle 3, detrás de comercial la gran parada, San Cristóbal 5001, Táchira, Venezuela",
"AquaFull - Av. Maracaibo, Caracas 1050, Distrito Capital, Venezuela",
"GRUPO CYXCOM C.A. - CENTRO COMERCIAL SABANA GRANDE LOCAL 7 NIVEL MESANINA CARACAS, Caracas 1050, Distrito Capital, Venezuela",
"Centro Comercial Lord Center - 1019 caracas, Caracas 1010, Distrito Capital, Venezuela",
"Inversiones Javimay1804, c.a - CC. Multicentro Maiquetia, calle Los Baños, H2WX+C69, C. Los Baños, Maiquetía 1162, Vargas, Venezuela",
"El Dulce Mundo de Cami - Centro Comercial Merpoeste, Piso 2, local 14, Caracas 1064, Miranda, Venezuela",
};
}
