class AutoSuggestions50879693 { static final reviewedTitles50879693 = const {"Trappa pizzeria&bar - Koprska ulica 94, 1000 Ljubljana, Slovenia",
"PraveStvari - Dunajska c. 122, 1000 Ljubljana, Slovenia",
"Mk Gril, priprava in dostava hrane, Miomir Kostić s.p. - Bratovševa ploščad 12, 1000 Ljubljana, Slovenia",
"Fotokopirnica Gallus, Kristina Kogelnik s.p. - Grajska ulica 5, 2000 Maribor, Slovenia",
"Maribor INN hotel - Karantanska ulica 26, 2000 Maribor, Slovenia",
"Um - ha, gostinske storitve, d.o.o. - BTC tržnica sever, Italijanska ulica 7, 1000 Ljubljana, Slovenia",
"Čebelarstvo Vasič - Litijska cesta 12, 1000 Ljubljana, Slovenia",
"Kava bar mi Srša Patricija s.p. - Ruska ulica 9, 2000 Maribor, Slovenia",
"Kavarnica Rokaj - Usnjarska ulica 3, 2000 Maribor, Slovenia",
"Kampus Food - Pivovarniška ulica 6, 1000 Ljubljana, Slovenia",
"Pause Cafe - Dravska ulica 7, 2000 Maribor, Slovenia",
"Ljubljanski Brivec by MIČ STYLING - SLOVENSKA - Slovenska cesta 30, 1000 Ljubljana, Slovenia",
"Young Mič Styling - Citypark - Moskovska ulica 4, 1000 Ljubljana, Slovenia",
"SIMPLE BARBER SHOP - Qlandia, Cesta 25. junija 1a, 5000 Nova Gorica, Slovenia",
"Sten Time - Otoška cesta 5, 8000 Novo mesto, Slovenia",
"STEN TIME - Ormoška cesta 15, 2250 Ptuj, Slovenia",
};
}
