class AutoSuggestions99520673 {
  static final reviewedTitles99520673 = const {
    "Leskovački dvor - Dunajska c. 57, 1000 Ljubljana, Slovenia",
    "Žito, Delikatesa Koseze - Vodnikova cesta 187, 1000 Ljubljana, Slovenia",
    "Kino Komuna - Kino Komuna, Kino Komuna, Tomšičeva ulica 2, 1000 Ljubljana, Slovenia",
    "SIMPLE - Novo mesto Mercator - Ljubljanska cesta 47, 8000 Novo mesto, Slovenia",
    "Gostilna Jakomin Kubed - Elvis Jakomin s.p. - Kubed 3a, 6272 Gračišče, Slovenia",
    "Venera Shop - Sex shop Domžale - Unnamed Road, 1230, 1230 Domžale, Slovenia",
    "Takos - Pobreška cesta 18, 2000 Maribor, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Prešernova cesta 53, 6310 Izola, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Ulica Gradnikove brigade 53, 5000 Nova Gorica, Slovenia",
    "Venera shop - Sex shop Murska Sobota - Nemčavci 1d, 9000 Murska Sobota, Slovenia",
    "Venera shop - Sex Shop Maribor - Cesta proletarskih brigad 100, 2000 Maribor, Slovenia",
    "Piccolo bar - BTC City, 9000, 9000 Murska Sobota, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Tržaška c. 63, 1000 Ljubljana, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Trubarjeva cesta 43, 1000 Ljubljana, Slovenia",
    "Km Terjatve in finančne storitve, Klementina Kurunić s.p. - Žolgarjeva ulica 25, 2310 Slovenska Bistrica, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Ulica pri Velikih vratih 18, 6000 Koper, Slovenia",
    "Imperija center zdravja in lepote, Karmen Puntar s.p. - Ameriška ulica 3, 1000 Ljubljana, Slovenia",
    "F. Dvor, services and trade D.O.O. - Ob železnici 14, 1000 Ljubljana, Slovenia",
    "Ljubljanski Brivec by Mič styling - HOTEL UNION - Miklošičeva cesta 1, 1000 Ljubljana, Slovenia",
    "YOUNG MIČ STYLING - Trubarjeva cesta 28, 1000 Ljubljana, Slovenia",
    "Mič Styling - Poljanska - Poljanska cesta 13, 1000 Ljubljana, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Seškova cesta 9, 1215 Medvode, Slovenia",
    "SIMPLE - Jurčkova Cesta 223, 1000 Ljubljana, Slovenia",
    "SIMPLE - Nova Gorica Qlandia - Cesta 25. junija 1a, 5000 Nova Gorica, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Šuceva ulica 25, 4000 Kranj, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Šaleška cesta 19a, 3320 Velenje, Slovenia",
    "Kavarna Zvezda - Wolfova ulica 14, 1000 Ljubljana, Slovenia",
    "Fitnesshop - Rakuševa ulica 10, 1000 Ljubljana, Slovenia",
    "Army Shop Landing Zone - Madžarska Ulica Šmartinska cesta 152 BTC- Hala 11, 1000 Ljubljana, Slovenia",
    "Bags & More - Igriška ulica 8, 1000 Ljubljana, Slovenia",
    "Mič Styling - Rimska - Rimska cesta 16, 1000 Ljubljana, Slovenia",
  };
}
