class AutoSuggestions99902538 {
  static final reviewedTitles99902538 = const {
    "Liupka BTC - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "Krisma design store - Avstrijska ulica 13, 1000 Ljubljana, Slovenia",
    "Avtocenter AvtoStop - Devova ulica 18, 1000 Ljubljana, Slovenia",
    "Tattoo & Piercing Studio CULT - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "ESPRESSO d.o.o. Ljubljana, PE ESPRESSO BTC - Ameriška ulica 8, 1000 Ljubljana, Slovenia",
    "ALS avdio.video - Masarykova ulica 24, 1230 Domžale, Slovenia",
    "Big Bang Ljubljana, BTC - Francoska ulica 17, 1000 Ljubljana, Slovenia",
    "Estetika Fabjan d.o.o. - Nova Gorica - Vipavska cesta 58, 5000 Nova Gorica, Slovenia",
    "GOLD STORE - PE CELJE - Ljubljanska c. 1B, 3000 Celje, Slovenia",
    "Breza caffe - Celovška cesta 179b, 1000 Ljubljana, Slovenia",
    "GOLD STORE - PE BTC - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "Barbarella BTC Bistro - Ameriška ulica 13, 1000 Ljubljana, Slovenia",
    "Q Vapehouse Maribor Ena - Premium Vape Shop - Trg svobode 5, 2000 Maribor, Slovenia",
    "GOLD STORE - PE LJUBLJANA 1 - Miklošičeva cesta 10, 1000 Ljubljana, Slovenia",
    "Gostilna in pizzerija Jurman - Zaloška cesta 151, 1000 Ljubljana, Slovenia",
// "Gostilna in pizzerija Jurman - Zaloška cesta 151, 1000 Ljubljana, Slovenia",
    "Happy End Club - Lochhausener Str. 106, 81249 München, Germany",
    "Zavrh - Zabreznica 75, 4274 Žirovnica, Slovenia",
    "Huda čupca frizerski salon - Topniška ulica 35 d, 1000 Ljubljana, Slovenia",
    "BARBARELLA ARKADE BISTRO - Adamič-Lundrovo nabrežje 3 nasproti pokrite, 1000 Ljubljana, Slovenia",
    "Vodno mesto Atlantis - Španska ulica 1, 1000 Ljubljana, Slovenia",
    "Restavracija City - Šmartinska c. 140, 1000 Ljubljana, Slovenia",
    "Minicity Ljubljana - Ameriška ulica 13, 1000 Ljubljana, Slovenia",
    "MIČ STYLING - Kristalna palača - 8, Ameriška ulica, 1000 Ljubljana, Slovenia",
    "Simple - Ljubljana Citypark - Moskovska ulica 4, 1000 Ljubljana, Slovenia",
    "Dnevna Soba - Radvanjska cesta 29, 2000 Maribor, Slovenia",
    "Kolesarska trgovina Maxisport Čerin Ljubljana - Letališka cesta 5, 1000 Ljubljana, Slovenia",
    "frizerski salon MIX - Litija Spar - Brodarska ulica 2, 1270 Litija, Slovenia",
    "Marpurgi - Grajski trg 3, 2000 Maribor, Slovenia",
    "Biljard klub Direkt - Tbilisijska ulica 83, 1000 Ljubljana, Slovenia",
    "Kozlovna Poštna - Poštna ulica 12, 2000 Maribor, Slovenia",
    "ActionMama outdoor shop - Dunajska c. 177, 1000 Ljubljana, Slovenia",
    "Acapulco gostinstvo d.o.o. - Vodnikova cesta 155, 1000 Ljubljana, Slovenia",
    "Bioguano trgovina in storitve d.o.o. - Toplarniška ulica 1b, 1000 Ljubljana, Slovenia",
    "Da Noi - Ulica Eve Lovše 1, 2000 Maribor, Slovenia",
    "Športni bar Krim - Ob dolenjski železnici 48, 1000 Ljubljana, Slovenia",
    "Sarajevski grill Pavza - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "Cacao Ljubljana - Petkovškovo nabrežje 3, 1000 Ljubljana, Slovenia",
    "Bungalow Portorož - Obala 18a, 6320 Portorož, Slovenia",
    "SIMPLE - Koper Park center - Ankaranska cesta 2, 6000 Koper - Capodistria, Slovenia",
    "Sten Time - Šmartinska c. 152g, 1000 Ljubljana, Slovenia",
    "Venera Shop - Sex shop & Erotic Botique Ljubljana BTC - Ameriška ulica 8, 1000 Ljubljana, Slovenia",
    "Lolita erotic shop, erotična trgovina, sex shop - Ameriška ulica 13 BTC dvorana A, 1000 Ljubljana, Slovenia",
// "Sten Time - Šmartinska c. 152g, 1000 Ljubljana, Slovenia",
// "Sten Time - Šmartinska c. 152g, 1000 Ljubljana, Slovenia",
    "Mič styling Maribor - Slovenska ulica 7, 2000 Maribor, Slovenia",
    "Cacao BTC - Letališka cesta 11, 1000 Ljubljana, Slovenia",
    // "Cacao Ljubljana - Petkovškovo nabrežje 3, 1000 Ljubljana, Slovenia",
    "FITNES KLINIKA d.o.o. - Španska ulica 1, 1000 Ljubljana, Slovenia",
    "Venera Shop - Sex shop Ljubljana - Vošnjakova ulica 5, 1000 Ljubljana, Slovenia",
    "Locap Group - Your Local Accommodation Point - Letoviška pot 11, 6320 Portorož, Slovenia",
    "SkyEye Bitcoin ATM - Obrežna ulica 33, 2000 Maribor, Slovenia",
    "Čisto Belo, čistilnica in pralnica perila, d.o.o. - Gradis, Letališka cesta 33 E, 1000 Ljubljana, Slovenia",
    "Laplac & Pizza Fabrika Ptuj - Rajšpova ulica 26, 2250 Ptuj, Slovenia",
    "LAM Care - Žanova ulica 3, 4000 Kranj, Slovenia",
    "Tuš supermarket Planet Koper - Ankaranska cesta 2, 6000 Koper - Capodistria, Slovenia",
    "Tuš supermarket Pobrežje - Ulica Veljka Vlahovića 21, 2000 Maribor, Slovenia",
    "Tuš supermarket Planet Novo mesto - Topliška cesta 2, 8000 Novo mesto, Slovenia",
    "Kava Bar - BS, Pot na Orle 2, 1000 Ljubljana, Slovenia",
    "Airsoft klub Ptuj - Ob Grajeni 1, 2250 Ptuj, Slovenia",
    "La Cantina - Pohorska ulica 60, 2000 Maribor, Slovenia",
    "GOLD STORE - PE KOPER - Pristaniška ulica 2, 6000 Koper - Capodistria, Slovenia",
    "GOLD STORE - PE MARIBOR - Cafova ulica 4, 2000 Maribor, Slovenia",
    // "GOLD STORE - PE BTC - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "Sport Vision City Park - Šmartinska c. 152g, 1000 Ljubljana, Slovenia",
    "Cafe Botique - Cesta 1. maja 77, 4000 Kranj, Slovenia",
    "Masim Caffe - Ulica XXX. divizije 21, 5000 Nova Gorica, Slovenia",
    "Molek.si d.o.o. - Vrtnarija 3, 1360 Vrhnika, Slovenia",
    "Tuš supermarket Grosuplje - Gasilska Cesta 1, 1290 Grosuplje, Slovenia",
    "Buzz - Šmartinska c. 152g, 1000 Ljubljana, Slovenia",
    "Elektro team servis Peter Čelesnik s.p. - Hrastulje 44, 8275 Škocjan, Slovenia",
    "PILAR INN bar - Kocljeva ulica 9, 9000 Murska Sobota, Slovenia",
    "Digitalno zobozdravstvo VBO d.o.o. - Mladinska ulica 54, 2000 Maribor, Slovenia",
    "ASTRO CAFFE - Vojkova cesta 49, 5000 Nova Gorica, Slovenia",
    "Bar & Gostinica PADELCA - Vogrsko 7, 5293 Volčja Draga, Slovenia",
    "Žito maloprodaja trgovsko podjetje na veliko in malo, d.o.o., poslovna enota Potojoča trgovina arkade - Tržnica, Pogačarjev trg 1, 1000 Ljubljana, Slovenia",
    "Domas - Kont družba za svetovanje in storitve d.o.o., Ljubljana - Rožna Dolina, cesta XIII 5, 1000 Ljubljana, Slovenia",
    "Gerry Weber - Wolfova ulica 6, 1000 Ljubljana, Slovenia",
    "Tkanina d.o.o. - Cankarjeva - Cankarjeva cesta 4, 1000 Ljubljana, Slovenia",
    "Pri Janezu - Tkanina d.o.o. - Vodnikov trg 3, 1000 Ljubljana, Slovenia",
    "Avtodeli Potokar - Ipavčeva ulica 21, 3000 Celje, Slovenia",
    "Piknik Park Podpeč - Cesta v Zgornji Log 32, 1000 Ljubljana, Slovenia",
    "bar Kofiček - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "Pr' Boltu, gostinska dejavnost Nina Denac s.p. - Litijska cesta 38, 1000 Ljubljana, Slovenia",
    "Tenis društvo ob Savi - Tenis drustvo, ob Savi, 1000 Ljubljana, Slovenia",
    "Kavarna Zlato Polje - Koroška cesta 30, 4000 Kranj, Slovenia",
    "Svet križarjenj - Potovalna agencija - Latinski trg 6, 1000 Ljubljana, Slovenia",
    "Avtodeli Potokar - Tovarniška cesta 4a, 5270 Ajdovščina, Slovenia",
    "Steklarstvo Potokar - Cesta Franceta Prešerna, 4270 Jesenice, Slovenia",
    "Hotenjka, D.O.O. - Tržaška c. 513b, 1351 Brezovica pri Ljubljani, Slovenia",
    "Avtodeli Potokar - Tovarniška ulica 7, 8270 Krško, Slovenia",
    "Avtodeli Potokar, Sežana - Cesta na Lenivec 34, 6210 Sežana, Slovenia",
    "Avtodeli Potokar - Dunajska c. 421, 1000 Ljubljana, Slovenia",
    "Atlantis Dive Center - 1000, Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "Avto center- Car Wash DIAMANT - Ulica Jožeta Jame 12, 1210 Ljubljana - Šentvid, Slovenia",
    "SIMPLE - Koper Mercator - Dolinska cesta 1a, 6000 Koper - Capodistria, Slovenia",
    "SIMPLE Frizerski salon - Spodnji Plavž 5, 4270 Jesenice, Slovenia",
    "SIMPLE - Logatec Mercator - Tržaška cesta 3, 1370 Logatec, Slovenia",
    "SIMPLE - Sežana Spar - Cesta na Lenivec 5, 6210 Sežana, Slovenia",
    // "SIMPLE - Koper Park center - Ankaranska cesta 2, 6000 Koper - Capodistria, Slovenia",
    "Avtodeli Potokar - Gojače 5e, 5262 Črniče, Slovenia",
    "Avtodeli Potokar - Cesta Kokrškega odreda 4, 4294 Križe, Slovenia",
    "Ljubljana Hippodrome - Stožice, 1000 Ljubljana, Slovenia",
    "SIMPLE - Domžale Mercator center - Cesta talcev 4, 1230 Domžale, Slovenia",
// "SIMPLE - Domžale Mercator center - Cesta talcev 4, 1230 Domžale, Slovenia",
    "SIMPLE - Hura diskont Črnuče - Pot k sejmišču 32, 1231 Ljubljana - Črnuče, Slovenia",
    "AVTO KADUNC, Miha Kadunc s.p. - Perovo 27A, 1290 Grosuplje, Slovenia",
    "SIMPLE - Ljubljana Mostec - Karingerjeva ulica 6, 1000 Ljubljana, Slovenia",
    "SIMPLE - Ajdovščina Mercator - Vipavska cesta 6, 5270 Ajdovščina, Slovenia",
    "SIMPLE - Ptuj Supernova Qlandija - Ormoška cesta 15, 2250 Ptuj, Slovenia",
    "SIMPLE - Jurčkova Cesta 223, 1000 Ljubljana, Slovenia",
    "SIMPLE - Ljubljana Vič - Tržaška c. 116, 1000 Ljubljana, Slovenia",
    "SIMPLE - Vrhnika Spar - Ljubljanska cesta 29, 1360 Vrhnika, Slovenia",
    "Modna kravata Gjergjek, Sandra Gjergjek s.p. - Gregorčičeva ulica 38, 9000 Murska Sobota, Slovenia",
    "SIMPLE - Trebnje Mercator - Stari trg 48, 8210 Trebnje, Slovenia",
    "Hotel Harmonija Mengeš - Linhartova cesta 33, 1234 Mengeš, Slovenia",
    "Kolesarski center Bauer trgovina, zastopstvo in posredovanje, d.o.o., Ljubljana - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "MORRO SARTORIALE LJUBLJANA - Ameriška ulica 8, 1000 Ljubljana, Slovenia",
    "TIP&TAP - Šmartinska c. 106, 1000 Ljubljana, Slovenia",
    "NŠ PLAC - Celovška cesta 177 Šiška, 1000 Ljubljana, Slovenia",
    "Toskana delikatesa- enota Gurman, Koseze - Vodnikova cesta 187, 1000 Ljubljana, Slovenia",
    "Gold Store Pe Kranj - Koroška cesta 4, 4000 Kranj, Slovenia",
    "Eko resort pod Veliko planino - 44b, Godič, 1242 Stahovica, Slovenia",
    // "Eko resort pod Veliko planino - 44b, Godič, 1242 Stahovica, Slovenia",
    "Takos - Pobreška cesta 18, 2000 Maribor, Slovenia",
    "Rona Caffe - Šuceva ulica 25, 4000 Kranj, Slovenia",
    // "Avtodeli Potokar - Dunajska c. 421, 1000 Ljubljana, Slovenia",
    "SOBA ROOM - Trg mladih 1, 1000 Ljubljana, Slovenia",
    "Al Capone - Pobreška cesta 18, 2000 Maribor, Slovenia",
    "Va Bene - Pobreška cesta 18, 2000 Maribor, Slovenia",
    "Cortez Bar - Litijska cesta 132, 1000 Ljubljana, Slovenia",
    "Gostilna Pri Škofu - Zaklanec 1, 1354 Horjul, Slovenia",
    "Magi bar - Dolenjska cesta 329, 1291 Škofljica, Slovenia",
  };
}
