class AutoSuggestionsAS {
  static final reviewedTitlesAS = const {
    "Reparacion Pcell Ml-105 - J9QH+RXG, Avenida Libertador, Maracaibo 4005, Zulia, Venezuela",
    "Total Service Printer - J9RJ+H37, Av 15, Maracaibo 4004, Zulia, Venezuela",
    "Sugar Cake Maracaibo - J9RJ+9J7, Distribuidor Jesús Enrique Lossada, Maracaibo 4005, Zulia, Venezuela",
    "Cr movil - J9RJ+9HJ, Av. Libertador, Maracaibo 4005, Zulia, Venezuela",
    "Intenxys Boutique - Carrera 7 con Calle 18, C.C Zafiro, Nivel PB, Local 5, C. 18, Guanare 3350, Portuguesa, Venezuela",
    "PCTRONICT - CARRERA 6 ENTRE AVENIDA UNDA Y CALLE 9 LOCAL 115 PCTRONICT, Guanare 3350, Portuguesa, Venezuela",
    "Club Deportivo Las Nazareth, C.A. - Av. El ejército, Asociación Aorafanb, Local 4C, Catia La Mar 1162, La Guaira, Venezuela",
    "Inversiones Jehová El Rey, C.A. - Calle Libertador, Local 26 y 27, Mercado Cacique Maiquetia, Pasillo 1, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones Yheremy, C.A. - Calle Libertador, Mercado Cacique Maiquetia, Local 81 Pasillo 1, Maiquetía 1161, La Guaira, Venezuela",
    "ADAM SPORT, C.A. - Calle Jefatura a Cristo, Pasaje el Cristo, Local N ° 15, Maiquetía 1161, La Guaira, Venezuela",
    "MiniMarket Bodegon la Roca, C.A. - Calle Los Baños, Frente a la Plaza Lourdes, Local 11, Maiquetía 1162, La Guaira, Venezuela",
    "Barbería Unisex Nautilus II - Local N° 04, con Cristo a Puente, C. Real de Maiquetía, Maiquetía 1161, La Guaira, Venezuela",
    "Restaurant Cabo Kenedy, C.A - Av. Ppal. de Caribe C.C. Houston PB, Local 01, Caraballeda 1165, La Guaira, Venezuela",
    "Picnic Burguer NC, C.A. - Av Costanera, Centro Comercial Costa del Sol, Nivel Playa, Local 12, Caraballeda 1165, La Guaira, Venezuela",
    "Tecnocelkc Ml-622 - J9RJ+72W, Avenida Las Delicias, Maracaibo 4005, Zulia, Venezuela",
    "Racarga-T - J9RJ+FPW, Av. 13 B, Maracaibo 4005, Zulia, Venezuela",
    "Cerrajería Industrial Mcbo - J9RH+MV2, Maracaibo 4005, Zulia, Venezuela",
    "Inversiones Carvajal Olivo, C.A. - Av. La Costanera, Edf. Palmar Este, PB, Local 1, Caraballeda 1165, La Guaira, Venezuela",
    "Panadería Ejército de Dios,C.A. - Calle Real de Maiquetía, de Cristo a Puente, Casa s/n, Local 4, Maiquetía 1161, La Guaira, Venezuela",
    "Aika Tattoo - Avenida Sucre, Caracas 1071, Miranda, Venezuela",
    "Kaska-Nueces - carrera 22, esquina con pasaje acueducto, casa #21-96. local #3, San Cristóbal 5001, Táchira, Venezuela",
    "Recol Repuestos - 5001 Calle 4 nro 9-21 concordia subiendo 100 metros del estadio Tachira, San Cristóbal 5001, Táchira, Venezuela",
    "Pa' Que Leo - J532+33W, Caraballeda 1165, Vargas, Venezuela",
    "Mundo Repuestos Panda - MQWV+W5P, Guanarito 3354, Portuguesa, Venezuela",
    "Kau Kids - AV. UNDA ENTRE CARRERAS 6 Y 7, Centro Comercial LOS ANDENES, 3350, Av. Unda, Guanare 3350, Portuguesa, Venezuela",
    "Bubbles fresh - la guairita, local 67 Avenida Luis De Camoens, Caracas 1073, Miranda, Venezuela",
    "AUTO REPUESTOS CHERYFORD - carrera 9 calle 4 y, C. 4 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "REPUESTOS CANCHICA - la concordia, carrera 9, Calle 4, San Cristóbal 5001, Táchira, Venezuela",
    "LA CASA DEL NINTENDO - Centro Comercial Metrocenter Capitolio Nivel 2 Caracas, Caracas 1030, Distrito Capital, Venezuela",
    "Alta Barberia Carlos - H9G9+99M, Maracaibo 4004, Zulia, Venezuela",
    "El Brasero de Maiquetia, C.A. - Calle Real de Maiquetía, Nivel PB, Local 88, Maiquetía 1161, La Guaira, Venezuela",
    "Agora Makeup C.A. - Av. La Atlántida, C.C. Jardines Plaza, Nivel PB, Local 05, Catia La Mar 1162, La Guaira, Venezuela",
    "Inversiones J.D 2020 - Av. La Playa, Caraballeda 1165, La Guaira, Venezuela",
    "Repuestos y Rodamientos REBERCA - QQ48+R86, San Cristobal 5001, Táchira, Venezuela",
    "Licorería Anare, C.A. - Local N° 40, Avenida Principal de, Anare 1166, La Guaira, Venezuela",
    "Inversiones Marioly Brett, c.a. - Av. El Ejército, Proveeduría de la Reserva Activa, Nivel PB, JX26+4MR, Local 5, Catia La Mar 1162, La Guaira, Venezuela",
    "Inversiones My friend Paul, C.A. - Calle Libertador, Local 165, Mercado Cacique Maiquetia, Pasillo 2, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones Ant-Shar, C.A. - Calle Real de Maiquetia, De Cristo a Puente, Edf. Profesional, PB, local A C. Real de Maiquetía, Maiquetía 1161, La Guaira, Venezuela",
    "Bodegón licorería El Golfeado de Macuto, C.A. - Av. Ppal de la Atlántida, con calle B, C.C. Prado, P.B., local 3, Urb, Catia La Mar 1162, La Guaira, Venezuela",
    "Ditaty C. A. - Local 2. Carrera 5 entre Calle 17 y 18, C.C Trafik, Nivel 2, Carrera 5, Guanare 3350, Portuguesa, Venezuela",
    "Jessimar Repuestos C.A. - Carrera 8 con Calle 7, Quinta Dolores, Local 2. Barrio Monseñor Unda 3354, Guanarito 3354, Portuguesa, Venezuela",
    "Tiendas Artes y Cueros - Local 6, Carrera 7 con Calle 18, C.C Zafiro, Nivel PB, C. 18, Guanare 3350, Portuguesa, Venezuela",
    "Tienda Linda 2011, F.P. - Calle Libertador, Mercado Cacique Maiquetía, Pasillo 5, Local 467 y 468, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones Henriday, C.A. - Calle Libertador, local 516, Mercado Cacique Maiquetia, Pasillo 5, Maiquetía 1161, La Guaira, Venezuela",
    "Yessenia Montilla, F.P. - Calle Libertador, Mercado Cacique Maiquetia, Local 21 Pasillo 1, Maiquetía 1162, La Guaira, Venezuela",
    "Tienda cosmética kc Minoristas - Socorro, Maracaibo 4005, Zulia, Venezuela",
    "CENTRO DIAGNOSTICO NATURISTA M. HILARION - 27W2+GHR, Guanare 3350, Portuguesa, Venezuela",
    "Representaciones Herdanys Fashion - Av. San Martin cc mercado san martin Zona 6 pasillo 10 y 11 Nivel PB local 317 y 341 Caracas, Caracas 1020, Distrito Capital, Venezuela",
    "Inversiónes Centrotienda, C.A. - Av. Sucre, entre Calle Principal de Altavista y Conexión con Autopista Caracas-La Guaira, Edif. La Fundación, PB Local 5, Caracas 1030, Distrito Capital, Venezuela",
    "Lácteos y Embutidos Diosharbell, C.A - Av San Martín CC Mercado municipal de San Martín zona 71 Puesto 217 Urb, Av. San Martín, Caracas 1020, Distrito Capital, Venezuela",
    "Inversiones Shalomlevi - Av Bolívar, Mercado Bolivariano La Hoyada, Pasillo Ecuador, Loc. 125, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Óptica Miro,C.A - Calle Panamericana, entre Calle Colombia y México, PB, Local C, Catia, Caracas 1030, Caracas 1030, Distrito Capital, Venezuela",
    "Chocolates Margaret - Av San Martín CC Mercado Municipal de San Martín Zona 22 Local 519, urb Av. San Martín, Caracas 1020, Distrito Capital, Venezuela",
    "Shalon - Av Bolívar, Mercado Bolivariano La Hoyada, Pasillo Ecuador, Local 119, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Inversiones Moriah 2014 C.A - Mercado Municipal de la Hoyada, Pasillo Nueva Esparta local 78-79, Caracas, 6311, Nueva Esparta, Venezuela",
    "Wiza - Mercado Bolivariano La Hoyada, Pasillo Lara, Local 478, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Artesanía y Novedades El Gocho 2018, C.A - Av Panamá Edif. Opppe 19 Piso PB local 1, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Wisaza - Mercado Bolivariano la Hoyada, Pasillo Nueva Esparta, local 2049, Caracas 1011, Caracas, Caracas 1011, Distrito Capital, Venezuela",
    "Rhema Service PC - Centro Comercial Candilito, Local 28 Av. Nte. 13, Caracas 1010, Distrito Capital, Venezuela",
    "Invedin - Quinta 20-65, Av. Neveri, Caracas 1080, Distrito Capital, Venezuela",
    "todoimpress C.A. - 26VX+P54, Carrera 5, Guanare 3350, Portuguesa, Venezuela",
    "Makeup Vino - Guanare 3350, Portuguesa, Venezuela",
    "Koala tecnología - 26VX+46H, Calle 18, Guanare 3350, Portuguesa, Venezuela",
    "Fullvape - Socorro, Maracaibo 4005, Zulia, Venezuela",
    "IP Depot - Ave 15 delicias calle 100 centro comercial gran bazar local Ml 270, Maracaibo 4002, Zulia, Venezuela",
    "BODEGON DE LA OCHO - Carrera 8 entre calle 9 y 10. Casa 9-6, Local 1, Guanare 3350, Portuguesa, Venezuela",
    "Motor cicles los Andes - 42J9+963, Troncal7, La Grita 5022, Táchira, Venezuela",
    "Aguacate cosmetic - J9RJ+953, Maracaibo 4005, Zulia, Venezuela",
    "Maxiphone - J9RJ+W3H, Maracaibo 4005, Zulia, Venezuela",
    "Novelty Style - 4001, Maracaibo 4001, Zulia, Venezuela",
    "El Punto Andino - Barrio El Cementerio, Carrera 6 con Calle 15, Esquina Local 1, Guanare 3350, Portuguesa, Venezuela",
    "Tecnoelectron Gran Bazar. Mayoristas y Servicio Técnico para Celulares - Avenida Las Delicias, Maracaibo 4005, Zulia, Venezuela",
    "C.A KS ML 1554 - Av 15 Delicias Con Calle 100, C.C Gran Bazar, Nivel2, Local, Maracaibo 1554, Zulia, Venezuela",
    "ML -105/106 Palermo - Av.15 Las Delicias Con Calle 100, Cc.Gran Bazar N1 Local 105/106, Maracaibo 4005, Zulia, Venezuela",
    "Z.P Tecnología PP-18 - J9RJ+9J7, Avenida Libertador, Maracaibo 4005, Zulia, Venezuela",
    "Zonephone Cima - J9PJ+MVX, Maracaibo 4005, Zulia, Venezuela",
    "Emi's Bows - J9RH+GX9, Maracaibo 4005, Zulia, Venezuela",
    "Apple World - J9RH+WQR, Maracaibo 4005, Zulia, Venezuela",
    "Iron Tech - J9RJ+P3M, Maracaibo 4005, Zulia, Venezuela",
    "Panaderia y Pastelería Tina C.A - Av. San Francisco &amp;, local 81 Avenida Francisco de Miranda, Caracas 1071, Miranda, Venezuela",
    "ALCANPO Mobile Store - Local 566, Urb.15 Delicias, C.C. Gran Bazar, Avenida Las Delicias, Maracaibo 4005, Zulia, Venezuela",
    "TELYCENT C.A. - 4005, Maracaibo 4005, Maracaibo 4001, Zulia, Venezuela",
    "Sensación Bellaroma - CC Grand Bazar, Av las Delicias frente al CC Cima Baracaibo, Maracaibo 4005, Maracaibo 4005, Zulia, Venezuela",
    "Inversiones Wapar - Mercado de Quinta Crespo, Local 100, Av. Baralt, Caracas 1014, Distrito Capital, Venezuela",
    "Diadema Group - Km 16, Carretera Panamericana. Centro Comercial Club de Campo, Nivel PB, Stand 02, Carr. Panamericana, San Antonio de Los Altos 1204, Miranda, Venezuela",
    "Kristy Cafe - F4XC+9XH, Caracas 1050, Capital District, Venezuela",
    "Ron&Jhon zapateria - Avenida Bolivar, Mercado Bolivariano la Hoyada, pasillo la Orchila, local 2887, Caracas, Caracas, Caracas 1040, Distrito Capital, Venezuela",
    "Peluquería Para Caballeros Ruzafa - C. Rbla. Baja, 13, 30800 Lorca, Murcia, Spain",
    "Pestana de Sousa & CIA - Calle Panamericana, Entre Calle Colombia y Calle México, P.B, local 40 Diagonal a Alimentos Caribe, Caracas 1030, Distrito Capital, Venezuela",
    "RegaladoGroup distribuidor de zapatos - Avenida Bolivar, Mercado Bolivariano la Hoyada, pasillo la Orchila, local 2779, Caracas, Caracas, Caracas 1011, Distrito Capital, Venezuela",
    "Quesos y Embutidos Doña Rosa 24 02, C.A - Calle Engracia, Edif. Federal, PB Local 9, Caracas 1030, Distrito Capital, Venezuela",
    "Zapatos Miguel - C. de San Gerardo, 8, 28035 Madrid, Spain",
    "Kabuky Cosmetics - J9RJ+829, Avenida Las Delicias, Maracaibo 4005, Zulia, Venezuela",
    "Supermercado Lo Mejor De Los Quesos C.A - 5ta Avenida entre Calle Argentina y Boulevar España, Local 3H, Caracas 1030, Distrito Capital, Venezuela",
    "Inv Gabyjuan C.A - Av francisco solano edf pasaje concordia Planta baja local 3v, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiónes perlas perladas, c.a - Esq madrices a ibarras local c edf bergatin local pb Caracas, G34P+MWG, Caracas 1010, Distrito Capital, Venezuela",
    "Mundo Chocolate Reposteria - Esquina La Marrón, a una cuadra de la Av Urdaneta CC Doral Nivel Mezzanina M5 URB. Catedral Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Piñateria Mundo Chocolate 1260, C.A - Esquina La Marrón, Una cuadra antes de la Av. Urdaneta CC Doral Nivel Mezzanina Local M8- M9 URB, Caracas 1010, Distrito Capital, Venezuela",
    "Bodega Variedades Rchell y Samantha - Av Baralt CC Doral baralt Nivel Mezzanine Local 91 sector, Caracas 1010, Distrito Capital, Venezuela",
    "Variedades Rchell y Samantha Sucursal - Av Doralt Baralt entre las esquinas bucare A Carmen CC Doral baralt Nivel Mezzanine Local 87 urb, Caracas, Caracas 1014, Distrito Capital, Venezuela",
    "Expoimpotmarhenzar2015 - F5HV+57Q, Av. Principal Las Vegas de Petare, Caracas 1073, Miranda, Venezuela",
    "Variedadesneomar - F5HV+87H, Av. Principal Las Vegas de Petare, Caracas 1073, Miranda, Venezuela",
    "Inversiones Andrews 2021, C.A - Av. Baralt, Locales 146 al 149, Cc Doral Baralt Esquina del Carmen a Buscarte, Caracas 1010, Av. Baralt, Caracas 1014, Distrito Capital, Venezuela",
    "INVERSIONES AURIGA, C.A. - F5HR+3V3 zona colonial de, C. La Paz, Caracas 1073, Miranda, Venezuela",
    "Best Cell, C.A. - Av La Atlántida, C.C. Jardines Plaza, Nivel PB, Local L-1, Catia La Mar 1162, La Guaira, Venezuela",
    "Saint-miguelacho- shoes zapateria deportiva - local 894, Avenida Bolivar, Mercado Bolivariano la Hoyada, pasillo Miranda con Ecuador, C. Los Ángeles, Caracas 1064, Distrito Capital, Venezuela",
    "Variedades JM14 - Centro Comercial Doral Barald av barald Local 279 PB Sector, Av. Baralt, Caracas 1014, Distrito Capital, Venezuela",
    "Miguelacho Shoes - G32R+R75, Caracas 1011, Capital District, Venezuela",
    "Pizza San Jose C.A. - Av. Bulevar Naiguatá, Centro Comercial Caribe, PB, Local N° 5, Urb, Caraballeda 1165, La Guaira, Venezuela",
    "Zapatos Miguelacho - Local 106, Avenida Bolívar, Mercado Bolivariano la Hoyada, Pasillo Miranda, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Nuva telo - Av. Baralt con esquina pedrera, C.C. Metrocenter, nivel Avenida, pasillo Medio, Caracas 1071, Av. Baralt, Caracas 1012, Miranda, Venezuela",
    "Zona Servi - H2WX+7QF, C. Jefatura a Cristo, Maiquetía 1161, La Guaira, Venezuela",
    "Tsunami Surfshop - H2WX+5X6, Maiquetía 1161, Vargas, Venezuela",
    "Inversiones Sport Family Full C.A - G45V+XX5, Avenida Mohedano, Caracas 1060, Miranda, Venezuela",
    "Yarman fashion new store - G32R+Q8V, Caracas 1011, Capital District, Venezuela",
    "Vida's Bike comercializadora c.a - Av Sur 4 esquina de dolores a Mamey Local nro 170, sector, Caracas 1040, Distrito Capital, Venezuela",
    "INVERSIONES AEGON, C.A. - Esquina conde a carmelitas av sur 4 Cc minitiendas expomeca nivel pb local 57, Capitolio, Caracas 1010, Distrito Capital, Venezuela",
    "Tu ciervo Shoes Sport - Mercado Bolivariano La Hoyada, Pasillo Zulia, Local 208, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Variedades Mauped C.A - Los Chorritos, Av Principal, Local Nro 1, Principal, Tocuyito 2035, Carabobo, Venezuela",
    "Oxígenos cabriales C.A - Av. 74, calle 106, Centro Comercial Infra, PB, Local 10 Av. Don Julio Centeno, San Diego 2006, Carabobo, Venezuela",
    "Delicateses la Gloria de Dios - 4W8M+8QM, Tocuyito 2035, Carabobo, Venezuela",
    "Audicenter C.A. - Avenida universidad, centro comercial Metrocenter, local mp33. Caracas, Avenida Universidad, Caracas 1012, Distrito Capital, Venezuela",
    "Leicacel Service LS, C.A. - Esquina el conde, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Biyetmar shoes - Mercado Bolivariano La Hoyada, Pasillo Portuguesa, Local 2345, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Distribuidora Najucar, C.A - Av. sur 4 esquinas Carmelitas a Conde CC expomeca 2000 Nivel Pasillo 1 Local 7 Urb, Av. Urdaneta, Caracas 1012, Distrito Capital, Venezuela",
    "EJCA Electrónica, C.A. - Av Sur 2. Entre Av Lecuna y Av Oeste 12. Edif. Sur 2, PB, Local 1, Caracas 1014, Distrito Capital, Venezuela",
    "Floristeria Paraiso Galipan - H2WQ+J8V, C. Real de Pariata, Maiquetía 1161, La Guaira, Venezuela",
    "Comercial el Divino Niño - J458+3GR, Vía Teleférico, Macuto 1164, La Guaira, Venezuela",
    "Inversiones VFC - H2WX+VCC, C. Los Baños, Maiquetía 1161, La Guaira, Venezuela",
    "Electrónica Compusol - H3W2+HF2, C. Los Baños, Maiquetía 1161, La Guaira, Venezuela",
    "Celest Decoraciones - JX2F+PV7, Av. La Páez, Catia La Mar 1162, La Guaira, Venezuela",
    "Heladería Fruti Cream - Los Chorritos, Calle El Valencia con 2da Calle, Local Nro A, 2, Tocuyito 2035, Carabobo, Venezuela",
    "Comercial LEC C.A - Calle Piar/c/c Carvajal Local 39B, Guacara 2015, Carabobo, Venezuela",
    "Herica Nails - Los Chorritos, Av Principal, sector Andrés Eloy Blanco, Centro comercial Pío Tamayo, Nivel 2, local B 05, 1, Tocuyito 2035, Carabobo, Venezuela",
    "Abasto A Dios JL - Local 110, Los Chorritos, 21 C. Las Bateas, Tocuyito 2035, Carabobo, Venezuela",
    "Inversiones Alianza de Dios JL C.A - Los Chorritos, Calle Las Bateas con 42, local 110-20, Tocuyito 2035, Carabobo, Venezuela",
    "Liontech Sambil - Avenida Libertador, C.C. Sambil Caracas, nivel acuario, local AC-C49, Caracas, Av. Libertador, Caracas 1064, Distrito Capital, Venezuela",
    "Abasto Los Chorritos - Los Chorritos, Av Venezuela, Casa Nro 67, Sector Uslar Pietri, Tocuyito 2035, Carabobo, Venezuela",
    "Variedades Mis Tesoros - Los Chorritos, Calle Las Bateas con Rómulo Gallegos, Nro de casa 52, Tocuyito 2035, Carabobo, Venezuela",
    "SC Canelones y Montaya - Carrera 8 Esquina calle 16 Edif Madel P/B local 2, Guanare 3350, Portuguesa, Venezuela",
    "Inversiones Las Julianas, C.A. - Calle Real de La Cañada, Bloque 15, Frente al, PB Local 13-04, Caracas 1030, Distrito Capital, Venezuela",
    "Kiosko EL OSO - HWVV+4WM, Avenida La Armada, Catia La Mar 1162, Vargas, Venezuela",
    "SagresMarket - 6 C. Negrín, Caracas 1050, Distrito Capital, Venezuela",
    "Comercial Barcelona,C.A - Calle Libertador, entre Calle Mare y Jefatura, Casa N° 1, PB, Frente al, Mercado Cacique Maiquetia, Maiquetía 1161, La Guaira, Venezuela",
    "Cocos y Cocadas El Trono de Odín - Av. san Martín con calle Mercado Municipal Oeste San Martín Local, 604-605 Sector, Caracas 1020, Distrito Capital, Venezuela",
    "Inversiones Gordo Pablo 2 C.A. - Centro comercial San Martin, locales 406-407. Caracas, Caracas, Caracas 1020, Distrito Capital, Venezuela",
    "Inversiones El Gordo Pablo 1. - Avenida principal, centro comercial San Martin, zona 22, local 513-514-515. Caracas 1020, Principal, Caracas 1020, Caracas 1020, Distrito Capital, Venezuela",
    "Viveres Pernia's 5-J - Av. san Martín edificio la araña_ planta baja local 36 37 y 38 urbanización, Caracas 1020, Distrito Capital, Venezuela",
    "Tu visión némesis C.A. - Avenida este, esquina Dr. Paul a Salvador de león, edificio 71 N.pb. L-11 La hoyada Caracas, Avenida E, Caracas 1040, Caracas 1012, Distrito Capital, Venezuela",
    "@Rossbertca - Av baralt, esquina del Carmen y buscaré con calle Sur cc.minicentro doral baralt Nivel planta baja local pan Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Nemesis ladiosa - Avenida este, esquina Dr Paul a Salvador de león, Edificio 71 Nivel PB, local 10. La hoyada Caracas 1040, Avenida E, Caracas 1020, Caracas 1012, Distrito Capital, Venezuela",
    "Sucursal Irowo Omaire y Asociados - Av Andrés Bello Mercado municipal de Guaicaipuro Piso Mezzanine local 72 Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Romy Shop - Centro Comercial Merpoeste, P-1, L-189, Caracas 1060, Distrito Capital, Venezuela",
    "Basket Burguer - Centro comercial Merpoeste, nivel feria, local 50, Caracas 1060, Distrito Capital, Venezuela",
    "Marvic Style - Local 88-89. Calle Chico Carrasquel, Nivel PB, Pasillo Paují, Caracas 1064, Miranda, Venezuela",
    "La casa de jade - 1060 Avenida Francisco de Miranda, Caracas 1060, Distrito Capital, Venezuela",
    "Vela Fermín - local 102, Mercado de, 24, Caracas 1020, Distrito Capital, Venezuela",
    "Perfumería el poder de la fe - Local-29, zona 71, Mercado de, Caracas 1020, Distrito Capital, Venezuela",
    "El Dulce Mundo de Cami - Centro Comercial Merpoeste, Piso 2, local 14, Caracas 1064, Miranda, Venezuela",
    "Exclusividades Adonis - local 18, Mercado de, 71, Caracas 1020, Distrito Capital, Venezuela",
    "Moda Patty Divina - local 31 C. Chico Carrasquel, Caracas 1064, Miranda, Venezuela",
    "Olofimar carnes - local-127, Mercado, 24, Caracas 1020, Distrito Capital, Venezuela",
    "Mini Lunch - 43 Av. Libertador, local 19, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones la rosa y la rosa. - Local-27, zona 71, Mercado de, Caracas 1020, Distrito Capital, Venezuela",
    "Gaby Kar - Local 95-96, Centro Comercial Merpoeste, Piso 1, Nivel Llanos, Caracas, Caracas 1064, Distrito Capital, Venezuela",
    "Tienda MIZ Diseños - Av. Libertador y Francisco de Miranda en Av. Libertador, Caracas 1060, Caracas 1060, Distrito Capital, Venezuela",
    "Comercializadora Punto Colonial - local-415, Mercado de, 22, Caracas 1020, Distrito Capital, Venezuela",
    "Edificio Miami - G42G+P4R, Av. Juan Bautista Arismendi, Caracas 1050, Distrito Capital, Venezuela",
    "Ultra Óptica S.A. - Av. Juan Bautista Arismendi, nivel 2, Unidad Comercial La Florida, local 3C, Caracas 1050, Distrito Capital, Venezuela",
    "Panadería Norma - G42G+P39, Av. Juan Bautista Arismendi, Caracas 1050, Distrito Capital, Venezuela",
    "ZAIMAR ELECTRONIC, C.A. - Calle Chico Carrasquel con, local 194, Piso 2 C. Los Ángeles, Caracas 1064, Miranda, Venezuela",
    "Maxi Pollo, C.A - Av. Baralt Esquina de balconcito Casa N° 19 Urb, Av. Baralt, Caracas 1014, Distrito Capital, Venezuela",
    "Atelier Emy - Avenida baralt, equina del carme, edificion Marisabel, sector, F3WJ+W7Q, Caracas 1010, Distrito Capital, Venezuela",
    "Maxiqueso - Calle 6 entre las esquinas del carmen y bucare Edificio residencias pedregal piso planta baja local 1 Urbanización, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones abel2011.ca - Av Andres mercado municipal guicaipuro Local 41 urbanización guacaipuro, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Rizos y Cabello Limpieza - Av Andrés Bello Edif. Mercado Municipal Guaicaipuro Piso PB Local 82 Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Rizos y Cabello 17, C.A - Av. Andrés bello Edif. Mercado Municipal Guaicaipuro Piso PB, Local 68 y 82 Urb, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Fauna Caracas Sucursal - esq. Barcenas A Dolores Local 8 Sector quinta crespo Frente al ac erradero Real caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Fauna Caracas C.A - F3WJ+8RF, Avenida Oeste 18, Caracas 1014, Distrito Capital, Venezuela",
    "Laras Tienda - 1071 Av. José Félix Sosa, Caracas 1071, Miranda, Venezuela",
    "Charcuteria Deli Siga La Vaca, C.A - Av Cumana Edif Rosa Piso PB Local E Urb, Caracas 1050, Distrito Capital, Venezuela",
    "La Energia Que Hay En Ti - Esquina bolsa a Padre sierra Antiguo Edificio continental, Local numero 24, Capitolio, Caracas 1010, Distrito Capital, Venezuela",
    "Technotrip - Esq Monjas a Padre Sierra Cc Pasaje Capitolio Nivel PB Local 2B Sector, Capitolio, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiónes d emely c. a - Av oste 2 entre las esquinas de padre cierra a Muñoz Local #16 zona centro de caracas Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Distribuidora jesus c.a - Avenida baral quinta el gran mercado del centro, Local 9 sector, capitolio, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Loreanny, C.A - Av. urdaneda cc Expomeca 2000 Nivel PB Local 83 pasillo 2 Esquina Conde a Carmelita Sector, Caracas 1010, Distrito Capital, Venezuela",
    "Distribuidora Hábitat, C.A. - Calle Real de Maiquetia, entre calle El Silencio y la Jefatura, Edif. Mónaco, PB, Local N° 72, Maiquetía 1161, La Guaira, Venezuela",
    "Almacenes Barcelona,C.A. - Calle Real de Maiquetía, Edf. Barcelona, PB, Local 1, Frente a la, Plaza Los Maestros, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones Rag Neill, C.A - Esquina la bolsa a padre Sierra Av este 2 Piso PB Local 34 y 35, Capitolio, Caracas, Caracas 1012, Distrito Capital, Venezuela",
    "inversiones full portatil - av universidad metro parque carabobo centro parque carabobo n1 local 110 caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Stylos Neyes - Calle bucare con Carmen calle el Carmen Centro comercial doral baralt PB local 125 y 126 Sector, Caracas 1020, Distrito Capital, Venezuela",
    "Peluquería MUNDO INFANTIL la florida - G42G+M4C, Avenida Juan Bautista Arismendi, Caracas 1050, Distrito Capital, Venezuela",
    "Carniceria y charcuteria LA ESPERANZA C.A - Esquinas de Conde a Piñango, al lado Prefectura de Catedral, Caracas 1012, Caracas 1012, Caracas 1012, Distrito Capital, Venezuela",
    "Tostadas Hernández - Esquina de Monjas a Padre Sierra Edificio número 6, P.B., local número 4 Parroquia Catedral, Urbanización, Capitolio, Caracas 1010, Distrito Capital, Venezuela",
    "Continental Store - Esquina bolsa a Padre Sierra, edificio Alto, Continental, Caracas 1010, Distrito Capital, Venezuela",
    "GRUPO BAZAR MARKET, C.A. - Residencia La Hacienda, Avenida Veracruz, Nivel PB, Local 3, Caracas 1061, Miranda, Venezuela",
    "Kiosco El Universal - Av Principal del Bosque, Kiosco 5, con Blvr. de Sabana Grande, Caracas 1060, Miranda, Venezuela",
    "Inversiones aleksey - QQ67+738, Calle 3, San Cristóbal 5001, Táchira, Venezuela",
    "Kiosco Luis Álvarez - Avenida Francisco de Miranda, Kiosco N°65, con C. Elice, Caracas 1060, Miranda, Venezuela",
    "Odontología zaralop,C.A. - JX26+49J, Avenida El Ejército, Catia La Mar 1162, Vargas, Venezuela",
    "Diadema Group - Caracas centro comercial metrocenter capitolio Caracas, Caracas 1012, Distrito Capital, Venezuela",
    "Melosa Café - Avenida Norte Av urdaneta de esquina de veroes a jesuitas Inicio boulevard Panteón Edificio San José Al lado de la Casa José Marti Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "@Amarte2902 - F5HV+57X, Av. Principal Las Vegas de Petare, Caracas 1073, Miranda, Venezuela",
    "Arj soluciones - Centro comercial City Market, piso 2, local B334, Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Grupo tuservinet C.A. - Centro parque Carabobo, local L10;L11. Caracas, Avenida Universidad, Caracas 1011, Distrito Capital, Venezuela",
    "Kiosco El Rosal - Av. Tamanaco, Kiosco 13, Con Calle Mohedano, Caracas 1060, Miranda, Venezuela",
    "Radio Bar Ccs - Planinco, Av. Libertador, Caracas 1040, Distrito Capital, Venezuela",
    "La Barra de Chacao - Calle El Muñeco Con esquina, Avenida Francisco de Miranda, Caracas 1060, Miranda, Venezuela",
    "Electronic store compa y Stiven Vallejo - local 433, Avenida Abraham Lincoln, centro comercial City Market, nivel mezzanina, Caracas 1050, Distrito Capital, Venezuela",
    "Chinatown C.A. - Esquina El Conde, edificio Hotel El Conde, PB, locales 4 y 5, Caracas 1012, Distrito Capital, Venezuela",
    "ÁREA DE CAMPING - Centro Polo, Av. Caroní, Caracas 1080, Miranda, Venezuela",
    "Inversiones Audi Center 5537, C.A - Av. Baralt CC Metrocenter Nivel colonial Local AC-c18, Capitolio, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones DACCELL - local C, edif. Espera, Av. Andrés Bello, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones hermanos salcedo 25-40 c.a - Esquina de garita a pescador, res capuchino Local PB C Urbanizacion, Caracas 1010, Distrito Capital, Venezuela",
    "Innovación Arianabella, C.A - Av Baralt Con Universidad, CC Metro Center Pasaje Nievel Contemporáneo Local 27 Caracas, Caracas 1020, Distrito Capital, Venezuela",
    "Licorería Rocha C.A. - local 6, Torre 18, C. El Mirador, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones DGlass ropa interior - Av Bolívar, Mercado Bolivariano La Hoyada, Pasillo Falcón, Local 1566, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Representaciones Glorifer C.A. - Esa. Conde a Carmelitas, C.C. Expomeca 2000 Nivel PB, Local 77. Urb, Caracas 1020, Distrito Capital, Venezuela",
    "Los Sabores de Barbarita - Av San Martin, Mercado Municipal de San Martin Pasillo 24, Local 304 al lado de las, cocadas, Caracas 1020, Distrito Capital, Venezuela",
    "María Representaciones ropa interior 3000 C.A - Avenida Bolivar, Mercado Bolivariano la Hoyada, pasillo Falcón con ecuador, local 1566, Caracas, Caracas, Caracas 1011, Distrito Capital, Venezuela",
    "Inversiones Variedades Ayala - Mercado Bolivariano La Hoyada, Pasillo Nueva Esparta, Local 125, Caracas 1011, Caracas, Caracas 1011, Distrito Capital, Venezuela",
    "Corporacion Compostela - Calle Negrin. Entre Calle Garcia y Porvenir, Edificio Francis, Nivel PB, Local 3A, Caracas 1050, Distrito Capital, Venezuela",
    "Bodegón Mega Caribe, 2020,C.A. - Av. La Playa, Edf. los Tres Hermanos,PB, Local 03, Caraballeda 1165, La Guaira, Venezuela",
    "Posada Bar Restaurant El Velero, C.A. - Av. La Playa, Edif. Los Tres Hermanos, PB, Local 2, Urb, Caraballeda 1165, La Guaira, Venezuela",
    "DAIO TECHNOLOGY CA - Av baralt, Centro Comercial Doral Baralt, local PB 60, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Lozano3112 ca - Av Baralt entre las esquina buscaré a Carmen Cc doral baralt nivel mezzanina local 135 y 136, Caracas 1020, Distrito Capital, Venezuela",
    "Inversiones 1G12, C.A - Av Baralt con Av. Universidad CC Metrocenter Nivel Colonial Local MP-01 Urb, Caracas 1012, Caracas 1012, Distrito Capital, Venezuela",
    "Accesorios Aquamoda, C.A - Av. Baralt con Av. Universidad CC Metrocenter Nivel Colonial Local Stand 8 y 9 Urb, Caracas 1012, Caracas 1012, Distrito Capital, Venezuela",
    "JJ Sport C.A - Mercado bolivariano la Hoyada, Pasillo Ecuador, Local 2010, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Inversiones elham c.a - Esq el cuji edificio torre el cuji piso pb local b Urb parroquia, Caracas 1020, Distrito Capital, Venezuela",
    "Unidad de Didtr. De alimentos MME98, C.A - Calle Av Baralt Edif. Bloque 2 Piso PB Local 1-D Urba, Av. Baralt, Caracas 1020, Distrito Capital, Venezuela",
    "Reparaciones y Repuestos Cesar C.A - Av. El Atlántico, Edificio Centro Industrial Don Salomon, PB Local 17H, Caracas 1030, Distrito Capital, Venezuela",
    "Inversiones Stargold, C.A. - G353+457, Caracas 1030, Capital District, Venezuela",
    "El chacal café - local 9, edificio Fondo común, PB Avenida Fuerzas Armadas, Caracas 1011, Distrito Capital, Venezuela",
    "Inversiones Seblo - Avenida principal de San Martin, centro comercial San Martin, zona 71, local 103-104, Caracas 1020, Distrito Capital, Venezuela",
    "Auto repuestos 2000 - QQ48+M9J, Calle 5 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "Ponkes mil sabores - Zona 01, Centro Comercial San Martín, local 35 , Caracas 1020, Caracas 1020, Caracas 1020, Distrito Capital, Venezuela",
    "Global PC Venezuela - Avenida principal, centro parque Carabobo, planta baja, local N1-127, Avenida Universidad, Caracas 1011, Distrito Capital, Venezuela",
    "Michael's Taires - Avenida Libertador con calle muñeco, edificio centro Mancom, piso PB, F4RR+HM8, Caracas 1060, Miranda, Venezuela",
    "Ak Aromas y Sabores - Bello Monte, Caracas 1050, Distrito Capital, Venezuela",
    "Centro de Estética Shadday 1006 CA - F4V9+WRX, Caracas 1050, Capital District, Venezuela",
    "V58 Store City Market 6 - F4VC+QV8, Caracas 1050, Capital District, Venezuela",
    "V58 Store City Market 5 - Piso 3, C.C City Market, Nivel Bazar, Local B408, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "V58 Store City Market 4 - C.C City Market, Nivel PB, Local Arca, N° 456 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "V58 Store City Market 3 - F4VC+QVH, Caracas 1050, Capital District, Venezuela",
    "V58 Store City Market 2 - Piso 2, C.C City Market, Nivel Bazar, Local B330, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Tienda El Molino, C.A. - Av. Bulevar España, Entre 2da y 3ra Avenida, PB Local 51, Caracas 1030, Distrito Capital, Venezuela",
    "Lunch Starbucks Café, C.A. - Local 50 Blvr. Av. España, Caracas 1030, Distrito Capital, Venezuela",
    "Inversiones Sunnet, C.A. - Calle Padre Machado, Local 45-07, Frente a la Plaza de los Maestros, Maiquetía 1161, Maiquetía 1161, La Guaira, Venezuela",
    "iMarket27 - Av. Chico Carrasquel Entre la Calle los Ángeles y, Calle Pantin, Caracas 1060, Miranda, Venezuela",
    "Inversiones Kamikira, C.A. - Av. Soublette, Edf. Julia Elvira, PB, Local S/N, frente a la Plaza el cónsul, H3W2+QR9, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones Luige - Centro Comercial Plaza Candelaria, Local 26A, Av. Urdaneta, Caracas 1011, Distrito Capital, Venezuela",
    "Inv anayurliian gorcell movistar - local 2, Av. Principal Las Vegas de Petare, Caracas 1073, Miranda, Venezuela",
    "DISTRIBUIDORA ALI - G33J+32M, Avenida, Caracas 1020, Distrito Capital, Venezuela",
    "Inversiones anair 86 C.A - local n°3, Av. Principal Las Vegas de Petare, Caracas 1073, Miranda, Venezuela",
    "Fanatic Sport Caracas - C.C Residencias La Candelaria, esquina Candelito al lado de Banco Provincial Caracas, G34V+7WJ, Caracas 1010, Distrito Capital, Venezuela",
    "Pauls Shop - Centro Comercial Merpoeste, P-1, L-178, Caracas 1060, Distrito Capital, Venezuela",
  };
}
