class AutoSuggestions87508588 { static final reviewedTitles87508588 = const {"Inversiones Las Julianas, C.A. - Calle Real de La Cañada, Bloque 15, Frente al, PB Local 13-04, Caracas 1030, Distrito Capital, Venezuela",
"Kiosko EL OSO - HWVV+4WM, Avenida La Armada, Catia La Mar 1162, Vargas, Venezuela",
"SagresMarket - 6 C. Negrín, Caracas 1050, Distrito Capital, Venezuela",
"Comercial Barcelona,C.A - Calle Libertador, entre Calle Mare y Jefatura, Casa N° 1, PB, Frente al, Mercado Cacique Maiquetia, Maiquetía 1161, La Guaira, Venezuela",
"Cocos y Cocadas El Trono de Odín - Av. san Martín con calle Mercado Municipal Oeste San Martín Local, 604-605 Sector, Caracas 1020, Distrito Capital, Venezuela",
"Inversiones Gordo Pablo 2 C.A. - Centro comercial San Martin, locales 406-407. Caracas, Caracas, Caracas 1020, Distrito Capital, Venezuela",
"Inversiones El Gordo Pablo 1. - Avenida principal, centro comercial San Martin, zona 22, local 513-514-515. Caracas 1020, Principal, Caracas 1020, Caracas 1020, Distrito Capital, Venezuela",
"Viveres Pernia's 5-J - Av. san Martín edificio la araña_ planta baja local 36 37 y 38 urbanización, Caracas 1020, Distrito Capital, Venezuela",
"Tu visión némesis C.A. - Avenida este, esquina Dr. Paul a Salvador de león, edificio 71 N.pb. L-11 La hoyada Caracas, Avenida E, Caracas 1040, Caracas 1012, Distrito Capital, Venezuela",
"@Rossbertca - Av baralt, esquina del Carmen y buscaré con calle Sur cc.minicentro doral baralt Nivel planta baja local pan Caracas, Caracas 1010, Distrito Capital, Venezuela",
"Nemesis ladiosa - Avenida este, esquina Dr Paul a Salvador de león, Edificio 71 Nivel PB, local 10. La hoyada Caracas 1040, Avenida E, Caracas 1020, Caracas 1012, Distrito Capital, Venezuela",
"Sucursal Irowo Omaire y Asociados - Av Andrés Bello Mercado municipal de Guaicaipuro Piso Mezzanine local 72 Urb, Caracas 1050, Distrito Capital, Venezuela",
"Romy Shop - Centro Comercial Merpoeste, P-1, L-189, Caracas 1060, Distrito Capital, Venezuela",
};
}
