class AutoSuggestions87508588 { static final reviewedTitles87508588 = const {"Inversiones Las Julianas, C.A. - Calle Real de La Cañada, Bloque 15, Frente al, PB Local 13-04, Caracas 1030, Distrito Capital, Venezuela",
"Kiosko EL OSO - HWVV+4WM, Avenida La Armada, Catia La Mar 1162, Vargas, Venezuela",
"SagresMarket - 6 C. Negrín, Caracas 1050, Distrito Capital, Venezuela",
"Comercial Barcelona,C.A - Calle Libertador, entre Calle Mare y Jefatura, Casa N° 1, PB, Frente al, Mercado Cacique Maiquetia, Maiquetía 1161, La Guaira, Venezuela",
"Cocos y Cocadas El Trono de Odín - Av. san Martín con calle Mercado Municipal Oeste San Martín Local, 604-605 Sector, Caracas 1020, Distrito Capital, Venezuela",
"Inversiones Gordo Pablo 2 C.A. - Centro comercial San Martin, locales 406-407. Caracas, Caracas, Caracas 1020, Distrito Capital, Venezuela",
"Inversiones El Gordo Pablo 1. - Avenida principal, centro comercial San Martin, zona 22, local 513-514-515. Caracas 1020, Principal, Caracas 1020, Caracas 1020, Distrito Capital, Venezuela",
"Viveres Pernia's 5-J - Av. san Martín edificio la araña_ planta baja local 36 37 y 38 urbanización, Caracas 1020, Distrito Capital, Venezuela",
"Tu visión némesis C.A. - Avenida este, esquina Dr. Paul a Salvador de león, edificio 71 N.pb. L-11 La hoyada Caracas, Avenida E, Caracas 1040, Caracas 1012, Distrito Capital, Venezuela",
"@Rossbertca - Av baralt, esquina del Carmen y buscaré con calle Sur cc.minicentro doral baralt Nivel planta baja local pan Caracas, Caracas 1010, Distrito Capital, Venezuela",
"Nemesis ladiosa - Avenida este, esquina Dr Paul a Salvador de león, Edificio 71 Nivel PB, local 10. La hoyada Caracas 1040, Avenida E, Caracas 1020, Caracas 1012, Distrito Capital, Venezuela",
"Sucursal Irowo Omaire y Asociados - Av Andrés Bello Mercado municipal de Guaicaipuro Piso Mezzanine local 72 Urb, Caracas 1050, Distrito Capital, Venezuela",
"Romy Shop - Centro Comercial Merpoeste, P-1, L-189, Caracas 1060, Distrito Capital, Venezuela",
"Basket Burguer - Centro comercial Merpoeste, nivel feria, local 50, Caracas 1060, Distrito Capital, Venezuela",
"Marvic Style - Local 88-89. Calle Chico Carrasquel, Nivel PB, Pasillo Paují, Caracas 1064, Miranda, Venezuela",
"La casa de jade - 1060 Avenida Francisco de Miranda, Caracas 1060, Distrito Capital, Venezuela",
"Vela Fermín - local 102, Mercado de, 24, Caracas 1020, Distrito Capital, Venezuela",
"Perfumería el poder de la fe - Local-29, zona 71, Mercado de, Caracas 1020, Distrito Capital, Venezuela",
"El Dulce Mundo de Cami - Centro Comercial Merpoeste, Piso 2, local 14, Caracas 1064, Miranda, Venezuela",
"Exclusividades Adonis - local 18, Mercado de, 71, Caracas 1020, Distrito Capital, Venezuela",
"Moda Patty Divina - local 31 C. Chico Carrasquel, Caracas 1064, Miranda, Venezuela",
"Olofimar carnes - local-127, Mercado, 24, Caracas 1020, Distrito Capital, Venezuela",
"Mini Lunch - 43 Av. Libertador, local 19, Caracas 1050, Distrito Capital, Venezuela",
"Inversiones la rosa y la rosa. - Local-27, zona 71, Mercado de, Caracas 1020, Distrito Capital, Venezuela",
"Gaby Kar - Local 95-96, Centro Comercial Merpoeste, Piso 1, Nivel Llanos, Caracas, Caracas 1064, Distrito Capital, Venezuela",
"Tienda MIZ Diseños - Av. Libertador y Francisco de Miranda en Av. Libertador, Caracas 1060, Caracas 1060, Distrito Capital, Venezuela",
"Comercializadora Punto Colonial - local-415, Mercado de, 22, Caracas 1020, Distrito Capital, Venezuela",
"Edificio Miami - G42G+P4R, Av. Juan Bautista Arismendi, Caracas 1050, Distrito Capital, Venezuela",
"Ultra Óptica S.A. - Av. Juan Bautista Arismendi, nivel 2, Unidad Comercial La Florida, local 3C, Caracas 1050, Distrito Capital, Venezuela",
"Panadería Norma - G42G+P39, Av. Juan Bautista Arismendi, Caracas 1050, Distrito Capital, Venezuela",
"ZAIMAR ELECTRONIC, C.A. - Calle Chico Carrasquel con, local 194, Piso 2 C. Los Ángeles, Caracas 1064, Miranda, Venezuela",
"Maxi Pollo, C.A - Av. Baralt Esquina de balconcito Casa N° 19 Urb, Av. Baralt, Caracas 1014, Distrito Capital, Venezuela",
"Atelier Emy - Avenida baralt, equina del carme, edificion Marisabel, sector, F3WJ+W7Q, Caracas 1010, Distrito Capital, Venezuela",
};
}
