class AutoSuggestions54550283 { static final reviewedTitles54550283 = const {"Perros Calientes y Hamburguesas Ortega M - Entrada mercado Bolivariano La Hoyada, G33R+26R, Avenida Fuerzas Armadas, Caracas 1012, Distrito Capital, Venezuela",
"ADVERSUM5 - C.C. Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
"Moder Cell AD 2021 - Centro Comercial City Market, nivel feria galerias, local 321, Caracas 1050, Distrito Capital, Venezuela",
"Bluaxcel, C.A - Av Casanova CC City Market Nivel 4 Local 421 Urb, Caracas 1040, Distrito Capital, Venezuela",
"COMERCIALIZADORA IREMI - Avenida Quito, Caracas 1050, Caracas 1041, Distrito Capital, Venezuela",
"Genius Machine Import, C.A - Av. Abraham Lincoln Entre calle unión Y Miraflor CC city market Nivel Feria, Local 324, Caracas 1050, Distrito Capital, Venezuela",
"Grupo Global Tec 2724, C.A - Calle Villa flor con Boulevard de sabana grande Cc City Market Nivel Mezz Local B319, Caracas 1050, Distrito Capital, Venezuela",
"Ovistore - Calle Villaflor CC Sabana Grande, Nivel Feria Local 12 Pasillo Central Caracas, Caracas 1050, Distrito Capital, Venezuela",
"Centro Comercial del Este - F4VC+P2V, Av. Casanova, Caracas 1050, Distrito Capital, Venezuela",
"electronica Marsali - Calle las palmas, Edf. OPP 16 PB L-2, Caracas 1050, Distrito Capital, Venezuela",
"Superformica C.A - Caracas 1050, Capital District, Venezuela",
"Mangueras los Molinos - QQ5C+C3P, San Cristobal 5001, Táchira, Venezuela",
"Serviphone - 1071 Caracas, Caracas 1071, Distrito Capital, Venezuela",
"Coffe Party Piñateria - CC del Este, Nv. PB L-16 Urb, Caracas 1050, Distrito Capital, Venezuela",
"Coffe Party Automotriz - CC del Este Nv PB, L-14 Urb, Caracas 1050, Distrito Capital, Venezuela",
"Forromania - Calle Villaflor con Union, CC City Market, N, L-175 C. El Kiosco, Caracas 1050, Distrito Capital, Venezuela",
"Tecnova - Calle Villaflor con Union C.C. Sabana Grande, N-Feria, L-1 Caracas, Caracas 1050, Distrito Capital, Venezuela",
"Inversiones Yumarca 44, C.A - Av. Abraham lincolin CC. City Market Nivel Plaza Local 168 Urb, Caracas 1050, Distrito Capital, Venezuela",
"Grupo Dinero Express C.A - F4VF+479, Av. Casanova, Caracas 1050, Distrito Capital, Venezuela",
};
}
