class AutoSuggestionsAM { static final reviewedTitlesAM = const {"EJCA Electrónica, C.A. - Av Sur 2. Entre Av Lecuna y Av Oeste 12. Edif. Sur 2, PB, Local 1, Caracas 1014, Distrito Capital, Venezuela",
"Ojo de Loto - Av vollmer y Av el lago C.C Lord Center Local S13 Nivel Feria Frente La panadería Vollmer, Caracas 1010, Distrito Capital, Venezuela",
"PIZZA KIERO - Maracaibo 4004, Zulia, Venezuela",
"ROTULARTE - calle 15 Av Morita Locales Eliezer Local 3 sector, Guanare 3350, Portuguesa, Venezuela",
"Moto Sport - Carrera 3 esquina calle 20, la peñita Edificio Moto Sport, local A-03, p/b, Guanare 3350, Portuguesa, Venezuela",
"Crearteideas - A.v 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"Fina Fantasia - A.V 15 Las Delicis, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
"Cocos Sweet Shop - Avenida Sur 15, C. Guillermo José Schael, Caracas 1011, Distrito Capital, Venezuela",
"Big Fashion Ccs - Avenida Sur 15, C. Guillermo José Schael, Caracas 1011, Distrito Capital, Venezuela",
"Repuestos Betancourt - J32F+M3R, La Guaira 1160, Vargas, Venezuela",
"Floristeria Paraiso Galipan - H2WQ+J8V, C. Real de Pariata, Maiquetía 1161, La Guaira, Venezuela",
"Trovas Ve - Av 40a entre calles 161 y, Calle 162, San Francisco 4004, Zulia, Venezuela",
"PandaFix - A.V 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
};
}
