class AutoSuggestionsAU { static final reviewedTitlesAU = const {"Heladería FRUT CREAM - casa, Avenida Simón Bolívar, Guanare, Portuguesa",
"Agro Ferreganga Jusdan - Guanare, Portuguesa",
"Ferretería Frando - casa, Avenida Simón Bolívar, Guanare, Portuguesa",
"Pollo a la Broaster "Mi Comida" - San Juan de Los Morros 2301, Guárico",
"Licoreria Cañazo - Av. El Ejército, Catia La Mar 1162, La Guaira",
"Materiales La Lucha - Av. La Armada, Catia La Mar 1162, La Guaira",
"Materiales La Lucha - Av. La Armada, Catia La Mar 1162, La Guaira",
"El Parador de la Empanada - Av. Balneario, Catia La Mar 1162, La Guaira",
"Chichi Burguer - Av. Balneario, Catia La Mar 1162, La Guaira",
"Rismary Fashion - Av. Balneario, Catia La Mar 1162, La Guaira",
"El Rey de la Hamburguesa - Av. Balneario, Catia La Mar 1162, La Guaira",
"Carne en Vara la Mulata - Troncal11, San Juan de Los Morros, Guárico",
"El Rey de la Hamburguesa - Av. Balneario, Catia La Mar 1162, La Guaira",
"El Rey de la Hamburguesa - Av. Balneario, Catia La Mar 1162, La Guaira",
"La Masion del Sabor Comercializadora C.A - Barquisimeto, Lara",
"ImichuStore - Barquisimeto, Lara",
"Signos Spa - C. B, Barquisimeto, Lara",
"Reigo C.A. - al inicio, Avenida Unda, Guanare, Portuguesa",
"Titanium autoparts ca - Calle 25, Barquisimeto, Lara",
"Isabel Modas Boutique - Caracas, Distrito Capital",
"Comercio Global AG c.a - Qta Cri-Cri, Avenida Washington, Caracas, Distrito Capital",
"Kari's Dulce C.A - Av. Principal de El Hatillo, Caracas, Miranda",
"DISTRIBUIDORA LA JOYA 2000 - C.A., Caracas, Miranda",
"El Criollito Sanchez - Guanare, Portuguesa",
"YC One Detail - Caracas, Distrito Capital",
"Acrílicos pintacatia ca - 5 Av. Balneario, Catia La Mar 1162, La Guaira",
"Carnicería y Charcutería Ña Carmen c.a. - Calle 24, Guanare, Portuguesa",
"El POTY - Barquisimeto, Lara",
"Repuestos Digaban 2210 - C.A., Caracas, Distrito Capital",
"King technology D&C - Caracas, Distrito Capital",
"Centro de Copiado Belen - Catia La Mar, La Guaira",
"MotoRespuestos El Peludo - Mun, Avenida José Antonio Páez, Oeste, Distrito Capital",
"Comercial Andrecaro’s - Caracas, Distrito Capital",
"Octopus Tattoo - Caracas, Distrito Capital",
"Blu-Ray Caracas - Calle Páez, Caracas, Distrito Capital",
"Time Game - Bulevar de Sabana Grande, Caracas, Distrito Capital",
"Global Cel C.A. - Bulevar de Sabana Grande, Caracas, Distrito Capital",
"Don Andres ferreteria - Guanare, Portuguesa",
"Sunset Coffee & Market - Avenida del Hotel, Maiquetía, La Guaira",
"Vespa Shoes Store - entre carrera, Avenida Unda, Guanare, Portuguesa",
"Inversiones Tecnológicas Lemus C.A. - Guanare, Portuguesa",
"Team Gamer - y, Avenida Sur 13, Caracas, Distrito Capital",
"PCLAND - y, Avenida Sur 13, Caracas, Distrito Capital",
"Inversiones Work Group 1063 C.A. - y, Avenida Sur 13, Caracas, Distrito Capital",
"BRIZUELA 2000 COSMOS C.A - Barquisimeto, Lara",
"Neder Cakes - Avenida, Catia La Mar, Vargas",
"Seven Seas - Catia La Mar, La Guaira",
"Alfa Computer C.A - 11, Caracas, Distrito Capital",
"Dubáis Café C.A - Avenida Universidad, Caracas, Distrito Capital",
"Dubáis Café C.A - Avenida Universidad, Caracas, Distrito Capital",
"Puyao's Café - Maiquetía, La Guaira",
"Mucho Más Que Pizza - Guanare, Portuguesa",
"JK Party LG - Av. El Ejército, Catia La Mar 1162, La Guaira",
"El Rincon de Píja - Terminal de Pasajeros de Catia la mar Planta baja Local p-7, Catia La Mar 1162, La Guaira",
"Inversiones y Juguetería Tic Tac - Av. El Ejército, Catia La Mar 1162, La Guaira",
"La Boutique del Pollo y la Carne - Catia La Mar, La Guaira",
"Celest Decoraciones - Av. La Páez, Catia La Mar 1162, La Guaira",
"El Point RC - Catia La Mar, La Guaira",
"Licoreria Kati Hogar - Catia La Mar, La Guaira",
"Inversiones Ariali - Catia La Mar, La Guaira",
"Comercial Nilson Modas - Catia La Mar, La Guaira",
"Distribuidora Yuruba - Catia La Mar, La Guaira",
"Mari&Alex Inversiones - Catia La Mar, La Guaira",
"Servidetalles - Catia La Mar, La Guaira",
"El Planeta de Los Repuestos - Catia La Mar, La Guaira",
"Pinturas Decopinta - Avenida, Catia La Mar, Vargas",
"Librería y papelería Satélite - Av La Atlántida, Catia La Mar 1162, La Guaira",
"Karol Angela Boutique - CC Galerias La Frayette, Local 61, Caracas, Distrito Capital",
"Caribe Phone - Catia La Mar, La Guaira",
"Frutería El Mercadito - Caracas, Miranda",
"Av Principal de Playa Grande - Catia La Mar 1162, La Guaira",
"Las Vegas Atelier de Uñas - Local 12, Caracas, Miranda",
"Vestidos Diosmary - Bulevar de Sabana Grande, Caracas, Distrito Capital",
"GordoBurguer - Caracas, Distrito Capital",
};
}
