class AutoSuggestions27657473 { static final reviewedTitles27657473 = const {"Extraordinary. Ljubljana - Novi trg 6, 1000 Ljubljana, Slovenia",
"Trikot Pizza - 9000 Nemčavci, Slovenia",
"Oskar Bar and Cafe - Litijska cesta 148, 1000 Ljubljana, Slovenia",
"Lekarna PRI KRANJSKEM ORLU - Glavni trg 21, 4000 Kranj, Slovenia",
"E5 storitve, trgovina in svetovanje, D. O. O. - Maistrova ulica 20 A, 2250 Ptuj, Slovenia",
"ANVINA, d.o.o., Vrhnika - Tržaška cesta 8, 1360 Vrhnika, Slovenia",
"Anvina d.o.o., PE Borovnica - Paplerjeva ulica 8, 1353 Borovnica, Slovenia",
"Anvina d.o.o., proizvodnja, storitve, trženje - Cankarjev trg 6, 1360 Vrhnika, Slovenia",
"Trgovina Conrad Celje - Vodnikova ulica 6, 3000 Celje, Slovenia",
"Kmetijska zadruga Ptuj z.o.o. - Pesnica pri Mariboru 20, 2211 Pesnica pri Mariboru, Slovenia",
"Kmetijska zadruga Ptuj - Placerovci 27, 2272 Gorišnica, Slovenia",
"Avtoservis BOH D.O.O. - Industrijska cesta 1, 1290 Grosuplje, Slovenia",
"Bar Local Aleš Andlovič s.p. - Rogoška cesta 53, 2204 Miklavž na Dravskem polju, Slovenia",
"Kava bar Joca - Ljubljanska cesta 9, 2327 Rače, Slovenia",
"Bišteka mesni butik & café - Partizanska c. 44, 6210 Sežana, Slovenia",
"AvtoDoktor doo - Trpinčeva ulica 108, 1000 Ljubljana, Slovenia",
"Bar - The Prince Pub Štefan Polajžer SpA - Cesta 2. grupe odredov 34, 1295 Ivančna Gorica, Slovenia",
"La Bocca - Marinovševa cesta 4, 1000 Ljubljana, Slovenia",
"TINK superfood café (Center) - Tavčarjeva ulica 4, 1000 Ljubljana, Slovenia",
"Surf’n’fries - Šubičeva ulica 1, 1000 Ljubljana, Slovenia",
"Jet bar - Šubičeva ulica 1, 1000 Ljubljana, Slovenia",
"Parlament pub - Šubičeva ulica 1, 1000 Ljubljana, Slovenia",
"Roma - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
"Chuty's BTC - Chuty's, Francoska ulica, 1000 Ljubljana, Slovenia",
"Dentalni center Clarus-Dr.Vrčkovnik in partnerji, center za preventivo Parodontalne bolezni, lasersko zobozdravstvo, estetsko zobozdravstvo in Implantologijo, d.o.o. - Grška ulica 13, 1000 Ljubljana, Slovenia",
"S-GRAF d.o.o. - Spodnje Jarše, Jarška cesta 7, 1230 Domžale, Slovenia",
"A1 Ljubljana Bežigrad - Dunajska c. 113, 1000 Ljubljana, Slovenia",
"Gostilna Ledinek - Šmarna Gora 4, 1211 Ljubljana - Šmartno, Slovenia",
"Kavarna Lira - Kavadarska cesta 5, 1000 Ljubljana, Slovenia",
"A1 Ljubljana E.leclerc - Jurčkova Cesta 225, 1000 Ljubljana, Slovenia",
"A1 Ljubljana Črnuče - Dunajska c. 367, 1231 Ljubljana - Črnuče, Slovenia",
"A1 Domžale M&T Mobil - Slamnikarska cesta 1d, 1230 Domžale, Slovenia",
"A1 Kranj Supernova - Cesta Staneta Žagarja 69, 4000 Kranj, Slovenia",
"A1 - Cesta 1. maja 77, 4000 Kranj, Slovenia",
"Fixie.si ; Servis koles in smuči - Poljanski nasip 42, 1000 Ljubljana, Slovenia",
"THE Nutrition Maribor - Tržaška cesta 14, (stari Mercator center Tabor), 2000 Maribor, Slovenia",
"ArmaMaxa OPTIKA · GALERIJA - DILECTUS, d.o.o. - Koroška cesta 9, 2000 Maribor, Slovenia",
"SUPER HRUST - Šmartinska c. 32, 1000 Ljubljana, Slovenia",
"Srki, turistični management, d.o.o. - Brest 45, 1292 Ig, Slovenia",
"Srki, turistični management, d.o.o. - Brest 45, 1292 Ig, Slovenia",
"Boschtiz - Litostrojska Cesta 56, 1000 Ljubljana, Slovenia",
"BP TASTE IT - Tržnica Bežigrad - Plava Laguna, Linhartov podhod 39, 1000 Ljubljana, Slovenia",
"Moment Bar - Litostrojska Cesta 44e, 1000 Ljubljana, Slovenia",
"Moment Bar - Litostrojska Cesta 44e, 1000 Ljubljana, Slovenia",
"Okrepčevalnica MM, PE Cesta 24. junija - C. 24. Junija 17, 1231 Ljubljana - Črnuče, Slovenia",
"Okrepcevalnica pri mileni,milena miljevic - 1000 Ljubljana, Slovenia",
"SIMPLE - Maribor E.Leclerc - Tržaška cesta 67a, 2000 Maribor, Slovenia",
"Construction store construction material d.o.o. Sežana - Kraška ulica 5, 6210 Sežana, Slovenia",
"UP lounge bar - Stegne 1, 1000 Ljubljana, Slovenia",
"Evforija, lepotni studio, Anja Arko s.p. - Trdinov trg 4a, 1234 Mengeš, Slovenia",
"Vodene vadbe - Partizanska c. 113, 6210 Sežana, Slovenia",
"Motel in pizzeria Črni Baron, Marjan Vidovič s.p. - Malečnik 158, 2229 Malečnik, Slovenia",
"Picerija Tinka d.o.o gostinstvo in storitve - Jareninski Dol 64 C, 2221 Jarenina, Slovenia",
"Piazza - Parmova ul. 51g, 1000 Ljubljana, Slovenia",
"Irish Pub Kranj - Cesta Staneta Žagarja 14, 4000 Kranj, Slovenia",
"Ambient - 5, Čufarjeva ulica 3, 1000 Ljubljana, Slovenia",
"Sombrero bar Maver Peter s.p. - Nove Fužine 49, 1000 Ljubljana, Slovenia",
"Šport Caffe, gostinske storitve, Mara Bobić s.p. - Ajdovščina 4, 1000 Ljubljana, Slovenia",
"Horacij local * food * drink * design - Petkovškovo nabrežje 27, 1000 Ljubljana, Slovenia",
"Top Dunaj'c - 1000 Ljubljana, Slovenia",
"Gp Aslani podjetje za gradbeno dejavnost, d.o.o. - Slamnikarska cesta 3, 1230 Domžale, Slovenia",
"Asm-Inženiring, gradbeništvo in nepremičnine, d.o.o. - Slamnikarska cesta 3, 1230 Domžale, Slovenia",
"Enis-Gradnja, gradbeništvo, d.o.o. - Savska cesta 10, 1000 Ljubljana, Slovenia",
"Gostilna Frajgraba Marija Torič s.p. - Vodole 1, 2229 Malečnik, Slovenia",
"16+, Navtične Storitve, d.o.o. - Veliki trg 10, 6310 Izola - Isola, Slovenia",
"Taco Polako - Gosposvetska cesta 7, 1000 Ljubljana, Slovenia",
"KIKANI Draško Ðuza s.p. - Tugomerjeva ulica 2, 1000 Ljubljana, Slovenia",
"El Patrón Tacos & Store - Gornji trg 10, 1000 Ljubljana, Slovenia",
"Vinski kotiček - Kajuhova ulica 42, 1000 Ljubljana, Slovenia",
"cafe Flerin - Ljubljanska cesta 59, 1230 Domžale, Slovenia",
"TOČKA 213 - Palmejeva ulica 14, 1000 Ljubljana, Slovenia",
};
}
