class AutoSuggestions34777538 { static final reviewedTitles34777538 = const {"BUZZ - Otoška cesta 5, 8000 Novo mesto, Slovenia",
"Vinska klet podutik - Gradnikova ulica 8, 1000 Ljubljana, Slovenia",
"Fast food Twins - Ulica Jožeta Jame 12, 1210 Ljubljana - Šentvid, Slovenia",
"Bit Computer Engineering, Matjaž Dobovičnik SpA - Prežihova ulica 3, 2392 Ravne na Koroškem, Slovenia",
"Agil d.o.o. - Brnčičeva ulica 11, 1231 Ljubljana, Slovenia",
"Eltok d.o.o. Grosuplje - Prešernova cesta 82, 1290 Grosuplje, Slovenia",
"Računovodski Servis | Računovodske storitve | Iccounting Slovenia - Zemljemerska ulica 12, 1000 Ljubljana, Slovenia",
"Repa sistemske rešitve, trgovina na drobno po pošti, Gašper Repanšek s.p. - Divjakova ulica 8, 1000 Ljubljana, Slovenia",
"FOTO ENCHPRO Škofja Loka - Frankovo naselje 69, 4220 Škofja Loka, Slovenia",
"Neuromedis - zdravstvene dejavnosti in raziskave, Daniela Kostanjevec s.p. - Vodovodna cesta 99a, 1000 Ljubljana, Slovenia",
"Gas Station, Trgovina In Gostinstvo, D.O.O., Ljubljana - Savska cesta 5, 1000 Ljubljana, Slovenia",
"Restavracija boem Marica Žigo s.p. - Belokriška cesta 68, 6320 Portorož - Portorose, Slovenia",
"Chianti - Rakuševa ulica 1, 1000 Ljubljana, Slovenia",
"Pr' brivcu, brivnica, Rok Černe s.p. - Ropretova cesta 18, 1234 Mengeš, Slovenia",
};
}
