class AutoSuggestions48302421 { static final reviewedTitles48302421 = const {"Mundo de Azúcar, f.p. - Av unda entre calle 9 y 8 C.C La arenosa nivel 1, local 39 Av. Unda, Guanare 3350, Portuguesa, Venezuela",
"UPF Delicateses la Gloria de Dios II - Calle Arvelo Casa Nro 03, Tocuyito 2035, Carabobo, Venezuela",
"AHOPE Style - Local A15 C. Rondon, Tocuyito 2035, Carabobo, Venezuela",
"Inversiones Peña Nuñez 2015 C.A - Calle Arvelo local Nro 15, Tocuyito 2035, Carabobo, Venezuela",
"Don Miguel Pizzería - Los Chorritos, Calle Valencia con 2da Calle, Local Nro A-1, Av. 109, Tocuyito 2035, Carabobo, Venezuela",
"AHOPE Style - Local A15 C. Rondon, Tocuyito 2035, Carabobo, Venezuela",
"Inversiones Alianza de Dios JL C.A - Los Chorritos, Calle Las Bateas con 42, local 110-20, Tocuyito 2035, Carabobo, Venezuela",
"Víveres Guacara F.P - Calle Bolivar, entre Jacinto Lara, Local 109 C. Laurencio Silva, Guacara 2015, Carabobo, Venezuela",
"Abasto A Dios JL - Local 110, Los Chorritos, 21 C. Las Bateas, Tocuyito 2035, Carabobo, Venezuela",
"Liontech Sambil - Avenida Libertador, C.C. Sambil Caracas, nivel acuario, local AC-C49, Caracas, Av. Libertador, Caracas 1064, Distrito Capital, Venezuela",
"Abasto Los Chorritos - Los Chorritos, Av Venezuela, Casa Nro 67, Sector Uslar Pietri, Tocuyito 2035, Carabobo, Venezuela",
"La Coromotana C.A - Local N°1, Los Chorritos, Calle El Valencia, con Av. 110, Tocuyito 2035, Carabobo, Venezuela",
"Variedades Mis Tesoros - Los Chorritos, Calle Las Bateas con Rómulo Gallegos, Nro de casa 52, Tocuyito 2035, Carabobo, Venezuela",
"SC Canelones y Montaya - Carrera 8 Esquina calle 16 Edif Madel P/B local 2, Guanare 3350, Portuguesa, Venezuela",
"Distribuidora de AVON - Calle Bellotn&#39;2, 3 Izquierda, 03300 Orihuela, Alicante, Spain",
"WAFFLES & BOUQUET VZLA C.A - 7C65+3V4, Maracay 2101, Aragua, Venezuela",
"Frigorífico Carnes el terminal. C.A. - Los Chorritos, Av 107 Venezuela, Casa, Nro 42 Av. 107, Tocuyito 2035, Carabobo, Venezuela",
"Importaciones Technology Import - Av 15 Las Delicias Con Calle 100, Cc Gran Bazar, N1, Local1569, Maracaibo 1570, Zulia, Venezuela",
"Ferreteria Torres Ingenieria de Venezuela - barrio la arenosa, centro, carrera 8 entre calle 11 y 12, edificio Torres Ingeniería, P/B, local 02, Guanare 3350, Portuguesa, Venezuela",
"Variedades Mafer Gómez - Los Chorritos, Calle Ezequiel Zamora, Casa Nro 107-21, Sector, Tocuyito 2035, Carabobo, Venezuela",
"Importaciones Technology Import - Av 15 Las Delicias Con Calle 100, Cc Gran Bazar, N1, Local1569, Maracaibo 1570, Zulia, Venezuela",
};
}
