class AutoSuggestions87285308 { static final reviewedTitles87285308 = const {"IL PASSO - Strada Palas 7A, Iași 700051, Romania",
"Rotexim Atic - Strada Dunărea 27, Oradea, Romania",
"IL PASSO - Bulevardul Alexandru Lăpușneanu 116C, Constanța 900419, Romania",
"Sâmbăta de Sus Monastery - DC79, Stațiunea Climaterică Sâmbăta 507267, Romania",
"Antrepriza Construcţii Montaj 4 S.A. - Str. Barasch Iuliu, 4A, Bucuresti-Sector 3, Bucuresti, 30791, București 030167, Romania",
"biciclaria.ro - Bulevardul Dacia 48, Oradea 410346, Romania",
"Zen Clinic - Bulevardul Epureanu 44, Bârlad, Romania",
"German Market - Piața Mihai Viteazu nr. 17, Cluj-Napoca 400151, Romania",
"IL PASSO - Calea Vitan nr. 55-59, București 031282, Romania",
"Vinotera - Strada Căii Ferate 9, Oradea 410561, Romania",
"Romagna Mia - Piața Regele Ferdinand, Oradea 410040, Romania",
"ELCATE - Bloc A15, Strada Carpenului 12, Brașov 500256, Romania",
"Merci Bistro & Coffee Oradea - Strada Aurel Lazăr 1, Oradea 410043, Romania",
"Ardelean Mihaela - Strada Corneliu Coposu 4, Sighetu Marmației 435500, Romania",
"Aparte Paine și Bunatati - Strada Ceyrat, Oradea 417498, Romania",
"Novokinetic - Strada Alexandru Vaida Voievod nr. 18, Oradea 410089, Romania",
"MLD Auto Service - Strada Cloşca 44, Florești 407280, Romania",
"Petit Cafe - Piața Libertății 36, Oradea 410080, Romania",
"IL PASSO - Strada Nufărului nr.30, Oradea 410583, Romania",
"Marco 21 - Piața Mihai Viteazu 32, Cluj-Napoca 400156, Romania",
"Dynamic Oradea - Sala de sport/fitness ALTFEL - Strada Alexandru Vaida Voievod 18, Oradea 410088, Romania",
"Bianco Milano Oradea - Strada Republicii 10, Oradea 410018, Romania",
"Holistic - Analize medicale Bistrita - Calea Moldovei 12, Bistrița, Romania",
"Avocat CEDO - Diana Dragomir si Asociatii - Strada Ion Bogdan 9, București 010538, Romania",
"Lee Cooper - Strada Termocentralei 10, Târgu Jiu, Romania",
"Dutch Pancakes, C.A - Av. Ernesto Blohm Centro Comercial Ciudad Tamanaco, CCCT Segunda Etapa, Nivel PB, local 43L06 al lado de Burger Bar, Caracas 2115, Distrito Capital, Venezuela",
"Pensiunea Regal - nr. 106, Haieu 417501, Romania",
"Ceasornicărie - reparații ceasuri - Piața Gării, Craiova, Romania",
"Global Top Business Solutions SRL - Strada Barbu Delavrancea 59, București, Romania",
"SINTEZIS BIROTICA - P-ta Ep. Ignatie Darabant nr. 24F, Complex Comercial Galassini, modul 14, Oradea 410235, Romania",
"Taxi alba iulia - Bl A7 Ap4, Strada Ampoiului 11, Alba Iulia 510001, Romania",
"CASA MATEO - Strada Valcelelor Nr 6, Toplița 535700, Romania",
"Alimar Concrete Construct - Bucea Nr 29A, Bucea 407441, Romania",
"Magazin alimentar Hello - Bulevardul Chimiei nr 52, Iași 700294, Romania",
"Servicii Generale S.R.L. - Strada Calistrat Hogaș 8, Piatra Neamț 610004, Romania",
"ImoComplet - Strada Avram Iancu 221, Florești 407280, Romania",
"Data Speed - Strada Corneliu Coposu 103, Cluj-Napoca 400394, Romania",
"GO SERV - Bulevardul Traian 8, Baia Mare, Romania",
"Pergola Cotroceni • Restaurant • Coffee Shop - Strada Doctor Frederic Joliot-Curie 1, București 050588, Romania",
"Amecs - Piața Abator nr.4-7, Cluj-Napoca 400394, Romania",
"Amecs - Strada Tudor Vladimirescu, Alba Iulia, Romania",
"Barmacie - Strada Piezișă 21, Cluj-Napoca 400394, Romania",
"Meda Service - Strada Tipografiei nr. 8 etaj 1, Cluj-Napoca 400101, Romania",
"Librăria Sabin Opreanu - Piața 1 Mai 3, Băile Herculane 325200, Romania",
};
}
