class AutoSuggestionsREVIEW { static final reviewedTitlesREVIEW = const {"TWIST Mall - St. Johns, Antigua and Barbuda",
"Learning Ladder Child Care Centre - St Georges, Antigua and Barbuda",
"Axxess Marine Antigua - St. Paul's, Antigua, Antigua and Barbuda",
"Creole Antigua Tours - St Mary, Antigua and Barbuda",
"M & M Service Station - St. Johns, Antigua and Barbuda",
"North Coast Hardware - St. John's, Antigua and Barbuda",
"Fort Medieval - West Coast Village, Antigua and Barbuda",
"Clean Food'n Jooce - St. John's, Antigua and Barbuda",
"West Coast Drive In - West Coast Village, Antigua and Barbuda",
"Sheer Rocks Restaurant - St. Marys, Antigua and Barbuda",
"Catherine's Cafe - English Harbour, Antigua and Barbuda",
"Gents World - St. John's, Antigua and Barbuda",
"Cool Cabana - English Harbour, Antigua and Barbuda",
"Paparazzi Pizzeria & Bar - English Harbour, Antigua and Barbuda",
"Skullduggery Cafe - English Harbour, Antigua and Barbuda",
"Garden Grill - St. George's, Antigua and Barbuda",
"Colibri Bistro Bar Lounge - English Harbour, Antigua and Barbuda",
"Hill & Hill - St Johns, Antigua and Barbuda",
"Regent Bay Fund - St. John’s, Antigua and Barbuda",
"Stella Ristorante - St. Johns, Antigua and Barbuda",
"Half Beard Chen (HBC) Store - St John's, Antigua and Barbuda",
"Ez Grab Jabberwock - st georges, Antigua and Barbuda",
"Antigua Yacht Club Resort - English Harbour, Antigua and Barbuda",
"2M Heavy Enterprises - Piggotts, Antigua and Barbuda",
"ZDK Liberty Radio 97.1 FM - St. Johns, Antigua and Barbuda",
"Ez Grab Village - st johns, Antigua and Barbuda",
"Antigua Yacht Club Marina - English Harbour, Antigua and Barbuda",
"Locman - English Harbour, Antigua and Barbuda",
"Townhouse Megastore - St. John’s, Antigua and Barbuda",
"Event Studios - St. George's Parish, Antigua and Barbuda",
"The Athletes Foot - St. Johns, Antigua and Barbuda",
"Relocate Antigua - St Johns, Antigua and Barbuda",
"Akropolis Greek Restaurant - Jolly Harbour, Antigua and Barbuda",
"Thirty Six 5 Beach Bar - St John, Antigua and Barbuda",
"Hemingways Caribbean Cafe & Restaurant - St. Johns's, Antigua and Barbuda",
"Quay Necessities - St. John's, Antigua and Barbuda",
"Quay Spirits, Wines & Tobacco - St. John's, Antigua and Barbuda",
"TWIST Fitness - St. Johns, Antigua and Barbuda",
"TWIST Market St. - St. Johns, Antigua and Barbuda",
"Kon Tiki, Floating Bar - St. John's, Antigua and Barbuda",
"Basilico Italian Restaurant - Jolly Harbour, Antigua and Barbuda",
"Ana's on the beach - St John's, Antigua and Barbuda",
"NOMAD - St. John's, Antigua and Barbuda",
"Cheers Antigua - St. John, Antigua and Barbuda",
"Steph & Vlada's Studio - Jolly Harbour, Antigua and Barbuda",
"The Cool Pool - West Coast Village, Antigua and Barbuda",
"Diamond Republic - St John's, Antigua and Barbuda",
"The Tailor's Daughter - Coolidge, Antigua and Barbuda",
"Creole Antigua Tours - Noemie Belle - St Mary, Antigua and Barbuda",
"Ticchio Italian Food and Wine - St. John's, Antigua and Barbuda",
"Spices of India - St. John's, Antigua and Barbuda",
"5 Senses - English Harbour, Antigua and Barbuda",
"Vineyard Restaurant & Bar - St John's, Antigua and Barbuda",
"Clean Juice - English Harbour, Antigua and Barbuda",
"Club House - St. Paul's, Antigua and Barbuda",
"Green Sea’s - St. John’s, Antigua and Barbuda",
"Rokuni - St. Phillips, Antigua and Barbuda",
"Incanto Restaurant - English Harbour, Antigua and Barbuda",
"All Saints Service Station - St Paul’s, Antigua and Barbuda",
"Everyday Store 24/7 - St. John’s, Antigua and Barbuda",
};
}
