class AutoSuggestions67493328 { static final reviewedTitles67493328 = const {"Sudio LaVida, Nega telesa, Kristina Babić, S.P. - Rudnik II 8, 1000 Ljubljana, Slovenia",
"inn Pečnikar - Šentjakob 47, 1231 Ljubljana - Črnuče, Slovenia",
"📲 iDoktor [iPhone iPad iPod Mac Servis] Murgle Center - Cesta v Mestni log 55, 1000 Ljubljana, Slovenia",
"Loving-wood.com - 16, 1317 Globel, Slovenia",
"Taxi Ljubljana - Parmova ul. 53, 1000 Ljubljana, Slovenia",
"Motocross Brnik - 4210 Zgornji Brnik, Slovenia",
"DanKuchen - BTC - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
"DanKuchen Dunajska - Dunajska c. 35, 1000 Ljubljana, Slovenia",
"Box Bar - 1000, Ljubljana, Slovenia",
"Pizzeria Oliva - Litijska cesta 38, 1000 Ljubljana, Slovenia",
"Pizzeria Oliva - Litijska cesta 38, 1000 Ljubljana, Slovenia",
"Gimnastični center Ljubljana - Koprska ulica 29, 1000 Ljubljana, Slovenia",
"everything you need for a pleasant stay - Štanjel 5A, 6222 Štanjel, Slovenia",
"OPTIKA ŠUC, d.o.o. - Partizanska cesta 32 nasproti Okrajnega sodišča v, Center, 2000 Maribor, Slovenia",
"GUD Shop - Stari trg 4, 1000 Ljubljana, Slovenia",
"1001 dar, Supernova Mercator center Ljubljana - Cesta Ljubljanske brigade 33, 1000 Ljubljana, Slovenia",
};
}
