class AutoSuggestions77896313 { static final reviewedTitles77896313 = const {"Incanto - Antigua Slipway, English Harbour, Antigua and Barbuda",
"Rubis All Saints Service Station - 3674+H3W, Jonas Rd, All Saints, Antigua and Barbuda",
"Everyday Service Station - 4596+528, Camacho Ave, St John&#39;s, Antigua and Barbuda",
"TWIST Mall - St John&#39;s, Antigua and Barbuda",
"Learning Ladder Preschool - 5569+W68, Cedar Grove, Antigua and Barbuda",
"Axxess Marine - Comercial centre, next to Marine, English Harbour, Antigua and Barbuda",
"Creole Antigua Tours - Jolly Harbour, Antigua and Barbuda",
"M & M Service Station - 45FF+VP5, Piggotts, Antigua and Barbuda",
"North Coast Hardware - 45J7+JQG, Friars Hill Road, St John&#39;s, Antigua and Barbuda",
"Fort Medieval - West Coast Village, Antigua and Barbuda",
"Clean Food'N Jooce - Antigua Avenue, English Harbour, Antigua and Barbuda",
"West Coast Village - West Coast Village Valley Road, Antigua and Barbuda",
"Sheer Rocks - Ffryes Beach, Valley Road, St Johns, Antigua and Barbuda",
"Catherines Café - 265F+FFJ, Piccadilly, Antigua and Barbuda",
"Paparazzi Pizzeria & Bar - corner of Dockyard Drive, English Harbor, Antigua and Barbuda",
};
}
