class AutoSuggestions2496120 {
  static final reviewedTitles2496120 = const {
    "Kon Tiki Bar and Grill - 544W+9X8, Dickenson Bay St, St John&#39;s, Antigua and Barbuda",
    "Diamond Republic - 45C3+CPG, St John&#39;s, Antigua and Barbuda",
    "The Tailor's Daughter - 45C3+5QG, Redcliffe St, St John&#39;s, Antigua and Barbuda",
    "Creole Antigua Tours - Jolly Harbour, Antigua and Barbuda",
    "Ticchio Italian Food and Wine - Sir George Walter Hwy, St John&#39;s, Antigua and Barbuda",
    "Spices of India - Village Walk Shopping Complex, Friars Hill Road, St John&#39;s, Antigua and Barbuda",
    "5 Senses Restaurant - Dockyard Drive, Antigua and Barbuda",
    "The Vineyard - Friars Hill Road Jasmine Court, Suite No. 20, Antigua and Barbuda",
    "Clean Food'N Jooce - Antigua Avenue, English Harbour, Antigua and Barbuda",
    "Club House - 266H+GPG, Falmouth, Antigua and Barbuda",
    "Green Sea's Restaurant - 45M7+W4V, St John&#39;s, Antigua and Barbuda",
    "Rokuni - 38F2+26, Willikies, Antigua and Barbuda",
    "Axxess Marine - Comercial centre, next to Marine, English Harbour, Antigua and Barbuda",
    "M & M Service Station - 45FF+VP5, Piggotts, Antigua and Barbuda",
    "North Coast Hardware - 45J7+JQG, Friars Hill Road, St John&#39;s, Antigua and Barbuda",
    "Fort Medieval - West Coast Village, Antigua and Barbuda",
    "West Coast Drive-In Cinema - West Coast Village, Antigua and Barbuda",
    "Sheer Rocks - Ffryes Beach, Valley Road, St Johns, Antigua and Barbuda",
    "Catherines Café - 265F+FFJ, Piccadilly, Antigua and Barbuda",
    "Paparazzi Pizzeria & Bar - corner of Dockyard Drive, English Harbor, Antigua and Barbuda",
    "Skullduggery Cafe - 265Q+G56, English Harbour, Antigua and Barbuda",
    "Garden Grill - Dutchman&#39;s Bay Drive, Antigua and Barbuda",
    "Colibri Bistro Bar Lounge - 57 Dockyard Drive, Antigua and Barbuda",
    "Hill & Hill Attorneys at Law - 45C5+Q3C, Long St, St John&#39;s, Antigua and Barbuda",
    "Stella's Ristorante - Sunset Ln, St John&#39;s, Antigua and Barbuda",
    "Northside EZ Grab - 558X+5J2, Jabberwock Road, and Barbuda, Antigua and Barbuda",
    "Spirits of the Caribbean - St, 45C3+CFP, John&#39;s, Antigua and Barbuda",
    "Twist Fitness - Lower RedCliff Street, Twist Mall, 3rd floor, St John&#39;s, Antigua and Barbuda",
    "TWIST Mall - St John&#39;s, Antigua and Barbuda",
    "Townhouse Megastore - Corner of All Saints and, American Road, Antigua and Barbuda",
    "The Athletes Foot (#416) - Heritage Quay, St John&#39;s, Antigua and Barbuda",
    "Relocate Antigua | Relocation Services Antigua - EHLORE Ltd., Suite 10, Jolly Harbour Commercial Centre Jolly Harbour, St Mary&#39;s, Antigua and Barbuda",
    "Akropolis Greek Restaurant - jolly harbour, saint Mary’s antigua, and barbuda, Antigua and Barbuda",
    "Thirty six 5 - St John&#39;s, Antigua and Barbuda",
    "Hemingway's Caribbean Cafe - 45C4+93R, Saint Mary&#39;s Street, St John&#39;s, Antigua and Barbuda",
    "Quay Necessities - 45C3+4JW, Redcliffe St, St John&#39;s, Antigua and Barbuda",
    "Basilico Italian Restautant | Antigua - Jolly Harbour Commercial Complex AG, Jolly Harbour, Antigua and Barbuda",
    "Ana's on the Beach - Dickenson Bay, St. John, 5542+J56, s, Antigua, Antigua and Barbuda",
    "NOMAD RESTAURANT - Marble Hill Road, Antigua and Barbuda",
    "Cheers Antigua - Heritage Quay, Saint John&#39;s,, St John&#39;s, Antigua and Barbuda",
    "Steph & Vlada’s Studio - Commercial centre, Jolly Harbour, Antigua and Barbuda",
    "The Cool Pool - West Coast Village Valley Road, Antigua and Barbuda",
    "Incanto - Antigua Slipway, English Harbour, Antigua and Barbuda",
    "Rubis All Saints Service Station - 3674+H3W, Jonas Rd, All Saints, Antigua and Barbuda",
    "Citizenship By Investment Unit - 45C8+6V4, Factory Road, St John&#39;s, Antigua and Barbuda",
    "Antigua Yacht Club Marina & Resort - Falmouth Harbour, Antigua and Barbuda",
    "2M Heavy Enterprises - 45GP+2P6, Sir George Walter Hwy, Piggotts, Antigua and Barbuda",
    "ZDK Liberty Radio 97.1 FM - All Saints Road, St John&#39;s, Antigua and Barbuda",
    "St. George's Anglican Church - Church Walk Road Osbourn Antigua, 46H7+F2R, and Barbuda, Antigua and Barbuda",
    "Learning Ladder Preschool - 5569+W68, Cedar Grove, Antigua and Barbuda",
    "West Coast Village - West Coast Village Valley Road, Antigua and Barbuda",
    "Mens World Antigua - 4548+MFW, American Road, St John&#39;s, Antigua and Barbuda",
    "The Inn At English Harbour - Freeman&#39;s Bay, no 1, English Harbour, Antigua and Barbuda",
    "Everyday Service Station - 4596+528, Camacho Ave, St John&#39;s, Antigua and Barbuda",
    "Todo Torta - Juan Maria Lheritier 539, San Carlos Centro, Santa Fe, Argentina",
    "Kiosco - Av. Salvador María del Carril 2706, C1419 GZT, Buenos Aires, Argentina",
    "Good Sas - Carrera 35 #59 45, Bogotá, 111321, Colombia",
    "Cyberlink - Buenos Aires 1631, 3300, N3301IJH Posadas, Misiones, Argentina",
    "Daniel Morales Automotores - -Canelones, 91600 San Jacinto Departamento de Canelones, Uruguay",
    "Embassy of Argentina - Carrera 11B #97 56 Piso 4. Edificio, Ápice, Bogotá, 110221, Colombia",
    "Athena Holding S.R.L. - Via Publio Virginio Marone, 13, 10024 Moncalieri TO, Italy",
    "barucshop - Calle 51 #73-134 Local 3640, Medellín, Laureles, Medellín, Antioquia, 050034, Colombia",
    "Matisse Hotel - Calle 67 #6-55, Bogotá, Cundinamarca, 110231, Colombia",
    "TAG SAS Internet Satelital - Carrera 1f #No. 40-195 OFICINA 611, Tunja, Boyacá, 150001, Colombia",
    "Doctor Ricardo De Lima - Megacentro Pinares. Torre 2. Consultorio 510, Calle 18 #12-75, Pereira, Risaralda, 660003, Colombia",
    "AVACOL AVALUOS DE COLOMBIA SAS - # 94a-61, Carrera 14 #, Oficina 205, Bogotá, 110221, Colombia",
    "Sala de Ventas Cerámica Italia S.A - Calle 15 ##2N-134, Cúcuta, Norte de Santander, 540005, Colombia",
    "Rodríguez & León - Whymper N27-70 y, Av. Francisco de Orellana, Quito 170517, Ecuador",
    "teknocome - carrera 55c#159 #10 int 11, Bogotá, 111156, Colombia",
    "Taller de Joyerias Medina Yepes - Calle 38 #40-09 6, Barranquilla, Atlántico, 080003, Colombia",
    "Quokka Coworking Startups - Calle 8 #43c 29, Medellín, El Poblado, Medellín, Antioquia, 050022, Colombia",
    "Alquitrajes - Calle 30 ##80-100 2do piso, Medellín, Belén, Medellín, Antioquia, 050030, Colombia",
    "DRONE4USPRO Servicios con drones Bogotá - Calle 124 #7b-11, Usaquén, Bogotá, 110111, Colombia",
    "LA CASA DEL CEVICHE - Calle 52 #43 - 32, Medellín, La Candelaria, Medellín, Antioquia, 050012, Colombia",
    "C&D Company - Avenida Calle 32 ## 6A - 15, Bogotá, 110311, Colombia",
    "Stg Group Sas - Calle 24 #8 23, Cali, Valle del Cauca, 760044, Colombia",
    "Droguería Salud & Éxito - Carrera 73, Cali, Valle del Cauca, 760035, Colombia",
    "Yakara - Calle 72 Sur #80m-21, Bogotá, 110731, Colombia",
    "FABRICA DE ALITAS - Carrera 5 ## 70a-90, Bogotá, Cundinamarca, 110231, Colombia",
    "Café El Industrial - Kilómetro 7 vía, Cajicá - Chía, Cajicá, El Tejar, Cajicá, Cundinamarca, 250247, Colombia",
    "LudixPay Albrook Mall - Albrook Mall, Feria del Carrusel. Nivel superior., Local Cyber Studio, Panamá, Panama",
    "DORLASH - Carrera 38 ## 8a - 24 Local 26, Bogotá, 111411, Colombia",
    "Kemlem - Carrera 43 ## 51-55, Barranquilla, Atlántico, 080002, Colombia",
  };
}
