class AutoSuggestions13293638 { static final reviewedTitles13293638 = const {"Avtodeli Potokar - Tovarniška cesta 4a, 5270 Ajdovščina, Slovenia",
"Steklarstvo Potokar - Cesta Franceta Prešerna, 4270 Jesenice, Slovenia",
"Hotenjka, D.O.O. - Tržaška c. 513b, 1351 Brezovica pri Ljubljani, Slovenia",
"Avtodeli Potokar - Tovarniška ulica 7, 8270 Krško, Slovenia",
"Avtodeli Potokar, Sežana - Cesta na Lenivec 34, 6210 Sežana, Slovenia",
"Avtodeli Potokar - Dunajska c. 421, 1000 Ljubljana, Slovenia",
"Atlantis Dive Center - 1000, Šmartinska c. 152, 1000 Ljubljana, Slovenia",
"Avto center- Car Wash DIAMANT - Ulica Jožeta Jame 12, 1210 Ljubljana - Šentvid, Slovenia",
"SIMPLE - Koper Mercator - Dolinska cesta 1a, 6000 Koper - Capodistria, Slovenia",
"SIMPLE Frizerski salon - Spodnji Plavž 5, 4270 Jesenice, Slovenia",
"SIMPLE - Logatec Mercator - Tržaška cesta 3, 1370 Logatec, Slovenia",
"SIMPLE - Sežana Spar - Cesta na Lenivec 5, 6210 Sežana, Slovenia",
"SIMPLE - Koper Park center - Ankaranska cesta 2, 6000 Koper - Capodistria, Slovenia",
"Avtodeli Potokar - Gojače 5e, 5262 Črniče, Slovenia",
"Avtodeli Potokar - Cesta Kokrškega odreda 4, 4294 Križe, Slovenia",
"Ljubljana Hippodrome - Stožice, 1000 Ljubljana, Slovenia",
"SIMPLE - Domžale Mercator center - Cesta talcev 4, 1230 Domžale, Slovenia",
"SIMPLE - Domžale Mercator center - Cesta talcev 4, 1230 Domžale, Slovenia",
"SIMPLE - Hura diskont Črnuče - Pot k sejmišču 32, 1231 Ljubljana - Črnuče, Slovenia",
"AVTO KADUNC, Miha Kadunc s.p. - Perovo 27A, 1290 Grosuplje, Slovenia",
"SIMPLE - Ljubljana Mostec - Karingerjeva ulica 6, 1000 Ljubljana, Slovenia",
"SIMPLE - Ajdovščina Mercator - Vipavska cesta 6, 5270 Ajdovščina, Slovenia",
"SIMPLE - Ptuj Supernova Qlandija - Ormoška cesta 15, 2250 Ptuj, Slovenia",
"SIMPLE - Jurčkova Cesta 223, 1000 Ljubljana, Slovenia",
"SIMPLE - Ljubljana Vič - Tržaška c. 116, 1000 Ljubljana, Slovenia",
"SIMPLE - Vrhnika Spar - Ljubljanska cesta 29, 1360 Vrhnika, Slovenia",
};
}
