class AutoSuggestions27657473 { static final reviewedTitles27657473 = const {"Extraordinary. Ljubljana - Novi trg 6, 1000 Ljubljana, Slovenia",
"Trikot Pizza - 9000 Nemčavci, Slovenia",
"Oskar Bar and Cafe - Litijska cesta 148, 1000 Ljubljana, Slovenia",
"Lekarna PRI KRANJSKEM ORLU - Glavni trg 21, 4000 Kranj, Slovenia",
"E5 storitve, trgovina in svetovanje, D. O. O. - Maistrova ulica 20 A, 2250 Ptuj, Slovenia",
"ANVINA, d.o.o., Vrhnika - Tržaška cesta 8, 1360 Vrhnika, Slovenia",
"Anvina d.o.o., PE Borovnica - Paplerjeva ulica 8, 1353 Borovnica, Slovenia",
"Anvina d.o.o., proizvodnja, storitve, trženje - Cankarjev trg 6, 1360 Vrhnika, Slovenia",
"Trgovina Conrad Celje - Vodnikova ulica 6, 3000 Celje, Slovenia",
"Kmetijska zadruga Ptuj z.o.o. - Pesnica pri Mariboru 20, 2211 Pesnica pri Mariboru, Slovenia",
"Kmetijska zadruga Ptuj - Placerovci 27, 2272 Gorišnica, Slovenia",
"Avtoservis BOH D.O.O. - Industrijska cesta 1, 1290 Grosuplje, Slovenia",
"Bar Local Aleš Andlovič s.p. - Rogoška cesta 53, 2204 Miklavž na Dravskem polju, Slovenia",
"Kava bar Joca - Ljubljanska cesta 9, 2327 Rače, Slovenia",
"Bišteka mesni butik & café - Partizanska c. 44, 6210 Sežana, Slovenia",
"AvtoDoktor doo - Trpinčeva ulica 108, 1000 Ljubljana, Slovenia",
"Bar - The Prince Pub Štefan Polajžer SpA - Cesta 2. grupe odredov 34, 1295 Ivančna Gorica, Slovenia",
};
}
