class AutoSuggestions15140377 { static final reviewedTitles15140377 = const {"Axxess Marine - Comercial centre, next to Marine, English Harbour, Antigua and Barbuda",
"Creole Antigua Tours - Jolly Harbour, Antigua and Barbuda",
"M & M Service Station - 45FF+VP5, Piggotts, Antigua and Barbuda",
"North Coast Hardware - 45J7+JQG, Friars Hill Road, St John&#39;s, Antigua and Barbuda",
"Fort Medieval - West Coast Village, Antigua and Barbuda",
"Clean Food'N Jooce - Antigua Avenue, English Harbour, Antigua and Barbuda",
"West Coast Drive-In Cinema - West Coast Village, Antigua and Barbuda",
"Sheer Rocks - Ffryes Beach, Valley Road, St Johns, Antigua and Barbuda",
"Catherines Café - 265F+FFJ, Piccadilly, Antigua and Barbuda",
"Paparazzi Pizzeria & Bar - corner of Dockyard Drive, English Harbor, Antigua and Barbuda",
"Skullduggery Cafe - 265Q+G56, English Harbour, Antigua and Barbuda",
"Garden Grill - Dutchman&#39;s Bay Drive, Antigua and Barbuda",
"Colibri Bistro Bar Lounge - 57 Dockyard Drive, Antigua and Barbuda",
"Hill & Hill Attorneys at Law - 45C5+Q3C, Long St, St John&#39;s, Antigua and Barbuda",
};
}
