class AutoSuggestions48605976 { static final reviewedTitles48605976 = const {"Мебели Нет ЕООД - ulitsa Georgi S. Rakovski 201, ет.1, 1142 Old City Center, Sofia, Bulgaria",
"Villa DELUXE Arbanassi - ul. Cofronij Vrachanski 6, 5029 Arbanasi, Bulgaria",
"Party Land - ul. Knyaz Aleksander Batenberg, 9000 Greek Neighborhood, Varna, Bulgaria",
"SDK - 08 - ul. Han Krum бл. 2, вх в ет 1, 8600 g.k. Iztok, Yambol, Bulgaria",
"Vesta B and C - ул. Капитан Дядо Никола 21, 5300 Radichevets, Gabrovo, Bulgaria",
"Vesta V i S Ltd - ul. Samara 7, 4003 Karshiaka, Plovdiv, Bulgaria",
"Магазин Ритони - ul. G.S. Rakovski, 8900 2, село, Roza, Bulgaria",
"поща Варна клон 2 - ul. Ivan Aksakov 7A, 9002 Varna Center, Varna, Bulgaria",
"CleanUp - ul. Sevastokrator Kaloyan 19, 1616 Bojana, Sofia, Bulgaria",
"ESCAPE REALITY - VR experience center - ul. Dunav 35-А, 1000 Old City Center, Sofia, Bulgaria",
"Estate - 1233 g.k. Banishora, Sofia, Bulgaria",
"Ralevi House - ulitsa Katunishte, 1444 Katunishte, Bulgaria",
"Hotel Pri Chakara - 28 Sv. Nikola str, 5029 Arbanasi, Bulgaria",
"Pri Marto Melnik Grill - bul. Patriarh Evtimiy 22, 1000 Sofia Center, Sofia, Bulgaria",
"Пловдив 24/7 Еконтомат OMV бул. България - бул. България №97, 4003 Plovdiv, Bulgaria",
"Pri Chakara - ul. Sveti Nikola 5, 5029 Veliko Tarnovo, Bulgaria",
"V&T TRADE - Централна 43, 2231 Golyanovtsi, Bulgaria",
};
}
