class AutoSuggestions23009220 {
  static final reviewedTitles23009220 = const {
    "Music Shop A-AUDIO - ul. Peyo K. Yavorov 83, 5000 g.k. Akatsia, Veliko Tarnovo, Bulgaria",
    "КРАЛСКАТА ИЗБА * CRAMA REGALA * ROYAL WINE CELLARoyal Wine Cellar * - КРАЛСКАТА ИЗБА* Crama Regala* ROYAL WINE CELLAR* THE PALACE, Balchik*, 9600 Dvoretsa, Balchik, Bulgaria",
    "Бирария Дондуковъ / Dondukov Pub - бул. княз Александър Дондуков 14, 1000 Old City Center, Sofia, Bulgaria",
    "Патешки вкуснотийки - ul. Vasil Kirkov 1, 1164 g.k. Lozenets, Sofia, Bulgaria",
    "Мебели Нет ЕООД - ulitsa Georgi S. Rakovski 201, ет.1, 1142 Old City Center, Sofia, Bulgaria",
    "Villa DELUXE Arbanassi - ul. Cofronij Vrachanski 6, 5029 Arbanasi, Bulgaria",
    "Party Land - ul. Knyaz Aleksander Batenberg, 9000 Greek Neighborhood, Varna, Bulgaria",
    "SDK - 08 - ul. Han Krum бл. 2, вх в ет 1, 8600 g.k. Iztok, Yambol, Bulgaria",
    "Vesta B and C - ул. Капитан Дядо Никола 21, 5300 Radichevets, Gabrovo, Bulgaria",
    "Vesta V i S Ltd - ul. Samara 7, 4003 Karshiaka, Plovdiv, Bulgaria",
    "Магазин Ритони - ul. G.S. Rakovski, 8900 2, село, Roza, Bulgaria",
    "поща Варна клон 2 - ul. Ivan Aksakov 7A, 9002 Varna Center, Varna, Bulgaria",
    "CleanUp - ul. Sevastokrator Kaloyan 19, 1616 Bojana, Sofia, Bulgaria",
    "ESCAPE REALITY - VR experience center - ul. Dunav 35-А, 1000 Old City Center, Sofia, Bulgaria",
    "Estate - 1233 g.k. Banishora, Sofia, Bulgaria",
    "Ralevi House - ulitsa Katunishte, 1444 Katunishte, Bulgaria",
    "Hotel Pri Chakara - 28 Sv. Nikola str, 5029 Arbanasi, Bulgaria",
    "Yazaki Bulgaria EOOD - бул. Европа 43, 8600 Western Industrial Zone, Yambol, Bulgaria",
    "Museum of Illusions Sofia - бул. княгиня Мария Луиза 16, 1000 Old City Center, Sofia, Bulgaria",
    "Smerch - ul. Han Kubrat 4, 8600 g.k. General Vladimir Zaimov, Yambol, Bulgaria",
    "Swiss Hotel - ul. Vasil Aprilov 56, 9705 Shumen Center, Shumen, Bulgaria",
    "MAXX21 - JumpMAXX, LaserMAXX - Holzmanngasse 1, Floridsdorf 1210 Wien, Austria",
    "Maxx21 - Jedlersdorfer Str. 94, Floridsdorf 1210 Wien, Austria",
    "LaserMAXX Bar - Roßauer Lände 45, Alsergrund 1090 Wien, Austria",
    "Restaurant-Bar Krahvogel - Anichstraße 12, Innenstadt 6020 Innsbruck, Austria",
    "WipeOut Austria Parndorf - Gewerbestraße 4, 7111 Parndorf, Austria",
    "ArtSmiles General & Cosmetic Dentistry - 4/45-49 Nind St, Southport QLD 4215, Australia",
    "Barbershop Old Capital - ul. Todor Balina 9a, 5006 Rayon Zapaden, Veliko Tarnovo, Bulgaria",
    "Ресторант Swiss - ul. Vasil Aprilov 56 А, 9700 Shumen Center, Shumen, Bulgaria",
    "Medilon - 98 Bulgaria” blvd. office 4D, entr.D, Business center ASTRA, 1680 Manastirski Livadi, Sofia, Bulgaria",
    // "Music Shop A-AUDIO - ul. Peyo K. Yavorov 83, 5000 g.k. Akatsia, Veliko Tarnovo, Bulgaria",
    "Бирария Стамболов - bul. Sveti Naum 1, 1421 g.k. Lozenets, Sofia, Bulgaria",
    // "Мебели Нет ЕООД - ulitsa Georgi S. Rakovski 201, ет.1, 1142 Old City Center, Sofia, Bulgaria",
    // "Villa DELUXE Arbanassi - ul. Cofronij Vrachanski 6, 5029 Arbanasi, Bulgaria",
    // "Party Land - ul. Knyaz Aleksander Batenberg, 9000 Greek Neighborhood, Varna, Bulgaria",
    // "SDK - 08 - ul. Han Krum бл. 2, вх в ет 1, 8600 g.k. Iztok, Yambol, Bulgaria",
    // "Vesta B and C - ул. Капитан Дядо Никола 21, 5300 Radichevets, Gabrovo, Bulgaria",
    // "Vesta V i S Ltd - ul. Samara 7, 4003 Karshiaka, Plovdiv, Bulgaria",
    // "Магазин Ритони - ul. G.S. Rakovski, 8900 2, село, Roza, Bulgaria",
    // "поща Варна клон 2 - ul. Ivan Aksakov 7A, 9002 Varna Center, Varna, Bulgaria",
    // "CleanUp - ul. Sevastokrator Kaloyan 19, 1616 Bojana, Sofia, Bulgaria",
    // "ESCAPE REALITY - VR experience center - ul. Dunav 35-А, 1000 Old City Center, Sofia, Bulgaria",
    // "Estate - 1233 g.k. Banishora, Sofia, Bulgaria",
    // "Ralevi House - ulitsa Katunishte, 1444 Katunishte, Bulgaria",
    // "Hotel Pri Chakara - 28 Sv. Nikola str, 5029 Arbanasi, Bulgaria",
    "Pri Marto Melnik Grill - bul. Patriarh Evtimiy 22, 1000 Sofia Center, Sofia, Bulgaria",
    "Пловдив 24/7 Еконтомат OMV бул. България - бул. България №97, 4003 Plovdiv, Bulgaria",
    "Pri Chakara - ul. Sveti Nikola 5, 5029 Veliko Tarnovo, Bulgaria",
    "V&T TRADE - Централна 43, 2231 Golyanovtsi, Bulgaria",
    // "MAXX21 - JumpMAXX, LaserMAXX - Holzmanngasse 1, Floridsdorf 1210 Wien, Austria",
    // "Maxx21 - Jedlersdorfer Str. 94, Floridsdorf 1210 Wien, Austria",
    // "LaserMAXX Bar - Roßauer Lände 45, Alsergrund 1090 Wien, Austria",
    // "Restaurant-Bar Krahvogel - Anichstraße 12, Innenstadt 6020 Innsbruck, Austria",
    // "WipeOut Austria Parndorf - Gewerbestraße 4, 7111 Parndorf, Austria",
    // "ArtSmiles General & Cosmetic Dentistry - 4/45-49 Nind St, Southport QLD 4215, Australia",
    "Oh My Burger Antwerp - Graaf van Egmontstraat 47, 2000 Antwerpen, Belgium",
    "Doner & Gyros - ul. Hristo Botev 12, 5000 Veliko Tarnovo Center, Veliko Tarnovo, Bulgaria",
    "Arbat Guest Rooms - ul. Kapitan Pavel Gramadov 1, 5029 Arbanasi, Bulgaria",
    "Architect's house ( Дом на Архитекта) - ul. Velcho Dzhamdzhiyata 14, 5000 g.k. Varusha - south, Veliko Tarnovo, Bulgaria",
    "Happy Potter - ceramics and souvenirs - ul. Stefan Stambolov 53А, 5000 g.k. Varusha - north, Veliko Tarnovo, Bulgaria",
    "Fresh bar - ul. Borisova 14-162, 7000 Ruse Center, Ruse, Bulgaria",
    "bar Taboo - g.k. Krasna polyana 2 38A, 1373 ж.к. Красна поляна 2, Sofia, Bulgaria",
    "Kuche Ninja - Dog Grooming (подстригване на кучета) - Mladost 3, bl. 302, ent. 3 - inner yard, 1712 ж.к. Младост 3, Sofia, Bulgaria",
    "Club Cult - ul. Sveti Sveti Kiril I Metodiy 8, 8600 Yambol Center, Yambol, Bulgaria",
    // "bar Taboo - g.k. Krasna polyana 2 38A, 1373 ж.к. Красна поляна 2, Sofia, Bulgaria",
    "Тристаен апартамент - бул. Македония 27 ЕТАЖ 1: APT.3, Център, 1606 Pette Kyosheta, Sofia, Bulgaria",
    "TABU Shisha & Dinner - ul. 8-mi dekemvri, 1700 Studentski Kompleks, Sofia, Bulgaria",
    "Слим Компютърс ООД - ul. Georgi S. Rakovski 13, 8600 Yambol Center, Yambol, Bulgaria",
    "Monaco - bul. Vitosha 133, 1408 Ivan Vazov, Sofia, Bulgaria",
    "TATTOO Party Boat - Marina Nessebar, str.Monsenior A. Ronkali 6, 8231, 8231 Стария Град, Несебър, Bulgaria",
    "GreenMobile - Изипей - Western Union - 1280 Kurilo, Novi Iskar, Bulgaria",
    "Магазин e-Point - Продажба на висок клас Електрически Тротинетки/Скутери с марката Kaabo - в ТОП 3 на доказаните марки и модели в света! - бул. св. Климент Охридски 39А, 1756 g.k. Darvenitsa, Sofia, Bulgaria",
    "Bee Mauri bar e ristorante veg - Viale Carlo Cattaneo 21, 6900 Lugano, Switzerland",
    "Studio Pixel - Via Mesolcina 2, 6500 Bellinzona, Switzerland",
    "Blessed Swiss - Corso Elvezia 7, 6900 Lugano, Switzerland",
    "Green Wolf CBD - Via Lugano 16, 6988 Ponte Tresa, Switzerland",
    "DIECI STYLE FACTORY - Corso Enrico Pestalozzi 4a, 6900 Lugano, Switzerland",
    "Vulkan Lugano - Via Trevano 3, 6900 Lugano, Switzerland",
    "Somazzi Orologeria - Via Nassa 36, 6900 Lugano, Switzerland",
    "Piadineria Romagna Mia - Via Marco da Carona 2, 6900 Lugano, Switzerland",
    "Ristorante Pizzeria Domino - Riva Antonio Caccia 12, 6900 Lugano, Switzerland",
    "Imove - 6900 Lugano, Switzerland",
    "Snack Ok Bar - Via Clemente Maraini 46, 6900 Lugano, Switzerland",
    "Kellerhals Carrard Lugano SA - Via Canova 15, 6901 Lugano, Switzerland",
    "cleomoda.com - Via Dufour 1, 6900 Lugano, Switzerland",
    "Mystic Shop - Corso Elvezia 13, 6900 Lugano, Switzerland",
    "PAPRIKA Lounge Bar - Piazza Nosetto 4C, 6500 Bellinzona, Switzerland",
    "Taqueria El Chilicuil - Corso Enrico Pestalozzi 12, 6900 Lugano, Switzerland",
    "Garage Golena SA - Centro Toyota Bellinzona - Via del Carmagnola 22- 24- 26, 6517 Arbedo, Switzerland",
    "Bar Osteria Indipendenza - Piazza Indipendenza 11, 6900 Lugano, Switzerland",
    "Gioielleria Preziosi - Viale Carlo Cattaneo 1, 6900 Lugano, Switzerland",
    "Pizza Burger Lugano - Via Luigi Lavizzari 5, 6900 Lugano, Switzerland",
    "Ottica Götte - Morottica SA - Via Pessina 8, 6900 Lugano, Switzerland",
    "Dilo’s Cafe & Bar cucina internazionale - Via Serafino Balestra 31, 6900 Lugano, Switzerland",
    "Parq - Via Pasquale Lucchini 1, 6900 Lugano, Switzerland",
    "Miss Spettino - Via Orti 8, 6900 Lugano, Switzerland",
    "Staglio - La Pizza al Taglio - Corso Elvezia 8, 6900 Lugano, Switzerland",
    "kios-ka - Viganello CH, Via alla Chiesa 1, 6900 Lugano, Switzerland",
    "Novaretis SAgl - Via Gerso 1, 6900 Lugano, Switzerland",
    "Debarcadero lugano - Riva Vincenzo Vela 2, 6900 Lugano, Switzerland",
    // "Debarcadero lugano - Riva Vincenzo Vela 2, 6900 Lugano, Switzerland",
    "Mauri Concept - Via Gerolamo Vegezzi 4, 6900 Lugano, Switzerland",
    "Dagorà - Lifestyle Innovation Hub - Galleria 1, Via Cantonale, 6928 Manno, Switzerland",
    "Ottica Vicari SA - Via Serafino Balestra 4, 6900 Lugano, Switzerland",
    "Musicdoor - Piazza Riforma, 6900 Lugano, Switzerland",
    "Balmelli Sport - Via G.B. Pioda 10, 6900 Lugano, Switzerland",
// "Balmelli Sport - Via G.B. Pioda 10, 6900 Lugano, Switzerland",
    "Balmelli Outlet Sport - Via Carlo Maderno 16, 6900 Lugano, Switzerland",
    "BB Motors - In Tirada 31, 6528 Camorino, Switzerland",
    "New Trends SA Immobiliare Fiduciaria - Via Pretorio 11, 6900 Lugano, Switzerland",
  };
}
