class AutoSuggestions99520673 {
  static final reviewedTitles99520673 = const {
    "Leskovački dvor - Dunajska c. 57, 1000 Ljubljana, Slovenia",
    "Žito, Delikatesa Koseze - Vodnikova cesta 187, 1000 Ljubljana, Slovenia",
    "Kino Komuna - Kino Komuna, Kino Komuna, Tomšičeva ulica 2, 1000 Ljubljana, Slovenia",
    "SIMPLE - Novo mesto Mercator - Ljubljanska cesta 47, 8000 Novo mesto, Slovenia",
    "Gostilna Jakomin Kubed - Elvis Jakomin s.p. - Kubed 3a, 6272 Gračišče, Slovenia",
    "Venera Shop - Sex shop Domžale - Unnamed Road, 1230, 1230 Domžale, Slovenia",
    "Takos - Pobreška cesta 18, 2000 Maribor, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Prešernova cesta 53, 6310 Izola, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Ulica Gradnikove brigade 53, 5000 Nova Gorica, Slovenia",
    "Venera shop - Sex shop Murska Sobota - Nemčavci 1d, 9000 Murska Sobota, Slovenia",
    "Venera shop - Sex Shop Maribor - Cesta proletarskih brigad 100, 2000 Maribor, Slovenia",
    "Piccolo bar - BTC City, 9000, 9000 Murska Sobota, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Tržaška c. 63, 1000 Ljubljana, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Trubarjeva cesta 43, 1000 Ljubljana, Slovenia",
    "Km Terjatve in finančne storitve, Klementina Kurunić s.p. - Žolgarjeva ulica 25, 2310 Slovenska Bistrica, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Ulica pri Velikih vratih 18, 6000 Koper, Slovenia",
    "Imperija center zdravja in lepote, Karmen Puntar s.p. - Ameriška ulica 3, 1000 Ljubljana, Slovenia",
    "F. Dvor, services and trade D.O.O. - Ob železnici 14, 1000 Ljubljana, Slovenia",
    "Ljubljanski Brivec by Mič styling - HOTEL UNION - Miklošičeva cesta 1, 1000 Ljubljana, Slovenia",
    "YOUNG MIČ STYLING - Trubarjeva cesta 28, 1000 Ljubljana, Slovenia",
    "Mič Styling - Poljanska - Poljanska cesta 13, 1000 Ljubljana, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Seškova cesta 9, 1215 Medvode, Slovenia",
    "SIMPLE - Jurčkova Cesta 223, 1000 Ljubljana, Slovenia",
    "SIMPLE - Nova Gorica Qlandia - Cesta 25. junija 1a, 5000 Nova Gorica, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Šuceva ulica 25, 4000 Kranj, Slovenia",
    "Venera Shop, podjetje za trgovino in storitve, d.o.o. - Šaleška cesta 19a, 3320 Velenje, Slovenia",
    "Kavarna Zvezda - Wolfova ulica 14, 1000 Ljubljana, Slovenia",
    "Fitnesshop - Rakuševa ulica 10, 1000 Ljubljana, Slovenia",
    "Army Shop Landing Zone - Madžarska Ulica Šmartinska cesta 152 BTC- Hala 11, 1000 Ljubljana, Slovenia",
    "Bags & More - Igriška ulica 8, 1000 Ljubljana, Slovenia",
    "Mič Styling - Rimska - Rimska cesta 16, 1000 Ljubljana, Slovenia",
    "Hala Tivoli - 1000, Celovška cesta 25, 1000 Ljubljana, Slovenia",
    "Malibu bar - Ob dolenjski železnici 12, 1000 Ljubljana, Slovenia",
    "Imperio Mexicano - Šmartinska c. 152g, 1000 Ljubljana, Slovenia",
    "Balkan Express - Moskovska ulica 4, 1000 Ljubljana, Slovenia",
    "Bs center trgovina in storitve d.o.o., poslovna enota Šmartinska - Šmartinska c. 199, 1000 Ljubljana, Slovenia",
    "OOOPS boutique d.o.o. - Slovenska cesta 30, 1000 Ljubljana, Slovenia",
    "Karin podjetje za trgovino, storitve in zastopanje, d.o.o., Ljubljana-Brezovica, Tržaška 438 - Tržaška c. 438, 1351 Brezovica pri Ljubljani, Slovenia",
    "Restavracija in pizzeria B2 - Tržaška c. 200, 1000 Ljubljana, Slovenia",
    "Club SEVEN - Šmartno - Brod, 1133 Ljubljana - Brod, Slovenia",
    // "Club SEVEN - Šmartno - Brod, 1133 Ljubljana - Brod, Slovenia",
    "Restavracija Dobri Čuk - Stegne 23a, 1000 Ljubljana, Slovenia",
    "Prosti čas Kamnik - Šutna 37, 1241 Kamnik, Slovenia",
    "Lečnik, urarstvo in trgovina, d.o.o. - Stari trg 14, 1000 Ljubljana, Slovenia",
    "SkyEye Bitcoin ATM - Šentviška ulica 7, 1210 Ljubljana - Šentvid, Slovenia",
    "Tehnično svetovanje, Matjaž Aleš s.p. - Tesovnikova ulica 50, 1000 Ljubljana, Slovenia",
    "Hotel Triglav l.l.c. Bled - Kolodvorska cesta 33, 4260 Bled, Slovenia",
    "Captain's Cabin - Ključavničarska ulica 5, 1000 Ljubljana, Slovenia",
    "Omega sport trgovina in servis koles ter ostale športne opreme d.o.o. - Dunajska c. 85, 1000 Ljubljana, Slovenia",
    "Bistro & Rooms Hiša Budja - Dupleška cesta 132, 2000 Maribor, Slovenia",
    "Mizarstvo Nemec - kuhinje po meri - Kamnica 2, 1262 Dol pri Ljubljani, Slovenia",
    "Šport & Wellness Center Harmonija - 1234 Mengeš, Slovenia",
    "XYZ - Rakuševa ulica 1, 1000 Ljubljana, Slovenia",
    "Autobroker by Kreativni najemi - Prodajni salon, Verovškova ulica 60a, 1000 Ljubljana, Slovenia",
    "📲 iDoktor [iPhone iPad iPod Mac Servis] Murgle Center - Cesta v Mestni log 55, 1000 Ljubljana, Slovenia",
    "XYZ - Celovška cesta 182, 1000 Ljubljana, Slovenia",
    "Florist Anaeva - Ljubljanska cesta 12c, 1236 Trzin, Slovenia",
    "TA NOV JOZL, gostinstvo in turizem, Denis Klaneček s.p. - Triglavska cesta 50, 4281 Mojstrana, Slovenia",
    "Taxi Bohinj - Polje 23, 4264 Bohinjska Bistrica, Slovenia",
    "Bioenergija, Bojan Bone s.p. - Slamnikarska cesta 22, 1230 Domžale, Slovenia",
    "Parfois - Rakuševa ulica 1, 1000 Ljubljana, Slovenia",
    "Agroremont d.o.o. Maribor - Obi, Tržaška cesta 65, 2000 Maribor, Slovenia",
    // "Takos - Pobreška cesta 18, 2000 Maribor, Slovenia",
    "Doget d.o.o. - Miklošičeva cesta 38, 1000 Ljubljana, Slovenia",
    "Bazaar Smoking shop - Gregorčičeva ulica 6, 4000 Kranj, Slovenia",
    "Klub Rečnih Kapitanov - Opekarska 1 (Pod Prulskim mostom), 1000 Ljubljana, Slovenia",
    "Trappa pizzeria&bar - Koprska ulica 94, 1000 Ljubljana, Slovenia",
    "PraveStvari - Dunajska c. 122, 1000 Ljubljana, Slovenia",
    "Mk Gril, priprava in dostava hrane, Miomir Kostić s.p. - Bratovševa ploščad 12, 1000 Ljubljana, Slovenia",
    "Fotokopirnica Gallus, Kristina Kogelnik s.p. - Grajska ulica 5, 2000 Maribor, Slovenia",
    "Maribor INN hotel - Karantanska ulica 26, 2000 Maribor, Slovenia",
    "Um - ha, gostinske storitve, d.o.o. - BTC tržnica sever, Italijanska ulica 7, 1000 Ljubljana, Slovenia",
    "Čebelarstvo Vasič - Litijska cesta 12, 1000 Ljubljana, Slovenia",
    "Kava bar mi Srša Patricija s.p. - Ruska ulica 9, 2000 Maribor, Slovenia",
    "Kavarnica Rokaj - Usnjarska ulica 3, 2000 Maribor, Slovenia",
    "Kampus Food - Pivovarniška ulica 6, 1000 Ljubljana, Slovenia",
    "Pause Cafe - Dravska ulica 7, 2000 Maribor, Slovenia",
    "Ljubljanski Brivec by MIČ STYLING - SLOVENSKA - Slovenska cesta 30, 1000 Ljubljana, Slovenia",
    "Young Mič Styling - Citypark - Moskovska ulica 4, 1000 Ljubljana, Slovenia",
    "SIMPLE BARBER SHOP - Qlandia, Cesta 25. junija 1a, 5000 Nova Gorica, Slovenia",
    "Sten Time - Otoška cesta 5, 8000 Novo mesto, Slovenia",
    "STEN TIME - Ormoška cesta 15, 2250 Ptuj, Slovenia",
    "Sten Time - Cesta 1. maja 77, 4000 Kranj, Slovenia",
    "Event transport, prevozi in posredništvo, d.o.o. - Dol pri Hrastovljah 44, 6275 Črni Kal, Slovenia",
    "Cvetličarna Bela, Onja Knol Čulk s.p. - Tržaška cesta 3, 1370 Logatec, Slovenia",
    "Gostilna Gitadela - Pševska cesta 43, 4000 Kranj, Slovenia",
    "Tuš supermarket Planet Kranj - Cesta Jaka Platiše 18, 4000 Kranj, Slovenia",
    "Tuš supermarket Radvanje - Streliška cesta 24, 2000 Maribor, Slovenia",
    "Tuš hipermarket Planet Celje - Mariborska cesta 128, 3000 Celje, Slovenia",
    "Tuš supermarket Bakovska Murska Sobota - Bakovska ulica 31a, 9000 Murska Sobota, Slovenia",
    "Lagev bar - Ulica dr. Vrbnjaka 10a, 9000 Murska Sobota, Slovenia",
    "Ag Gantar - Kranjska cesta 22, 4202 Naklo, Slovenia",
    "Galerija Kofi Design - Kersnikova ulica 10, 1000 Ljubljana, Slovenia",
    "Škrnic'lj restavracija - Andrej Belovič s.p. - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "Quicksilver Store - Mestni trg 16, 1000 Ljubljana, Slovenia",
    "Mlada Lipa-Picerija-Igralnica-Gostišče Marko Budja s.p. - Lackova cesta 76, 2000 Maribor, Slovenia",
    "GARDEROBA tiskarna majic - Pot heroja Trtnika 45, 1000 Ljubljana, Slovenia",
    "Sudio LaVida, Nega telesa, Kristina Babić, S.P. - Rudnik II 8, 1000 Ljubljana, Slovenia",
    "inn Pečnikar - Šentjakob 47, 1231 Ljubljana - Črnuče, Slovenia",
    // "📲 iDoktor [iPhone iPad iPod Mac Servis] Murgle Center - Cesta v Mestni log 55, 1000 Ljubljana, Slovenia",
    "Loving-wood.com - 16, 1317 Globel, Slovenia",
    "Taxi Ljubljana - Parmova ul. 53, 1000 Ljubljana, Slovenia",
    "Motocross Brnik - 4210 Zgornji Brnik, Slovenia",
    "DanKuchen - BTC - Šmartinska c. 152, 1000 Ljubljana, Slovenia",
    "DanKuchen Dunajska - Dunajska c. 35, 1000 Ljubljana, Slovenia",
    "Box Bar - 1000, Ljubljana, Slovenia",
    "Pizzeria Oliva - Litijska cesta 38, 1000 Ljubljana, Slovenia",
// "Pizzeria Oliva - Litijska cesta 38, 1000 Ljubljana, Slovenia",
    "Gimnastični center Ljubljana - Koprska ulica 29, 1000 Ljubljana, Slovenia",
    "everything you need for a pleasant stay - Štanjel 5A, 6222 Štanjel, Slovenia",
    "OPTIKA ŠUC, d.o.o. - Partizanska cesta 32 nasproti Okrajnega sodišča v, Center, 2000 Maribor, Slovenia",
    "GUD Shop - Stari trg 4, 1000 Ljubljana, Slovenia",
    "1001 dar, Supernova Mercator center Ljubljana - Cesta Ljubljanske brigade 33, 1000 Ljubljana, Slovenia",
    "SENS d.o.o. družba za oblikovanje in trgovino Ljubljana - Obleke za moške - Men's Wear - Italijanska ulica 8, 1000 Ljubljana, Slovenia",
    "Extremo.si - Šmartinska c. 16, 1000 Ljubljana, Slovenia",
    "Viki's Bar - Wolfova ulica 10a, 1000 Ljubljana, Slovenia",
    "1001 dar, Europark Maribor - Pobreška cesta 18, 2000 Maribor, Slovenia",
    "1001 dar, Plava laguna Ljubljana - Dunajska c. 50, 1000 Ljubljana, Slovenia",
    "1001 dar, Citypark Ljubljana - Moskovska ulica 4, 1000 Ljubljana, Slovenia",
    "Poslovni sistem Mercator d.d. - Špindlerjeva ulica 3, 2250 Ptuj, Slovenia",
    "Kopališče Kodeljevo - Poljanska cesta 99, 1000 Ljubljana, Slovenia",
    "BubbleWaffle Maribor - Strossmayerjeva ulica 13, 2000 Maribor, Slovenia",
    "Hotspot Bistro And Bar - Kardeljeva ploščad, 1000 Ljubljana, Slovenia",
// "Hotspot Bistro And Bar - Kardeljeva ploščad, 1000 Ljubljana, Slovenia",
    "iPub - Devova ulica 6, 1000 Ljubljana, Slovenia",
    "HeadShop Vršiček Shop - Turnerjeva ulica 22, 2000 Maribor, Slovenia",
    "Cannabis, posredništvo, trgovina in storitve, D.O.O.- PE Celje - Gledališka ulica 9, 3000 Celje, Slovenia",
    "Zobozdravstvo Bele, Simon Bele s.p. - Seidlova cesta 30, 8000 Novo mesto, Slovenia",
    "Hiša sanjajočih knjig | House of Dreaming Books - Trubarjeva cesta 29, 1000 Ljubljana, Slovenia",
    "TISHLER EYEWEAR - Cesta svobode 15, 4260 Bled, Slovenia",
    "POTOKAR d.o.o., p.e. Vrhnika - Cankarjev trg 4, 1360 Vrhnika, Slovenia",
    "VAPE ON SHOP - Trubarjeva cesta 46, 1000 Ljubljana, Slovenia",
    "ALEJA - Rakuševa ulica 1, 1000 Ljubljana, Slovenia",
    "Soba pobega MindMaze, Escape Room Ljubljana - Trubarjeva cesta 24, Ground floor, 1000 Ljubljana, Slovenia",
    "Sončni Studio Diamant - Letališka cesta 5, 1000 Ljubljana, Slovenia",
    "Maxisport trženje športnih Artiklov, d.o.o., Ljubljana, Šmartinska 211 - Šmartinska c. 211, 1000 Ljubljana, Slovenia",
    "Kozmetični salon Neguj.se 👩 - Tacenska cesta 108, 1000 Ljubljana, Slovenia",
    "BARBARELLA JUICEBAR - Slovenska cesta 38, 1000 Ljubljana, Slovenia",
    "Pleskarska dela, Darko Vindiš s.p. - Cesta v Pečale 17, 1231 Ljubljana - Črnuče, Slovenia",
  };
}
