class AutoSuggestions90671291 {
  static final reviewedTitles90671291 = const {
    "Joyas Juan del Gaudio - Av. Libertador. Multicentro Empresarial del Este, Local 20. Nivel Miranda, Caracas 1060, Miranda, Venezuela",
    "Fotocopias Marbelia, C.A - Calle Miranda, Casa N° 24-10, Local 1, Barrio Sucre, La Cañada, Caracas 1030, Distrito Capital, Venezuela",
    "Kiosko Raysol - Calle Nicolas Copernico &amp;, Avenida Principal de las Mercedes, Caracas 1080, Miranda, Venezuela",
    "AMD Computer Shop - G33M+R4M, Caracas 1014, Capital District, Venezuela",
    "Comercializadora somos sazón k.y,c.a - F3WJ+CH9, Caracas 1014, Capital District, Venezuela",
    "Foto Relampago C.A. - Edificio Plaza Miranda, Torre A, Nivel PB, Local 9, Av Baralt, Zona Postal, con Av. Oeste 8 Bis, Caracas 1010, Distrito Capital, Venezuela",
    "Inv. Di-Quesos 2000 - Avenida Sur 2, entre esquina de Hospital a Cárcel, Edif. Belmonte, planta baja, Local 1 Av Sur 2, Caracas 1014, Distrito Capital, Venezuela",
    "MOTORCYCLES LOS ANDES C.A - Prolongacion de la 5ta avenida , edificio Maxicol local 1 al lado de bicicletas, al M. Publico, 5ta. Av &quot;Francisco García de Hevia&quot;, San Cristóbal 5001, Táchira, Venezuela",
    "Kiosko lorena - Calle abanico a socorro frente a la residencia el dorado diagonal a pdval Parroquia Altagracia diagonal a la, Avenida Fuerzas Armadas, Caracas 1020, Distrito Capital, Venezuela",
    // "Joyas Juan del Gaudio - Av. Libertador. Multicentro Empresarial del Este, Local 20. Nivel Miranda, Caracas 1060, Miranda, Venezuela",
    "Kiosco Ortega- M - Esquina de Perico a San Lazaro.. Av Universidad. Mercado La Hoyada, Pasillo ARAGUA, local 940 941, Caracas 1011, Avenida Universidad, Caracas 1011, Distrito Capital, Venezuela",
    "Santa Barbara, C.A - Avenida Baralt, entre calle Maderero y Calle Miranda, Edificio Miranda, Nivel PB, Local A, G32J+4H7, Caracas 1014, Distrito Capital, Venezuela",
    "Emprendedora Jj 2017, C.A - Avenida Principal de las Mercedes, Kiosco N°13, con C. Mucuchíes, Caracas 1080, Miranda, Venezuela",
    "Cafetin con sabor chacaro - Calle 5 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "Auto repuestos Canmar - Calle5, San Cristóbal 5001, Táchira, Venezuela",
    "Inversiones García Guzman, C.A. - Av. Universidad, con Av Baralt, Esquina de Pedrera, Galerías José Antonio Páez, P.B, Local 1, Diagonal al C.C. Metro Center, Capitolio, Caracas 1012, Caracas 1012, Distrito Capital, Venezuela",
    "Quincalla y Ferretería Zapata, C.A. - Calle Ayacucho, Cruce con Calle Miranda, P.B, Casa n° 23-10, Local 1, Frente a la Redoma del Bloque 7, La Cañada, Caracas 1030, Distrito Capital, Venezuela",
    "Mini Market DS, C.A - J263+346, Maiquetía 1162, Vargas, Venezuela",
    "TecnoLion MerpoEste - Centro Comercial MerpoEste, C. Los Ángeles, Caracas 1064, Distrito Capital, Venezuela",
    "Burger Center - Centro Comercial Metrocenter Nivel Amarillo Local PA-07, Caracas 1012, Distrito Capital, Venezuela",
    "La botanita mexicana - Av. Baralt con esquina pedrera, cc metrocenter, nivel colonial, paseo colonial, local mp29, Av. Baralt, Caracas 1012, Distrito Capital, Venezuela",
    "Andina Venezolana del Repuesto - QQ48+W8Q, Carrera 6 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "INVERSIONES ARANGO TECHNOLOGY C,A - CHACAO MULTICENTRO EMPRESARIAL DEL ESTE TORRE MIRANDA NUCLEO A LOCAL PB 10 GRAN CARACAS, Caracas 1060, Miranda, Venezuela",
    "Blue Store - Calle Chico Carrasquel con Calle Los Angeles. Local 46, Nivel PB. 1060, Caracas 1064, Miranda, Venezuela",
    "Mamro Cell - local 27, Centro comercial Plaza, Caracas 1011, Distrito Capital, Venezuela",
    "Maison Plaza - F5W3+JQR, Caracas 1060, Miranda, Venezuela",
    "V58 Store City Market 4 - C.C City Market, Nivel PB, Local Arca, N° 456 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Mr.ShopCcs - C.C. Metrocenter Pasaje Contemporáneo, Local MT08 Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Kiosko Restaurant mi Rinconcito - Playa Candilejas, Calle Real De Playa Verde, Maiquetía 1162, La Guaira, Venezuela",
    "Frigorífico El Imperio del Pollo - JX26+586, Avenida El Ejército, Catia La Mar 1162, Vargas, Venezuela",
    "Kiosko restaurant Oshun - Playa Culito, Calle Real De Playa Verde, Maiquetía 1162, La Guaira, Venezuela",
    "Autopartes Bencarmotor - QQ48+85Q, Calle 6, San Cristóbal 5001, Táchira, Venezuela",
    "Inversiones Cleoribet, C.A. - Av. Baralt, Esquina de Pedrera, Centro Comercial Galerías Capitolio, PB, Local P6F2, Capitolio, Caracas 1030, Caracas 1012, Distrito Capital, Venezuela",
    "Di Catia Pizza,C.A. - 2da Avenida, Entre Boulevar España y Calle Colombia, Quinta Corazón de Jesús, Local 1, Caracas 1030, Distrito Capital, Venezuela",
    "Repuestos Guayas Car's - QQ48+C5C, Carrera 6 Bis, San Cristóbal 5001, Táchira, Venezuela",
    "Mesón de Pita Restaurante - F4RW+XC8, Caracas 1060, Miranda, Venezuela",
    "Molise Bistro - Centro, Caracas 1012, Caracas 1012, Caracas 1012 Edificio Carmo Caracas, Caracas 1012, Distrito Capital, Venezuela",
    "Perfumescss Metrocenter - Centro comercial metrocenter nivel avenida local pb-2 Caracas, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones Tocoquera 2021, C.A. - F3WJ+WQP, Caracas 1014, Capital District, Venezuela",
    // "Inversiones Tocoquera 2021, C.A. - F3WJ+WQP, Caracas 1014, Capital District, Venezuela",
    "PC MANIA, C.A. - Av. Francisco de Miranda, Multicentro Empresarial del Este, Edif. Central Planta Baja, Local PB-24, Caracas 1060, Miranda, Venezuela",
  };
}
