class AutoSuggestions40383361 { static final reviewedTitles40383361 = const {"Beluga House - Calle California, Caracas 1060, Miranda, Venezuela",
"Grupo Zoom - Final Av. Principal, Qta. Grupo Zoom, Bello Campo, Caracas, F4RX+8HQ, Caracas 1060, Miranda, Venezuela",
"Panadería Y Pastelería Perimetral 2013 C.A. - MQF5+35M, Carúpano 6150, Sucre, Venezuela",
"Mookah Restaurant & Lounge - Av. Intercomunal La Trinidad - El Hatillo C.C. Trinidad Tepuy Caracas, Caracas 1081, Miranda, Venezuela",
"Frenos y Silenciadores Maxituning C.A. - entre calles 30 y 31, 30-45 Av. Don Tulio Febres Cordero, Mérida 5101, Mérida, Venezuela",
"Bodca Bodegón - C.C. Alto Prado, Av. Los Próceres, Mérida 5101, Mérida, Venezuela",
"MT MARKETING - Calle Jesús María Patiño con Calle Ortega, Local 7. Porlamar, Isla de Margarita., Calle Ortega, Porlamar 6301, Nueva Esparta, Venezuela",
"Algo Rico. Inversiones Jorge Madriz F.P - Calle Paez a una cuadra del Bco de Vzla, Tinaquillo 2209, Cojedes, Venezuela",
"Inversiones Todo Oficina Y Computación C.A. - Esquina de Candilito a Cruz de Candelaria, G34V+9W4, Caracas 1011, Distrito Capital, Venezuela",
"Soluciones Tecnológicas Venepos - Torre Cari, 2da Avenida Campo Alegre, Caracas 1060, Distrito Capital, Venezuela",
"CAM SOLUCIONES C.A - BOLEITA SUR, AV. FRANCISCO DE MIRANDA, CENTRO SEGUROS LA PAZ, Caracas 1050, Miranda, Venezuela",
"Representaciones Abanet CA - Av. Monseñor Pellin, Centro Comercial El Colonial, Planta Alta, Oficina, 43, Cúa 1211, Miranda, Venezuela",
"Spa Enza Martino - Centro Integral Santa Rosa, Calle A, PS, Local PS, 8, Caracas 1060, Miranda, Venezuela",
"Auto Repuestos Glenda, c.a. - Segunda Avenida entre calles 7 y 8 Local 1 Sector Cantarrana, San Felipe 3201, Yaracuy, Venezuela",
"TEMACO PUNTO FIJO - Punto Fijo 4102, Falcón, Venezuela",
"Ferre Técnicos Camperos - Sucursal, avenida cirilo agvis sector, Romulo Gallegos, El Nula 5032, Apure, Venezuela",
"Farmarket - Av. Francisco de Miranda, C.C. Lido, Nivel Miranda Local M41, Caracas 1060, Miranda, Venezuela",
"Farmarket - Av. Ppal. de Chuao C.C. Ciudad Tamanaco Nivel C-1 Local 47-H-7, Caracas 1061, Miranda, Venezuela",
"Farmarket - Calle Acuario, C.C. Santa Paula Nivel PB Locales 1,2,3, Urb. Leoncio Martínez, Caracas 1061, Miranda, Venezuela",
"SGC Consultores C.A. - Sector, #99-13 Avenida 87 Uslar, Valencia 2001, Carabobo, Venezuela",
"Xinestesia Bodegón - CC Los Chaguaramos #35, Av. Ezio Valeri, Mérida 5101, Mérida, Venezuela",
"Inversiones VidaCell, C.A - C. Villaflor, Caracas 1052, Distrito Capital, Venezuela",
"Sánchez Solutions - Avenida 3 Independencia entre Calle 20 y 21, Torre Empresarial Gran Mundo Oficina 7-2, Mérida 5101, Mérida, Venezuela",
};
}
