class AutoSuggestions79160504 {
  static final reviewedTitles79160504 = const {
    "Big Bang Kamnik, Qlandia - Domžalska cesta 3, 1241 Kamnik, Slovenia",
    "Qulto :: qoffee & qulinaris - Slovenska ulica 9, 2000 Maribor, Slovenia",
    "Zavod naravni zdravilni Gaj Tunjice - Tunjice 12, 1241 Kamnik, Slovenia",
    "AcuModerna - reopens end of May, June 2020 - Vipavska cesta 23a, 5000 Nova Gorica, Slovenia",
    "Ošterija pri oljki - Šmartinska c. 152g, 1000 Ljubljana, Slovenia",
    "Big Bang - Otoška cesta 5 Nakupovalni center Qlandia, 8000 Novo mesto, Slovenia",
    "Big Bang Ljubljana, Rudnik - Park Center - Jurčkova Cesta 228, 1000 Ljubljana, Slovenia",
    "Big Bang Nova Gorica, Qlandia - Cesta 25. junija 1a Nakupovalni center Qlandia, 5000 Nova Gorica, Slovenia",
    "Big Bang - Cesta krških žrtev 141, 8270 Krško, Slovenia",
    "Big Bang Slovenj Gradec, Qlandia - Francetova cesta 16, 2380 Slovenj Gradec, Slovenia",
    "Sportina Group - Sportina Outlet - Jalnova cesta 2, 4240 Radovljica, Slovenia",
    "Big Bang - Mariborska cesta 100, 3000 Celje, Slovenia",
// "Big Bang - Mariborska cesta 100, 3000 Celje, Slovenia",
    "Big Bang Ptuj - Ormoška 15 Nakupovalni center Qlandia, 2250 Ptuj, Slovenia",
    "SkyEye Bitcoin ATM - Gasilska ulica 10, 1292 Ig, Slovenia",
    "Big Bang Kranj, Stop Shop - Cesta Staneta Žagarja 71, 4000 Kranj, Slovenia",
    "Big Bang - Pobreška cesta 18, 2000 Maribor, Slovenia",
    "The Fifth Element studio - Barjanska cesta 62, 1000 Ljubljana, Slovenia",
    "Big Bang Jesenice - Fužinska cesta 8, 4270 Jesenice, Slovenia",
    "Tuš supermarket C&C Sežana - Partizanska c. 71, 6210 Sežana, Slovenia",
    "Tuš supermarket Žalec - Ulica heroja Staneta 8, 3310 Žalec, Slovenia",
    "Tuš supermarket Planet Maribor - Studenci - Na Poljanah 18, 2000 Maribor, Slovenia",
    "Tuš supermarket Rače - Ljubljanska cesta 13, 2327 Rače, Slovenia",
    "Marella - Miklošičeva cesta 1, 1000 Ljubljana, Slovenia",
  };
}
