class Suggestions {
  static final locations = const {
    'Europe, europe, continent',
    'Germany - Europe, e-ger, state',
    'Berlin - Germany - Europe, e-ger-ber, city',
    'Spain - Europe, e-spa, state',
    'Barcelona - Spain - Europe, e-spa-bar, city',
    'Benidorm',
    'Tarifa',
    'France',
    'Paris',
    'England',
    'London',
    'Holywell',
    'Rhos on Sea',
    'Brackley',
    'Norway',
    'Bergen', 'Sweden', 'Göteborg', 'Rychnov nad Kněžnou', 'Czechia', 'Piran',
    'Slovenia', 'Yerevan', 'Armenia', 'Yaroslavl',
    'America',
    'Venezuela', 'Caracas', 'Maracaibo', 'Puerto la Cruz', 'Catia La Mar',
    'El Parmazo', 'Acarigua', 'San Cristobal',
    'Columbia',
    'Popayan',
    'Belize',
    'Hopkins',
    'Unitedville',
    'Mexico',
    'Tabasco',
    'Villahermosa',
    'Dominican Republic',
    'Santo Domingo',
    'Canada',
    'Saint Stephen',
    'New Hampshire',
    'Alstead',
    'Portsmouth',
    'Virginia',
    'Norfolk',
    'New York',
    'NYC',
    'California',
    'San Jose',
    'Los Angeles',
    'Florida',
    'Orlando',
    'Wisconsin',
    'Madison', 'Milwaukee', 'Wyoming', 'Sheridan', 'Utah', 'Salt Lake City',
    'Toronto',
    'USA',
    'Colorado',
    'Asia',
    'Indonesia', 'Bali', 'Singapore', 'Philippines', 'Manila', 'Thailand',
    'Pattaya', 'Bangkok', 'Chiang May',
    'Japan',
    'Tokyo',
    'Osaka', 'Fukuoka', 'Nagasaki', 'Samoa', 'Apia', 'Russia',
    'Australia', 'Gold Coast', 'Melbourne', 'Sidney', 'Nelson Bay',
    'Christchurch', 'Byron Bay', 'Brisbane',
    'Queensland', 'Agnes Water', 'Aitkenvale', 'Townsville', 'Cairns', 'Perth',
    'Africa',
  };
}
