class Tag {
  final String content;
  final int id;

  Tag(this.content, this.id);

  static final List<List<Tag>> tagsSortedByCategory = [
    [
      Tag('Sweet 🍭', 142),
      Tag('Spicey 🌶️', 0),
      Tag('Salty 🥨', 1),
      Tag('Sour 😜', 2)
    ],
    [
      Tag('Italian 🇮🇹', 102),
      Tag('Arabic 🥙', 13),
      Tag('Chinese 🇨🇳', 34),
      Tag('Vegan 🐮', 5),
      Tag('Mexican 🇲🇽', 128),
      Tag('Greek 🇬🇷', 154),
    ],
    [
      Tag('Falafel 🥙', 44),
      Tag('Salad 🥗', 15),
      Tag('Fruit 🍓', 17),
      Tag('Burger 🍔', 7),
      Tag('Sandwich 🥪', 8),
      Tag('Burrito 🌯', 129),
      Tag('Tortilla 🌮', 130)
    ],
    [
      Tag('Muffin 🧁', 9),
      Tag('Brownie 🥮', 10),
      Tag('Cake 🎂', 11),
      Tag('Cookie 🍪', 12)
    ],
    [
      Tag('Smoothie 🥤', 16),
    ],
    [
      Tag('Duck 🍱', 35),
    ],
    [
      Tag('Healthy 💓', 6),
    ]
  ];

  static int findTagIndex(String tag) {
    for (int i = 0; i < tagText.length; i++) {
      String item = tagText.elementAt(i);
      if (item == tag) {
        return i;
      }
    }
    return -1;
  }

  //Only if the tag is totally unused, that means there are zero results when searching inside the app, then it can be replaced by another tag

  static final tagText = const {
    'Spicey 🌶️', //0
    'Salty 🥨',
    'Sour 😜',
    'Organic 🐵',
    'Vegetarian 🥕', //4
    'Vegan 🐮',
    'Healthy 💓',
    'Burger 🍔',
    'Sandwich 🥪',
    'Muffin 🧁', //9 The muffin icon is invisible
    'Brownie 🥮', //10 Brownie is invisible too
    'Cake 🎂',
    'Cookie 🍪',
    'Arabic 🥙',
    'Pizza 🍕', //14
    'Salad 🥗',
    'Smoothie 🥤',
    'Fruit 🍓',
    'IceCream 🍦',
    'Raw 🥦', //19
    'Handbag 👜',
    'Cosmetic 💅',
    'Tattoo ♣',
    'Piercing 🌀',
    'Souvenir 🎁', //24
    'Hatha 🧘',
    'Vinyasa 🧘',
    'Massage 💆',
    'Upcycled 🌲',
    'Coffee ☕', //29
    'NoGluten 🌽',
    'Cocktails 🍹',
    'Beer 🍺',
    'Music 🎵',
    'Chinese 🍜', //34
    'Duck 🍱',
    'Rock 🎸',
    'LiveDJ 🎧',
    'Terrace ☀️',
    'Seeds 🌱', //39
    'Grinder 🍌',
    'Papers 🚬',
    'Advice 🌴',
    'Calzone 🥟',
    'Falafel 🥙', //44
    'MakeUp 🤡',
    'Gifts 🎁',
    'Tapas 🍠',
    'Copas 🍹',
    'Piadina 🌮', //49
    'Cheese 🧀',
    'Grains 🌾',
    'Fashion 👗',
    'Fair 🤗',
    'Women 👩', //54
    'Drinks 🍹',
    'TV 📺',
    'Retro 🦄',
    'Feta 🐐',
    'DASH ₿', //59
    'BTC ₿',
    'BCH ₿',
    'BSV ₿',
    'ETH ₿',
    'HotDog 🌭', //64
    'Fast ⏩',
    'Kosher 🦄',
    'Sushi 🍣',
    'Moto 🛵',
    'Coche 🚘', //69
    'LTC ₿',
    'Chicken 🐔',
    'Rabbit 🐰',
    'Potato 🥔',
    'Kumpir 🥔', //74
    'Kebap 🐄',
    'ATM 🏦',
    'Gyros 🐖',
    'Coconut 🥥',
    'ToGo 📦', //79
    'Meditation 🧘',
    'Wine 🍷',
    'Champagne 🥂',
    'Alcohol 🍾',
    'Booze 🥃', //84
    'Pancakes 🥞', //You cant remove because we use fixed indexes, but replace with another string that is unlikely to be typed in by the user
    'Croissant 🥐',
    'Popcorn 🍿',
    'SoftIce 🍦',
    'Dango 🍡',
    'BnB 🛏️', //90
    'Haircut ✂️',
    'Candy 🍭',
    'Beauty 💅',
    'Miso 🍱',
    'Chocolate 🍫', //95
    'Rice 🍚',
    'Seafood 🦀',
    'Hostel 🛏️',
    'Fries 🍟',
    'Fish 🐟', //100
    'Chips 🍟',
    'Italian 🇮🇹',
    'Whiskey 🥃',
    'Rum 🥃', //This is number 104 the no tag indicator, currently not used
    'Bourbon 🥃', //105
    'Liquor 🥃',
    'Men ♂️',
    'Pasta 🍝',
    'Dessert 🍬', //109
    'Starter 🥠', //110
    'BBQ 🍗',
    'Noodle 🍜',
    'Korean 🥟',
    'Market 🧺', //114 invisible item
    'Bread 🥖',
    'Bakery 🥨',
    'Cafe ☕',
    'Games 🎮',
    'Snacks 🍿', //119
    'Elegant 🕴️',
    'Piano 🎹',
    'Brunch 🍱',
    'Nachos 🌽',
    'Lunch 🥡',
    'Breakfast 🥐', //125
    'HappyHour 🥳', //hidden item
    'LateNight 🌜',
    'Mexican 🇲🇽',
    'Burrito 🌯',
    'Tortilla 🌮', //130
    'Indonesian 🇮🇩',
    'Sports 🏆',
    'Pastry 🥧',
    'Bistro 🍲',
    'Soup 🥣', //135
    'Tea 🍵',
    'Onion',
    'Steak 🥩',
    'Shakes 🥤',
    'Empanadas 🥟', //140
    'Dinner 🍽️',
    'Sweet 🍭',
    'Fried 🍳',
    'Omelette 🥚',
    'Gin 🍸', //145
    'Donut 🍩',
    'Delivery 🚚',
    'Cups ☕',
    'Filter',
    'Juice 🍊', //150
    'Vietnamese 🇻🇳',
    'Pie 🥮', //invisible item
    'Unagi 🐡',
    'Greek 🇬🇷',
    'Japanese 🇯🇵', //155
    'Tacos 🌮',
    'Kombucha 🍵',
    'Indian 🇮🇳',
    'Nan 🥪', //
    'Club 🎶', //160
    'Honey 🍯',
    'Pool 🎱',
    'Hotel 🏨',
    'Pork 🥓',
    'Ribs 🍖', //165
    'Kava 🍵',
    'Chai 🍵',
    'Izzy 🍵',
    'Matcha 🍵',
    'Oden 🍢', //170
    'Latte ☕'
  };

  static final tagTextJP1 = const {
    'スパイシー🌶️',
    '塩味の🥨',
    '酸っぱい😜',
    'オーガニック🐵',
    'ベジタリアン🥕',
    'ビーガン🐮',
    '健康💓',
    'バーガー🍔',
    'サンドイッチ🥪',
    'マフィン🧁',
    'ブラウニー🥮',
    'ケーキ🎂',
    'クッキー🍪',
    'アラビア語',
    'ピザ🍕',
    'サラダ🥗',
    'スムージー🥤',
    'フルーツ🍓',
    'IceCream🍦',
    '生🥦',
    'ハンドバッグ,',
    '化粧品💅',
    'タトゥー♣',
    'ピアス🌀',
    'お土産'
        'ハタ🧘',
    'ヴィンヤサ🧘',
    'マッサージ💆',
    'アップサイクル🌲',
    'コーヒー☕',
    'NoGluten🌽',
    'カクテル🍹',
    'ビール🍺',
    'ミュージック🎵',
    '中国語🍜',
    'アヒル🍱',
    'ロック🎸',
    'LiveDJ🎧',
    'テラス☀️',
    '種子🌱',
    'グラインダー🍌',
    '論文🚬',
    'アドバイス🌴',
    'カルゾーン🥟',
    'ファラフェル🥙',
    'MakeUp🤡',
    'ギフト🎁',
    'タパス🍠',
    'コパス🍹',
    'Piadina🌮',
    'チーズ🧀',
    '穀物🌾',
    'ファッション👗',
    'フェア🤗',
    '女性👩',
    '飲み物🍹',
    'テレビ📺',
    'レトロ🦄',
    'Feta🐐',
    'DASH₿',
    'BTC₿',
    'BCH₿',
    'BSV₿',
    'ETH,',
    'HotDog🌭',
    '速い⏩',
    'コーシャー',
    '寿司🍣',
    'モト🛵',
    'コシェ🚘',
    'LTC₿',
    'チキン🐔',
    'うさぎ🐰',
    'じゃがいも🥔',
    'Kumpir🥔',
    'ケバプ🐄',
    'ATM🏦',
    'ジャイロ🐖',
    'ココナッツ🥥',
    'ToGo📦',
    '瞑想🧘',
    'ワイン🍷',
    'シャンパン'
        'アルコール🍾',
    '酒o',
    'パンケーキ🥞',
    'クロワッサン',
    'ポップコーン🍿',
    'SoftIce🍦',
    'Dango🍡',
    'BnB🛏️',
    'ヘアカット✂️',
    'キャンディ🍭',
    '美しさ💅',
    'みそ🍱',
    'チョコレート🍫',
    '米🍚',
    'シーフード🦀',
    'ホステル🛏️',
    'フライドポテト',
    '魚🐟',
    'チップ'
        'イタリア語🇮🇹',
    'ウイスキー🥃',
    'ラム🥃',
    'ブルボン🥃',
    '酒🥃',
    'メン♂️',
    'パスタ🍝',
    'デザート🍬',
    'スターター🥠',
    'バーベキュー',
    '麺',
    '韓国語🥟',
    'マーケット🧺',
    'パン🥖',
    'パン屋さん',
    'カフェ☕',
    'ゲーム',
    'スナック🍿',
    'エレガント🕴️',
    'ピアノ🎹',
    'ブランチ🍱',
    'ナチョス',
    'ランチ🥡',
    '朝食🥐',
    'HappyHour🥳',
    'LateNight🌜',
    'メキシカン🇯🇽',
    'ブリトー🌯',
    'トルティーヤ🌮',
    'インドネシア語🇮🇩',
    'スポーツ🏆',
    'ペストリー🥧',
    'ビストロ🍲',
    'スープ🥣',
    'お茶'
        '玉ねぎ',
    'ステーキ🥩',
    'シェイク🥤',
    'Empanadas🥟',
    '夕食🍽️',
    '甘い🍭',
    '揚げ🍳',
    'オムレツ🥚',
    'ジン🍸',
    'ドーナツ🍩',
    '配達',
    'カップ☕',
    'フィルタ',
    'ジュース🍊',
    'ベトナム語🇻🇳',
    'パイ🥮',
    'うなぎ🐡',
    'ギリシャ語🇬🇷',
    '日本の🇯🇵',
    'タコス🌮',
    'こんぶちゃ',
    'インド🇮🇳',
    '南🥪',
    'クラブ🎶',
    'ハニー🍯',
    'プール🎱',
    'ホテル🏨',
    '豚肉',
    'リブ🍖',
    'カバ🍵',
    'チャイ',
    'イジー🍵',
    '抹茶🍵',
    'おでん🍢',
    'ラテ☕'
  };
  /*
  static final tagTextJP1 = const {
    'Spicy 🌶️',
    'Salty 🥨',
    'Sour 😜',
    'Organic 🐵',
    'Vegetarian 🥕',
    'Vegan 🐮',
    'Healthy 💓',
    'Burger 🍔',
    'Sandwich 🥪',
    'Muffin 🧁',
    'Brownie 🥮',
    'Cake 🎂',
    'Cookie 🍪',
    'Arabic 🥙',
    'Pizza 🍕',
    'Salad 🥗',
    'Smoothie 🥤',
    'Fruit 🍓',
    'IceCream 🍦',
    'Raw 🥦',
    'Handbag 👜',
    'Cosmetic 💅',
    'Tattoo ♣',
    'Piercing 🌀',
    'Souvenir 🎁',
    'Hatha 🧘',
    'Vinyasa 🧘',
    'Massage 💆',
    'Upcycled 🌲',
    'Coffee ☕',
    'NoGluten 🌽',
    'Cocktails 🍹',
    'Beer 🍺',
    'Music 🎵',
    'Chinese 🍜',
    'Duck 🍱',
    'Rock 🎸',
    'LiveDJ 🎧',
    'Terrace ☀️',
    'Seeds 🌱',
    'Grinder 🍌',
    'Papers 🚬',
    'Advice 🌴',
    'Calzone 🥟',
    'Falafel 🥙',
    'MakeUp 🤡',
    'Gifts 🎁',
    'Tapas 🍠',
    'Copas 🍹',
    'Piadina 🌮',
    'Cheese 🧀',
    'Grains 🌾',
    'Fashion 👗',
    'Fair 🤗',
    'Women 👩',
    'Drinks 🍹',
    'TV 📺',
    'Retro 🦄',
    'Feta 🐐',
    'DASH ₿',
    'BTC ₿',
    'BCH ₿',
    'BSV ₿',
    'ETH ₿',
    'HotDog 🌭',
    'Fast ⏩',
    'Kosher 🦄',
    'Sushi 🍣',
    'Moto 🛵',
    'Coche 🚘',
    'LTC ₿',
    'Chicken 🐔',
    'Rabbit 🐰',
    'Potato 🥔',
    'Kumpir 🥔',
    'Kebap 🐄',
    'ATM 🏦',
    'Gyros 🐖',
    'Coconut 🥥',
    'ToGo 📦',
    'Meditation 🧘',
    'Wine 🍷',
    'Champagne 🥂',
    'Alcohol 🍾',
    'Booze 🥃',
    'Pancakes 🥞',
    'Croissant 🥐',
    'Popcorn 🍿',
    'SoftIce 🍦',
    'Dango 🍡',
    'BnB 🛏️',
    'Haircut ✂️',
    'Candy 🍭',
    'Beauty 💅',
    'Miso 🍱',
    'Chocolate 🍫',
    'Rice 🍚',
    'Seafood 🦀',
    'Hostel 🛏️',
    'Fries 🍟',
    'Fish 🐟',
    'Chips 🍟',
    'Italian 🇮🇹',
    'Whiskey 🥃',
    'Rum 🥃',
    'Bourbon 🥃',
    'Liquor 🥃',
    'Men ♂️',
    'Pasta 🍝',
    'Dessert 🍬',
    'Starter 🥠',
    'BBQ 🍗',
    'Noodle 🍜',
    'Korean 🥟',
    'Market 🧺',
    'Bread 🥖',
    'Bakery 🥨',
    'Cafe ☕',
    'Games 🎮',
    'Snacks 🍿',
    'Elegant 🕴️',
    'Piano 🎹',
    'Brunch 🍱',
    'Nachos 🌽',
    'Lunch 🥡',
    'Breakfast 🥐',
    'HappyHour 🥳',
    'LateNight 🌜',
    'Mexican 🇲🇽',
    'Burrito 🌯',
    'Tortilla 🌮',
    'Indonesian 🇮🇩',
    'Sports 🏆',
    'Pastry 🥧',
    'Bistro 🍲',
    'Soup 🥣',
    'Tea 🍵',
    'Onion',
    'Steak 🥩',
    'Shakes 🥤',
    'Empanadas 🥟',
    'Dinner 🍽️',
    'Sweet 🍭',
    'Fried 🍳',
    'Omelette 🥚',
    'Gin 🍸',
    'Donut 🍩',
    'Delivery 🚚',
    'Cups ☕',
    'Filter',
    'Juice 🍊',
    'Vietnamese 🇻🇳',
    'Pie 🥮',
    'Unagi 🐡',
    'Greek 🇬🇷',
    'Japanese 🇯🇵',
    'Tacos 🌮',
    'Kombucha 🍵',
    'Indian 🇮🇳',
    'Nan 🥪',
    'Club 🎶',
    'Honey 🍯',
    'Pool 🎱',
    'Hotel 🏨',
    'Pork 🥓',
    'Ribs 🍖',
    'Kava 🍵',
    'Chai 🍵',
    'Izzy 🍵',
    'Matcha 🍵',
    'Oden 🍢',
    'Latte ☕'
  };*/
  //TODO capitalize the first letter?! during output?
  static final tagTextJP2 = const {
    'supaishī 🌶️ ',
    'shioaji no 🥨',
    'suppai 😜',
    'ōganikku 🐵',
    'bejitarian 🥕',
    'bīgan 🐮',
    'kenkō 💓',
    'bāgā 🍔',
    'sandoitchi 🥪',
    'mafin 🧁',
    'buraunī 🥮',
    'kēki 🎂',
    'kukkī 🍪',
    'Arabia-go',
    'piza 🍕',
    'sarada 🥗',
    'sumūjī 🥤',
    'furūtsu 🍓',
    'IceCream 🍦',
    '-sei 🥦',
    'handobaggu,',
    'keshōhin 💅',
    'tato~ū ♣',
    'piasu 🌀',
    'odosan',
    'Hata 🧘',
    'vu~inyasa 🧘',
    'massāji 💆',
    'appu saikuru 🌲',
    'kōhī ☕',
    'NoGluten 🌽',
    'kakuteru 🍹',
    'bīru 🍺',
    'myūjikku 🎵',
    'chūgokugo 🍜',
    'ahiru 🍱',
    'rokku 🎸',
    'LiveDJ 🎧',
    'terasu ☀ ️ ',
    'shushi 🌱',
    'guraindā 🍌',
    'ronbun 🚬',
    'adobaisu 🌴',
    'karuzōn 🥟',
    'faraferu 🥙',
    'MakeUp 🤡',
    'gifuto 🎁',
    'tapasu 🍠',
    'kopasu 🍹',
    'piadīna 🌮',
    'chīzu 🧀',
    'kokumotsu 🌾',
    'fasshon 👗',
    'fea 🤗',
    'josei 👩',
    'nomimono 🍹',
    'terebi 📺',
    'Retoro 🦄',
    'feta 🐐',
    'dasshu ₿',
    'BTC ₿',
    'BCH ₿',
    'BSV ₿',
    'ETH,',
    'HotDog 🌭',
    'hayai ⏩',
    'kōshā',
    'sushi 🍣',
    'Moto 🛵',
    'koshe 🚘',
    'LTC ₿',
    'chikin 🐔',
    'usagi 🐰',
    'jagaimo 🥔',
    'Kumpir 🥔',
    'kebapu 🐄',
    'ATM 🏦',
    'jairo 🐖',
    'kokonattsu 🥥',
    'ToGo 📦',
    'meisō 🧘',
    'wain 🍷',
    'shanpan' 'arukōru 🍾',
    '-shu o',
    'pankēki 🥞',
    'kurowassan',
    'poppukōn 🍿',
    'SoftIce 🍦',
    'Dango 🍡',
    'BnB 🛏️ ',
    'hea katto ✂ ️ ',
    'kyandi 🍭',
    'utsukushi-sa 💅',
    'miso 🍱',
    'chokorēto 🍫',
    'Amerika 🍚',
    'shīfūdo 🦀',
    'hosuteru 🛏️ ',
    'furaidopoteto',
    '-gyo 🐟',
    'chippu' 'Itaria-go 🇮🇹',
    'uisukī 🥃',
    'ramu 🥃',
    'Burubon 🥃',
    'sake 🥃',
    'men ♂ ️ ',
    'pasuta 🍝',
    'dezāto 🍬',
    'sutātā 🥠',
    'bābekyū',
    'men',
    'Kankoku-go 🥟',
    'māketto 🧺',
    'pan 🥖',
    'panyasan',
    'kafe ☕',
    'gēmu',
    'sunakku 🍿',
    'ereganto 🕴️ ',
    'piano 🎹',
    'buranchi 🍱',
    'nachosu',
    'ranchi 🥡',
    'chōshoku 🥐',
    'HappyHour 🥳',
    'LateNight 🌜',
    'mekishikan 🇯🇽',
    'buritō 🌯',
    'torutīya 🌮',
    'Indoneshia-go 🇮🇩',
    'supōtsu 🏆',
    'pesutorī 🥧',
    'bisutoro 🍲',
    'sūpu 🥣',
    'ocha',
    'tamanegi',
    'sutēki 🥩',
    'Sheiku 🥤',
    'Empanadas 🥟',
    'yūshoku 🍽️ ',
    'amai 🍭',
    '-age 🍳',
    'omuretsu 🥚',
    'Jin 🍸',
    'dōnatsu 🍩',
    'haitatsu',
    'kappu ☕',
    'firuta',
    'jūsu 🍊',
    'Betonamu-go 🇻🇳',
    'pai 🥮',
    'unagi 🐡',
    'Girisha-go 🇬🇷',
    'Nihon no 🇯🇵',
    'takosu 🌮',
    'konbucha',
    'Indo 🇮🇳',
    'minami 🥪',
    'kurabu 🎶',
    'hanī 🍯',
    'pūru 🎱',
    'hoteru 🏨',
    'butaniku',
    'ribu 🍖',
    'kaba 🍵',
    'Chai',
    'ijī 🍵',
    'matcha 🍵',
    'oden 🍢',
    'rate ☕'
  };
  static final tagTextINDONESIA = const {
    'Spicey 🌶️', //0
    'Salty 🥨',
    'Sour 😜',
    'Organic 🐵',
    'Vegetarian 🥕', //4
    'Vegan 🐮',
    'Healthy 💓',
    'Burger 🍔',
    'Sandwich 🥪',
    'Muffin 🧁', //9 The muffin icon is invisible
    'Brownie 🥮', //10 Brownie is invisible too
    'Cake 🎂',
    'Cookie 🍪',
    'Arabic 🥙',
    'Pizza 🍕', //14
    'Salad 🥗',
    'Smoothie 🥤',
    'Fruit 🍓',
    'IceCream 🍦',
    'Raw 🥦', //19
    'Handbag 👜',
    'Cosmetic 💅',
    'Tattoo ♣',
    'Piercing 🌀',
    'Souvenir 🎁', //24
    'Hatha 🧘',
    'Vinyasa 🧘',
    'Massage 💆',
    'Upcycled 🌲',
    'Coffee ☕', //29
    'NoGluten 🌽',
    'Cocktails 🍹',
    'Beer 🍺',
    'Music 🎵',
    'Chinese 🍜', //34
    'Duck 🍱',
    'Rock 🎸',
    'LiveDJ 🎧',
    'Terrace ☀️',
    'Seeds 🌱', //39
    'Grinder 🍌',
    'Papers 🚬',
    'Advice 🌴',
    'Calzone 🥟',
    'Falafel 🥙', //44
    'MakeUp 🤡',
    'Gifts 🎁',
    'Tapas 🍠',
    'Copas 🍹',
    'Piadina 🌮', //49
    'Cheese 🧀',
    'Grains 🌾',
    'Fashion 👗',
    'Fair 🤗',
    'Women 👩', //54
    'Drinks 🍹',
    'TV 📺',
    'Retro 🦄',
    'Feta 🐐',
    'DASH ₿', //59
    'BTC ₿',
    'BCH ₿',
    'BSV ₿',
    'ETH ₿',
    'HotDog 🌭', //64
    'Fast ⏩',
    'Kosher 🦄',
    'Sushi 🍣',
    'Moto 🛵',
    'Coche 🚘', //69
    'LTC ₿',
    'Chicken 🐔',
    'Rabbit 🐰',
    'Potato 🥔',
    'Kumpir 🥔', //74
    'Kebap 🐄',
    'ATM 🏦',
    'Gyros 🐖',
    'Coconut 🥥',
    'ToGo 📦', //79
    'Meditation 🧘',
    'Wine 🍷',
    'Champagne 🥂',
    'Alcohol 🍾',
    'Booze 🥃', //84
    'Pancakes 🥞', //You cant remove because we use fixed indexes, but replace with another string that is unlikely to be typed in by the user
    'Croissant 🥐',
    'Popcorn 🍿',
    'SoftIce 🍦',
    'Dango 🍡',
    'BnB 🛏️', //90
    'Haircut ✂️',
    'Candy 🍭',
    'Beauty 💅',
    'Miso 🍱',
    'Chocolate 🍫', //95
    'Rice 🍚',
    'Seafood 🦀',
    'Hostel 🛏️',
    'Fries 🍟',
    'Fish 🐟', //100
    'Chips 🍟',
    'Italian 🇮🇹',
    'Whiskey 🥃',
    'Rum 🥃', //This is number 104 the no tag indicator, currently not used
    'Bourbon 🥃', //105
    'Liquor 🥃',
    'Men ♂️',
    'Pasta 🍝',
    'Dessert 🍬', //109
    'Starter 🥠', //110
    'BBQ 🍗',
    'Noodle 🍜',
    'Korean 🥟',
    'Market 🧺', //114 invisible item
    'Bread 🥖',
    'Bakery 🥨',
    'Cafe ☕',
    'Games 🎮',
    'Snacks 🍿', //119
    'Elegant 🕴️',
    'Piano 🎹',
    'Brunch 🍱',
    'Nachos 🌽',
    'Lunch 🥡',
    'Breakfast 🥐', //125
    'HappyHour 🥳', //hidden item
    'LateNight 🌜',
    'Mexican 🇲🇽',
    'Burrito 🌯',
    'Tortilla 🌮', //130
    'Indonesian 🇮🇩',
    'Sports 🏆',
    'Pastry 🥧',
    'Bistro 🍲',
    'Soup 🥣', //135
    'Tea 🍵',
    'Onion',
    'Steak 🥩',
    'Shakes 🥤',
    'Empanadas 🥟', //140
    'Dinner 🍽️',
    'Sweet 🍭',
    'Fried 🍳',
    'Omelette 🥚',
    'Gin 🍸', //145
    'Donut 🍩',
    'Delivery 🚚',
    'Cups ☕',
    'Filter',
    'Juice 🍊', //150
    'Vietnamese 🇻🇳',
    'Pie 🥮', //invisible item
    'Unagi 🐡',
    'Greek 🇬🇷',
    'Japanese 🇯🇵', //155
    'Tacos 🌮',
    'Kombucha 🍵',
    'Indian 🇮🇳',
    'Nan 🥪', //
    'Club 🎶', //160
    'Honey 🍯',
    'Pool 🎱',
    'Hotel 🏨',
    'Pork 🥓',
    'Ribs 🍖', //165
    'Kava 🍵',
    'Chai 🍵',
    'Izzy 🍵',
    'Matcha 🍵',
    'Oden 🍢', //170
    'Latte ☕'
  };

  static final tagTextIT = const {
    'Spicey 🌶️', //0
    'Salty 🥨',
    'Sour 😜',
    'Organic 🐵',
    'Vegetarian 🥕', //4
    'Vegan 🐮',
    'Healthy 💓',
    'Burger 🍔',
    'Sandwich 🥪',
    'Muffin 🧁', //9 The muffin icon is invisible
    'Brownie 🥮', //10 Brownie is invisible too
    'Cake 🎂',
    'Cookie 🍪',
    'Arabic 🥙',
    'Pizza 🍕', //14
    'Salad 🥗',
    'Smoothie 🥤',
    'Fruit 🍓',
    'IceCream 🍦',
    'Raw 🥦', //19
    'Handbag 👜',
    'Cosmetic 💅',
    'Tattoo ♣',
    'Piercing 🌀',
    'Souvenir 🎁', //24
    'Hatha 🧘',
    'Vinyasa 🧘',
    'Massage 💆',
    'Upcycled 🌲',
    'Coffee ☕', //29
    'NoGluten 🌽',
    'Cocktails 🍹',
    'Beer 🍺',
    'Music 🎵',
    'Chinese 🍜', //34
    'Duck 🍱',
    'Rock 🎸',
    'LiveDJ 🎧',
    'Terrace ☀️',
    'Seeds 🌱', //39
    'Grinder 🍌',
    'Papers 🚬',
    'Advice 🌴',
    'Calzone 🥟',
    'Falafel 🥙', //44
    'MakeUp 🤡',
    'Gifts 🎁',
    'Tapas 🍠',
    'Copas 🍹',
    'Piadina 🌮', //49
    'Cheese 🧀',
    'Grains 🌾',
    'Fashion 👗',
    'Fair 🤗',
    'Women 👩', //54
    'Drinks 🍹',
    'TV 📺',
    'Retro 🦄',
    'Feta 🐐',
    'DASH ₿', //59
    'BTC ₿',
    'BCH ₿',
    'BSV ₿',
    'ETH ₿',
    'HotDog 🌭', //64
    'Fast ⏩',
    'Kosher 🦄',
    'Sushi 🍣',
    'Moto 🛵',
    'Coche 🚘', //69
    'LTC ₿',
    'Chicken 🐔',
    'Rabbit 🐰',
    'Potato 🥔',
    'Kumpir 🥔', //74
    'Kebap 🐄',
    'ATM 🏦',
    'Gyros 🐖',
    'Coconut 🥥',
    'ToGo 📦', //79
    'Meditation 🧘',
    'Wine 🍷',
    'Champagne 🥂',
    'Alcohol 🍾',
    'Booze 🥃', //84
    'Pancakes 🥞', //You cant remove because we use fixed indexes, but replace with another string that is unlikely to be typed in by the user
    'Croissant 🥐',
    'Popcorn 🍿',
    'SoftIce 🍦',
    'Dango 🍡',
    'BnB 🛏️', //90
    'Haircut ✂️',
    'Candy 🍭',
    'Beauty 💅',
    'Miso 🍱',
    'Chocolate 🍫', //95
    'Rice 🍚',
    'Seafood 🦀',
    'Hostel 🛏️',
    'Fries 🍟',
    'Fish 🐟', //100
    'Chips 🍟',
    'Italian 🇮🇹',
    'Whiskey 🥃',
    'Rum 🥃', //This is number 104 the no tag indicator, currently not used
    'Bourbon 🥃', //105
    'Liquor 🥃',
    'Men ♂️',
    'Pasta 🍝',
    'Dessert 🍬', //109
    'Starter 🥠', //110
    'BBQ 🍗',
    'Noodle 🍜',
    'Korean 🥟',
    'Market 🧺', //114 invisible item
    'Bread 🥖',
    'Bakery 🥨',
    'Cafe ☕',
    'Games 🎮',
    'Snacks 🍿', //119
    'Elegant 🕴️',
    'Piano 🎹',
    'Brunch 🍱',
    'Nachos 🌽',
    'Lunch 🥡',
    'Breakfast 🥐', //125
    'HappyHour 🥳', //hidden item
    'LateNight 🌜',
    'Mexican 🇲🇽',
    'Burrito 🌯',
    'Tortilla 🌮', //130
    'Indonesian 🇮🇩',
    'Sports 🏆',
    'Pastry 🥧',
    'Bistro 🍲',
    'Soup 🥣', //135
    'Tea 🍵',
    'Onion',
    'Steak 🥩',
    'Shakes 🥤',
    'Empanadas 🥟', //140
    'Dinner 🍽️',
    'Sweet 🍭',
    'Fried 🍳',
    'Omelette 🥚',
    'Gin 🍸', //145
    'Donut 🍩',
    'Delivery 🚚',
    'Cups ☕',
    'Filter',
    'Juice 🍊', //150
    'Vietnamese 🇻🇳',
    'Pie 🥮', //invisible item
    'Unagi 🐡',
    'Greek 🇬🇷',
    'Japanese 🇯🇵', //155
    'Tacos 🌮',
    'Kombucha 🍵',
    'Indian 🇮🇳',
    'Nan 🥪', //
    'Club 🎶', //160
    'Honey 🍯',
    'Pool 🎱',
    'Hotel 🏨',
    'Pork 🥓',
    'Ribs 🍖', //165
    'Kava 🍵',
    'Chai 🍵',
    'Izzy 🍵',
    'Matcha 🍵',
    'Oden 🍢', //170
    'Latte ☕'
  };

  static final tagTextFR = const {
    'Spicey 🌶️', //0
    'Salty 🥨',
    'Sour 😜',
    'Organic 🐵',
    'Vegetarian 🥕', //4
    'Vegan 🐮',
    'Healthy 💓',
    'Burger 🍔',
    'Sandwich 🥪',
    'Muffin 🧁', //9 The muffin icon is invisible
    'Brownie 🥮', //10 Brownie is invisible too
    'Cake 🎂',
    'Cookie 🍪',
    'Arabic 🥙',
    'Pizza 🍕', //14
    'Salad 🥗',
    'Smoothie 🥤',
    'Fruit 🍓',
    'IceCream 🍦',
    'Raw 🥦', //19
    'Handbag 👜',
    'Cosmetic 💅',
    'Tattoo ♣',
    'Piercing 🌀',
    'Souvenir 🎁', //24
    'Hatha 🧘',
    'Vinyasa 🧘',
    'Massage 💆',
    'Upcycled 🌲',
    'Coffee ☕', //29
    'NoGluten 🌽',
    'Cocktails 🍹',
    'Beer 🍺',
    'Music 🎵',
    'Chinese 🍜', //34
    'Duck 🍱',
    'Rock 🎸',
    'LiveDJ 🎧',
    'Terrace ☀️',
    'Seeds 🌱', //39
    'Grinder 🍌',
    'Papers 🚬',
    'Advice 🌴',
    'Calzone 🥟',
    'Falafel 🥙', //44
    'MakeUp 🤡',
    'Gifts 🎁',
    'Tapas 🍠',
    'Copas 🍹',
    'Piadina 🌮', //49
    'Cheese 🧀',
    'Grains 🌾',
    'Fashion 👗',
    'Fair 🤗',
    'Women 👩', //54
    'Drinks 🍹',
    'TV 📺',
    'Retro 🦄',
    'Feta 🐐',
    'DASH ₿', //59
    'BTC ₿',
    'BCH ₿',
    'BSV ₿',
    'ETH ₿',
    'HotDog 🌭', //64
    'Fast ⏩',
    'Kosher 🦄',
    'Sushi 🍣',
    'Moto 🛵',
    'Coche 🚘', //69
    'LTC ₿',
    'Chicken 🐔',
    'Rabbit 🐰',
    'Potato 🥔',
    'Kumpir 🥔', //74
    'Kebap 🐄',
    'ATM 🏦',
    'Gyros 🐖',
    'Coconut 🥥',
    'ToGo 📦', //79
    'Meditation 🧘',
    'Wine 🍷',
    'Champagne 🥂',
    'Alcohol 🍾',
    'Booze 🥃', //84
    'Pancakes 🥞', //You cant remove because we use fixed indexes, but replace with another string that is unlikely to be typed in by the user
    'Croissant 🥐',
    'Popcorn 🍿',
    'SoftIce 🍦',
    'Dango 🍡',
    'BnB 🛏️', //90
    'Haircut ✂️',
    'Candy 🍭',
    'Beauty 💅',
    'Miso 🍱',
    'Chocolate 🍫', //95
    'Rice 🍚',
    'Seafood 🦀',
    'Hostel 🛏️',
    'Fries 🍟',
    'Fish 🐟', //100
    'Chips 🍟',
    'Italian 🇮🇹',
    'Whiskey 🥃',
    'Rum 🥃', //This is number 104 the no tag indicator, currently not used
    'Bourbon 🥃', //105
    'Liquor 🥃',
    'Men ♂️',
    'Pasta 🍝',
    'Dessert 🍬', //109
    'Starter 🥠', //110
    'BBQ 🍗',
    'Noodle 🍜',
    'Korean 🥟',
    'Market 🧺', //114 invisible item
    'Bread 🥖',
    'Bakery 🥨',
    'Cafe ☕',
    'Games 🎮',
    'Snacks 🍿', //119
    'Elegant 🕴️',
    'Piano 🎹',
    'Brunch 🍱',
    'Nachos 🌽',
    'Lunch 🥡',
    'Breakfast 🥐', //125
    'HappyHour 🥳', //hidden item
    'LateNight 🌜',
    'Mexican 🇲🇽',
    'Burrito 🌯',
    'Tortilla 🌮', //130
    'Indonesian 🇮🇩',
    'Sports 🏆',
    'Pastry 🥧',
    'Bistro 🍲',
    'Soup 🥣', //135
    'Tea 🍵',
    'Onion',
    'Steak 🥩',
    'Shakes 🥤',
    'Empanadas 🥟', //140
    'Dinner 🍽️',
    'Sweet 🍭',
    'Fried 🍳',
    'Omelette 🥚',
    'Gin 🍸', //145
    'Donut 🍩',
    'Delivery 🚚',
    'Cups ☕',
    'Filter',
    'Juice 🍊', //150
    'Vietnamese 🇻🇳',
    'Pie 🥮', //invisible item
    'Unagi 🐡',
    'Greek 🇬🇷',
    'Japanese 🇯🇵', //155
    'Tacos 🌮',
    'Kombucha 🍵',
    'Indian 🇮🇳',
    'Nan 🥪', //
    'Club 🎶', //160
    'Honey 🍯',
    'Pool 🎱',
    'Hotel 🏨',
    'Pork 🥓',
    'Ribs 🍖', //165
    'Kava 🍵',
    'Chai 🍵',
    'Izzy 🍵',
    'Matcha 🍵',
    'Oden 🍢', //170
    'Latte ☕'
  };

  static final tagTextDE = const {
    'Würzig 🌶️', //0
    'Salzig 🥨',
    'Sauer 😜',
    'Biologisch 🐵',
    'Vegetarisch 🥕', //4
    'Vegan 🐮',
    'Gesund 💓',
    '🍔🍔🍔Burger 🍔',
    'Stulle 🥪',
    '🍔🍔🍔Muffin 🧁', //9 The muffin icon is invisible
    '🍔🍔🍔Brownie 🥮', //10 Brownie is invisible too
    'Kuchen 🎂',
    'Kekse 🍪',
    'Arabisch 🥙',
    '🍔🍔🍔Pizza 🍕', //14
    'Salat 🥗',
    '🍔🍔🍔Smoothie 🥤',
    'Früchte 🍓',
    'Eis 🍦',
    'Roh 🥦', //19
    'Handtasche 👜',
    'Kosmetik 💅',
    '🍔🍔🍔Tatu ♣',
    '🍔🍔🍔Piercing 🌀',
    '🍔🍔🍔Souvenir 🎁', //24
    '🍔🍔🍔Hatha 🧘',
    '🍔🍔🍔Vinyasa 🧘',
    '🍔🍔🍔Massage 💆',
    '🍔🍔🍔Upcycled 🌲',
    'Kaffee ☕', //29
    'GlutenFrei 🌽',
    '🍔🍔🍔Cocktails 🍹',
    'Bier 🍺',
    'Musik 🎵',
    'Chines. 🍜', //34
    'Ente 🍱',
    '🍔🍔🍔Rock 🎸',
    '🍔🍔🍔LiveMusik 🎧',
    'Terasse ☀️',
    'Samen 🌱', //39
    'Mühle 🍌',
    'Blättchen 🚬',
    'Beratung 🌴',
    '🍔🍔🍔Calzone 🥟',
    '🍔🍔🍔Falafel 🥙', //44
    'Schminke 🤡',
    'Geschenke 🎁',
    '🍔🍔🍔Tapas 🍠',
    'Gläser 🍹',
    '🍔🍔🍔Piadina 🌮', //49
    'Käse 🧀',
    'Körner 🌾',
    'Mode 👗',
    '🍔🍔🍔Fair 🤗',
    'Frauen 👩', //54
    'Getränke 🍹',
    'Fernseher 📺',
    '🍔🍔🍔Retro 🦄',
    'Ziegenkäse 🐐',
    'DASH ₿', //59
    'BTC ₿',
    'BCH ₿',
    'BSV ₿',
    'ETH ₿',
    'Wurst 🌭', //64
    'Schnell ⏩',
    '🍔🍔🍔Kosher 🦄',
    '🍔🍔🍔Sushi 🍣',
    'Motorrad 🛵',
    'Auto 🚘', //69
    'LTC ₿',
    'Huhn 🐔',
    'Hase 🐰',
    'Kartoffel 🥔',
    '🍔🍔🍔Kumpir 🥔', //74
    'Döner 🐄',
    'Geldautomat 🏦',
    '🍔🍔🍔Gyros 🐖',
    'Kokosnuss 🥥',
    'Mitnehmen 📦', //79
    '🍔🍔🍔Meditation 🧘',
    'Wein 🍷',
    'Champagner 🥂',
    'Alkohol 🍾',
    'Schnaps 🥃', //84
    'Pfannkuchen 🥞', //
    '🍔🍔🍔Croissant 🥐',
    '🍔🍔🍔Popcorn 🍿',
    'SoftEis 🍦',
    '🍔🍔🍔Dango 🍡',
    '🍔🍔🍔BnB 🛏️', //90
    'Haarschnitt ✂️',
    'Süßes 🍭',
    'Schönheit 💅',
    '🍔🍔🍔🍔Miso 🍱',
    'Schokolade 🍫', //95
    'Reis 🍚',
    'Meeresfr. 🦀',
    'Herberge 🛏️',
    'Fritten 🍟',
    'Fisch 🐟', //100
    'Pommes 🍟',
    'Ital. 🇮🇹',
    '🍔🍔🍔Whiskey 🥃',
    '🍔🍔🍔Rum 🥃', //This is number 104 the no tag indicator, currently not used
    '🍔🍔🍔Bourbon 🥃', //105
    'Shots 🥃',
    'Männer ♂️',
    'Spaghetti 🍝',
    'Nachtisch 🍬', //109
    'Vorspeise 🥠', //110
    'Grill 🍗',
    'Nudeln 🍜',
    'Korean. 🥟',
    'Markt 🧺', //114 invisible item
    'Brot 🥖',
    'Bäckerei 🥨',
    '🍔🍔🍔Cafe ☕',
    'Spiele 🎮',
    '🍔🍔🍔Snacks 🍿', //119
    '🍔🍔🍔Elegant 🕴️',
    'Klavier 🎹',
    '🍔🍔🍔Brunch 🍱',
    '🍔🍔🍔Nachos 🌽',
    'Mittag 🥡',
    'Frühstück 🥐', //125
    '🍔🍔🍔HappyHour 🥳', //hidden item
    'Nachts 🌜',
    'Mexikan. 🇲🇽',
    '🍔🍔🍔Burrito 🌯',
    '🍔🍔🍔Tortilla 🌮', //130
    'Indones. 🇮🇩',
    'Sport 🏆',
    'Torte 🥧',
    'Bistrot 🍲',
    'Suppe 🥣', //135
    'Tee 🍵',
    'Zwiebeln',
    'Steak 🥩',
    '🍔🍔🍔Shakes 🥤',
    '🍔🍔🍔Empanadas 🥟', //140
    'Abendmahl 🍽️',
    'Süßigk. 🍭',
    'Fritiert 🍳',
    '🍔🍔🍔Omelette 🥚',
    'Gin 🍸', //145
    'Donut 🍩',
    'Delivery 🚚',
    'Cups ☕',
    'Filter',
    'Juice 🍊', //150
    'Vietnamese 🇻🇳',
    'Pie 🥮', //invisible item
    'Unagi 🐡',
    'Greek 🇬🇷',
    'Japanese 🇯🇵', //155
    'Tacos 🌮',
    'Kombucha 🍵',
    'Indian 🇮🇳',
    'Nan 🥪', //
    'Club 🎶', //160
    'Honey 🍯',
    'Pool 🎱',
    'Hotel 🏨',
    'Pork 🥓',
    'Ribs 🍖', //165
    'Kava 🍵',
    'Chai 🍵',
    'Izzy 🍵',
    'Matcha 🍵',
    'Oden 🍢', //170
    'Latte ☕'
  };

  static final tagTextES = const {
    'Picante 🌶️', //0
    'Salado 🥨',
    'Acido 😜',
    'Ecologico 🐵',
    'Vegetariano 🥕', //4
    'Vegano 🐮',
    'Saludable 💓',
    'Hamburguesa 🍔',
    'Bocadillo 🥪',
    '🍔🍔🍔Muffin 🧁', //9 The muffin icon is invisible
    '🍔🍔🍔Brownie 🥮', //10 Brownie is invisible too
    'Tarta 🎂',
    'Galletas 🍪',
    'Árabe 🥙',
    '🍔🍔🍔Pizza 🍕', //14
    'Ensalada 🥗',
    'Jugo 🥤',
    'Fruta 🍓',
    'Helado 🍦',
    'Crudo 🥦', //19
    'Bolsas 👜',
    'Cosmética 💅',
    'Tatuaje ♣',
    '🍔🍔🍔Piercing 🌀',
    'Recuerdo 🎁', //24
    '🍔🍔🍔Hatha 🧘',
    '🍔🍔🍔Vinyasa 🧘',
    'Masaje 💆',
    'Reciclado 🌲',
    '🍔🍔🍔Coffee ☕', //29
    'SinGluten 🌽',
    'Cócteles 🍹',
    'Cerveza 🍺',
    'Música 🎵',
    'Chino 🍜', //34
    'Pato 🍱',
    'Rock 🎸',
    'EnVivo 🎧',
    'Terraza ☀️',
    'Semillas 🌱', //39
    'Grinder 🍌',
    'Papeles 🚬',
    'Consejos 🌴',
    '🍔🍔🍔Calzone 🥟',
    '🍔🍔🍔Falafel 🥙', //44
    'Maquillaje 🤡',
    'Regalos 🎁',
    '🍔🍔🍔Tapas 🍠',
    '🍔🍔🍔Copas 🍹', //TODO english translation???
    '🍔🍔🍔Piadina 🌮', //49
    'Queso 🧀',
    'Granos 🌾',
    'Moda 👗',
    'Justo 🤗',
    'Mujer 👩', //54
    'Bebida 🍹',
    'Tele 📺',
    '🍔🍔🍔Retro 🦄',
    '🍔🍔🍔Feta 🐐',
    'DASH ₿', //59
    '🍔🍔🍔BTC ₿',
    '🍔🍔🍔BCH ₿',
    '🍔🍔🍔BSV ₿',
    '🍔🍔🍔ETH ₿',
    'PerroCal. 🌭', //64
    'Rapido ⏩',
    '🍔🍔🍔Kosher 🦄',
    '🍔🍔🍔Sushi 🍣',
    'Moto 🛵', //TODO translate in original to english
    'Coche 🚘', //69
    '🍔🍔🍔LTC ₿',
    'Pollo 🐔',
    'Conejo 🐰',
    'Patata 🥔',
    '🍔🍔🍔Kumpir 🥔', //74
    '🍔🍔🍔Kebap 🐄',
    '🍔🍔🍔ATM 🏦',
    '🍔🍔🍔Gyros 🐖',
    'Coco 🥥',
    'Llevar 📦', //79
    'Meditación 🧘',
    'Vino 🍷',
    '🍔🍔🍔Champagne 🥂',
    'Alcool 🍾',
    '🍔🍔🍔Booze 🥃', //84
    'Panqueques 🥞', //You cant remove because we use fixed indexes, but replace with another string that is unlikely to be typed in by the user
    '🍔🍔🍔Croissant 🥐',
    'Palomitas 🍿',
    '🍔🍔🍔SoftIce 🍦',
    '🍔🍔🍔Dango 🍡',
    '🍔🍔🍔BnB 🛏️', //90
    'CortePelo ✂️',
    'Caramelo 🍭',
    'Belleza 💅',
    '🍔🍔🍔Miso 🍱',
    'Chocolate 🍫', //95
    'Riso 🍚',
    'Mariscos 🦀',
    '🍔🍔🍔Hostel 🛏️',
    'Patatas 🍟',
    'Pescado 🐟', //100
    'Fritas 🍟',
    '🍔🍔🍔Italiano 🇮🇹',
    'Whisky 🥃',
    'Ron 🥃', //This is number 104 the no tag indicator, currently not used
    'Borbón 🥃', //105
    'Licor 🥃',
    'Hombres ♂️',
    'Pasta 🍝',
    'Postre 🍬', //109
    'Arrancador 🥠', //110
    'Barbacoa 🍗',
    'Fideos 🍜',
    'Coreano 🥟',
    'Mercado 🧺', //114 invisible item
    'Pan 🥖',
    'Panadería 🥨',
    'Café ☕',
    'Juegos 🎮',
    'Caramelo 🍿', //119
    'Elegante 🕴️',
    '🍔🍔🍔Piano 🎹',
    '🍔🍔🍔Brunch 🍱',
    '🍔🍔🍔Nachos 🌽',
    'Almuerzo 🥡',
    'Desayuno 🥐', //125
    '🍔🍔🍔HappyHour 🥳', //hidden item
    'Noche 🌜',
    'Mexicano 🇲🇽',
    '🍔🍔🍔Burrito 🌯',
    '🍔🍔🍔Tortilla 🌮', //130
    'Indonesio 🇮🇩',
    'Deportes 🏆',
    'Pasteles 🥧',
    'Bistro 🍲',
    'Sopa 🥣', //135 //TODO FIX EMOJICONS AFTER TRANSLATION SOME GET LOST
    'Té 🍵', //TODO translate all accent letters to normal to show them as suggestions
    'Cebolla',
    '🍔🍔🍔Steak 🥩',
    'Zumo 🥤',
    '🍔🍔🍔Empanadas 🥟', //140
    'Cena 🍽️',
    'Bonbon 🍭',
    'Frito 🍳',
    'Tortilla 🥚',
    '🍔🍔🍔Gin 🍸', //145
    'Donas 🍩',
    'Entrega 🚚',
    'Copas ☕',
    'Filtro',
    'Jugo 🍊', //150
    'Vietnamita 🇻🇳',
    '🍔🍔🍔Pie 🥮', //invisible item
    '🍔🍔🍔Unagi 🐡',
    'Griego 🇬🇷',
    'Japonés 🇯🇵', //155
    '🍔🍔🍔Tacos 🌮',
    '🍔🍔🍔Kombucha 🍵',
    '🍔🍔🍔Indio 🇮🇳',
    '🍔🍔🍔Nan 🥪', //
    '🍔🍔🍔Club 🎶', //160
    'Miel 🍯',
    '🍔🍔🍔Pool 🎱',
    '🍔🍔🍔Hotel 🏨',
    'Cerdo 🥓',
    'Costillas 🍖', //165
    '🍔🍔🍔Kava 🍵',
    '🍔🍔🍔Chai 🍵',
    '🍔🍔🍔Izzy 🍵',
    '🍔🍔🍔Matcha 🍵',
    '🍔🍔🍔Oden 🍢', //170
    '🍔🍔🍔Latte ☕'
  };

  static final titleTags = const {
    'Muerde La Carne',
    'Caffe Meranto',
    'Meranto',
    'Las Empanadas de Simon',
    'Empanadas de Simon',
    'Posada El Oasis',
    'Fanatic Sport',
    'Steak Burger',
    'La Soga',
    'L\'Italia',
    'Urban Pizza',
    '1903',
    'Veruca Salt',
    'Altos del Este',
    'MiniGolf',
    'Windschief',
    'Beach',
    'Casa Sofia Inn',
    'Maya Lous Place',
    'Artehelado Villahermosa',
    'Plaza',
    'City Center',
    'Rempah Rempah',
    'People\'s Pub',
    'Figures',
    'Kirby\'s Q',
    'STREET\'za 360',
    'Liar\'s Bench',
    '3S Artspace',
    'STREET eat/drink 360',
    'La Maison Navarre',
    'Fezziwig\'s',
    'The Bold Mariner Brewing Company',
    'Brew',
    'Bold Mariner Brewing Company',
    'La Sirene Upper West Side',
    'La Sirene',
    'MAMACHA',
    'Korean Spring',
    'Mystic Water Kava Bar',
    'Trevi Pasta',
    'Bandung Indonesian Restaurant',
    'City Lounge',
    'Luminous Brewhouse',
    'Mill Inn',
    'Classic Crust Pizza',
    'Apia Inn Samoa',
    'Sushi-Bar Numazuko',
    'Numazuko',
    '回転寿司酒場',
    '銀座沼津港',
    'Villa Vveden',
    'Введенье',
    'Береговая',
    'MEZZO Luxury Bar & Lounge',
    'daikanyama O\'KOK',
    'Cafe de Perle',
    'カフェ・ド・ペルル',
    'Two Dogs Taproom',
    'トゥー·ドッグス·タップルーム',
    'The Pink Cow Akasaka',
    '赤坂 The Pink Cow (ピンクカウ)',
    'Pink Cow',
    'The Pink Cow',
    'ピンクカウ',
    '赤坂',
    'Downtown B\'s Indian Kitchen',
    'Kitchen',
    'ダウンタウン ビーズ',
    'f,line',
    'エフライン',
    'Kagurazaka aka be e tasuki',
    '神楽坂 あかべえ 襷｜神楽坂 焼き鳥 ワイン 日本酒',
    'New Salsa Sudada',
    'サルサスダーダ',
    'Good Heavens',
    'Greek bar',
    'ギリシャ小町三丁目',
    'Bar Golden',
    'Golden',
    'Gluten Free 61',
    '330BAR 私を恵比寿に連れてって',
    '私を恵比寿に連れてって',
    'RAKAN TOKYO',
    'Kawashou',
    'うなぎ 川昌',
    'Soul Food House',
    'ラ コシーナ デ ゲン - la cocina de gaston',
    'la cocina de gaston',
    'RicePlus（ライスプラス）',
    'ライスプラス',
    'Hackers Bar',
    'GYOZA SHACK',
    'Yakiniku Tamura - 北海道の旬 焼肉たむら',
    '北海道の旬',
    '焼肉たむら',
    'オサル コーヒー osaru coffee',
    'osaru coffee',
    '喫茶・軽食 ユニティーフェイス - Unity Faith',
    'Unity Faith',
    'ENGARO organic & hair clinic 大阪市北区大淀南オーガニック美容室',
    '大阪市北区大淀南オーガニック美容室',
    '仮想通貨カフェ＆バーＣＯＩＮＳ',
    'ＣＯＩＮＳ',
    '04village',
    'なんば',
    'cycle&cafe TRI⊿NGLE',
    'TRI⊿NGLE',
    'bit cafe',
    'Slices Pizza Restaurant',
    'スライシーズ',
    'toripao - 鶏料理pao',
    '鶏料理pao',
    'ナジミチヂミ Izakaya Restaurant',
    'Izakaya',
    '味乃家 2号店',
    'Ajinoya 2nd Shop - 味乃家 2号店',
    '炭火焼肉たむら福岡店 - Yakiniku Tamura Fukuoka',
    'Yakiniku Tamura Fukuoka',
    '炭火焼肉たむら 長崎店 - Yakiniku Tamura Nagasaki',
    'Yakiniku Tamura Nagasaki',
    'DUCATUS CAFE Bali',
    'Ducatus Cafe Singapore',
    'BUNK 5021 HOSTEL',
    'Pattaya Beer Garden',
    'Cocotte Soi',
    'Catmosphere Cat Cafe',
    'Gringo Loco Cantina',
    'Cantina',
    'Francesca\'s Bar',
    'Platform 62',
    'Spawn Point Small Bar',
    'La Stazione Bakery & Cafe',
    'Port Stephens Motel',
    'Nutrient Depot',
    'Stone & Wood Brewing Company',
    'Brewing Company',
    'Next Hotel Brisbane',
    'Brew Cafe & Wine Bar',
    'X CARGO - Beer Garden',
    'Boroughs of New York Wood fire Pizza',
    'New York',
    'Nom Nom Korean Eatery',
    '5 Dogs',
    'Steph\'s Cafe',
    'Ovolo The Valley - 5 Star Hotel',
    'Spoon Deli Cafe',
    'Airport',
    'The Botanist Kitchen And Bar',
    'Burger Urge DFO skygate',
    'Windmill & Co - Bar & Bistro',
    'Red Rooster',
    'Mad Mex Fresh Mexican Grill',
    'Mad Mex',
    'SumoSalad',
    'Giancarlo Coffee',
    'Wasabi Warriors',
    'Lagoons 1770 Resort & Spa',
    '1770',
    '1770 Southern Cross Backpackers',
    'Southern Cross Backpackers',
    'Getaway Garden Cafe',
    'Agnes Water Tavern',
    'Cafe Discovery',
    'Backpackers @ 1770',
    'Green Turtle Brasserie',
    'Sandcastles 1770 Motel & Resort',
    'The Cat\'s Meow',
    'Cats Meow',
    'Little Pegs Cafe', 'Alt Brew', 'The Watermark', 'The Downunder Bar',
    'Downunder Bar',
    'La Lima, comedor vegano',
    'La Pasticceria di Gracia',
    'Pasticceria',
    'La Vermu',
    'Gelatology',
    'Atabalats Gastrobar',
    'Free and Sweet',
    'La Pizza',
    'Candela Canela - Sweet Desserts',
    'Chatelet',
    'MIT K',
    'Molsa L\'Estel',
    'Supermercado',
    'Ecologico',
    'King Kaya',
    'VeGala Vegan Beauty',
    'Perruqueria Akash',
    'Akash',
    'Sincronia Yoga',
    'Yoga',
    'Kamoma Spritz Bar',
    'Rekup & Co Verdi',
    'Amelia Bakery - Tartas',
    'Pollo Expresss Gourmet', 'Gourmet',
    'Eco Center',
    'El Cuartito',
    'Bambule Sancho - Clothing and Asseccories',
    'Clothing and Asseccories',
    'Ecobakery Gluten Free',
    'Gluten Free',
    'Grow Cafe',
    'Deux Point Zero',
    'LLS Cafe Deli',
    'BrewDog Canary Wharf',
    'Canary Wharf',
    'Westland Coffee & Wine',
    'Nimcomsoup',
    'Sarahs Coffee, The Coffee Bean',
    'The Coffee Bean',
    'The Corner Cafe',
    'Corner Cafe',
    'Coffee Bean',
    'The Green Room',
    'Green Room',
    'Chaos Coffee Bar / Kafe Chaos',
    'Kafe Chaos',
    'Tonys coffeebar',
    'Mamas Banh | Prenzlauer Berg',
    'Prenzlauer Berg',
    'Friedel Richter Restaurant',
    'Taverna Pizza&Pinsa Romana',
    'Gostisce Pirat, Robin Vogric',
    'Pirat',
    'Robin Vogric',
    'Helado',
    'Heladeria',
    'Truck',
    'Cerveceria',
    'Dulces',
    'Hamburguesas',
    'Tentacion',
    'Delicias',
    'Pasteles',
    'Pasteleria',
    'Panaderia',
    'Subway', //TODO BLINK REVIEW BUTTON like the search button
    'Papa John',
  };
}
