class SuggestionsTitles {
  //DONE
  // south japon, south africa, jason

  static final List<Map<String, dynamic>> continents = const [
    {
      'value': 0,
      'label': 'Africa',
    },
    {
      'value': 1,
      'label': 'Asia',
      //'textStyle': TextStyle(color: Colors.red),
    },
    {
      'value': 2,
      'label': 'Australia',
      //'icon': Icon(Icons.stop),
    },
    {
      'value': 3,
      'label': 'Europe',
    },
    {
      'value': 4,
      'label': 'North America',
    },
    {
      'value': 5,
      'label': 'South America',
    }
  ];

  static final List searchCombos = [
    searchCombosAfrica,
    searchCombosAsia,
    searchCombosAustralia,
    searchCombosEurope,
    searchCombosNorthAmerica,
    searchCombosSouthAmerica
  ];

  static final List<Map<String, dynamic>> searchCombosAustralia = const [
    {
      'value': 0,
      'label': 'Acacia Limousines, Currajong QLD, Australia',
    },
    {
      'value': 1,
      'label': 'Alt Brew, Townsville City QLD, Australia',
    },
    {
      'value': 2,
      'label': 'Aptissio Australia Pty Ltd, Townsville QLD, Australia',
    },
    {
      'value': 3,
      'label': 'Archer Mobile Coffee, Garbutt QLD, Australia',
    },
    {
      'value': 4,
      'label': 'Aroi Bangkok Thai Restaurant, Hermit Park QLD, Australia',
    },
    {
      'value': 5,
      'label': 'Aussie Thai Fusion, North Ward QLD, Australia',
    }
  ];

  static final List<Map<String, dynamic>> searchCombosEurope = const [
    {
      'value': 0,
      'label': 'Joels Crepes, The Headrow, Leeds',
    },
    {
      'value': 1,
      'label': 'The Block, Lisboa',
    },
    {
      'value': 2,
      'label': 'Sailing Munich, Munich, Germany',
    },
    {
      'value': 3,
      'label': 'Country House "La Grancia", Treia, Macerata, Italy',
    },
  ];

  static final List<Map<String, dynamic>> searchCombosAfrica = const [
    {
      'value': 0,
      'label': 'Froggs & Habit Intergalactic Trading Corporation, South Africa',
    },
    {
      'value': 1,
      'label': 'Citihoppers (Pty) Ltd, Joubertina, South Africa',
    },
    {
      'value': 2,
      'label': 'Nduli, Ceres, South Africa',
    },
    {
      'value': 3,
      'label': 'JMK Apartment Rentals, Cape Town, South Africa',
    },
    {
      'value': 4,
      'label': 'The Scone Shack, Cape Town, South Africa',
    },
    {
      'value': 5,
      'label': 'Damas Bodyworks Express, Cape Town, South Africa',
    }
  ];

  static final List<Map<String, dynamic>> searchCombosAsia = const [
    {
      'value': 0,
      'label': 'ジェムキャッスルゆきざき 熊本店, Japan',
    },
    {
      'value': 1,
      'label': 'Yuji Kajiwara ゆうじ・かじわらの店, Japan',
    },
    {
      'value': 2,
      'label': 'Yakiniku Nurubon, 焼肉ヌルボン 大名Kitchen, Japan',
    },
    {
      'value': 3,
      'label': 'ジェムキャッスルゆきざき 福岡セレクト館, Japan',
    },
    {
      'value': 4,
      'label':
          'ジェムキャッスルゆきざき 福岡本店 天神 婚約指輪, Japan, 〒810-0001 Fukuoka, Chuo Ward, Tenjin, 2 Chome−6−14 ゆきざきビル',
    },
    {
      'value': 5,
      'label': 'Gem Castle Yukizaki Nakasu, Japan',
    },
    {
      'value': 6,
      'label': 'Kyushu Diamond Center (KDC) 九州ダイヤモンドセンター, Japan',
    }
  ];

  static final List<Map<String, dynamic>> searchCombosSouthAmerica = const [
    {
      'value': 0,
      'label': 'Newpoint, Cuyagua, Venezuela',
    },
    {
      'value': 1,
      'label': 'Burger Center, Caracas, Venezuela',
    },
    {
      'value': 2,
      'label': 'metromercados, Heredia, Costa Rica',
    },
    {
      'value': 3,
      'label': 'Kullawa Shop, Cuyagua, Venezuela',
    },
    {
      'value': 4,
      'label': 'Bodegon El Saman Cuyaguero, Cuyagua, Venezuela',
    },
    {
      'value': 5,
      'label': 'Posada Casa Grande, Cuyagua, Venezuela',
    },
    {
      'value': 6,
      'label': 'Pura Vida Cuyagua Surf y Moda Playera, Cuyagua, Venezuela',
    },
    {
      'value': 7,
      'label': "Cacao's Canela, El Castano, Maracay, Venezuela",
    },
    {
      'value': 8,
      'label': "Supermercado Walio, El Castano, Maracay, Venezuela",
    }
  ];

  static final List<Map<String, dynamic>> searchCombosNorthAmerica = const [
    {
      'value': 0,
      'label': '',
    },
  ];

  static final titleTags = const {
    'Muerde La Carne',
    'Caffe Meranto',
    'Meranto',
    'Las Empanadas de Simon',
    'Empanadas de Simon',
    'Posada El Oasis',
    'Fanatic Sport',
    'Steak Burger',
    'La Soga',
    'LItalia',
    'Urban Pizza',
    '1903',
    'Veruca Salt',
    'Altos del Este',
    'MiniGolf',
    'Windschief',
    'Beach',
    'Casa Sofia Inn',
    'Maya Lous Place',
    'Artehelado Villahermosa',
    'Plaza',
    'City Center',
    'Rempah Rempah',
    'Peoples Pub',
    'Figures',
    'Kirbys Q',
    'STREETza 360',
    'Liars Bench',
    '3S Artspace',
    'STREET eat-drink 360',
    'La Maison Navarre',
    'Fezziwigs',
    'The Bold Mariner Brewing Company',
    'Brew',
    'Bold Mariner Brewing Company',
    'La Sirene Upper West Side',
    'La Sirene',
    'MAMACHA',
    'Korean Spring',
    'Mystic Water Kava Bar',
    'Trevi Pasta',
    'Bandung Indonesian Restaurant',
    'City Lounge',
    'Luminous Brewhouse',
    'Mill Inn',
    'Classic Crust Pizza',
    'Apia Inn Samoa',
    'Sushi-Bar Numazuko',
    'Numazuko',
    '回転寿司酒場',
    '銀座沼津港',
    'Villa Vveden',
    'Введенье',
    'Береговая',
    'MEZZO Luxury Bar n Lounge',
    'daikanyama OKOK',
    'Cafe de Perle',
    'カフェ・ド・ペルル',
    'Two Dogs Taproom',
    'トゥー·ドッグス·タップルーム',
    'The Pink Cow Akasaka',
    '赤坂 The Pink Cow (ピンクカウ)',
    'Pink Cow',
    'The Pink Cow',
    'ピンクカウ',
    '赤坂',
    'Downtown Bs Indian Kitchen',
    'Kitchen',
    'ダウンタウン ビーズ',
    'f,line',
    'エフライン',
    'Kagurazaka aka be e tasuki',
    '神楽坂 あかべえ 襷｜神楽坂 焼き鳥 ワイン 日本酒',
    'New Salsa Sudada',
    'サルサスダーダ',
    'Good Heavens',
    'Greek bar',
    'ギリシャ小町三丁目',
    'Bar Golden',
    'Golden',
    'Gluten Free 61',
    '330BAR 私を恵比寿に連れてって',
    '私を恵比寿に連れてって',
    'RAKAN TOKYO',
    'Kawashou',
    'うなぎ 川昌',
    'Soul Food House',
    'ラ コシーナ デ ゲン - la cocina de gaston',
    'la cocina de gaston',
    'RicePlus（ライスプラス）',
    'ライスプラス',
    'Hackers Bar',
    'GYOZA SHACK',
    'Yakiniku Tamura - 北海道の旬 焼肉たむら',
    '北海道の旬',
    '焼肉たむら',
    'オサル コーヒー osaru coffee',
    'osaru coffee',
    '喫茶・軽食 ユニティーフェイス - Unity Faith',
    'Unity Faith',
    'ENGARO organic hair clinic 大阪市北区大淀南オーガニック美容室',
    '大阪市北区大淀南オーガニック美容室',
    '仮想通貨カフェ＆バーＣＯＩＮＳ',
    'ＣＯＩＮＳ',
    '04village',
    'なんば',
    'cycle-cafe TRI⊿NGLE',
    'TRI⊿NGLE',
    'bit cafe',
    'Slices Pizza Restaurant',
    'スライシーズ',
    'toripao - 鶏料理pao',
    '鶏料理pao',
    'ナジミチヂミ Izakaya Restaurant',
    'Izakaya',
    '味乃家 2号店',
    'Ajinoya 2nd Shop - 味乃家 2号店',
    '炭火焼肉たむら福岡店 - Yakiniku Tamura Fukuoka',
    'Yakiniku Tamura Fukuoka',
    '炭火焼肉たむら 長崎店 - Yakiniku Tamura Nagasaki',
    'Yakiniku Tamura Nagasaki',
    'DUCATUS CAFE Bali',
    'Ducatus Cafe Singapore',
    'BUNK 5021 HOSTEL',
    'Pattaya Beer Garden',
    'Cocotte Soi',
    'Catmosphere Cat Cafe',
    'Gringo Loco Cantina',
    'Cantina',
    'Francescas Bar',
    'Platform 62',
    'Spawn Point Small Bar',
    'La Stazione Bakery n Cafe',
    'Port Stephens Motel',
    'Nutrient Depot',
    'Stone n Wood Brewing Company',
    'Brewing Company',
    'Next Hotel Brisbane',
    'Brew Cafe n Wine Bar',
    'X CARGO - Beer Garden',
    'Boroughs of New York Wood fire Pizza',
    'New York',
    'Nom Nom Korean Eatery',
    '5 Dogs',
    'Stephs Cafe',
    'Ovolo The Valley - 5 Star Hotel',
    'Spoon Deli Cafe',
    'Airport',
    'The Botanist Kitchen And Bar',
    'Burger Urge DFO skygate',
    'Windmill n Co - Bar n Bistro',
    'Red Rooster',
    'Mad Mex Fresh Mexican Grill',
    'Mad Mex',
    'SumoSalad',
    'Giancarlo Coffee',
    'Wasabi Warriors',
    'Lagoons 1770 Resort n Spa',
    '1770',
    '1770 Southern Cross Backpackers',
    'Southern Cross Backpackers',
    'Getaway Garden Cafe',
    'Agnes Water Tavern',
    'Cafe Discovery',
    'Backpackers @ 1770',
    'Green Turtle Brasserie',
    'Sandcastles 1770 Motel n Resort',
    'The Cats Meow',
    'Cats Meow',
    'Little Pegs Cafe', 'Alt Brew', 'The Watermark', 'The Downunder Bar',
    'Downunder Bar',
    'La Lima, comedor vegano',
    'La Pasticceria di Gracia',
    'Pasticceria',
    'La Vermu',
    'Gelatology',
    'Atabalats Gastrobar',
    'Free and Sweet',
    'La Pizza',
    'Candela Canela - Sweet Desserts',
    'Chatelet',
    'MIT K',
    'Molsa LEstel',
    'Supermercado',
    'Ecologico',
    'King Kaya',
    'VeGala Vegan Beauty',
    'Perruqueria Akash',
    'Akash',
    'Sincronia Yoga',
    'Yoga',
    'Kamoma Spritz Bar',
    'Rekup n Co Verdi',
    'Amelia Bakery - Tartas',
    'Pollo Expresss Gourmet', 'Gourmet',
    'Eco Center',
    'El Cuartito',
    'Bambule Sancho - Clothing and Asseccories',
    'Clothing and Asseccories',
    'Ecobakery Gluten Free',
    'Gluten Free',
    'Grow Cafe',
    'Deux Point Zero',
    'LLS Cafe Deli',
    'BrewDog Canary Wharf',
    'Canary Wharf',
    'Westland Coffee n Wine',
    'Nimcomsoup',
    'Sarahs Coffee, The Coffee Bean',
    'The Coffee Bean',
    'The Corner Cafe',
    'Corner Cafe',
    'Coffee Bean',
    'The Green Room',
    'Green Room',
    'Chaos Coffee Bar - Kafe Chaos',
    'Kafe Chaos',
    'Tonys coffeebar',
    'Mamas Banh - Prenzlauer Berg',
    'Prenzlauer Berg',
    'Friedel Richter Restaurant',
    'Taverna Pizza-Pinsa Romana',
    'Gostisce Pirat, Robin Vogric',
    'Pirat',
    'Robin Vogric',
    'Helado',
    'Heladeria',
    'Truck',
    'Cerveceria',
    'Dulces',
    'Tentacion',
    'Delicias',
    'Pasteles',
    'Pasteleria',
    'Panaderia', //TODO BLINK REVIEW n LOCATE BUTTON like the search button
  };
}
