class Tags {
  static final locations = const {
    'Europe',
    'Germany',
    'Berlin',
    'Spain',
    'Barcelona',
    'Benidorm',
    'Tarifa',
    'France',
    'Paris',
    'England',
    'London',
    'Holywell',
    'Rhos on Sea',
    'Brackley',
    'Norway',
    'Bergen', 'Sweden', 'Göteborg', 'Rychnov nad Kněžnou', 'Czechia', 'Piran',
    'Slovenia', 'Yerevan', 'Armenia', 'Yaroslavl',
    'America',
    'Venezuela', 'Caracas', 'Maracaibo', 'Puerto la Cruz', 'Catia La Mar',
    'El Parmazo', 'Acarigua', 'San Cristobal',
    'Columbia',
    'Popayan',
    'Belize',
    'Hopkins',
    'Unitedville',
    'Mexico',
    'Tabasco',
    'Villahermosa',
    'Dominican Republic',
    'Santo Domingo',
    'Canada',
    'Saint Stephen',
    'New Hampshire',
    'Alstead',
    'Portsmouth',
    'Virginia',
    'Norfolk',
    'New York',
    'NYC',
    'California',
    'San Jose',
    'Los Angeles',
    'Florida',
    'Orlando',
    'Wisconsin',
    'Madison', 'Milwaukee', 'Wyoming', 'Sheridan', 'Utah', 'Salt Lake City',
    'Toronto',
    'USA',
    'Colorado',
    'Asia',
    'Indonesia', 'Bali', 'Singapore', 'Philippines', 'Manila', 'Thailand',
    'Pattaya', 'Bangkok', 'Chiang May',
    'Japan',
    'Tokyo',
    'Osaka', 'Fukuoka', 'Nagasaki', 'Samoa', 'Apia', 'Russia',
    'Australia', 'Gold Coast', 'Melbourne', 'Sidney', 'Nelson Bay',
    'Christchurch', 'Byron Bay', 'Brisbane',
    'Queensland', 'Agnes Water', 'Aitkenvale', 'Townsville', 'Cairns', 'Perth',
    'Africa',
  };

  static final titleTags = const {
    'Helado','Heladeria','Truck','Cerveceria','Dulces','Hamburguesas', 'Tentacion', 'Delicias', 'Pasteles','Pasteleria', 'Panaderia', 'Subway','Papa John','Pasticceria',
  };

  static final tagText = const {
    'Bitcoin',
    //TODO make tags clickable
    'Events',
    'Trading',
    'Organic',
    'Vegetarian',
    'Vegan',
    'Healthy',
    'Burger',
    'Sandwich',
    'Muffin',
    'Brownie',
    'Cake',
    'Cookie',
    'Tiramisu',
    'Pizza',
    'Salad',
    'Smoothie',
    'Fruit',
    'IceCream',
    'Raw',
    'Handbag',
    'Cosmetic',
    'Tattoo',
    'Piercing',
    'Souvenir',
    'Hatha',
    'Vinyasa',
    'Massage',
    'Upcycled',
    'Coffee',
    'NoGluten',
    'Cocktails',
    'Beer',
    'Music',
    'Projects',
    'Electro',
    'Rock',
    'LiveDJ',
    'Terrace',
    'Seeds',
    'Grinder',
    'Papers',
    'Advice',
    'Calzone',
    'Suppli',
    'MakeUp',
    'Gifts',
    'Tapas',
    'Copas',
    'Piadina',
    'Herbs',
    'Grains',
    'Fashion',
    'Fair',
    'Women',
    'Drinks',
    'TV',
    'Retro',
    'Color',
    'BW',
    'BTC',
    'BCH',
    'Online',
    'Booking',
    'HotDog',
    'Fast',
    'Kosher',
    'Sushi',
    'Moto',
    'Coche',
    'Tablet',
    'Chicken',
    'Rabbit',
    'Potatoe',
    'DASH',
    'ETH',
    'ATM',
    'Disco',
    'Dance',
    'TakeAway',
    'Meditation',
    'Wine',
    'Champagne',
    'Alcohol',
    'Booze',
    'Hookers',
    'Girls',
    'Gay',
    'Party',
    'English',
    'BnB',
    'Haircut',
    'Nails',
    'Beauty',
    'Miso',
    'Teriyaki',
    'Rice',
    'Seafood',
    'Hostel',
    'Fries',
    'Fish',
    'Chips',
    'Italian',
    'Karaoke',
    ' o o o ',
    'Battery',
    'Wheels',
    'Men',
    'Pasta',
    'Dessert',
    'Starter',
    'BBQ',
    'Noodle',
    'Korean',
    'Market',
    'Bread',
    'Bakery',
    'Cafe',
    'Games',
    'Snacks',
    'Elegant',
    'Piano',
    'Brunch',
    'Nachos',
    'Lunch',
    'Breakfast',
    'HappyHour',
    'LateNight',
    'Mexican',
    'Burrito',
    'Tortilla',
    'Indonesian',
    'Sports',
    'Pastry',
    'Bistro',
    'Soup',
    'Tea',
    'Onion',
    'Steak',
    'Shakes',
    'Empanadas',
    'Dinner',
    'Sweet',
    'Fried',
    'Omelette',
    'Gin',
    'Donut',
    'Delivery',
    'Cups',
    'Filter',
    'Juice',
    'Vietnamese',
    'Pie',
    'Unagi',
    'Greek',
    'Japanese',
    'Tacos',
    'Kombucha',
    'Indian',
    'Nan',
    'Club',
    'Liquor',
    'Pool',
    'Hotel',
    'Pork',
    'Ribs',
    'Kava',
    'Chai',
    'Izzy',
    'Matcha',
    'CBD',
    'Latte'
  };
}
