class AutoSuggestions93905006 {
  static final reviewedTitles93905006 = const {
    "Comercial Nilson Modas - JX2F+X4X, Catia La Mar 1162, Vargas, Venezuela",
    "Distribuidora Yuruba - JX3G+7F3, Catia La Mar 1162, Vargas, Venezuela",
    "Mari&Alex Inversiones - JX3G+7F3, Catia La Mar 1162, Vargas, Venezuela",
    "Servidetalles - JX3F+86W, Catia La Mar 1162, Vargas, Venezuela",
    "El Planeta de Los Repuestos - JX3F+F9R, Catia La Mar 1162, Vargas, Venezuela",
    "Pinturas Decopinta - JX3C+9XF, Avenida, Catia La Mar 1162, Vargas, Venezuela",
    "Librería y papelería Satélite - Av La Atlántida, Catia La Mar 1162, La Guaira, Venezuela",
    "Karol Angela Boutique - Av. Abraham Lincoln, CC Galerias La Frayette, Benedetti, PB Local 61, Caracas 1050, Distrito Capital, Venezuela",
    "Caribe Phone - JX3F+95F, Catia La Mar 1162, Vargas, Venezuela",
    "Frutería El Mercadito - Av Principal de Baruta, C5J4+923, Caracas 1083, Miranda, Venezuela",
    "POSADA VILLA DEL CARMEN - Avenida principal de Playa Grande, Calle 1, Catia La Mar 1162, La Guaira, Venezuela",
    "Centro de Copiado Belen - JX3G+FF6, Catia La Mar 1162, Vargas, Venezuela",
    "MotoRespuestos El Peludo - Av José Antonio Paez, Resd Atlas, Local 02, Mun, Av. José Antonio Páez, Oeste 1021, Distrito Capital, Venezuela",
    "NIVEL 1 LOCAL 33 - G33P+HW9, Avenida Universidad, Caracas 1012, Distrito Capital, Venezuela",
    "Octopus Tattoo - F3V8+555, Caracas 1020, Capital District, Venezuela",
    "Blu-Ray Caracas - F4VV+R4M, Calle Páez, Caracas 1060, Distrito Capital, Venezuela",
    "Time Game - Centro de la Economía Popular Manuela Sáenz, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Global Cel C.A. - Centro Comercial Único, Blvr. de Sabana Grande, Caracas 1060, Distrito Capital, Venezuela",
    "Don Andres ferreteria - Carrera 12 con calle 18, edificio Don Andrés, p/b local 01, Guanare 3350, Portuguesa, Venezuela",
    "Sunset Coffee & Market - Residencias Playate, Av. del Hotel, Maiquetía 1162, La Guaira, Venezuela",
    "Vespa Shoes Store - 9 y 11, entre carrera, Muro de Los Lamentos, local 5 Av. Unda, Guanare 3350, Portuguesa, Venezuela",
    "Inversiones Tecnológicas Lemus C.A. - Carrera 13 entre calle 15 y 16 casa 15-40 local 1 Sector, cementerio, Guanare 3350, Portuguesa, Venezuela",
    "Team Gamer - Local C002, nivel sótano. Centro Parque Carabobo, Avenida Universidad, entre Av Sur 11, y, Avenida Sur 13, Caracas 1011, Distrito Capital, Venezuela",
    "PCLAND - Local L10-08, planta baja, pasillo La Feria. Centro Parque Carabobo, Avenida Universidad, entre Av Sur 11, y, Avenida Sur 13, Caracas 1011, Distrito Capital, Venezuela",
    "Inversiones Work Group 1063 C.A. - Local 17, planta baja. Centro Parque Carabobo, Avenida Universidad, entre Av. Sur 11, y, Avenida Sur 13, Caracas 1011, Distrito Capital, Venezuela",
    "BRIZUELA 2000 COSMOS C.A - Calle 25 entre Carrera 21 y 22 CC Cosmos Nivel PB Local C-14 sector Centro, Barquisimeto 3001, Lara, Venezuela",
    "Neder Cakes - JX3G+345, Avenida, Catia La Mar 1162, Vargas, Venezuela",
    "Seven Seas - Catia La Mar 1162, Vargas, Venezuela",
    "Alfa Computer C.A - Centro Parque Carabobo, Avenida Universidad, local A3, PB 11, Caracas 1011, Distrito Capital, Venezuela",
    "Dubáis Café C.A - local 1-2, Centro Parque Carabobo, PB Avenida Universidad, Caracas 1011, Distrito Capital, Venezuela",
    "Puyao's Café (Terminal Nacional) - Entrada Aeropuerto Internacional, Maiquetía 1162, La Guaira, Venezuela",
    "Mucho mas Que Pizza - Carrera 12 Entre Calles 14 y 15, Casa Nro 14-37 Local 1 Sector, Guanare 3350, Portuguesa, Venezuela",
    "JK Party LG - JX25+5P2, Av. El Ejército, Catia La Mar 1162, La Guaira, Venezuela",
    "El Rincon de Píja - Terminal de Pasajeros de Catia la mar Planta baja Local p-7, Catia La Mar 1162, La Guaira, Venezuela",
    "Inversiones y Juguetería Tic Tac - JX25+7X2, Av. El Ejército, Catia La Mar 1162, La Guaira, Venezuela",
    "La Boutique del Pollo y la Carne - JX2F+VRF, Catia La Mar 1162, Vargas, Venezuela",
    "El Point RC - JX2F+PW6, Catia La Mar 1162, Vargas, Venezuela",
    "Licoreria Kati Hogar - JX2F+WJX, Catia La Mar 1162, Vargas, Venezuela",
    "Inversiones Ariali - JX3F+78R, Catia La Mar 1162, Vargas, Venezuela",
    "Las Vegas Atelier de Uñas - Chacaito, Av Casanova, Centro Comercial Único, PB Local 12, Caracas 1060, Miranda, Venezuela",
    "Vestidos Diosmary - Galerias La Frayette, Edificio Benedetti, PB, Local 66, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "El Gordo Burger 12 - F3P6+899, Caracas 1020, Capital District, Venezuela",
    "El Rey de la Hamburguesa - JX26+J43, Av. Balneario, Catia La Mar 1162, La Guaira, Venezuela",
    "La Masion del Sabor Comercializadora C.A - Calle 29 con Carrera 28 casa N° 28-31,zona centro, Barquisimeto 3001, Lara, Venezuela",
    "ImichuStore - Av Caracas entre calle Anacoco y Av Caroni mini local N° 1, Barquisimeto 3001, Lara, Venezuela",
    "Signos Spa - Calle 25 entre carreras 32 y 33, Edif don Pablo, Local N°2, C. B, Barquisimeto 3001, Lara, Venezuela",
    "Reigo C.A. - al inicio, Av. Unda, Guanare 3350, Portuguesa, Venezuela",
    "Titanium autoparts ca - 3MHM+Q5P, Calle 25, Barquisimeto 3001, Lara, Venezuela",
    "Comercio Global AG c.a - Qta Cri-Cri, Avenida Washington, Caracas 1020, Distrito Capital, Venezuela",
    "Heladería FRUT CREAM - Av. Unda entre carrera 15 y, local 02, casa, nro 15-214 Avenida Simón Bolívar, Guanare 3350, Portuguesa, Venezuela",
    "Agro Ferreganga Jusdan - Av. Principal la importancia cuatricentenario con esquina calle 2, casa s/n, Local 01, Guanare 3350, Portuguesa, Venezuela",
    "Ferretería Frando - Av. Unda entre callejón 2 y, local 01 p/b, casa, nro 15-220 Avenida Simón Bolívar, Guanare 3350, Portuguesa, Venezuela",
    "Pollo a la Broaster 'Mi Comida' - Casco Central, San Juan de Los Morros 2301, Guárico, Venezuela",
    "Licoreria Cañazo - JX2J+C34, Av. El Ejército, Catia La Mar 1162, La Guaira, Venezuela",
    "Materiales La Lucha - JX2H+7QH, Av. La Armada, Catia La Mar 1162, La Guaira, Venezuela",
    "Chichi Burguer - JX26+F58, Av. Balneario, Catia La Mar 1162, La Guaira, Venezuela",
    "Rismary Fashion - JX26+J43, Av. Balneario, Catia La Mar 1162, La Guaira, Venezuela",
    "DISTRIBUIDORA LA JOYA 2000, C.A. - CALLE LA JOYA EDIFICIO LA JOYA PB, LOCAL A, Caracas 1060, Miranda, Venezuela",
    "El Criollito Sanchez - La peñita, calle 23 con carrera 3, casa nro 22-43, local 2, planta baja, Guanare 3350, Portuguesa, Venezuela",
    "YC One Detail - Avenida Urdaneta &amp; Avenida Norte 1, entre esquina Madrices e Ibarra, Local 002, Caracas 1012, Distrito Capital, Venezuela",
    "Acrílicos pintacatia ca - 5 Av. Balneario, Catia La Mar 1162, La Guaira, Venezuela",
    "Carnicería y Charcutería Ña Carmen c.a. - Sector la Peñita Guanare Carrera 3 con, local 5 C. 24, Guanare 3350, Portuguesa, Venezuela",
    "El POTY - Vía a Carorita,Andrés bello calle 1., El Cují, Barquisimeto 3001, Lara, Venezuela",
    "Repuestos Digaban 2210, C.A. - Av. José Antonio Páez, entre Av. Loiro y Valparaíso, Qta. Digaban, P.B, Caracas 1020, Distrito Capital, Venezuela",
    "King technology D&C - Piso 2, Local MT48. Av José Antonio Paez con Av O&#39;Higgins. C. C. Galerías Paraíso, Nivel Paraíso, Caracas 1020, Distrito Capital, Venezuela",
  };
}
