class AutoSuggestions87285308 {
  static final reviewedTitles87285308 = const {
    "IL PASSO - Strada Palas 7A, Iași 700051, Romania",
    "Rotexim Atic - Strada Dunărea 27, Oradea, Romania",
    "IL PASSO - Bulevardul Alexandru Lăpușneanu 116C, Constanța 900419, Romania",
    "Sâmbăta de Sus Monastery - DC79, Stațiunea Climaterică Sâmbăta 507267, Romania",
    "Antrepriza Construcţii Montaj 4 S.A. - Str. Barasch Iuliu, 4A, Bucuresti-Sector 3, Bucuresti, 30791, București 030167, Romania",
    "biciclaria.ro - Bulevardul Dacia 48, Oradea 410346, Romania",
    "Zen Clinic - Bulevardul Epureanu 44, Bârlad, Romania",
    "German Market - Piața Mihai Viteazu nr. 17, Cluj-Napoca 400151, Romania",
    "IL PASSO - Calea Vitan nr. 55-59, București 031282, Romania",
    "Vinotera - Strada Căii Ferate 9, Oradea 410561, Romania",
    "Romagna Mia - Piața Regele Ferdinand, Oradea 410040, Romania",
    "ELCATE - Bloc A15, Strada Carpenului 12, Brașov 500256, Romania",
    "Merci Bistro & Coffee Oradea - Strada Aurel Lazăr 1, Oradea 410043, Romania",
    "Ardelean Mihaela - Strada Corneliu Coposu 4, Sighetu Marmației 435500, Romania",
    "Aparte Paine și Bunatati - Strada Ceyrat, Oradea 417498, Romania",
    "Novokinetic - Strada Alexandru Vaida Voievod nr. 18, Oradea 410089, Romania",
    "MLD Auto Service - Strada Cloşca 44, Florești 407280, Romania",
    "Petit Cafe - Piața Libertății 36, Oradea 410080, Romania",
    "IL PASSO - Strada Nufărului nr.30, Oradea 410583, Romania",
    "Marco 21 - Piața Mihai Viteazu 32, Cluj-Napoca 400156, Romania",
    "Dynamic Oradea - Sala de sport/fitness ALTFEL - Strada Alexandru Vaida Voievod 18, Oradea 410088, Romania",
    "Bianco Milano Oradea - Strada Republicii 10, Oradea 410018, Romania",
    "Holistic - Analize medicale Bistrita - Calea Moldovei 12, Bistrița, Romania",
    "Avocat CEDO - Diana Dragomir si Asociatii - Strada Ion Bogdan 9, București 010538, Romania",
    "Lee Cooper - Strada Termocentralei 10, Târgu Jiu, Romania",
    "Dutch Pancakes, C.A - Av. Ernesto Blohm Centro Comercial Ciudad Tamanaco, CCCT Segunda Etapa, Nivel PB, local 43L06 al lado de Burger Bar, Caracas 2115, Distrito Capital, Venezuela",
    "Pensiunea Regal - nr. 106, Haieu 417501, Romania",
    "Ceasornicărie - reparații ceasuri - Piața Gării, Craiova, Romania",
    "Global Top Business Solutions SRL - Strada Barbu Delavrancea 59, București, Romania",
    "SINTEZIS BIROTICA - P-ta Ep. Ignatie Darabant nr. 24F, Complex Comercial Galassini, modul 14, Oradea 410235, Romania",
    "Taxi alba iulia - Bl A7 Ap4, Strada Ampoiului 11, Alba Iulia 510001, Romania",
    "CASA MATEO - Strada Valcelelor Nr 6, Toplița 535700, Romania",
    "Alimar Concrete Construct - Bucea Nr 29A, Bucea 407441, Romania",
    "Magazin alimentar Hello - Bulevardul Chimiei nr 52, Iași 700294, Romania",
    "Servicii Generale S.R.L. - Strada Calistrat Hogaș 8, Piatra Neamț 610004, Romania",
    "ImoComplet - Strada Avram Iancu 221, Florești 407280, Romania",
    "Data Speed - Strada Corneliu Coposu 103, Cluj-Napoca 400394, Romania",
    "GO SERV - Bulevardul Traian 8, Baia Mare, Romania",
    "Pergola Cotroceni • Restaurant • Coffee Shop - Strada Doctor Frederic Joliot-Curie 1, București 050588, Romania",
    "Amecs - Piața Abator nr.4-7, Cluj-Napoca 400394, Romania",
    "Amecs - Strada Tudor Vladimirescu, Alba Iulia, Romania",
    "Barmacie - Strada Piezișă 21, Cluj-Napoca 400394, Romania",
    "Meda Service - Strada Tipografiei nr. 8 etaj 1, Cluj-Napoca 400101, Romania",
    "Librăria Sabin Opreanu - Piața 1 Mai 3, Băile Herculane 325200, Romania",
    "e-scutere - Strada Locotenent Ovidiu Balea 51A, Timișoara 300620, Romania",
    "STATIE ITP CT149 OVIDIU - Ovidiu 905900, Romania",
    "Case de marcat Demalli Serv Cluj - E81 39, Cluj-Napoca 400394, Romania",
    "Restaurant Park - Calea Republicii 3, Marghita 415300, Romania",
    "Sistloial Service S.R.L. - Strada Ștefan Cel Mare 22, Bistrița 420091, Romania",
    "Deustech - Strada Cuza Vodă 16, Cluj-Napoca 400107, Romania",
    "SGI Service M SRL - Calea Moldovei 17, Bistrița 420110, Romania",
    "FISCAL ONLINE - Case Marcat Oradea - Aparatura Fiscala - Strada Independenței 11, Oradea 410065, Romania",
    "Csermobil GSM - Strada Gábor Áron 2, Vlăhița 535800, Romania",
    "NN FISCALPRINT SB S.R.L. - etaj 1, Str. Autogării 16, Sibiu 550135, Romania",
    "Taxi Albertini Galati - Str. AUREL VLAICU nr. 7 Corp C2, Et.1, Galați 800508, Romania",
    "Padrino Suceava - Strada Universității 15, Suceava 720225, Romania",
    "Auto Dany Drive - Strada Popa Stoica din Farcas 72, București, Romania",
    "Il Passo - Strada Republicii nr. 25, Brașov 500030, Romania",
    "Elcom Internaţional S.A. - Strada Crinilor 2, Bistrița, Romania",
    "Datacon Solutions - Strada Câmpului 91, Cluj-Napoca 400656, Romania",
    "Lounge Pub - Strada Ștefan cel Mare 22, Suceava 720005, Romania",
    "TIP Software Transilvania - Strada Axente Sever, Bistrița, Romania",
    "ADN FINANZ - etaj 1, Corp C4, Strada Odobești nr. 1 Bis, Galați 800509, Romania",
    "Krusty Krab Burgers - Bernolákova, 031 01 Liptovský Mikuláš, Slovakia",
    "Sedačky Phase - Trenčín - Belá oproti OC, NC Laugaricio, 911 01 Trenčín, Slovakia",
    "MM taxi a preprava - Slovenská 1538/10, 085 01 Bardejov, Slovakia",
    "SeeU - Košická 4985/39, 821 08 Bratislava-Ružinov, Slovakia",
    "Alpha Taxi - M. R. Štefánika 03601, 036 01 Martin, Slovakia",
    "PCexpres Eperia Prešov - oprava mobilov a elektroniky - Arm. gen. Svobodu 25, 080 01 Prešov-Sekčov, Slovakia",
    // "PCexpres Eperia Prešov - oprava mobilov a elektroniky - Arm. gen. Svobodu 25, 080 01 Prešov-Sekčov, Slovakia",
    "BEFITT STAR Fitness store - Hlavná 805/51, 077 01 Kráľovský Chlmec, Slovakia",
    "DISCOVERY TRAVEL CK - Smrečianska 664, 031 04 Liptovský Mikuláš-Podbreziny, Slovakia",
    "ALBA-TRADE,s.r.o. - Cínová 5, 040 17 Barca, Slovakia",
    "Tricklandia - Cesta Slobody 4, 062 01 Vysoké Tatry-Starý Smokovec, Slovakia",
    "Reštaurácia KOHÚT Kurtáň - Kohut-rb.sk - Kurtáň 199, 986 01 Fiľakovské Kováče, Slovakia",
    // "MM taxi a preprava - Slovenská 1538/10, 085 01 Bardejov, Slovakia",
    "Zlatníctvo Slovšperk - Obchodná 6717/43, 811 06 Bratislava, Slovakia",
    "Pelimo - 24, Krížna 4087, 811 07 Bratislava-Staré Mesto, Slovakia",
    "Vináreň u andelička - Víťaz 310, 082 38 Víťaz, Slovakia",
    "Teta drogéria - Mierové námestie 29, 018 51 Nová Dubnica, Slovakia",
    "Detect Serv - Strada Năsăud 8, Cluj-Napoca 400610, Romania",
    "Danicode Solutions - Strada Nicolae Bălcescu Nr. 1, Bacău 600050, Romania",
    "Kindergarten & Nursery HAPPY KIDS - Strada Trandafirilor 18, Hunedoara 331157, Romania",
    "Restaurant The Place - Strada Cetății 3a, Florești 407280, Romania",
    // "German Market - Piața Mihai Viteazu nr. 17, Cluj-Napoca 400151, Romania",
    "Theta - Strada Iuliu Maniu 40/B, Satu Mare 440115, Romania",
    "Il Passo - Strada Alexandru Vaida Voevod nr. 53-55, Cluj-Napoca 400394, Romania",
    "Şura - Dumbrava 174, Dumbrava 307155, Romania",
    "IL PASSO - Bulevardul Doina Cornea 4, București 061344, Romania",
    "Electronics Sales - Prelungirea București 5, Călărași 910079, Romania",
    "Bottega Artigianale - Strada Energiei 25, Bacău 600273, Romania",
    "IL PASSO - Bd. Timișoara nr. 26, București 061331, Romania",
    "IL PASSO - Strada Aristide Demetriade nr. 1, Timișoara 300088, Romania",
    "IL PASSO - Str. Calea Bucuresti, nr 80, Craiova, Romania",
    "Sc.Autohaus car ayy.srl - Bulevardul Grănicerilor 66b, Nasaud 425200, Romania",
    "IL PASSO - Str. Liviu Rebreanu nr 4, București 031771, Romania",
    "Taxi Saturn - Strada Henny Ignatie nr 2, Corp Beta, Saturn 905500, Romania",
    "Hot Pipes Coffee Shop & Roastery - Strada Cireșilor 84, Cluj-Napoca 400487, Romania",
    "Magazin Piese Auto - Calea Aradului 59, Oradea, Romania",
    "Fiscal Service SRL - Strada Doctor Gheorghe Iacomi 6, Piatra Neamț 610150, Romania",
    "Beauty Store - Strada 22 Decembrie 1989 35, Târgu Jiu 210245, Romania",
    "IL PASSO - Șoseaua București-Ploiești nr. 44A, București 013696, Romania",
    "Embassy of Argentina - Carrera 11B #97 56 Piso 4. Edificio, Ápice, Bogotá, 110221, Colombia",
    "El Rey de los Enrollados - Av Francisco de -Miranda, Centro comercial El Marques, piso 1 local 217, Caracas 1071, Miranda, Venezuela",
    // "Sedačky Phase - Trenčín - Belá oproti OC, NC Laugaricio, 911 01 Trenčín, Slovakia",
  };
}
