class AutoSuggestions3119473 {
  static final reviewedTitles3119473 = const {
    "Porlamar - W4VF+WJV, Porlamar 6301, Nueva Esparta, Venezuela",
    "CEINB PEDRO ELIAS GUTIERREZ - MQ79+R5M, Barinas 5213, Barinas, Venezuela",
    "Lodisca Maracaibo - Calle 110A Entre Av 19 y 19A CASA 19A-33 Sector Cerro Pelado Maracaibo, Venezuela, Maracaibo 4002, Zulia, Venezuela",
    "Tecnopapeles Group, C.A - PRWG+JGC, Calle Bermúdez, Maturín 6201, Monagas, Venezuela",
    "Torni Hogar TM, C.A. - Calle Bella Vista con Callejón Santander, Sector Campiña, La, La Sabanita 8001, Bolívar, Venezuela",
    "Simón Bolívar University - Sartenejas, Caracas, Miranda, Venezuela",
    "Auto Repuestos Glenda, c.a. - Segunda Avenida entre calles 7 y 8 Local 1 Sector Cantarrana, San Felipe 3201, Yaracuy, Venezuela",
    "PandaBTM - Avenida Carrera 7 #66 34 local 4, Bogotá, 110231, Colombia",
    "Hotel Elimar - a 12-85, Calle 28 ##12-1, Girardot, Cundinamarca, 252432, Colombia",
    "Servicios Odontológicos Diseño e Imágen - Calle 63 ## 13 - 12, Bogotá, 110231, Colombia",
    "IKI SUSHI & POKE - Carrera 29 #47 - 14, Bucaramanga, Santander, 680003, Colombia",
    "Kinean Worldwide - Bogotá, Bogota, 111611, Colombia",
    "RED COLOMBIA MANGA - Distrito Turístico Y Cultural, Calle 26 ##17-64, Cartagena de Indias, Provincia de Cartagena, Bolívar, 130001, Colombia",
    "Galileo Restaurante Bar - Avenida 3 Este ## 14A-25, Cúcuta, Norte de Santander, 540003, Colombia",
    "Panda Express - Local 274, Cra. 49 #52-107, La Candelaria, Medellín, Antioquia, 050012, Colombia",
    // "PandaBTM - Avenida Carrera 7 #66 34 local 4, Bogotá, 110231, Colombia",
// "Panda Express - Local 274, Cra. 49 #52-107, La Candelaria, Medellín, Antioquia, 050012, Colombia",
// "Panda Express - Local 274, Cra. 49 #52-107, La Candelaria, Medellín, Antioquia, 050012, Colombia",
    "Webhelp - Carrera 52 # 65 - 91, Centro Comercial Aventura, La Candelaria, Medellín, Antioquia, 050010, Colombia",
    "DROGUERIA PARA TODOS - a 198, Calle 7 #1-1, Cúcuta, Norte de Santander, 540006, Colombia",
    "Red Colombia Crespo - Calle 70 ## 3-31, Cartagena de Indias, Provincia de Cartagena, Bolívar, 130002, Colombia",
    "ePayco - Carrera 48 # 20-114 - Torre 3 - Oficina 655 Centro Empresarial Ciudad del Río, El Poblado, Medellín, Antioquia, 050021, Colombia",
    "Cyberlink St. Kitts - 77VH+44Q, Basseterre, St Kitts &amp; Nevis",
    "Naranjeria - Mexico 1ra Secc, 57620 Nezahualcóyotl, Méx., Mexico",
    "El Gallo Mini Market. C.A - Calle, 3122, 3122, Trujillo, Venezuela",
    "Ofiprinter.com, c.a. - Centro ciudad comercial Tamanaco, nivel C1, local 47h09, Caracas 1064, Distrito Capital, Venezuela",
    "COOPERATIVA CELESTINA - 5X3M+3R6, Valencia 2001, Carabobo, Venezuela",
    "Inversiones La Fortuna Delta C.A - 3W5X+8J6, Tucupita 6401, Delta Amacuro, Venezuela",
    "Supermercado Todo Listo C.A. - F35M+VJV, Av. Intercomunal de El Valle, Caracas 1090, Distrito Capital, Venezuela",
    "phone store maracaibo - Av el milagro, hotel del lago Tibisay, locales 18 19, Maracaibo 4002, Zulia, Venezuela",
    "Optica Tamanaco - F4MV+QX9, Caracas 1064, Miranda, Venezuela",
    "Palo Palito - HRPF+9H5, Merida 5101, Mérida, Venezuela",
    "Grupo Centro Beco - F5WH+W9M, Caracas 1071, Miranda, Venezuela",
    "VEPAY - Nizhniy Susalnyy pereulok, 5с18, Moskva, Russia, 105064",
    "Beluga House - Calle California, Caracas 1060, Miranda, Venezuela",
    "TRIXEL - Carrera 51B #80-58 Oficina 1203, Barranquilla, Atlántico, 080020, Colombia",
    "Industria Metalmecanica Lozano - 1-29 Zona Industrial Comditaca Ureña, C. 17, Ureña 5048, Táchira, Venezuela",
    // "COOPERATIVA CELESTINA - 5X3M+3R6, Valencia 2001, Carabobo, Venezuela",
    "FUTURE TECHNOLOGY SAS - CR 29, Calle 81 Sur #N 40, Bogotá, Cundinamarca, 110111, Colombia",
    "Labcooper Servicio Técnico de celulares IPhone - Carrera 59 #130-28, Suba, Bogotá, 111111, Colombia",
    "Zipaquirá Empresas - calle 10 No 1B - 57, Zipaquirá, Cundinamarca, 250252, Colombia",
    "fisioesteticalalibertad - calle 22# 12 -- 40, la libertad, Cúcuta, Norte de Santander, 540005, Colombia",
    "Dido Veterinaria - AV PRADILLA # 1B -21, Chía, Cundinamarca, 250001, Colombia",
    "TACO TIME COLOMBIA - Calle 99 ##13-50, Bogotá, 110221, Colombia",
    "La Boulangerie - Av. 11e #7a - 17 Local 4, Cúcuta, Norte de Santander, 540003, Colombia",
    "FIT TEC (Gimnasio de Electroestimulacion) - Calle 106 #14-30, Bogotá, 110111, Colombia",
    "casa burger pamplona - Calle 4 ## 3 - 67, Pamplona, Norte de Santander, 543050, Colombia",
    "Seguridad Informática DragonJAR SAS - 23 C # 62 -72 Oficina 705 Edificio Pranha, Centro Empresarial, Manizales, Caldas, 000057, Colombia",
    "Gracon Latam - Carrera 80E, Diagonal 32, Cartagena de Indias, Provincia de Cartagena, Bolívar, 130010, Colombia",
    "Cripto Trading Colombia - Calle 53 #No 16-73, Bogotá, 111311, Colombia",
    "MyF Import S.A.S - Avenida Santander ## 53-8, Manizales, Caldas, 170002, Colombia",
    "Sancte - El Centro, Cartagena, Cartagena Province, Bolivar, 130001, Colombia",
    "La Tortáta - Calle 64 ###7-55 Local 3, Bogotá, 111011, Colombia",
    "Darwinos - Calle 2 Norte #10E-35, Cúcuta, Norte de Santander, 540003, Colombia",
    "CARLO UOMO - Centro Comercial Puerto libre Calle 9 # 36 03 Locales 156-157-158-159 Colombia, Bogotá, 111611, Colombia",
    "Pagos Inteligentes - Platy - ¡Ningún pago se nos escapa! - Carrera 3 # 73 - 91, Bogotá, Cundinamarca, 110221, Colombia",
    "Panda Express Cafeteria - Carrera 5 #27A 36Sur, San Cristóbal, Bogotá, 110421, Colombia",
    // "Beluga House - Calle California, Caracas 1060, Miranda, Venezuela",
    "Grupo Zoom - Final Av. Principal, Qta. Grupo Zoom, Bello Campo, Caracas, F4RX+8HQ, Caracas 1060, Miranda, Venezuela",
    "Panadería Y Pastelería Perimetral 2013 C.A. - MQF5+35M, Carúpano 6150, Sucre, Venezuela",
    "Mookah Restaurant & Lounge - Av. Intercomunal La Trinidad - El Hatillo C.C. Trinidad Tepuy Caracas, Caracas 1081, Miranda, Venezuela",
    "Frenos y Silenciadores Maxituning C.A. - entre calles 30 y 31, 30-45 Av. Don Tulio Febres Cordero, Mérida 5101, Mérida, Venezuela",
    "Bodca Bodegón - C.C. Alto Prado, Av. Los Próceres, Mérida 5101, Mérida, Venezuela",
    "MT MARKETING - Calle Jesús María Patiño con Calle Ortega, Local 7. Porlamar, Isla de Margarita., Calle Ortega, Porlamar 6301, Nueva Esparta, Venezuela",
    "Algo Rico. Inversiones Jorge Madriz F.P - Calle Paez a una cuadra del Bco de Vzla, Tinaquillo 2209, Cojedes, Venezuela",
    "Inversiones Todo Oficina Y Computación C.A. - Esquina de Candilito a Cruz de Candelaria, G34V+9W4, Caracas 1011, Distrito Capital, Venezuela",
    "Soluciones Tecnológicas Venepos - Torre Cari, 2da Avenida Campo Alegre, Caracas 1060, Distrito Capital, Venezuela",
    "CAM SOLUCIONES C.A - BOLEITA SUR, AV. FRANCISCO DE MIRANDA, CENTRO SEGUROS LA PAZ, Caracas 1050, Miranda, Venezuela",
    "Representaciones Abanet CA - Av. Monseñor Pellin, Centro Comercial El Colonial, Planta Alta, Oficina, 43, Cúa 1211, Miranda, Venezuela",
    "Spa Enza Martino - Centro Integral Santa Rosa, Calle A, PS, Local PS, 8, Caracas 1060, Miranda, Venezuela",
    // "Auto Repuestos Glenda, c.a. - Segunda Avenida entre calles 7 y 8 Local 1 Sector Cantarrana, San Felipe 3201, Yaracuy, Venezuela",
    "TEMACO PUNTO FIJO - Punto Fijo 4102, Falcón, Venezuela",
    "Ferre Técnicos Camperos - Sucursal, avenida cirilo agvis sector, Romulo Gallegos, El Nula 5032, Apure, Venezuela",
    "Farmarket - Av. Francisco de Miranda, C.C. Lido, Nivel Miranda Local M41, Caracas 1060, Miranda, Venezuela",
    "Farmarket - Av. Ppal. de Chuao C.C. Ciudad Tamanaco Nivel C-1 Local 47-H-7, Caracas 1061, Miranda, Venezuela",
    "Farmarket - Calle Acuario, C.C. Santa Paula Nivel PB Locales 1,2,3, Urb. Leoncio Martínez, Caracas 1061, Miranda, Venezuela",
    "SGC Consultores C.A. - Sector, #99-13 Avenida 87 Uslar, Valencia 2001, Carabobo, Venezuela",
    "Xinestesia Bodegón - CC Los Chaguaramos #35, Av. Ezio Valeri, Mérida 5101, Mérida, Venezuela",
    "Inversiones VidaCell, C.A - C. Villaflor, Caracas 1052, Distrito Capital, Venezuela",
    "Sánchez Solutions - Avenida 3 Independencia entre Calle 20 y 21, Torre Empresarial Gran Mundo Oficina 7-2, Mérida 5101, Mérida, Venezuela",
    "Farmatodo - Av Arturo Michelena Esq C/Calle Jesus, Semprun Qta Rakel, Sta Monica, Caracas 1040, Distrito Capital, Venezuela",
    "SERVICIOS L Y P La Coromoto - H947+4X5, Maracaibo 4004, Zulia, Venezuela",
    "Crown Donuts - Calle Cecilio Acosta, Pueblo de Chacao Diagonal a la entrada del estacionamiento del, Mercado Municipal de Chacao, Caracas 1060, Miranda, Venezuela",
    "Commerce Chemical C.A - Piso 15, Centro Empresarial Torre Humboldt, 15-03 Av. Río Caura, Caracas 1080, Distrito Capital, Venezuela",
    "Maderas BoleitA34,ca - F5XH+RX5, Caracas 1071, Miranda, Venezuela",
    "SOMOS SISTEMAS - Estacion de Servicio Cocheima, Arriba del antiguo Autolavado - Local 1 - Piso 1, La Asunción 6311, Nueva Esparta, Venezuela",
    // "COOPERATIVA CELESTINA - 5X3M+3R6, Valencia 2001, Carabobo, Venezuela",
    "University of Carabobo - 7XGV+V8P, Naguanagua 2005, Carabobo, Venezuela",
    "Conexión Digital Express Ciudad Verde - Diagonal 38 F, Soacha, Cundinamarca, 250051, Colombia",
    "Guanare.Mas - 372H+432, Guanare 3350, Portuguesa, Venezuela",
    "96.1 FM San Diego de Alcala - 627P+CGF, San Diego 2006, Carabobo, Venezuela",
    "Representaciones y Variedades JV Núñez - Av Sesquicentenario, Valencia 2001, Carabobo, Venezuela",
    // "University of Carabobo - 7XGV+V8P, Naguanagua 2005, Carabobo, Venezuela",
    "Corporacion GalaIt.c.a - Avenida Libertador, Residencias Lidomar Plaza, Calle Panama, Caracas 1010, Distrito Capital, Venezuela",
    "Servicio Repacell - Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
// "Servicio Repacell - Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
//     "Bodca Bodegón - C.C. Alto Prado, Av. Los Próceres, Mérida 5101, Mérida, Venezuela",
    "ITELSA Repuestos JJM, C.A. - Avenida Este 16, Entre Esquinas de Palmita A Tablita, Casa 18, Caracas 1010, Distrito Capital, Venezuela",
    "La Pulperia Marketplace - El Dátil, 6320, Nueva Esparta, Venezuela",
    "Auto PCR. Laboratorio Eficiente - Metrobús Sucre, Avenida Sucre, Caracas 1071, Distrito Capital, Venezuela",
    "Superintendencia Nacional de Cooperativas (SUNACOOP) - Centro, Caracas 1012, Caracas 1012, Distrito Capital, Venezuela",
// "University of Carabobo - 7XGV+V8P, Naguanagua 2005, Carabobo, Venezuela",
    "Osoria Velásquez & Asociados. S.C. - 4FH7+68R, Av. Andrés Bello, Cdad. Bolívar 8001, Bolívar, Venezuela",
    "Eventos Barlog - Calle Real de Maiquetía, Locales : 047 y 048, Mercado Cacique Maiquetia, Av. Maiquetía, La Guaira 1161, La Guaira, Venezuela",
  };
}
