class AutoSuggestions79461818 {
  static final reviewedTitles79461818 = const {
    "Multihidromaticos JJYAÑEZ CA - La Concordia Carrera 5 con calle 4 y 5 Local N- 4 - 96, San Cristóbal 5001, Táchira, Venezuela",
    "Mundo de Azúcar, f.p. - Av unda entre calle 9 y 8 C.C La arenosa nivel 1, local 39 Av. Unda, Guanare 3350, Portuguesa, Venezuela",
    "RedsComp - La Concordia Carrera 5 con calle 4 y 5 Casa N- 4 - 42, San Cristóbal 5001, Táchira, Venezuela",
    "Tecnochia - 5ta avenida entre calles 8 y 9 CC Shopping Center Nivel PB Local 12, San Cristóbal 5001, Táchira, Venezuela",
    "Inversiones Darwin Rojas, C.A. - Calle Real de Maiquetia, Local 667, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Milca Torres 2021, C.A. - Calle Real de Maiquetia, Local 597, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones M & M 2013, C.A. - Calle Real de Maiquetia, Local 689, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Josdavier 2017, C.A. - Calle Real de Maiquetia, Local 677, Mercado Cacique Maiquetia, Pasillo 12, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Delgado Maiquel(K.D.F.2176) F.P. - Calle Real de Maiquetia, Local 631, Mercado Cacique Maiquetia, Pasillo Central, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Orocristal, C.A. - Calle Real de Maiquetia, Local 478, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Carol, C.A. - Calle Libertador local 247, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1162, La Guaira, Venezuela",
    "Ferreteria Arturo G - Carrera 6 con esquina calle 2 casa Nro 2-3, local 1 y 2, Guanare 3350, Portuguesa, Venezuela",
    "El Tinajero Hogar C.A. - Calle 11 entre carrera 5 y 6 Edificio El Tinajero P/B Local 1, Guanare 3350, Portuguesa, Venezuela",
    "Ricar2 House - Los Chorritos, Av Principal, Casa Nro 34, Principal, Tocuyito 2035, Carabobo, Venezuela",
    "BB Store Servicios, CA - AV. Alirio Ugarte Pelayo, Centro Comercial Virgen Del Valle, Local 47 Piso 1, Maturín 6201, Monagas, Venezuela",
    "XTREMO JULKAR 27, C.A - Local 41 Piso PB, Centro Comercial Virgen Del Valle, Av. Alirio Ugarte Pelayo, Maturín 6201, Monagas, Venezuela",
    "FRUTTY MANIA - Centro Comercial Virgen Del Valle, AV. Alirio Ugarte Pelayo, Local 53, Piso 1 Via Viboral, Maturín 6201, Monagas, Venezuela",
    "Sucursal CA BST FARMA - Zona Industrial Castillito Centro Comercial Termini PB local 2. Av. Don Julio Centeno San diego, Valencia 2006, Carabobo, Venezuela",
    "Inversiones Chiquita Plus, C.A. - Calle Libertador, local 016, Mercado Cacique Maiquetia, Pasillo 1, Maiquetía 1161, La Guaira, Venezuela",
    "Video Club - AV. Alirio Ugarte Pelayo, Centro Comercial Virgen Del Valle, Local 51 Piso 1, Maturín 6201, Monagas, Venezuela",
    "Inversiones Pris Muel David, F.P. - Calle Libertador, local 083, Mercado Cacique Maiquetia, pasillo 1, Maiquetía 1162, La Guaira, Venezuela",
    "Panda Verde - Carrera 12 entre calle 9 y 10 casa 9-28 Local 1 sector, Guanare 3350, Portuguesa, Venezuela",
    "O&J Suministros C.A - Av. 74, calle 106, Centro Comercial Infra, PB local 11, San Diego 2006, Carabobo, Venezuela",
    "Mango de Oro C.A. - Av unda esquina carrera 11 Casa nro 1 local 1 sector, Guanare 3350, Portuguesa, Venezuela",
    "11.11 Boutique - G46V+MR8, Avenida Transversal 10, Caracas 1060, Distrito Capital, Venezuela",
    "Pintacar Express - JX49+V7F, Calle Tacagua, Catia La Mar 1162, La Guaira, Venezuela",
    "Inversiones Oshun, C.A. - Calle libertador, Local 182, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1161, La Guaira, Venezuela",
    "Fruber 1111 - Calle Páez, entre Av Guaicaipuro y calle Elice. Edificio Caracas, local C. Chacao, Caracas 1080, C. Páez, Caracas 1060, Distrito Capital, Venezuela",
    "Tu Cuevita Repostera La Arenosa - Carrera 12 entre calles 14 y 15 local 1 casa 12-37, Sector, Guanare 3350, Portuguesa, Venezuela",
    "Helados Dulces y Antojos - Av. Paseo los Ilustres con, Local 01, Sector la Comunidad, Casa, nro 9-169 Principal de la Comunidad, Guanare 3350, Portuguesa, Venezuela",
    "2 PI, C.A. Materiales De Carpintería - 3MJH+RF5, Av. Simón Rodriguez, Barquisimeto 3001, Lara, Venezuela",
    "Inversiones Somger Cells, C.A. - Calle Real de Maiquetia, Local 670, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Disvimol - Carretera Panamericana altura Patiecitos casa N 9-6 local 1A, Táchira Venezuela, Vista Alegre, Panama",
    "Bodega la 30 - Carrera 30 &amp; Calle 26 y 25, Barquisimeto 3001, Lara, Venezuela",
    "Centro de Economia Comunal Manuelita Saenz - C.C Manuelita Sáenz Nv. 4, Local #123, Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Jhoelins, C.A. - Calle Libertador, Local 406, Mercado Cacique Maiquetia, Pasillo 5, Maiquetía 1161, La Guaira, Venezuela",
    "Full Pizza - 27R4+2W6, Av. Unda, Guanare 3350, Portuguesa, Venezuela",
    "Café Plaza - Calle 16 Entre Carreras 4 Y 5 Edificio Don Armando local 02 Frente A La Plaza Bolivar, Guanare 3350, Portuguesa, Venezuela",
    "Inversiones Don Miguelacho - Av. Principal de los proceres entre calle 1 y 2, sector los Próceres, casa nro 30, local 01, Guanare 3350, Portuguesa, Venezuela",
    "la boca del lobo - HQGG+J5Q, Ejido 5111, Mérida, Venezuela",
    "Restaurante Siglo XXI - Calle la Iglesia, Casa numero 4, local PB Calle La Iglesia, Sabana Caracas 1050, Distrito Capital, Venezuela",
    "Puerkos Restaurant - Sabana grande, local sede, PB, Edificio Don Fernando, Av. Casanova, Caracas 1060, Distrito Capital, Venezuela",
    "Antojitos de Ysabell, C.A - Local 5, Catedral de San Agustín, C. Ricaurte, Valencia 2015, Carabobo, Venezuela",
    "Inversiones Foncho Peña - Av. Unda con carrera 9 y 11 Sector La Arenosa, Mercado Municipal, Muro de Los Lamentos, Local 08, Guanare 3350, Portuguesa, Venezuela",
    "Optica Servilens CA - Av. Sucre, Maracay 2101, Aragua, Venezuela",
    "N.B King Shoes C.A - C.c Las americas P.B 39, Calle El Bosque, Maracay 2101, Aragua, Venezuela",
    "Talabarteria m & villalobos g III - 2GQ9+89V, Avenida Lisandro Alyarado, Maracay 2126, Aragua, Venezuela",
    "Barber Tatto 911 - Carrera 4 calle 2 y 3 frente a la Plaza Bolívar Tariba Centro comercial Los Daniel&#39;s local N-16 P1, Táriba 5017, Táchira, Venezuela",
    "Soul Rebel Moda - Boulevard de Sabana Grande, entre Mercado Colonial y Centro Comercial Chacaito, local 1, Caracas 1050, Distrito Capital, Venezuela",
    "11:11 Sport Bar Restaurant - Centro Empresarial Barquisimeto, Local 14, Barquisimeto 3001, Lara, Venezuela",
    "Mr mascotas - Av. Los Leones, planta baja cc.trinitarias, local 25g, Barquisimeto 3001, Lara, Venezuela",
    "Multiservicios Barreto - Calle 41 &amp; Carrera 28, Barquisimeto 3001, Lara, Venezuela",
    "Comercial Marinera C.A - JX5P+C37 de, Avenida Principal, Catia La Mar 1162, Vargas, Venezuela",
    "Sinaí Market - Av Primera Transversal, Caracas 1060, Miranda, Venezuela",
    "Bodegón Los Tesoros de Papá - Calle 8a entre carreras 1 y 2 El Carmen, Barquisimeto 3001, Lara, Venezuela",
    "Beauty Shop - Av Unda CC del Este P/B Mini Tienda 3 Sector, Guanare 3350, Portuguesa, Venezuela",
    "Abasto Alvarez C.A. - 3JJR+9VH, Barquisimeto 3001, Lara, Venezuela",
    "Pizzas Rafucho - urb. Simón Bolívar, Av. 3, casa nro 8 local 01. Sector, Los Próceres, Guanare 3350, Portuguesa, Venezuela",
    "Antojitos - Av. Unda, C.c del Este, planta baja, local 15, Guanare 3350, Portuguesa, Venezuela",
    "Pidiendo y Comiendo Pizzeria - Sector los Proceres, local 1, casa 74 C. 9, Guanare 3350, Portuguesa, Venezuela",
    "POSADA VILLA DEL CARMEN - Avenida principal de Playa Grande, Calle 1, Catia La Mar 1162, La Guaira, Venezuela",
    "La caridad fresco market - Centro comercial galerías playa grande nivel 1 local 18, Maiquetía 1162, La Guaira, Venezuela",
    "Gaby Technology - local 123, Centro de Economía Comunal Manuelita Saenz, Piso 4 Blvr. de Sabana Grande, Caracas 1050, Distrito Capital, Venezuela",
    "ArepaTrekking - Calle principal de Güeime, casa S/N, C92G+JC2, Santa Lucía 1214, Miranda, Venezuela",
    "Mariangel Studio - Carrera 4 calle 2 y 3 frente a la Plaza Bolívar Tariba Centro comercial Los Daniel&#39;s local N- 11 P1, Táriba 5017, Táchira, Venezuela",
    "Haru Nails Studio - Carrera 4 calle 2 y 3 frente a la Plaza Bolívar Tariba Centro comercial Los Daniel&#39;s local N-13, Troncal 1, Táriba 5017, Táchira, Venezuela",
    "La Brachera In C.A. - CALLE PIAR, LOCAL 03 C. Montilla, Guacara 2015, Carabobo, Venezuela",
    "Creaciones Doumari, F.P. - Calle Libertador, Local 013, Mercado Cacique Maiquetia, Pasillo 1, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Charay, C.A. - Calle Real de Maiquetia, Local 664, Mercado Cacique Maiquetia, Pasillo 12, Maiquetía 1162, La Guaira, Venezuela",
    "El Rincóncito de Romi, C.A. - Calle Real de Maiquetia, Local 669, Mercado Cacique Maiquetia, Pasillo 11, Maiquetía 1162, La Guaira, Venezuela",
    "Bodegón RMR - Av. Unda con, P/B, edificio Aura, local 05 Carrera 12, Guanare 3350, Portuguesa, Venezuela",
    "Strong Physical Center, C.A - Nivel Mezzanina, Centro Comercial Virgen Del Valle, Local LM-45 A, Av. Alirio Ugarte Pelayo, Via Viboral, Maturín 6201, Monagas, Venezuela",
    "Alimentos y Suministros Galax - Centro Comercial Comunitario Norte, Local 0809, Av. Alirio Ugarte Pelayo, Via Viboral, Maturín 6201, Monagas, Venezuela",
    "Inversiones Marchael, C.A. - Calle Real de Maiquetia, Local 469, Mercado Cacique Maiquetia, pasillo 6, Maiquetía 1162, La Guaira, Venezuela",
    "Vaporhot vzla - Av Principal de Playa Grande, Catia La Mar 1162, La Guaira, Venezuela",
    "Ferretería Comercial Ramar - Quinta Nilsa N°31. Calle Real De Antimano, entre calle montalbancito, y, C. La Estación, Caracas 1100, Distrito Capital, Venezuela",
    "Distribuidora Olivo C.A - Carrera 25 &amp;, C. 33, Barquisimeto 3001, Lara, Venezuela",
    "Cassa Market - 37 Carrera 25, Barquisimeto 3001, Lara, Venezuela",
    "Dulces y algo más - Carrera 28 &amp;, Calle 25, Barquisimeto 3001, Lara, Venezuela",
    "Clínica Vitalis - Piso 10, oficina 03, Torre América, Avenida Venezuela, Caracas 1050, Distrito Capital, Venezuela",
    "Novedades Hello C.A. - Av. Principal de Propatria &amp; Av Simón Bolívar. Centro Comercial Propatria, nivel 2, local 26 A, Caracas 1030, Distrito Capital, Venezuela",
    "Frigususa - Urb. Playa Grande Av. Hotel Marriott, 1162, La Guaira, Venezuela",
    "Zulyslunchandgrill - 3MGJ+6WX, C. 26, Barquisimeto 3001, Lara, Venezuela",
    "Restaurante Mansión Oriental - Av. Principal de Caribe, Bulevar Naiguata, Parcela 38-35, Qta. Timotes, PB, Local 1, Caraballeda 1165, La Guaira, Venezuela",
    "Burger Grill, C.A. - Av. La Playa con, local 38 Calle El Hambre, Caraballeda 1165, La Guaira, Venezuela",
    "Inversiones Erlyn, C.A. - Calle libertador, Puesto 215, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1162, La Guaira, Venezuela",
    "Inversiones Rubí Esmeralda, C.A. - Av. Soublette, local 463, Mercado Cacique Maiquetia, Pasillo 5, Maiquetia 1162, La Guaira, Venezuela",
    "UPF Delicateses la Gloria de Dios II - Calle Arvelo Casa Nro 03, Tocuyito 2035, Carabobo, Venezuela",
    "AHOPE Style - Local A15 C. Rondon, Tocuyito 2035, Carabobo, Venezuela",
    "Inversiones Peña Nuñez 2015 C.A - Calle Arvelo local Nro 15, Tocuyito 2035, Carabobo, Venezuela",
    "Don Miguel Pizzería - Los Chorritos, Calle Valencia con 2da Calle, Local Nro A-1, Av. 109, Tocuyito 2035, Carabobo, Venezuela",
    "Inversiones Alianza de Dios JL C.A - Los Chorritos, Calle Las Bateas con 42, local 110-20, Tocuyito 2035, Carabobo, Venezuela",
    "Víveres Guacara F.P - Calle Bolivar, entre Jacinto Lara, Local 109 C. Laurencio Silva, Guacara 2015, Carabobo, Venezuela",
    "Abasto A Dios JL - Local 110, Los Chorritos, 21 C. Las Bateas, Tocuyito 2035, Carabobo, Venezuela",
    "Liontech Sambil - Avenida Libertador, C.C. Sambil Caracas, nivel acuario, local AC-C49, Caracas, Av. Libertador, Caracas 1064, Distrito Capital, Venezuela",
    "Abasto Los Chorritos - Los Chorritos, Av Venezuela, Casa Nro 67, Sector Uslar Pietri, Tocuyito 2035, Carabobo, Venezuela",
    "La Coromotana C.A - Local N°1, Los Chorritos, Calle El Valencia, con Av. 110, Tocuyito 2035, Carabobo, Venezuela",
    "Variedades Mis Tesoros - Los Chorritos, Calle Las Bateas con Rómulo Gallegos, Nro de casa 52, Tocuyito 2035, Carabobo, Venezuela",
    "SC Canelones y Montaya - Carrera 8 Esquina calle 16 Edif Madel P/B local 2, Guanare 3350, Portuguesa, Venezuela",
    "Distribuidora de AVON - Calle Bellotn&#39;2, 3 Izquierda, 03300 Orihuela, Alicante, Spain",
    "WAFFLES & BOUQUET VZLA C.A - 7C65+3V4, Maracay 2101, Aragua, Venezuela",
    "Frigorífico Carnes el terminal. C.A. - Los Chorritos, Av 107 Venezuela, Casa, Nro 42 Av. 107, Tocuyito 2035, Carabobo, Venezuela",
    "Importaciones Technology Import - Av 15 Las Delicias Con Calle 100, Cc Gran Bazar, N1, Local1569, Maracaibo 1570, Zulia, Venezuela",
    "Ferreteria Torres Ingenieria de Venezuela - barrio la arenosa, centro, carrera 8 entre calle 11 y 12, edificio Torres Ingeniería, P/B, local 02, Guanare 3350, Portuguesa, Venezuela",
    "Variedades Mafer Gómez - Los Chorritos, Calle Ezequiel Zamora, Casa Nro 107-21, Sector, Tocuyito 2035, Carabobo, Venezuela",
    "Inversiones Georgis JRS CA - Los Chorritos, Av. Principal Local Nro111-50, Principal, Tocuyito 2035, Carabobo, Venezuela",
    "Keves Vision - Avenida Este 0, entre av. Sur 19 y 21. C.C. Parque Caracas, PB, local 2, Caracas 1011, Caracas 1011, Distrito Capital, Venezuela",
    "Frutimarket Ccs - Av Este 2, entre av. sur 21 y 23. Edif. Torre Canaima, PB, local 2 y 3, Caracas 1011, Distrito Capital, Venezuela",
    "Casa Hot Dog - Av. Universidad, casa N. 179-105. Sector, Av. Universidad, Naguanagua 2005, Carabobo, Venezuela",
    "Lucian's tech - C.C. Gran bazar, J9RH+FRP, Maracaibo 4001, Zulia, Venezuela",
    "Representaciones Sitec C.A. - Quinta Irlanda, Calle Nicanor Bolet Peraza, Caracas 1040, Distrito Capital, Venezuela",
    "Inversiones Compucel DM, C.A. - Av. Sur entre Este Dos, Centro Comercial Parque Caracas, Planta Baja, Local 2-3, Urbanización, Caracas 1011, Distrito Capital, Venezuela",
    "Tu market y algo más C.A - Calle Puerto Cabello, local 3, Centro Comercial Cap Conte, c/c Av. 100 Bolívar, Naguanagua 2005, Carabobo, Venezuela",
    "MULTISERVICIOS EL PUENTE II, C.A. - Calle Carvajal, casa número 38, Guacara 2015, Carabobo, Venezuela",
    "Importadora RCZ C.A. - Av. Libertador centro comercial Sambil, Nivel acuario plaza música local ACC-52, Caracas 1064, Miranda, Venezuela",
    "Grachi C.A. - Av. Libertador. Centro Comercial Sambil, nivel feria local FC-18, Caracas 1064, Miranda, Venezuela",
    "Licoven Guacara I c.a - Calle Bolivar c/c Montilla Edif. Magallanes PB locales 2,3 y, 4, Guacara 2015, Carabobo, Venezuela",
    "Optica 360 - J9RJ+H52, Maracaibo 4005, Zulia, Venezuela",
    "Inversiones yed 2030 c.a - Calle libertador, local 071, Mercado Cacique Maiquetia, pasillo 1, Maiquetía 1162, La Guaira, Venezuela",
    "Onlytie Sport - Av. Libertador centro comercial Sambil, nivel autopista local AC-31, Caracas 1064, Miranda, Venezuela",
    "Servitmovil - Gran bazar, Maracaibo 4005, Zulia, Venezuela",
    "Reparaciones Con Tigo - Av 15 Las Delicias Con Calle 100 Nivel 1, Local 145, Maracaibo 4005, Zulia, Venezuela",
    "Respuestos Pirineos - Carrera 5 &amp;, 5ta. Av &quot;Francisco García de Hevia&quot;, San Cristóbal 5001, Táchira, Venezuela",
    "Inversiones Betty mis logros 2018, .C.A. - Calle Libertador, local 153, Mercado Cacique Maiquetia, pasillo 02, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones De Todo un Poco 2019, C.A. - Calle Libertador, local 025, Mercado Cacique Maiquetia, Pasillo 1, Maiquetía 1162, La Guaira, Venezuela",
    "Krispy Donuts El Bosque - Av Las Delicias, Edificio Doña Clemencia, Piso P.B, Local 231, Maracay 2102, Aragua, Venezuela",
    "Krispy Donuts - E/S Circulo Militar, Local Nro, Zona Postal, S/N Avenida Las Delicias, Maracay 2102, Aragua, Venezuela",
    "Tecnoberry C.A - 27W3+FV8, Guanare 3350, Portuguesa, Venezuela",
    "Krispy Donuts - 5GFR+PJH, Cagua 2122, Aragua, Venezuela",
    "Krispy Donuts El Limón - Av Caracas, Edificio Vanessa, Local Nro 03, Conjunto Residencial Vanessa, Sector, Zona Postal, El Limón 2103, Aragua, Venezuela",
    "Krispy Donuts El Terminal - Terminal Central, Nro DDAE102, Av Fuerzas Aéreas &amp; Avenida Constitución, Sector Centro, Maracay, Aragua, zona Postal, Maracay 2103, Aragua, Venezuela",
    "Krispy Donuts San Jacinto - Centro Comercial y Profesional Ciudad Jardín, Nivel PB, Zona Postal, Local 06 Av. Bolívar, Maracay 2102, Aragua, Venezuela",
    "Canguro sede city market 1 - Calle Villa flor, centro comercial City market PB local 114 código postal 1050. Caracas, C. Villaflor, Caracas 1050, Distrito Capital, Venezuela",
    "Canguro sede city market 2 - Calle Villa Flor Centro Camercial City Market, Piso 3, Local 335 codigo postal 1050. Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Canguro Sede Sabana Grande - Caracas - Bulevar de Sabana Grande, Centro Comercial Sabana Grande, Nivel PB, Local 08, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Densor - local 1, Calle 8 Carrera 8, Guanarito 3354, Portuguesa, Venezuela",
    "Led-Computer - Av. 15 Las Delicias con calle 100, C.C. Gran Bazar, nivel 1, local 756, Maracaibo 4005, Zulia, Venezuela",
    "Diseños & creaciones Snarpy - Local 4, Av. Unda, barrio La Arenosa, esquina Carrera 7, C.C Cordillera, Nivel 1, Av. Unda, Guanare 3350, Portuguesa, Venezuela",
    "Evoualji - Barrio Cementerio, esquina Carrera 8 con Calle 20, C.C City Center, P/B, Local 1, Guanare 3350, Portuguesa, Venezuela",
    "Rio Celeste - G36G+M92, Avenida Sucre, Caracas 1010, Distrito Capital, Venezuela",
    "MOTORS REPUESTOS OMG - G36G+J9R, Avenida Sucre, Caracas 1030, Distrito Capital, Venezuela",
    "Abasto la o de oro C.A - Av. Sucre de Catia, Residencia Naiguata, Torre B, Local B-4 Urbanización, Zona Postal, Av. Sucre, Caracas 1010, Distrito Capital, Venezuela",
    // "Abasto la o de oro C.A - Av. Sucre de Catia, Residencia Naiguata, Torre B, Local B-4 Urbanización, Zona Postal, Av. Sucre, Caracas 1010, Distrito Capital, Venezuela",
    "Inversiones flor María 2010 c.a - Av. Sucre de catia edif.naiguta p.b local 03 sector, Av. Sucre, Caracas 1010, Distrito Capital, Venezuela",
    "Dulce Panela Cafe - Barrio La arenosa, carrera 7 entre calle 14 y 15, casa N°14, local 1, Guanare 3350, Portuguesa, Venezuela",
    "Krispy Donuts Avenida Bolívar - Av Bolivar Norte Centro Comercial Roosvelt 1 Nivel PB, Local 3, Valencia 2001, Carabobo, Venezuela",
    "Ferreteria Fermil la 5ta - Carrera 5 con calle 10 Barrio la arenosa Edif. Abboud Piso P/B local 4 y, Troncal5, Guanare 3350, Portuguesa, Venezuela",
    "Iluminaciones Alvarez - esquina calle 14, local 2, Carrera 7, Guanare 3350, Portuguesa, Venezuela",
    "Ankara Catia - 2da avenida de la panamericana entre Colombia y argentina quinta el milagro local 37. Caracas, Caracas, Caracas 1030, Distrito Capital, Venezuela",
    // "Ankara Catia - 2da avenida de la panamericana entre Colombia y argentina quinta el milagro local 37. Caracas, Caracas, Caracas 1030, Distrito Capital, Venezuela",
    "Inversiones Linda 2014, C.A. - Calle Libertador, Local 466, Mercado Cacique Maiquetia, Pasillo 5, Maiquetía 1161, La Guaira, Venezuela",
    // "Ankara Catia - 2da avenida de la panamericana entre Colombia y argentina quinta el milagro local 37. Caracas, Caracas, Caracas 1030, Distrito Capital, Venezuela",
    "Mojito House - Av principal con calle 2, Edificio Okay Nivel P/B, local 2, Guanare 3350, Portuguesa, Venezuela",
    "Flamingru - 7 Carrera 6, Guanare 3350, Portuguesa, Venezuela",
    "Lio's Store - Unnamed Road, Guanarito 3354, Guanarito 3354, Portuguesa, Venezuela",
    "La Tiendita GA Saavedra - calle 5 entre carreras 5 y 6, local 07. Barrio Madre Vieja, 3354, Guanarito 3354, Portuguesa, Venezuela",
    "D Vivas Shop - MQVR+QJ8, Guanarito 3354, Portuguesa, Venezuela",
    "Zapatería Jkamy Boutique segundo piso local 1 - Carrera 7 con Calle 18, C.C Zafiro, Nivel 2, Local 1, Guanare 3350, Portuguesa, Venezuela",
    "GUERRERO SERVICELL CA (GRAN BAZAR) - J9RJ+M36, Maracaibo 4005, Zulia, Venezuela",
    "Inversiones Barac 2013 - local 76-77, Mercado Bolivariano de la Hoyada, Caracas, Caracas 1011, Distrito Capital, Venezuela",
    "lola express - local 12 y 13, Edificio Martín, Av. San Martín, Caracas 1020, Distrito Capital, Venezuela",
    "Multiservicios Mundo Tecnologia C.A. - Local Comercial ubicado en av. 15 Delicias CC Bazar, Maracaibo 4001, Zulia, Venezuela",
    "JKAMY Boutique - Local 3, Carrera 7 con Calle 18, C.C Zafiro, Nivel PB, C. 18, Guanare 3350, Portuguesa, Venezuela",
    "Inversiones la Esquina de Sharon, C.A. - Calle Libertador, Local 275, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1161, La Guaira, Venezuela",
    "Yessenia Montilla, F.P. - Calle Libertador, Mercado Cacique Maiquetia, Local 21 Pasillo 1, Maiquetía 1162, La Guaira, Venezuela",
    "Creaciones Decomari - J9RJ+Q5F, Maracaibo 4005, Zulia, Venezuela",
    "Gravity Games - Planta Baja, Centro Plaza La Candelaria, local 26 Av. Urdaneta, Caracas 1011, Distrito Capital, Venezuela",
    "Android Store - J9RH+6QX, Av. Libertador, Maracaibo 4005, Zulia, Venezuela",
    "Arepas Full Sabor - Av 15 Las Delicias Con Calle 100, Centro Comercial GRAN BAZAR, Nivel 2, Local 10, Maracaibo 4005, Zulia, Venezuela",
    "Inversiones Dey 98 ó 2013, F.P. - Calle Libertador, Mercado Cacique Maiquetia, Local 70 Pasillo 1, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones Mafer, C.A. - Calle Libertador, Local 213, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1161, La Guaira, Venezuela",
    "Agua Purificada y Algo Más... - Avenida Luis De Camoens, Caracas 1061, Distrito Capital, Venezuela",
    // "Inversiones Jhoelins, C.A. - Calle Libertador, Local 406, Mercado Cacique Maiquetia, Pasillo 5, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones Chango 66, C.A - Calle Libertador, Local 210, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones Linda Bonita, C.A. - Calle Libertador, Locales 375 y 376, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1161, La Guaira, Venezuela",
    "Canguro sede Urdaneta tienda mayorista - Av. Urdaneta, de Pelota a Punceres. Residencias 26. PB y piso 1. Caracas, 1020, Av. Urdaneta, Caracas 1010, Distrito Capital, Venezuela",
    "Canguro Sede Sabana Grande (Servicio Técnico) - Caracas - Bulevar de Sabana Grande, C.C Sabana Grande, Nivel Mezanina, Local 3, local 03 C. Villaflor, Caracas 1050, Distrito Capital, Venezuela",
    // "Canguro sede city market 2 - Calle Villa Flor Centro Camercial City Market, Piso 3, Local 335 codigo postal 1050. Caracas, Caracas 1050, Distrito Capital, Venezuela",
    "Inversiones Sandy, F.P. - Calle Libertador, Local 208, Mercado Cacique Maiquetia, Pasillo 3, Maiquetía 1161, La Guaira, Venezuela",
    "Inversiones Marcelo - Carrera 5 y 6 con, C.C. Eustoquio, C. 12, Guanare 3350, Portuguesa, Venezuela",
    "Boutique Jessimar - Unnamed Road, Guanarito 3354, Guanarito 3354, Portuguesa, Venezuela",
    "Baby chic Boutique - Barrio Monseñor Unda Carrera 8 con calle 7, Carrera 8, Guanarito 3354, Portuguesa, Venezuela",
    "SUPERMERCADO MIYOVI, C.A. - Los Guaritos III, canal 90, vereda, 30 C. 7, Maturín 6201, Monagas, Venezuela",
    "Velvet The Beauty House - Avda Francisco de Miranda, Centro Lido Nivel Miranda Local M14, Caracas 1060, Distrito Capital, Venezuela",
  };
}
