class AutoSuggestionsAM {
  static final reviewedTitlesAM = const {
    "Trovas Ve - Av 40a entre calles 161 y, Calle 162, San Francisco 4004, Zulia, Venezuela",
    "Freddytattoo - JX2G+W45, Av. La Armada, Catia La Mar 1162, La Guaira, Venezuela",
    "Anais Nails - JX3G+37R, Catia La Mar 1162, Vargas, Venezuela",
    "Zona Servi - H2WX+7QF, C. Jefatura a Cristo, Maiquetía 1161, La Guaira, Venezuela",
    "Multiservicios Germany C.A. - Calle 14 De Febrero. Entre Calle Sol de Madrid &amp; Calle el Centro, Casa 12-A, Piso 2, Caracas 1030, Distrito Capital, Venezuela",
    "Servicio técnico electrónica - Catia La Mar 1162, Vargas, Venezuela",
    "Inversiones Valentina Bisutery C.A - Av. Universidad, Centro Comercial La Castilla, C. Guillermo José Schael, Caracas 1011, Distrito Capital, Venezuela",
    "Inversiones Sport Family Full C.A - G45V+XX5, Avenida Mohedano, Caracas 1060, Miranda, Venezuela",
    "7 Estelas - JX3F+7VF, Avenida Tacagua, Catia La Mar 1162, La Guaira, Venezuela",
    "Goodstyleccs - Edif.san Luis parque Carabobo, Caracas, G32W+X96, Caracas 1011, Distrito Capital, Venezuela",
    "Ekko Barber Shop - Av. Universidad, Centro Comercial La Castilla, C. Guillermo José Schael, Caracas 1011, Distrito Capital, Venezuela",
    "Arame Accesorios - Torre C, Trans. 1, Caracas 1060, Distrito Capital, Venezuela",
    "Tecno7Repair - Bellas Artes, Caracas 1011, Distrito Capital, Venezuela",
    "Área Electric - Av. Urdaneta. Entre Av Vollmer &amp;, Planta baja, CC Lord Center, local 39 Av. El Lago, Caracas 1011, Distrito Capital, Venezuela",
    "EJCA Electrónica, C.A. - Av Sur 2. Entre Av Lecuna y Av Oeste 12. Edif. Sur 2, PB, Local 1, Caracas 1014, Distrito Capital, Venezuela",
    "Ojo de Loto - Av vollmer y Av el lago C.C Lord Center Local S13 Nivel Feria Frente La panadería Vollmer, Caracas 1010, Distrito Capital, Venezuela",
    "PIZZA KIERO - Maracaibo 4004, Zulia, Venezuela",
    "ROTULARTE - calle 15 Av Morita Locales Eliezer Local 3 sector, Guanare 3350, Portuguesa, Venezuela",
    "Moto Sport - Carrera 3 esquina calle 20, la peñita Edificio Moto Sport, local A-03, p/b, Guanare 3350, Portuguesa, Venezuela",
    "Crearteideas - A.v 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "Fina Fantasia - A.V 15 Las Delicis, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "Cocos Sweet Shop - Avenida Sur 15, C. Guillermo José Schael, Caracas 1011, Distrito Capital, Venezuela",
    "Big Fashion Ccs - Avenida Sur 15, C. Guillermo José Schael, Caracas 1011, Distrito Capital, Venezuela",
    "Repuestos Betancourt - J32F+M3R, La Guaira 1160, Vargas, Venezuela",
    "Floristeria Paraiso Galipan - H2WQ+J8V, C. Real de Pariata, Maiquetía 1161, La Guaira, Venezuela",
    "PandaFix - A.V 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "Pastelería El Punto Andino - esquina calle 16 con Carrera 9, local 02, p/b, Sector Cementerio, Guanare 3350, Portuguesa, Venezuela",
    "Supermercado La Sorpresa De Pariata - Maiquetía 1161, Vargas, Venezuela",
    "Luncheria el Rincon de Pariata - H2XQ+4JW, Maiquetía 1161, Vargas, Venezuela",
    "Comercial el Divino Niño - J458+3GR, Vía Teleférico, Macuto 1164, La Guaira, Venezuela",
    "Café Teleférico Douglas - J458+5CQ, Vía Teleférico, Macuto 1164, La Guaira, Venezuela",
    "Inversiones VFC - H2WX+VCC, C. Los Baños, Maiquetía 1161, La Guaira, Venezuela",
    "Electrónica Compusol - H3W2+HF2, C. Los Baños, Maiquetía 1161, La Guaira, Venezuela",
    "Inverciones YOYO C.A - J9RJ+X9H, Avenida Las Delicias, Maracaibo 4005, Zulia, Venezuela",
    "Party y Algo Más - A.v 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "Calzados Emanuel - JX2G+W3V, Av. La Armada, Catia La Mar 1162, La Guaira, Venezuela",
    "Bungalow - Av. Los Leones &amp; Calle Caroni, Urb. Fundalara, Edif. Centro Empresarial Barquisimeto, Barquisimeto 3001, Lara, Venezuela",
    "Comercializadora Don Apolinar Campos - Guanare Sector Cementerio Carrera 8 con calle 20 C.C. City Center p/b local 4, Guanare 3300, Portuguesa, Venezuela",
    "TODOTOYOTA, C.A. - Carrera 14 entre Calles 10 y 11 , Sector, Guanare 3350, Portuguesa, Venezuela",
    "Inversiones Chop 2017 - JX3G+36Q, Av. La Armada, Catia La Mar 1162, La Guaira, Venezuela",
    "Servicell - JX2G+W5C, Av. La Armada, Catia La Mar 1162, La Guaira, Venezuela",
    "Repuestos Tu Preferido - Entre calle 20 y 21 Av. Simón Bolívar, edificio Ferretería Venezuela p/b local 01. Sector El, Cementerio, Guanare 3350, Portuguesa, Venezuela",
    "Charcutería Capuchino C.A - WJ7R+4Q8, C. Roscio, San Juan de Los Morros 2301, Guárico, Venezuela",
    "Totimarket - 15 Avenida Las Delicias, Maracaibo 4005, Zulia, Venezuela",
    "Un Lugar Diferente para Comprar - Av. Padilla C. 93, Maracaibo 4001, Zulia, Venezuela",
    "JEOTCELL - A.V 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "ALCANPO Cell Sucursal #2 - Av. 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "Agrotienda - 5M5J+32J, Avenida, El Cují 3001, Lara, Venezuela",
    "DC Grand Bazaar - Av 15 Delicias, Calle 100, Av. Libertador, Maracaibo 4005, Zulia, Venezuela",
    "Optica Visión - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "Comercializadora & Distribuidora Fabrimuebles Remolina C.a - Av José Antonio Paez, C.C Multiplaza El Paraíso, Nivel 6, Local C-12 y C-13, Urb, Zona Postal 1020, Caracas 1020, Distrito Capital, Venezuela",
    "Global Cell System - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "Servicio Técnico JR Cell - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "Magic Import - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "mmsolucionestecnologicas - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "StarFactory4 - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "TECNOCELL2021,C.A - Av 15 Las Delicias, Con Calle 100, Maracaibo 4005, Zulia, Venezuela",
    "Ferreteria Coinvergar - Av Simón Bolívar con calle 23 y 24 Edificio Blandiski local 1 sector, Cementerio, Guanare 3350, Portuguesa, Venezuela",
    "Glou Chic - Mercado Economía Popular la Hoyada. Pasillo Venezuela Local 1866, Avenida Fuerzas Armadas, Caracas 1012, Distrito Capital, Venezuela",
    "Techno Spacex - Avenida Universidad, entre Av Sur 11 &amp; Av Sur 13. Edificio City Alianza, Local 07, Caracas 1011, Distrito Capital, Venezuela",
    "El Techo de La Ballena - entre esquina Gradilla y San Jacinto, Av Este 2, Caracas 1012, Distrito Capital, Venezuela",
    "Inversiones I Store - H2VX+VFJ, Av. Soublette, Maiquetía 1161, La Guaira, Venezuela",
    "M&L2021 - 1060 C. Sorocaima, Maiquetía 1161, La Guaira, Venezuela",
    "Litoral Mall - H2WV+QM4, Av. Soublette, Maiquetía 1060, La Guaira, Venezuela",
    "Inversiones Store Son - H2WV+QJ5, Av. Soublette, Maiquetía 1161, La Guaira, Venezuela",
  };
}
